### ISSUE TITLE
consecutively sent HID output messages are skipped

### ISSUE THREAD

**Issue by Be-ing** [mixxxdj/mixxx#10828]
HID output with my [Kontrol S4 Mk3 mapping](https://github.com/be-ing/mixxx/tree/kontrol_s4_mk3) was broken by #4585. Initially, all duplicate HID output packets were not sent. That was fixed by #4692. However, there is still another critical bug. Sometimes, Mixxx will neither send the output packet for the right jog wheel motor nor the right jog wheel LEDs. When this happens, HID output for the separate packet controlling the buttons' LEDs continues to work, so the bug seems to be specific to the output packets that are continuously sent. This is not 100% reproducible, so I am guessing there's a race condition involved. In the meantime I've had to use a commit before #4585 was merged.

**Comment by Be-ing** [comment]
This has been confirmed by @fayaaz and [another user on the forum](https://mixxx.discourse.group/t/traktor-kontrol-s4-mk3/21613/90).

**Comment by Swiftb0y** [comment]
ping @JoergAtGithub

**Comment by uklotzde** [comment]
I suppose that releasing the mutex in HidIoOutputReport::sendCachedData() could be the culprit. `m_lastSentData` might be swapped out and modified again while `hid_write()` is still reading it.

**Comment by uklotzde** [comment]
@Swiftb0y Please flag this issue as a critical bug.

**Comment by uklotzde** [comment]
Untested hotfix for my guess: 
[fix-hidoutputreport-sendcacheddata.zip](https://github.com/mixxxdj/mixxx/files/9438829/fix-hidoutputreport-sendcacheddata.zip)

**Comment by JoergAtGithub** [comment]
I'm currently away from my computer and writing from my phone, I can't look for this until Tuesday.
HidIoOutputReport::sendCachedData can only be called from the HidIO thread of the device. Therefore it can't be executed a second time, while hid_write execution is pending.
I guess, that the problem lies in the initialization section of the mapping. The content to be send to OutputReport 0x48 is immideately replaced by a new value. The HidIO thread has no chance to send it from the cache, before it's superseded by new data:  https://github.com/Be-ing/mixxx/blob/355f0ba9fb158f283cde84bcc1463d4da1730c14/res/controllers/Traktor-Kontrol-S4-MK3.js#L1997
@Be-ing Could you please attach a log of the output with --controller-debug activated. There should be a message, that this happens.

**Comment by Be-ing** [comment]
> Untested hotfix for my guess:
[fix-hidoutputreport-sendcacheddata.zip](https://github.com/mixxxdj/mixxx/files/9438829/fix-hidoutputreport-sendcacheddata.zip)

I tested this and it does not fix the bug.

**Comment by Be-ing** [comment]
> @Be-ing Could you please attach a log of the output with --controller-debug activated. There should be a message, that this happens.

[mixxx.log](https://github.com/mixxxdj/mixxx/files/9439064/mixxx.log)

**Comment by uklotzde** [comment]
The `Skipped superseded OutputReport` messages are worrisome. This should not happen, especially not during initialization when certain reports might only be sent once.

We probably need to introduce different buffering behavior for output reports. Reports might be discarded by default when a previous sent operation is still pending, but need to be buffered (FIFO) if requested by the caller.

**Comment by uklotzde** [comment]
Instead of caching only a single output report a ring buffer should be used to enqueue incoming updates. A capacity of 1 then reflects the current behavior.

**Comment by Be-ing** [comment]
> I guess, that the problem lies in the initialization section of the mapping. The content to be send to OutputReport 48 is immideately replaced by a new value. The HidIO thread has no chance to send it from the cache, before it's superseded by new data: https://github.com/Be-ing/mixxx/blob/355f0ba9fb158f283cde84bcc1463d4da1730c14/res/controllers/Traktor-Kontrol-S4-MK3.js#L1997

This seems to be correct. Commenting out the sending of the initialization packets with 19560e2c7df6f3a313b457df2809f0edf5538116 from before #4585 was merged, turning the controller off and on again, then restarting Mixxx reproduces the bug. I'm not confident this is related to packets being sent at high frequencies.

**Comment by JoergAtGithub** [comment]
I'm working on a solution. As a bandaid, please add wait times of ~20ms at lines 1998 and 2015 to your mapping.

**Comment by Be-ing** [comment]
Sending the second initialization packet on a 35 ms timer hacks around the problem.

**Comment by Be-ing** [comment]
@JoergAtGithub have you had a chance to work on this?

**Comment by acolombier** [comment]
Any update on this? I have picked up the work from @Be-ing and it seems that this issue is making more than just one problem. 
Happy to help with that!

**Comment by JoergAtGithub** [comment]
I will work on a PR, which implements an alternate mode, for such non HID class compliant use.

**Comment by acolombier** [comment]
Thanks for the speedy feedback, will give it a spin as soon as you have it :)

**Comment by JoergAtGithub** [comment]
I've the code ready now, and will provide a PR this weekend!

**Comment by acolombier** [comment]
Awesome stuff! I don't think the S4 Mk3 PR will be merged by then, so should be able to undo the workaround and test with it
