### ISSUE TITLE
Mixxx app name is mixxx.app on macOS - should be Mixxx.app

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#10845]
**Currently**
Discovered this when launching Mixxx via [Sol](https://github.com/ospfranco/sol) launcher:
![sol](https://user-images.githubusercontent.com/5708172/187514426-bc6e5f66-f592-4cd3-9031-0814bd61d4d5.png)
For whatever reason when launching via Raycast the app shows up as `Mixxx`, it also shows with capital M in macOS Finder > Applications folder, however when looking at the app details, `Name & Extensions` shows `mixxx.app`:
![app name](https://user-images.githubusercontent.com/5708172/187514197-bd8ea5b4-da6d-4eea-bbbf-aec8f6e51cfa.png)

**Expected**
Would expect the app to be named Mixxx.app as that is what is used everywhere else.

Unsure how this discrepancy came about or where app name is defined and why it is showing as Mixxx in Applications folder.

**Comment by Swiftb0y** [comment]
Probably because the executable is lowercase but the displayname is titlecase...
https://github.com/mixxxdj/mixxx/blob/c9d95818b69c28fcd66adea58c35bcc4a15fdfc9/packaging/macos/bundle.plist.in#L5-L22

**Comment by fwcd** [comment]
I agree, the canonical name should be capitalized as `Mixxx.app`, just wanted to note that most file systems on `macOS` are case-insensitive, so in _principle_ it shouldn't matter (though it tends to confuse e.g. shell completion when using the 'wrongly spelled' version).

**Comment by Be-ing** [comment]
IIRC this was related to something with CPack that required using the name of the executable which is lowercase. Not sure about that though.

**Comment by DaveFlashNL** [comment]
> I agree, the canonical name should be capitalized as `Mixxx.app`, just wanted to note that most file systems on `macOS` are case-insensitive, so in _principle_ it shouldn't matter (though it tends to confuse e.g. shell completion when using the 'wrongly spelled' version).

true, but don't forget many nerds on mac, like me always like to run the file system as case-sensitive, also of note is a time machine backup volume always is case sensitive...

**Comment by ronso0** [comment]
How is this handled by other apps? Is there some poilicy, i.e. is what @foss- noticed only an issue with the Sol launcher?

**Comment by fwcd** [comment]
I believe this should be solved as of #12656. Feel free to reopen if not.

**Comment by foss-** [comment]
Verified in 2.5-alpha-251-g99bc5c200a (main), thanks. Wow, Mixxx went from 119 MB to 194 MB in a bit over a year.

![1](https://github.com/mixxxdj/mixxx/assets/5708172/a472defa-8d8e-4054-a96c-eab61eef33a5)
