### ISSUE TITLE
crash when ctrl clicking hotcue number three times on macOS

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#10847]
macOS 12.5.1 (Intel mac)
2.4-alpha-1282-gc9d95818b6 (main)

**Reproduce**
- Load track with hotcues or create a hotcue
- ctrl+click on hotcue three times

**Currently**
On first click Hotcue details open
On second click Hotcue details close
On third click Mixxx crashes
Crash (1 year): https://bin.disroot.org/?bfa39408ab0c180f#B9JDTUQyp1ZFp642sXJnnyU5zEJRe2U2LyaHrLEge8Zj

**Expected**
No crash

@daschuer mentioned the trace looks familiar to https://github.com/mixxxdj/mixxx/issues/9687 (fixed in 2.3.0)

Wondering if this is yet another variety of https://github.com/mixxxdj/mixxx/pull/10839 behavior?

**Comment by ronso0** [comment]
This is not a crash but a hit debug assert:
https://github.com/mixxxdj/mixxx/blob/c9d95818b69c28fcd66adea58c35bcc4a15fdfc9/src/mixxxapplication.cpp#L111-L126

As noticed in #10839 the reason is very likely the same: no button release is emitted when using `Ctrl` + left-click on macOS.
I guess no one would close a popup with another right-click, besides debug assertions are not fatal in releases.
Thus: low prio : )

**Comment by foss-** [comment]
no longer reproducible testing build from https://github.com/mixxxdj/mixxx/pull/10839

**Comment by ronso0** [comment]
Huuh? #10839 only touches the knob/slider event handlers.
Is `DEBUG_ASSERTIONS_FATAL` turned off for some strange reason?

**Comment by foss-** [comment]
Unsure how to tell. But I am no longer ablt to trigger the crash which I previously was able to reliable reproduce.

**Comment by ronso0** [comment]
You didn't Ctrl+click anything else in Mixxx after launch, only 3 x on the hotcue button?

**Comment by foss-** [comment]
RIght and the hotcue details open and close in alternating order.

**Comment by foss-** [comment]
2.3.3 Qt: 5.12.3
2.4.0 Qt: 5.12.4
So maybe that is the difference and issue is limited to 5.12.4 😵‍💫

**Comment by ronso0** [comment]
...that, or there are some more debug assertions in 2.4 (didn't look at the backtrace, yet)

**Comment by ronso0** [comment]
Wait, this is about the hotcue button, not about hotcue markers on waveforms, right?

**Comment by foss-** [comment]
> Wait, this is about the hotcue button, not about hotcue markers on waveforms, right?

ack

**Comment by ronso0** [comment]
Is fixed after https://github.com/mixxxdj/mixxx/pull/10869 was merged to 2.3.4?

**Comment by foss-** [comment]
macOS 12.6
Mixxx 2.3.3-50-g5e551aaaa1 (HEAD) from https://github.com/mixxxdj/mixxx/actions/runs/3103325423#artifacts

No longer crashes. Closing.
