### ISSUE TITLE
Experimental QML UI does not load with Qt 6.3

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/mixxx#10854]
Currently, Mixxx fails to start when built with Qt 6.3.

I already spent some hours debugging it, but to no avail.

Using Qt 6.3.1 on ArchLinux, I'm getting the following terminal output when running Mixxx:

```
warning [QQmlThread] Binding on contentItem is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on background is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on background is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [QQmlThread] Binding on handle is not deferred as requested by the DeferredPropertyNames class info because one or more of its sub-objects contain an id.
warning [Main] QQmlApplicationEngine failed to load component
warning [Main] file:///path/to/mixxx/res/qml/main.qml:91:21: Type DeveloperToolsWindow unavailable
warning [Main] file:///path/to/mixxx/res/qml/DeveloperToolsWindow.qml:115:20: Mixxx.ControlSortFilterModel is not a type
critical [Main] Failed to load QML file "/path/to/mixxx/res/qml/main.qml"
```

**Comment by Be-ing** [comment]
I can reproduce this with Qt 6.3.1 on Fedora 36.

**Comment by m0dB** [comment]
With Qt 6.3.2 (binary, macOS) I don't see this problem. This UI opens correctly and the QML widgets are drawn. However, none of the c++ qml elements are available. There are many warnings during startup, but also for example clicking on the Prefs buttons results in a "TypeError: Cannot read property 'show' of undefined". I am reading https://www.qt.io/blog/introduction-to-the-qml-cmake-api which added the c++ sources of the QML elements to the qt6_add_qml_module(...) cmake call, which mixxx doesn't. I'll try if that makes a difference.

**Comment by Holzhaus** [comment]
I can confirm that the UI actually loads with Qt 6.3.2, but throws a lot of errors on the terminal. But at least it looks like this:

![Screenshot from 2022-09-28 11-11-51](https://user-images.githubusercontent.com/1834516/192740070-b7d70806-fa81-422f-a0c8-4fbc2f89388f.png)


```
$ pacman -Q qt6-base
qt6-base 6.3.2-1
```

**Comment by m0dB** [comment]
I managed to get the PreferencesDialog working by registering it manually. Not sure why the automated registration is not working.

https://github.com/mixxxdj/mixxx/pull/10922

On a side note, I also notice that every time I build (using make), mixxx-lib_qmltyperegistrations.cpp, MathUtils_mjs.cpp and PlayerDropArea_qml.cpp are being regenerated and recompiled, even though there have been no changes. This is pretty annoying and slowing me down.

**Comment by m0dB** [comment]
Also strange: the preferences dialog is in Spanish. Any idea where that might come from?

**Comment by Holzhaus** [comment]
We found the cause of the type registration issue. It's this Qt bug: 
https://bugreports.qt.io/browse/QTBUG-104373

Will probably be fixed in Qt 6.3.3.

Related discussion: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/QML.20scrolling.20waveform.20proof.20of.20concept/near/301340350

**Comment by daschuer** [comment]
This bug is already fixed. Can you please file a new issue?

**Comment by jospezial** [comment]
#14670
