### ISSUE TITLE
Closing Tag Fetcher via "x" close button doesn't stop the WebTask

### ISSUE THREAD

**Issue by fatihemreyildiz** [mixxxdj/mixxx#10877]
### Bug Description

When a task is started and rejected (pressed 'x' button) before it finishes, the task never stops or either aborts. 

If the task is started via "Track Properties -> Import Metadata From Musicbrainz" the task never stops until it fetches all the Recording ID's.

If the task is started via WTrackMenu, it doesn't continue but it doesn't abort either. 

This doesn't happen when `Cancel` button is pressed.

### Version

upstream/2.3

### OS

Ubuntu 20.04

**Comment by daschuer** [comment]
Fixed in https://github.com/mixxxdj/mixxx/pull/10878
