### ISSUE TITLE
Wrong Key format written to the file Tags 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#10890]
### Bug Description

According to https://id3.org/id3v2.3.0 the content of TKEY is well defined: 

>TKEY
>    The 'Initial key' frame contains the musical key in which the sound starts. It is represented as a string with a maximum length of three characters. The ground keys are represented with "A","B","C","D","E", "F" and "G" and halfkeys represented with "b" and "#". Minor is represented as "m". Example "Cbm". Off key is represented with an "o" only. 

Mixxx currently writes the String visible at the GUI into the TKEY field. This is wrong and can cause issues in third party applications. 

### Version

2.3.3 and main 

### OS

All

**Comment by daschuer** [comment]
Since this bug fix may break user workflows with external programs that are showing the key info literally, I will move it to the 2.4-beta

**Comment by acolombier** [comment]
@daschuer is this completely fixed now? Close?

**Comment by daschuer** [comment]
Yes
