### ISSUE TITLE
25 second hang at startup

### ISSUE THREAD

**Issue by TimbreAndTone** [mixxxdj/mixxx#10895]
### Bug Description

Hi, Mixxx 2.3.3 hangs at the black startup screen with Mixxx in center. When the opening progress bar reaches about 65% it stops. And a small white top of a dialog window flashes above the Mixxx logo. After about 25 seconds the progress bar goes to 100 % and Mixxx starts slowly, after which it runs normally. Windows 11 with a Scarlett 18i8 interface, ASIO drivers. Sample rate at 48kHz. I’ve changed the Mixxx Sound Hardware settings a couple times and tried again with same results. I’ve tried it with and without the interface. Thanks! It’s a great program. Did not have this issue on my older Windows 10 machine.

### Version

2.3.3

### OS

Windows 11

**Comment by ronso0** [comment]
As mentioned on the forum, please provide the log file [Finding the mixxx.log file · mixxxdj/mixxx Wiki · GitHub](https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file). That will hopefully provide more info than asking a hundred questions about your setup.

**Comment by TimbreAndTone** [comment]
log file
[mixxx.log](https://github.com/mixxxdj/mixxx/files/9561040/mixxx.log)

**Comment by ronso0** [comment]
Do you have "Rescan at startup" ticked in Preferences > Library?
If yes, does it start quicker if you untick it?

**Comment by TimbreAndTone** [comment]
I found it, kind of. Windows 8 compatibility mode. When I first ran MIxxx a few weeks ago I had this problem and ran windows troubleshooter. It suggested I use Windows 8 compatibility mode. So I enable it but it made no difference. Right now, just to be sure, I just hunted down the exe and removed Windows 8 compatibility mode and it now starts normal. When it opens the progress bar still stops at the same spot but only for a second or so. Something Windows 11 is going on there but it seems to have resolved itself.

**Comment by ronso0** [comment]
Grrat, thanks for clarifying!

**Comment by TimbreAndTone** [comment]
Sorry, I found it kind of. Windows 8 compatibility mode. When I first ran MIxxx a few weeks ago I had this problem and ran windows troubleshooter. It suggested I use Windows 8 compatibility mode. So I enable it but it made no difference. Right now, just to be sure, I just hunted down the exe and removed Windows 8 compatibility mode and it now starts normal.
________________________________
