### ISSUE TITLE
Show warning when trying to enable AutoDJ if there's no left & right deck (xfader assign switches)

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#10903]
currently AutoDJ simply refuses to start (or stops if the xfader switches are flpped while AutoDj is running),

**Comment by ronso0** [comment]
https://github.com/mixxxdj/mixxx/blob/main/src/library/autodj/autodjprocessor.cpp#L375
So the goal is to open a QMessageBox if AutoDJ can't start or one of the AutoDJ functions can't be run because there's no deck assigned to left side of the crossfader **and** none for the right side (=`AutoDJProcessor::AutoDJError ADJ_NOT_TWO_DECKS`)

**Comment by ywwg** [comment]
This is nice-to-have but not a blocker for 2.3.4 imho.

**Comment by ronso0** [comment]
Of course not.. Assigning this to 2.3.4 just signals this can be fixed in 2.3 already

**Comment by MetriSomesh** [comment]
hello @ronso0  I wanted to solve this issue and make my first contribution to Mixxx. I need your help I was trying this for 2 days but I am getting this error please help me.

 no instance of overloaded function matches the argument list     argument types are: (AutoDJProcessor *, QString, QString)

**Comment by MetriSomesh** [comment]
![autoDj](https://user-images.githubusercontent.com/80524132/197738198-fe3fbf2e-b82e-4900-bf3b-3649bb6f8110.jpg)
@ronso0  is it correct?

**Comment by daschuer** [comment]
Not completely. Please just issue a PR with the code to discuss. A screenshot does not suite, because we do not see your changes. 

The errors returned by this function are handled here: 
https://github.com/mixxxdj/mixxx/blob/a25c021faf2bf25249ed95a7bbad9f3c4021856f/src/library/autodj/dlgautodj.cpp#L274

I guess it is best to move the message box there. 

Than you should consider to put into the message box and advice how to fix the issue.

**Comment by MetriSomesh** [comment]
@ronso0  Ohh thanks a lot , and am really sorry I am very new to the open source . But you thought me 2 important lessons about how opensource works now I got it

**Comment by MetriSomesh** [comment]
@ronso0 What happened?

**Comment by MetriSomesh** [comment]
@ronso0  Will you close this issue or their is something else left?
