### ISSUE TITLE
Randomly missing playlists in Rekordbox formated drives

### ISSUE THREAD

**Issue by emmetiray** [mixxxdj/mixxx#10923]
When i go to my Rekordbox usb devices in Mixxx there are always some playlists missing. 
![rekordbox01](https://user-images.githubusercontent.com/114584321/192774780-3dc78bcc-0763-4c30-94fe-c75c0aa0486a.JPG)

Don't know if this is a known issue.

Cheers Jakob

**Comment by Holzhaus** [comment]
Thanks for reporting, but some information is missing in this bug report. For example, what OS and what Mixxx version do you use? (GitHub should ask for this information when you choose "Bug Report" when opening a new issue).

In this case, it would also be helpful if you could attach a `mixxx.log` logfile. Ideally, we'd also appreciate if you could attach the PDB file from the USB drive in case it's some issue with our parser.

**Comment by emmetiray** [comment]
thx for the infos. and great work by the way. at the moment i'm using mixxx under win10 but my plan is to install
it on the steam deck. so it will be steamos/arch linux soon.


![mixxx_version](https://user-images.githubusercontent.com/114584321/192844757-e1b3e45c-f153-40c7-b3e5-a6efec57f5d1.JPG)
[pdb.zip](https://github.com/mixxxdj/mixxx/files/9667399/pdb.zip)
[mixxx.log](https://github.com/mixxxdj/mixxx/files/9667419/mixxx.log)

**Comment by emmetiray** [comment]
2.4 windows alpha same problem.

**Comment by emmetiray** [comment]
its working fine on rekordbox and my xdj700 btw.

**Comment by Swiftb0y** [comment]
@emmetiray can you elaborate what playlists are missing exactly? The database is too big to find irregularities by hand. I'd need to know what to look for. Can you tell me what info is missing exactly? Is it just the playlist name or also its content? Does it have anymore identifying data (how many tracks did it contain, what tracks for example, etc). Are these playlists missing completely or just empty like in your screenshot?

**Comment by Holzhaus** [comment]
Maybe this is due to non-ascii chars? For example, is the playlist `BEAT PVP - BEAT PVP 1ª EDIÇÃO`  one of the missing ones?

**Comment by emmetiray** [comment]
@Swiftb0y @Holzhaus 
so in mixxx some playlists are just empty fields and there is nothing in it. there is one really big folder called "oldfolders" with a lot of different playlists inside. mixxx seems to be unable of showing more then 2 correct playlists and 2 unnamed empty fields with nothing in it once they are inside a subfolder. and there are actually two correctly named playlists in the main directory (so not in some sub folder) which in mix are just empty. "mix" and "skeelo". i took some screencaps comparing the playlist structure in mixxx and rekordbox. perhaps that helps? thx.
![mixxx_list01](https://user-images.githubusercontent.com/114584321/193283322-6599001f-b8b5-4555-9d3d-b5648a64e340.jpg)
![mixxx_list02](https://user-images.githubusercontent.com/114584321/193283347-e1fa8845-cf54-4b08-8895-4b8f866bd7c1.jpg)
![rekordbox_list01](https://user-images.githubusercontent.com/114584321/193283371-8b9f85f9-af7f-439a-bf8d-c6544e33d9e1.JPG)
![rekordbox_list02](https://user-images.githu
![emptyplaylists](https://user-images.githubusercontent.com/114584321/193283448-25279147-284d-4104-b782-e1e8767b10bc.jpg)

![rekordbox_list03](https://user-images.githubusercontent.com/114584321/193283407-6fde8e6c-c872-4b55-b13d-b2125c804131.JPG)
busercontent.com/114584321/193283393-8ec2ee74-4a38-45e8-a3ca-c97a18fee67d.JPG)

**Comment by emmetiray** [comment]
if you place the screenshots next to each other you see some big differences...

**Comment by Holzhaus** [comment]
I had another look at this. Is the following list complete?

<details><summary>PDB Playlist Tree</summary>
<pre><code>🗀 15.07.22
    🗎 riot code
🗀 jaki_21_05_22
    🗎 jaki_melow
    🗎 jaki2
    🗎 jaki
🗀 18.05.22
    🗎 plaid - dial p
    🗎 otherstuff
    🗎 wettrax
    🗎 kumo99
🗎 breakcore_gabba
🗎 10.05.22
🗀 grime_hardwave
    🗎 maindir
    🗎 TMSV - Jungle- Vol. 2
    🗎 ian shirtman - The Shirt Tape
    🗎 Deadcrow - Transmission
    🗎 Deadcrow - Lies
    🗎 Deadcrow - 2015-2017
    🗎 BEAT PVP - BEAT PVP 1ª EDIÇÃO
    🗎 Vinnie Grapes - Radiohooligans
🗀 loststuff
    🗎 maindir
    🗎 Tommy Holohan & Casper Hastings
    🗎 The Horrorist
    🗎 peryl
    🗎 Pavel K. Novalis
    🗎 Mode In Gliany
    🗎 Mass-X-Odus
    🗎 Kas_st
    🗎 Jokasti & Nek
    🗎 Jacidorex
    🗎 Homemade Weapons & Red Army
    🗎 Homemade Weapons & Gremlinz
    🗎 Homemade Weapons
    🗎 Hephaistos
    🗎 FSOM
    🗎 FRACTIONS
    🗎 B2
    🗎 Endlec
    🗎 Danilo Incorvaia
    🗎 V_A_ Lars Huismann & Chris Koegler, Alignment, T
    🗎 Ansome
🗀 oldfolders
    🗎 Houndstooth
    🗎 Jiri Ceiver
    🗎 KiNK
    🗎 halloween
    🗎 Justin Berkovi
    🗎 jackwho
    🗎 HTH vs HTH
    🗎 maindir
    🗎 [tiva011] Justin Berkovi - Gravel Heart EP
    🗎 _IGOR
    🗎 acephale
    🗎 15.12.2017
    🗎 v-tracks - limits
    🗎 Vtracks
    🗎 Vectors 3
    🗎 VA-Phuture_Beats_Vol._1-(DCD089-41802)-2CD-FLAC-1995-dL
    🗎 va - kids (soundtrack)
    🗎 usbcd
    🗎 URBAN HOMES - Centres
    🗎 Tube Jerk
    🗎 this machine is broken
    🗎 The Sound of Belgium
    🗎 Terence_Fixmer-Depth_Charged
    🗎 telex - remixes
    🗎 Studio672
    🗎 Sound Architecture
    🗎 schnoerres
    🗎 RussianTechno
    🗎 Rush Hour
    🗎 Quarks - Rehmix (2000)
    🗎 Physically Sick - Physically Sick
    🗎 Point B - Suicide Beauty Spot
    🗎 Physically Sick 2 - Physically Sick 2
    🗎 Palette_All-Stars--After_School_Special-(PAL051)-WEB-2008-dh
    🗎 Mr Ozio - Lambs Anger
    🗎 nachtigal
    🗎 newstuff
    🗎 nachtigal2
    🗎 Mr.Oizo-Analog Worms Attack_224kbps_mFY
    🗎 marcel
    🗎 mix
    🗎 MMODEMM
    🗎 Missile Recordings
    🗎 Marcus Zils Musik
    🗎 Lena Willikens - Phantom Dalia Ep
    🗎 Kate Tempest-Everybody Down-Paul'sBoutique
    🗎 Magazine 18 DigiFiles
    🗎 koelncampus
    🗎 Lorenzo Senni - Persona (2016)
    🗎 khmparty
    🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An-AT-2013-BCC
    🗎 Koenigleopold-Eure_Armut_Kotzt_Mich_An
    🗎 Jeandado - Globale Welt
    🗎 Hotline Miami OST
    🗎 Helena Hauff - Discreet Desires
    🗎 hinterhof
    🗎 Hotline Miami 2 - Soundtrack (2015) 1
    🗎 Gold+Beton 02
    🗎 group A - INITIATION
    🗎 hafen
    🗎 Gewoelbe
    🗎 Halloween2
    🗎 gewoelbe217
    🗎 btf_sommerfest2
    🗎 DrumnBass
    🗎 Good Stuff 7
    🗎 gold+beton
    🗎 Comeme
    🗎 btf_neo
    🗎 Cristian Vogel
    🗎 game tracks
    🗎 btfweihnachts
    🗎 campinc
    🗎 Baumusik
    🗎 Clipping - CLPPNG
    🗎 baumusik's dozen - 1st anniversary compilation
    🗎 btfsommerparty
    🗎 Border Community
    🗎 AZ
    🗎 btf grimme
    🗎 Albrecht Schrader - Leben in der Großstadt
    🗎 Alex_Smoke-Vaporub__HAH001_-Promo_CDS-2008-HFT-1
    🗎 AWeX_-_Its_Our_Future-(SUPER_DJ_2024)-CDM-FLAC-2001
    🗎 antwerpen
    🗎 baumusik - it is a rose- a raisin - a festive compilation
    🗎 acephale27
    🗎 At the Drive-In - Relationship of Command
    🗎 Atelier
    🗎 ADA
    🗎 Alex_Smoke-Blingkered-_HAH005D_-WEB-2009-XXW
    🗎 A-Musik
    🗎 Afreuroparemixes and more
    🗎 Alex_Smoke_-_Paradolia__2006_
🗎 easy
🗎 medium2
🗎 hard2
🗎 SARAHBD
🗎 easy2
🗎 medium
🗎 31.03.2022
🗎 kbirthday
🗎 26.03.2022
🗎 30.07.2022
🗎 05.03.2022
🗎 Acephale_22.01.2022
🗎 heavy
🗎 Acephale30
🗎 neumix
🗎 08.0.8.2022
🗀 Ace_20_08_22
    🗎 dance
    🗎 soft
🗎 Unbetitelte Liste (2)
🗎 mix
🗎 skeelo
🗎 btf lockdown
</code></pre>
</details>

**Comment by emmetiray** [comment]
playlist and folders seem to be complete. :)

**Comment by Holzhaus** [comment]
Ok. that means that [rekordcrate](https://github.com/Holzhaus/rekordcrate) can read the whole list properly, so it's probably not some issue where the unofficial docs are wrong. It's either a bug in the generated kaitai code or some issue with our library feature implementation (more likely IMHO).

**Comment by Swiftb0y** [comment]
I guess the second one too. Browsing the pdb using the kaitai web ide also makes it look like its complete. So I'd blame the library feature implementation too.

**Comment by Holzhaus** [comment]
@emmetiray please have a look at: https://github.com/mixxxdj/mixxx/pull/10955

**Comment by Swiftb0y** [comment]
I think the original issue should have been addressed by #10955. Lets close this for now. Feel free to reopen if not.
