### ISSUE TITLE
Discrete streaming volume

### ISSUE THREAD

**Issue by TristanYoung** [mixxxdj/mixxx#10935]
### Feature Description

I wish there was a dedicated streaming output volume control.

On my setup, I use a pro audio interface, as I prefer the sound (better DAC's compared with the DDJ-SX3 built-in sound).

To get decent streaming out volume, I have to raise MASTER, which raises the volume of my monitors.  Since my interface is set to high volume, and have everything else set up around that (gaming, discord, system sounds, etc.), raising MASTER makes it too loud on my end.

If there was a dedicated streaming out volume control, then I could independently set the streaming and master output without having volume inconsistencies with other software I need to hear.

If anyone has an option I haven't thought of that could help me out, I'm all ears.

**Comment by ronso0** [comment]
Use Main for broadcasting and route the Booth output to your pro audio interface for local playback?

What means "raise Master"? What level do you use, what level is required for broadcasting?

Usually the Mixxx Master/Main gain should remain at 12 o'clock for proper gain staging https://manual.mixxx.org/2.3/chapters/djing_with_mixxx.html?highlight=staging#setting-your-levels-properly-gain-staging.
Personally I have adjusted the ReplayGain level so with channel and Main gain knobs centered (default) both channel and Main levels are around top of the green / mid of the yellow region for most songs and only clip very rarely. For outliers (above and below average) you'd use the channel gain.

**Comment by TristanYoung** [comment]
Thank you for responding Ronso0.

I have the Focusrite Saffire Pro 40 audio interface.  I have two sets of monitors, one for the studio (booth), and one for the dancefloor (master).  I also have the Behringer U-Touch control surface, which I would like to put into service to adjust the various outputs, as it's easier for myself or one of the other DJ's to make adjustments to suit (master, booth and headphones).

The Saffire Mixcontrol software doesn't let me control its faders via midi, so the only other way I can adjust the various outputs with the U-Touch is in Mixxx itself.

So, until I start working on the U-Touch scripts, I can use MASTER for streaming, and Booth for both sets of speakers, but I will very quickly hit the point where I need another output that I can control in Mixxx via midi.

I'm familiar with gain staging.

So, my audio interface is set to maximum output, and all speakers can deliver their full output at any time.  I then adjust Mixxx to suit this environment.  For preventing damage to the speakers, I was thinking of adding a compressor/limiter, but it's really only a safety net, the speakers never get driven that loud.  Installing the audio interface driver in Windows tends to set the Windows volume to max, but I turn off my interface during install to prevent extreme loud sounds.

**Comment by daschuer** [comment]
This issue describes an undesired solution for an issue. 

In Mixxx, the default gain levels are optimized for the recommended streaming loudness of 16 LUFS. This gives enough headroom for mixing and a good noise/signal ratio. All other outputs are derived from this. 

The volume is controlled at the listeners side. A streaming gain knob will likely only mess up the well defined gain level in Mixxx.

The main gain knob is NOT the master volume. 
The Mixxx cannot control the volume without adding "bitcrusher" noise to the signal. That is why volume should be always controlled in the analog domain, preferable at the amplifiers.

Most soundcards have also an analog circuit vor controlling the output volume. This is not yet controllable by Mixxx. For this we have two open issues: 
https://github.com/mixxxdj/mixxx/issues/7942
https://github.com/mixxxdj/mixxx/issues/7944

Would this solve you needs? Can we close this one? Do you have interest to help implemting real volume control in Mixxx?

**Comment by TristanYoung** [comment]
Hi Daschuer,

After reading the two open issues you highlighted, I hope it would help, especially if we can control them via a controller script.

Using ASIO, I notice that Mixxx doesn't appear in Windows's sound mixer.  I don't know if this is important.  I'm not sure if this solution is able to control the sliders in Saffire MixControl.  I don't think I know enough about this solution to be able to answer it with confidence.

For now, I'm using booth output for my studio and dancefloor monitors, and am controlling the volume to them primarily from Saffire MixControl.  I set a pre-determined volume level for each set of monitors, and make small adjustments through either the channel trim (fast and easy for on-the-fly), or the booth control dial (slower, currently need to use the mouse).

I may have to be satisfied with this current setup, since it works, albeit not as on-the-fly user-friendly as I'd like.

I'm not currently set up for developing for Mixxx or other packages, other than javascript controller scripts.  I was contemplating installing the necessary stuff to compile Mixxx, as there's a more important set of changes I'd love to write with regards to library browsing via controller scripts when the Mixxx window isn't focused (not using hotkeys), but with future library changes coming down the line eventually, and my busy 5-year apprenticeship I'm tackling, I've held off on getting deeper into coding.

**Comment by TristanYoung** [comment]
You can close this one.

**Comment by daschuer** [comment]
OK, Thanks.
