### ISSUE TITLE
Graphic interface in ubuntu 22.04

### ISSUE THREAD

**Issue by panchosk8ordead** [mixxxdj/mixxx#10945]
### Bug Description

No render screen in ubuntu 22.04. Mixxx 3.2

![Captura desde 2022-10-06 15-01-01](https://user-images.githubusercontent.com/4378427/194407406-098d6c6e-9dc8-47a5-b732-8ac43a14c988.png)

### Version

2.3

### OS

Ubuntu 22.04

**Comment by panchosk8ordead** [comment]
Attach the log 
Warning [Main]: Configuration file is at version "2.3.2" instead of the current "2.3.3"
ALSA lib pcm_dsnoop.c:601:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Cannot connect to server socket err = No existe el archivo o el directorio
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No existe el archivo o el directorio
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No existe el archivo o el directorio
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.
Warning [Controller]: USB permissions problem (or device error.) Your account needs write access to USB HID controllers.

**Comment by ronso0** [comment]
The Mixxx window seems to small for Deere skin (deck2 is not displayed completely), the spinnies are bigger than expected etc.
Do you use some kind of GUI scaling?

What happens if you maximize the window?

**Comment by panchosk8ordead** [comment]
![image](https://user-images.githubusercontent.com/4378427/194443993-e13b7814-2002-4719-a699-1a6cb515c55a.png)

**Comment by panchosk8ordead** [comment]
This is the maximized screen

**Comment by Gairick52** [comment]
@daschuer i am new to open source can you suggest me some beginner friendly issues

**Comment by panchosk8ordead** [comment]
Hi guys, 
Still not working.
it's my first install. first install from ubuntu 22.04(It's not an upgrade, it's a clean install) and second I Installed Mixxx, and i used the comands of the official page: https://mixxx.org/download/#stable
thank you for your prompt response.

**Comment by daschuer** [comment]
[Gairick52](https://github.com/Gairick52) let's move this discussion to https://mixxx.zulipchat.com/ you may also have a look here: https://github.com/mixxxdj/mixxx/wiki/Bugfix-Workflow

**Comment by daschuer** [comment]
@panchosk8ordead I have no idea what goes wrong at your side do you? Please attache the mixxx.log: https://github.com/mixxxdj/mixxx/wiki/Finding-The-Mixxx.Log-File

**Comment by panchosk8ordead** [comment]
Oh Cool.
[mixxx.log](https://github.com/mixxxdj/mixxx/files/9737675/mixxx.log)

**Comment by ronso0** [comment]
This is not anew install
`Warning [Main]: Configuration file is at version "2.3.2" instead of the current "2.3.3" `

Please try what @daschuer suggested above

> You may start with a fresh alternative settings directory to check the default preferences without loosing your original settings: `mixxx --serringsPath ~/mixxx_experimental`
