### ISSUE TITLE
Pre-Commit changes case of keyword "Object" in JavaScript file to "object"

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#10951]
### Bug Description

While working on #4718, I noted that pre-commit replaces "Object" on many places to "object".

After commiting my code, with active pre-commit, I get errors, due to this changes:
![grafik](https://user-images.githubusercontent.com/64457745/194750430-00b4638a-1cf1-4fb3-9aa6-c6dde180dafb.png)

### Version

Main

### OS

Windows 11

**Comment by JoergAtGithub** [comment]
Found the solution myselft in the eslint-plugin-jsdoc documentation. It's a special case described there.

**Comment by daschuer** [comment]
Do you have some hints in case of others hit this trap?

**Comment by daschuer** [comment]
Thank you.
