### ISSUE TITLE
Searchbox: Auto completion is applied before it is selected

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#10977]
### Bug Description

When I start typing "A" the previous search "ABBA Dancing Queen" is directly applied. This breaks the use case to watch the intermediate results when stopping typing.
 
Compared with Google or Firefox, the Auto-Completion is proposed but not applied. It is applied by "Enter" or selected by "cursor right". I think both will help the Mixxx search box to behave more natural. 

 

### Version

2.4-alpha

### OS

Ubuntu Focal

**Comment by daschuer** [comment]
I think to "fix" this bug, we don't need necessarily change the GUI. It is just the string we send to the actual search. 
In case A***BBA*** the BBA is selected, but only the A should be searched. When pressing "cursor right" or enter, the whole string is send. Will this work for you as well?

**Comment by ronso0** [comment]
> When pressing "cursor right" or enter, the whole string is send.

_Sounds_ simple, would work for me, yes.
Though, searches are also triggered by `m_debouncingTimer::timeout`, and for this to work (**don't** search if completion was not selected) we'd need to hook up to `QComboBox::editTextChanged`/`QLineEdit::textChanged` **and** [`QCompleter::highlighted`](https://doc.qt.io/qt-5/qcompleter.html#highlighted-1) (which would also fire `editTextChanged`) and figure what to do.

I doubt that's easier than figuring out the comleter styling.

**Comment by ronso0** [comment]
I did hook up to these signals, and this is how QCompleter seems to work here:
* type "**c**" > `textChanged("c")` emitted
* the completer finds "cloud", `QCompleter::highlighted("cloud")` emitted
* c**loud** is appended and selected, which fires `textChanged("cloud")`, and evetually `QLineEdit::selectedText` is now also "loud"

**Comment by daschuer** [comment]
This bug causes also that the section keeping logic breaks.
