### ISSUE TITLE
Use search bar in computer folders

### ISSUE THREAD

**Issue by LeonTheOriginal** [mixxxdj/mixxx#11012]
Currently, the search bar is not available when browsing a folder in the "Computer" section of the library. (Tested with Mixxx 2.3.3 on Windows.)
This is problably due to the fact that the search bar only searches tracks which are added to the library database. As Mixxx reads and displays all metadata of the files in this view anyway as a sortable list, it should be no big issue to also search within that temporary list.

**Comment by ronso0** [comment]
Thanks for the headsup!
I did look into this some while ago, but being a total noob with trackmodels I couldn't figure how to (re-)enable the search...

Taking a fresh look now, I see everything is actually already in place and only requires flipping some switches and some minimal adjustments.
I'll open a PR soonish, stay tuned!
