### ISSUE TITLE
GUI grinds to a halt if a track finishes playing as the sync leader

### ISSUE THREAD

**Issue by fayaaz** [mixxxdj/mixxx#11016]
### Bug Description

Steps to reproduce:
- Play a track
- Set it as the sync leader
- Wait for track to finish
- GUI grinds to a halt and is unresponsive.

Workaround:
- Take the track off sync and the GUI eventually returns

### Version

2.4

### OS

Ubuntu 22.04

**Comment by Russe** [comment]
Same issue here with most recent 2.4 alpha version on Xubuntu 22.04
But I never got your workaround to end this situation.
Sometimes the freeze of GUI will also affect Linux system to not respond anymore.
This seems not to happen when sync is off.
It is not related to a connected controller, this will happen also with internal audio output.

**Comment by JoergAtGithub** [comment]
I see this slowdown with Sync enabled single deck at track end also on Windows 11!
I built Main myself. My system is rather fast, but this slows the Mixxx GUI down to an unusable state. After some ~20s it became usable again.

**Comment by Russe** [comment]
Did some more tests. I believe that all my Mixxx GUI and system slow downs belong to this issue.
When sync is disabled I never got such problems when testing.

**Comment by fayaaz** [comment]
PR to address the problem is here: https://github.com/mixxxdj/mixxx/pull/11035

**Comment by Russe** [comment]
Last gig I had some of the GUI issues again, and I'm pretty sure this is related to this bug.
As well I noticed that Mixxx log files raised to 50 and 70 GB so I deleted them immediately because I was running out of space.
It seems when GUI grinds that log files will be flooded with controller communication.
Do you see the same with the large log files?

**Comment by JoergAtGithub** [comment]
Fixed in 2.4 and Main
