### ISSUE TITLE
Track order will not be updated when changing # to ascending/descending

### ISSUE THREAD

**Issue by Russe** [mixxxdj/mixxx#11024]
### Bug Description

1. Create a playlist and add some tracks
2. Click on column header "Title"
3. Click again on column header "Title", now the sort order will be changed from ascending to descending and order of tracks in playlist view will be updated

When doing the same with column header "#" to have a manual sort order, the  playlist view will not be updated. I need to select another playlist first and come back to the above mentioned playlist. Then sort order of tracks will be updated.
Guess there is missing a trigger to update the playlist view when clicking on column header "#".

I'm not sure if this was working in an older version, currently I have no other version for testing.

### Version

2.4.0-alpha-1342

### OS

Xubuntu 22.04.1

**Comment by ronso0** [comment]
Yes, this was a regression that should always be fixed in 2.4.0-alpha-1343 https://launchpad.net/~mixxx/+archive/ubuntu/nightlies/+packages

Can you confirm?

**Comment by Russe** [comment]
This is fixed now with 2.4.0-alpha-1343
Thank you.
