### ISSUE TITLE
Auto Dj Stops during Auto Dj

### ISSUE THREAD

**Issue by VanderheidenDesign** [mixxxdj/mixxx#11027]
### Bug Description

When I first downloaded the mixxx software I never had a issue. The Auto Dj would play all the way through. But recently it will just stop in the middle of the playlist. No specific song it just stops. I was wondering if there is a some new update? Thank you!

### Version

2.3.3

### OS

Windows

**Comment by ronso0** [comment]
That bug should have been fixed in 2.3.3 by https://github.com/mixxxdj/mixxx/pull/4698

Any new update is made available on https://mixxx.org/download/
If you like to get notified of new updates subscribe to the newsletter on mixxx.org

**Comment by VanderheidenDesign** [comment]
thank you!

**Comment by daschuer** [comment]
Can you confirm that you have experienced the issue with 2.3.2 and it is fixed with 2.3.3 or do you suffer another issue that is not yet fixed?
