### ISSUE TITLE
Show units of effect parameter knobs 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11033]
### Feature Description

This may be an addition to https://github.com/mixxxdj/mixxx/issues/9022
Currently only the value is shown. It would be very useful to see the unit is addition like 
"-6 dB" 
or 
"0.2 s" 

We already have an unused stub for this: 
https://github.com/mixxxdj/mixxx/blob/b0f19c31018ff66ff464b8dc073d6bd176de8660/src/effects/backends/effectmanifestparameter.h#L37

But I think we should adopt the LV2 system: 
http://lv2plug.in/ns/extensions/units#unit

**Comment by ronso0** [comment]
@daschuer Could you give some hints re "adopt the LV2 system"?

**Comment by daschuer** [comment]
When you follow the link you find a list of units including their rendering. We currently maintain a different incomplete list in UnitsHint enum. 
My proposal is to replace our enum with the LV2 one.

**Comment by ronso0** [comment]
Yes, understood. My question was rather whether you propose to **a)** adopt the LV2 map (replacing existing Mixxx enum, change all built-in effects' manifests) or **b)** somehow map LV2 units to the extended Mixxx list.
The latter sounds complicated and means we'd have two lists / standards. So I'd go with **a**

Second question that arises: how to translate the enum to dispay strings?
I never did that, and it seems there are a few ways to accomplish this. However, for sake of consistency, I'd use a switch-case function like 
https://github.com/mixxxdj/mixxx/blob/f96d16875efcb86bafc6bc7fa299db863ec071e7/src/effects/backends/effectmanifestparameter.h#L61-L66

**Comment by ronso0** [comment]
Though, a QMap looks nicer, but requires a translator:
``` c++
QMap<UnitsHint, QString> unitStringsMap {
    {UnitsHint::Unknown, ""},
    {UnitsHint::Beat, "Beat"},
    {UnitsHint::Beats, "Beats"},
    {UnitsHint::Bar, "Bar"},
    {UnitsHint::BPM, "BPM"},
    {UnitsHint::Cent, "Cent"},
    {UnitsHint::Hz, "Hz"}
};

const QString UnitsHintToString(const UnitsHint unitHint) {
    return unitStringsMap.find(unitHint);
}
```

**Comment by ronso0** [comment]
I'll do a quick test with:
* existing `enum class UnitsHint : int` extended by LV2 units
* `QMap<QString, EffectManifestParameter::UnitsHint> lv2ToUnitsHintEnum`
* `QMap<EffectManifestParameter::UnitsHint, QString> unitsHintToDisplayString`
* `const QString UnitsHintToString(const UnitsHint unitHint) { return unitStringsMap.find(unitHint); }`
