### ISSUE TITLE
Cover Art Fetcher: cache fetched images per track

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11084]
### Feature Description

#4851
Selecting a TagFetcher result instantly fetches the cover image. Thus, selecting multiple results to find the best-matching cover (actual picture, size, quality) would needlessly re-download images that were already viewed.

Let's cache the images per track. We can either use a strict memory limit or just clear the cache once another track is loaded.

**Comment by daschuer** [comment]
I think we should do both, use a separate cache only for the dialog and clear it if we go to another track.

**Comment by ywwg** [comment]
@ronso0 is this really an item for 2.4? Adding a new caching layer sounds risky and complex at this late date.

**Comment by ronso0** [comment]
I attached it to 2.4 because it makes the new cover fetcher complete. By now it will delay the release, so it can go to 2.4.1.
The changes of #12301 are not risky, please take a look at the essence in src/library/dlgtagfetcher.cpp https://github.com/mixxxdj/mixxx/pull/12301/commits/178b2245629b9b86456f0753435dd9ea81e55a14#diff-679b7c04399af1221df243a3d7555a986537c6a297d7d88f2ca4a03d0b325803
But we need to test how it performs of course.
