### ISSUE TITLE
Navigation wraparound in library tracks list

### ISSUE THREAD

**Issue by robbert-vdh** [mixxxdj/mixxx#11088]
### Feature Description

I just started using Mixxx and I'm seriously impressed by how well it works. One thing I did notice was that there is no wraparound in the library. When browsing a collection of tracks sorted by key (which Mixxx sorts according to the circle of fifths, awesome), you can't easily go from the end of the list back to the beginning or the other way around without reaching for a mouse or keyboard.

Is this desirable behavior? I can submit a PR, but I thought I'd ask first. This would make navigating the library with a controller much better especially when sorting by key. I did see [some reference to this](https://github.com/mixxxdj/mixxx/blob/8affbbb2c5e429b9aa8e6ea7410b65c8a50e46b1/src/library/librarycontrol.cpp#L638-L642) in the library implementation already. If this behavior was previously deemed to be confusing, could it maybe just become an option in the preferences?

**Comment by daschuer** [comment]
Yes, it does make sense in case of sorting by key. I think we need to do some usability test to find the sweet spot between annoying and useful. A preferences option should be the last resort. 
Go ahead if you have interest ti implement this. 
Here some general hints: https://github.com/mixxxdj/mixxx/wiki/Bugfix-Workflow

**Comment by poelzi** [comment]
I implemented this at my library rework, guess this got lost when the branch was updated to master.

**Comment by robbert-vdh** [comment]
Oh I hadn't seen that. #11090 adds it back to both the `[Library],MoveVertical` action that can be mapped to controllers and cursor key navigation (without breaking support for shift/ctrl+cursor keys). And anything else that relies on `moveCursor()`.
