### ISSUE TITLE
mixxx crash on macOS ventura

### ISSUE THREAD

**Issue by Vincenzo160468** [mixxxdj/mixxx#11097]
### Bug Description

Last login: Mon Nov 28 12:26:16 on console
vincenzomatalucci@MBP-di-Vincenzo ~ % /Applications/mixxx.app/Contents/MacOS/mixxx ; exit;
Setting Qt plugin search path to: "/Applications/mixxx.app/Contents/PlugIns"
Warning [Main]: Configuration file is at version "2.3.0" instead of the current "2.3.3"
Warning [Main]: Failed to load "qt" translations for locale "it_IT" from "/Users/mixxx/bs-2.3-mac/amd64/environment/2.3-j00026-0b1209e3-osx10.12-x86_64-release/Qt-5.12.3/translations"
Critical [Main]: <QNSWindow: 0x7f986d0586e0; contentView=<QNSView: 0x7f986d0582e0; QCocoaWindow(0x600003ac2e10, window=QWidgetWindow(0x6000028974e0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986348b150; contentView=<QNSView: 0x7f986348ad50; QCocoaWindow(0x600003a7ce70, window=QWidgetWindow(0x6000028937e0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986338f830; contentView=<QNSView: 0x7f986338f430; QCocoaWindow(0x600003a78580, window=QWidgetWindow(0x6000028a0240, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9863390270; contentView=<QNSView: 0x7f986338fe70; QCocoaWindow(0x600003a78790, window=QWidgetWindow(0x6000028a0ba0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9863498120; contentView=<QNSView: 0x7f9863497d20; QCocoaWindow(0x600003a7d760, window=QWidgetWindow(0x60000289e940, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986d0b9ea0; contentView=<QNSView: 0x7f986d0b9aa0; QCocoaWindow(0x600003ac39c0, window=QWidgetWindow(0x6000028b3060, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986d0d1dd0; contentView=<QNSView: 0x7f986d0d19d0; QCocoaWindow(0x600003ac3a70, window=QWidgetWindow(0x6000028b6f40, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986d0d81c0; contentView=<QNSView: 0x7f986d0d7f10; QCocoaWindow(0x600003a00000, window=QWidgetWindow(0x6000028b7780, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9866be7570; contentView=<QNSView: 0x7f9866be7170; QCocoaWindow(0x600003aca940, window=QWidgetWindow(0x600002898cc0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9863393200; contentView=<QNSView: 0x7f9863392e00; QCocoaWindow(0x600003a789a0, window=QWidgetWindow(0x6000028a2160, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98634a0da0; contentView=<QNSView: 0x7f98634a09a0; QCocoaWindow(0x600003a7e050, window=QWidgetWindow(0x600002840960, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98634fa3c0; contentView=<QNSView: 0x7f98634f9fc0; QCocoaWindow(0x600003a7eaa0, window=QWidgetWindow(0x60000284f240, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986434d4e0; contentView=<QNSView: 0x7f986434d0e0; QCocoaWindow(0x600003a01b80, window=QWidgetWindow(0x6000028664c0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986339ded0; contentView=<QNSView: 0x7f986339dad0; QCocoaWindow(0x600003a78f20, window=QWidgetWindow(0x600002868180, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9864373e00; contentView=<QNSView: 0x7f9864373a00; QCocoaWindow(0x600003a01b80, window=QWidgetWindow(0x60000286e6a0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98633a16c0; contentView=<QNSView: 0x7f98633a12c0; QCocoaWindow(0x600003a79130, window=QWidgetWindow(0x600002868ea0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9859a11160; contentView=<QNSView: 0x7f9859a10eb0; QCocoaWindow(0x600003a7f440, window=QWidgetWindow(0x600002852460, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98633f9960; contentView=<QNSView: 0x7f98633f9560; QCocoaWindow(0x600003a79b80, window=QWidgetWindow(0x60000287b900, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986440acf0; contentView=<QNSView: 0x7f986440a8f0; QCocoaWindow(0x600003acab50, window=QWidgetWindow(0x6000028bfea0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98633ff930; contentView=<QNSView: 0x7f98633ff680; QCocoaWindow(0x600003a7a1b0, window=QWidgetWindow(0x60000287dbc0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9859a36fd0; contentView=<QNSView: 0x7f9859a36bd0; QCocoaWindow(0x600003a7f440, window=QWidgetWindow(0x600002805bc0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986440de80; contentView=<QNSView: 0x7f986440b730; QCocoaWindow(0x600003acacb0, window=QWidgetWindow(0x6000028011a0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98644176b0; contentView=<QNSView: 0x7f9864417400; QCocoaWindow(0x600003acb5a0, window=QWidgetWindow(0x6000028036c0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f986455fab0; contentView=<QNSView: 0x7f986455f800; QCocoaWindow(0x600003a7ac00, window=QWidgetWindow(0x600002818060, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9864c3f410; contentView=<QNSView: 0x7f9864c3f010; QCocoaWindow(0x600003a20e70, window=QWidgetWindow(0x600002722340, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9864892cf0; contentView=<QNSView: 0x7f98648928f0; QCocoaWindow(0x600003a161b0, window=QWidgetWindow(0x6000027268e0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f9864d15d50; contentView=<QNSView: 0x7f9864d15950; QCocoaWindow(0x600003ad44d0, window=QWidgetWindow(0x60000272c480, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
Critical [Main]: <QNSWindow: 0x7f98643a7db0; contentView=<QNSView: 0x7f98643a79b0; QCocoaWindow(0x600003a00790, window=QWidgetWindow(0x600002735ce0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
libc++abi: terminating
zsh: abort      /Applications/mixxx.app/Contents/MacOS/mixxx

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      13 completed.

[Processo completato]

### Version

2.3.3

### OS

macOS ventura

**Comment by daschuer** [comment]
Is this still an issue when using the latest development build towards 2.3.4? 
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-99-g53d43ccb2a-macosintel.dmg

**Comment by Vincenzo160468** [comment]
No issue using 2.3.4.  I'm waiting for new official release. Do you think I can try mixxx-2.3.3-99-g53d43ccb2a-macosintel.dmg?
Thank you for your interesting..

Best regards

**Comment by daschuer** [comment]
Yes, you can use that.
