### ISSUE TITLE
Rubberband R3 time stretching algorithm adds a fade in/eats the transient on playback start

### ISSUE THREAD

**Issue by robbert-vdh** [mixxxdj/mixxx#11093]
### Bug Description

I just noticed the new time stretching option on the main branch added in #4853. It sounds much better than the existing two options, but I'm finding it not suitable for most applications as it seems to kill the initial transient on playback for me by adding a quite lengthy fade in. I searched through the issue tracker but I couldn't find anything referencing this. Here's a demonstration using all three time stretching algorithms:

https://user-images.githubusercontent.com/748520/203995909-82995781-8b21-4b94-9fb9-5f4b2563c774.mp4

Out of the three the v2 Rubber Band one sounds the closest to what I'd expect. The SoundTouch one is also fine, but the Rubber Band v3 kills the transient completely.

### Version

The branch from #11090, or 8affbbb2c5 on the main branch

### OS

Arch Linux

**Comment by MarcPlace** [comment]
Can confirm this behaviour here with Rubberband R3 when using time stretching, that it cuts off (or eats) the first beat on playback start. If you listen closely, even R2 cuts it of a bit. But the impact is very small and it's still OK to work with (compared to R3).
I'm using commit 9965d55f6e00cd1982f78cf09ac6196887869487 (main branch) and Gentoo Linux.

**Comment by daschuer** [comment]
A workaround would be to "settle" Rubberband with the samples before the cue point to move the ramp up out of the hear-able range. We have such a code for SoundTouch and a workaround in Mixxx: https://github.com/mixxxdj/mixxx/blob/6fbc27d653772b438c41c41015af010a00eca6b2/src/engine/bufferscalers/enginebufferscalest.cpp#L117

**Comment by robbert-vdh** [comment]
I just started looking into this when I thought to check what other rubberband time stretching implementations do. I created a quick .wav file containing a train of DC pulses to test with ([the sample](https://github.com/mixxxdj/mixxx/files/10171485/dc-train.zip), if anyone needs it). I noticed in Mixxx this starting playback at the edge of the DC block adds a relatively lengthy fade in from what looks like a linear phase filter or (more likely) a window function used in an STFT process. I then found out that I already had a `rubberband-r3` CLI tool installed. Running that with `rubberband-r3 --fine --realtime --tempo 1 dc-train.wav dc-train-resampled.wav` should behave the same as in Mixxx, but the `rubberband-r3` version doesn't have the long fade in. I then dug op the source code of that command line tool and spotted this:

https://github.com/breakfastquay/rubberband/blob/8edf1723c4f8a8f3b558607b2b1055c23aed48cb/main/main.cpp#L776-L800

As I already expected at this point, in realtime mode you need to pad the input with a certain number of samples and subsequently discard the outputs from processing those samples after resetting rubberband. With these settings that's 2048 samples, which corresponds nicely with the fade in I'm seeing. The [docs](https://breakfastquay.com/rubberband/code-doc/) and [faq](https://breakfastquay.com/rubberband/integration.html#faqs) also mention that you need to do this. I'll implement this tomorrow, here's hoping it's actually as simple as it seems ha.

**Comment by uklotzde** [comment]
> As I already expected at this point, in realtime mode you need to pad the input with a certain number of samples and subsequently discard the outputs from processing those samples after resetting rubberband.

A comment in the SoundTouch code confirms this wrong assumption:

https://github.com/mixxxdj/mixxx/blob/8f5ed3f7df82dc1ad74b67104edebe77b47f3007/src/engine/bufferscalers/enginebufferscalest.cpp#L24

**Comment by robbert-vdh** [comment]
It was indeed as simple as I hoped it would be. The initial transient plays back just fine now, even with this pulse train sample. Did some more minor clean up while I was at it. I'll submit a PR soon:

https://user-images.githubusercontent.com/748520/206300404-02d89b5e-1f2d-426c-9574-7b2550fe2743.mp4
