### ISSUE TITLE
Sort by column

### ISSUE THREAD

**Issue by conducator** [mixxxdj/mixxx#11107]
### Bug Description

Hi, while I can sort songs by clicking any column in the Playlists visualization (duration, key, artist, album, or any other), I can't do the same in the Autodj window, so I can't mix matching the key, 

### Version

2.3.3

### OS

Windows 11

**Comment by ronso0** [comment]
In AutoDJ tracks are always sorted by # so the tracks should always be in the order they'll be played (and removed / requeued) to aoid any confusion.

The AutoDJ view is not meant for manual mixing, if you want to do so simply copy all tracks to a separate playlist.

**Comment by conducator** [comment]
Well this feature would be nice to have in Autodj (sort columns like in Playlist view) not for manual mixing (if it's called Autodj it's not for manual mixing...). You could use Autodj for harmonic mixing too and not only using always the same # tracks

**Comment by ronso0** [comment]
Hmm for mixing by key that makes sense, probably also for in- or decreasing the BPM during an AutoDJ mix.

However, if sorting was enabled, and the position # could be adjusted when sorting, if you had the tracks carefully ordered before, and didn't intend to change the play order, there is no way to restore the previous order.
How could the UI be adjusted to avoid mistakes like that?

**Comment by daschuer** [comment]
In Playlists, you can sort by any column, but the position # of the track in the playlist is kept. So when you sort by # everything is back in consecutive order. 
If we do the same at Auto DJ, you loose track of which track is played next, because it is no longer the topmost. That's why this type of sorting is disabled. 

Playing the tracks by key is another type of sorting. It is more like Shuffle, which we already have. Schuffle with additional rules. 
 
I can imagine to implement that, but that is nothing we should do by a column click.

**Comment by daschuer** [comment]
This duplicates: 
https://github.com/mixxxdj/mixxx/issues/6509
https://github.com/mixxxdj/mixxx/issues/6335

The same for searching:
https://github.com/mixxxdj/mixxx/issues/6408

Workaround: 
https://github.com/mixxxdj/mixxx/issues/6598

**Comment by conducator** [comment]
Hi, I'm not an expert programmer, I was only used to mix by sorting columns, so that I was easily able to vary from mixing according to harmonic principles, then switcth to mixing by increasing bpm (or decreasing bpm), then jump from latin to disco or rock or house, or even by sorting by stars # (once you have all your tracks accordingly complete with all infos) by simply clicking the desired column. I hope this will be possible as Mixxx is much faster than VDJ for example, it starts much faster (my pc is Ryzen 9/5950x, 48Gb ram and 16Gb ramdisk, GTX 2060S, my library is more than 48k tracks), I can say that VDJ is not as much ready to use as Mixxx. Last but not least, even if "you loose track of which track is played next, because it is no longer the topmost", as daschuer is correctly pointing out, this is of non relevance since you are choosing another criteria for your mixing, so that your next track will actually be the one in the new visualization.
