### ISSUE TITLE
Mixxx does not scan files with some Unicode characters on macOS

### ISSUE THREAD

**Issue by floppydiskette** [mixxxdj/mixxx#11103]
### Bug Description

Mixxx will scan all folders but will not add songs to library if they contain certain unicode characters in the filename. Unicode in the metadata is fine, however the song will not get scanned if it's in the filename (e.g. "xXXi_wud_nvrstøp_ÜXXx" will be scanned ONLY if the filename does not contain 'Ü', the ø is fine for some reason).  
  
I have written a short one-line bash script to remove troublesom characters from my Music folder, however I would not recommend running this unless you want your filenames to look like `"aa - aaai_wud_nvrstøp_aaaa (aemia) afeat. aommy aash & aannah aiamond].flac"`  
  
`find . -exec bash -c "mv \"{}\" \"\$(echo \"{}\" | sed 's/[\x00-\xFF]/a/g')\"" \;`

### Version

2.3.3 & 2.4.0 alpha

### OS

macOS Monterey, M1 Processor

**Comment by daschuer** [comment]
Is there something suspicious in the mixxx.log file after a failing scan? https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file#macos
Is the affected file visible when browsing to it using the Computer library feature of Mixxx? 
Can you play such tracks when dropping them to the decks? 

We have a duplicated issue here: 
https://github.com/mixxxdj/mixxx/issues/9892

The workaround was to rename the track with finder: 
https://github.com/mixxxdj/mixxx/issues/9892#issuecomment-1225428782

**Comment by daschuer** [comment]
It is interesting if the log file contains "ImportFilesTask: Skipping inaccessible file"
https://github.com/mixxxdj/mixxx/blob/f2d670edeb483efb066bf7f00255d01df2f0017c/src/library/scanner/importfilestask.cpp#L48

You may also add additional qDebug here: 
https://github.com/mixxxdj/mixxx/blob/f2d670edeb483efb066bf7f00255d01df2f0017c/src/library/scanner/recursivescandirectorytask.cpp#L59

**Comment by foss-** [comment]
No longer able to reproduce. `Ænima` by Tool was added to library and search also works as expected. Please close and re-open should this persist for you.

@floppydiskette can you confirm this finding?
