### ISSUE TITLE
Mixxx cannot scan library on macOS Monterey

### ISSUE THREAD

**Issue by floppydiskette** [mixxxdj/mixxx#11102]
### Bug Description

When I attempt to press the "Rescan Library" button, no window pops up and nothing changes despite having added files to my Music folder

### Version

2.3.3

### OS

macOS Monterey, M1 Processor

**Comment by floppydiskette** [comment]
## Update
I was able to fix this temporarily by deleting all track metadata, this is not favourable though.

**Comment by ronso0** [comment]
so this is a symptom of #11103 and can be closed?
