### ISSUE TITLE
Unexpected results when filtering by year

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11113]
### Bug Description

Filtering by an integer year only covers the special case where the corresponding `date` field contains an integer value. All other tracks are ignored.

### Example

`year:2022`

#### Found

- `2022`

#### Not found

- `2022-12-06`
- `2022-05-19T07:00:00Z`

And this is only a small subset of what ID3v2 considers as valid. Surprisingly, these tracks are found when using the filter `year:2022-` with a trailing slash. ~~Probably because the search is now falling back to a string-like match.~~ The filter condition is silently ignored and simply all tracks are found, which is even worse.

### Version

2.3

**Comment by ronso0** [comment]
> And this is only a small subset of what ID3v2 considers as valid.

@uklotzde Please share your source. [For 2.3 I only found TYER](https://id3.org/id3v2.3.0):
"The 'Year' frame is a numeric string with a year of the recording. This frames is always four characters long (until the year 10000)."

Assuming that any 'year' string has just _one_ four-char numerical field (at string index 0), a quick fix is to move "year" [from `m_numericFilters` to `m_textFilters`](https://github.com/mixxxdj/mixxx/blob/736627c4af28e2e9393fc2623ade93b37cb02b08/src/library/searchqueryparser.cpp#L12-L22).

**Comment by uklotzde** [comment]
<https://id3.org/id3v2.4.0-structure>
> Hence valid timestamps  are  yyyy, yyyy-MM, yyyy-MM-dd, yyyy-MM-ddTHH, yyyy-MM-ddTHH:mm and yyyy-MM-ddTHH:mm:ss.

**Comment by uklotzde** [comment]
The raw `year` field must be treated and preserved as an arbitrary string as it is. But without parsing time stamps when importing file metadata and storing them in an appropriate format in the database this could never work as intended.

**Comment by daschuer** [comment]
It is a bit complicated because of legacy: 
TDRC (ID3v2.4) = TYER + TDAT (ID3v2.3)

See: 
https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id31

**Comment by uklotzde** [comment]
For extracting meaningful data you need to parse those values liberally and then store them in your database: https://gitlab.com/uklotzde/aoide-rs/-/blob/dev/crates/media/src/util/mod.rs#L323

Don't expect that anyone adheres to specifications. You will find all kinds of values in user data.
