### ISSUE TITLE
Latency introduced by the time stretching algorithms isn't compensated for

### ISSUE THREAD

**Issue by robbert-vdh** [mixxxdj/mixxx#11125]
### Bug Description

This is a follow up on conversation about dropouts when disabling scratching on [Zulip](https://mixxx.zulipchat.com/#narrow/stream/113295-controller-mapping/topic/engine.2EscratchDisable.28.29.20during.20playback.20results.20in.20hickup). Mixxx doesn't seem to compensate for the latency introduced by the time stretching algorithms. The result is that keylock will delay a track ever so slightly. You can clearly hear that if you double a track playing at 100% rate and then enable keylock on only one of the two tracks. Enabling keylock also causes a short period of silence as a result and disabling keylock causes the track to jump forward ever so slightly. You'll also hear the same thing happening when scratching with a controller. When keylock gets reenabled after disabling scratching you'll hear the same dropout. And it also happens when beat jumping with keylock enabled.

Note that this is separate from the issue fixed by #11120, without which the issue would be made even more obvious but it still exists regardless.

### Version

main branch, 0826902

### OS

Arch Linux

**Comment by daschuer** [comment]
Unfortunately the delay depends on the pitch for both, rubberband and soundtouch.

**Comment by robbert-vdh** [comment]
I don't know about SoundTouch (it sounds like it's granular so the delay may be variable), but the latency doesn't depend on the tempo or pitch with Rubber Band. Without looking at its source code I'm 98% sure it uses an STFT, and the reported initial delay and padding size being 2048 kind of confirms that (and those numbers are consistent regardless of tempo and pitch settings as you'd expect).

I messed around a bit and modified #11120 to compensate for the latency by reading by first processing an entire window of past samples through Rubber Band. The way it works now is a hack and I definitely wouldn't upstream it in its current state, but it does compensate for the latency and outside of the expected phase differences a doubled track keeps playing in sync when you toggle keylock on one of the tracks.

**Comment by robbert-vdh** [comment]
Here's a demonstration before and after this change.

This is the current behavior:

https://user-images.githubusercontent.com/748520/207369884-434d3b4f-a10d-496f-990b-38fda93e2c86.mp4

And this is the same setup with my change to the Rubber Band time stretcher (and the readahead manager, that was part of my hack heh):

https://user-images.githubusercontent.com/748520/207369937-6aa8021e-e12c-4305-ba2f-f7db780e6ec0.mp4

With these changes there's still a small discontinuity on scratch disable, but it's much better than before. I'll keep trying things to see if I can improve this further.

**Comment by daschuer** [comment]
Which version and algorithm of rubberband is used in this test?

**Comment by robbert-vdh** [comment]
This should no longer be an issue in the 2.4 branch.
