### ISSUE TITLE
HID not recognized on Arch (Traktor S2 MK2)

### ISSUE THREAD

**Issue by fbmoose48** [mixxxdj/mixxx#11138]
### Bug Description

I'm trying to resolve what I think is a udev issues on Arch for my Traktor S2 MK2, but the guidance in the mixxx-usb-uaccess.rules files is not clear to me. The controller is not recognized. I created both `/etc/udev/rules.d/mixxx-usb-uaccess.rules` and `/etc/udev/rules.d/69-mixxx-usb-uaccess.rules`. Any guidance would be appreciated. I can provide more mixxx.logs if that helps

### Version

2.3.3

### OS

Arch

**Comment by fbmoose48** [comment]
log

`Debug [Main]: SoundSourceProxy - Registering SoundSource providers
Debug [Main]: SoundSourceProxy - Registering platform and fallback SoundSource providers
Debug [Main]: SoundSourceProviderRegistry - Registering provider "FFmpeg"
Info [Main]: SoundSourceFFmpeg - Disabling untested input formats: aa, aax, ac3, ace, acm, act, adf, adp, ads, adx, aea, afc, aix, alp, amr, amrnb, amrwb, anm, apc, ape, apm, apng, aptx, aptx_hd, aqtitle, argo_asf, argo_brp, argo_cvg, asf, asf_o, ass, ast, au, av1, avi, avisynth, avr, avs, avs2, avs3, bethsoftvid, bfi, bin, bink, binka, bit, bitpacked, bmv, bfstm, brstm, boa, c93, caf, cavsvideo, cdg, cdxl, cine, codec2, codec2raw, concat, dash, data, daud, dcstr, derf, dfa, dfpwm, dhav, dirac, dnxhd, dsf, dsicin, dss, dts, dtshd, dv, dvbsub, dvbtxt, dxa, ea, ea_cdata, eac3, epaf, ffmetadata, filmstrip, fits, flac, flic, flv, live_flv, 4xm, frm, fsb, fwse, g722, g723_1, g726, g726le, g729, gdv, genh, gif, gsm, gxf, h261, h263, h264, hca, hcom, hevc, hls, hnm, ico, idcin, idf, iff, ifv, ilbc, image2, image2pipe, alias_pix, brender_pix, imf, ingenient, ipmovie, ipu, ircam, iss, iv8, ivf, ivr, jacosub, jv, kux, kvag, lmlm4, loas, luodat, lrc, lvf, lxf, mca, mcc, matroska,webm, mgsts, microdvd, mjpeg, mjpeg_2000, mlp, mlv, mm, mmf, mods, moflex, mpc, mpc8, mpeg, mpegts, mpegtsraw, mpegvideo, mpjpeg, mpl2, mpsub, msf, msnwctcp, msp, mtaf, mtv, musx, mv, mvi, mxf, mxg, nc, nistsphere, nsp, nsv, nut, nuv, obu, ogg, oma, paf, alaw, mulaw, vidc, f64be, f64le, f32be, f32le, s32be, s32le, s24be, s24le, s16be, s16le, s8, u32be, u32le, u24be, u24le, u16be, u16le, u8, pjs, pmp, pp_bnk, pva, pvf, qcp, r3d, rawvideo, realtext, redspark, rl2, rm, roq, rpl, rsd, rso, rtp, rtsp, s337m, sami, sap, sbc, sbg, scc, scd, sdp, sdr2, sds, sdx, film_cpk, ser, sga, shn, siff, simbiosis_imx, sln, smk, smjpeg, smush, sol, sox, spdif, srt, psxstr, stl, subviewer1, subviewer, sup, svag, svs, swf, tak, tedcaptions, thp, 3dostr, tiertexseq, tmv, truehd, tta, txd, tty, ty, v210, v210x, vag, vc1, vc1test, vividas, vivo, vmd, vobsub, voc, vpk, vplayer, vqf, w64, wc3movie, webm_dash_manifest, webvtt, wsaud, wsd, wsvqa, wtv, wve, xa, xbin, xmv, xvag, xwma, yop, yuv4mpegpipe, bmp_pipe, cri_pipe, dds_pipe, dpx_pipe, exr_pipe, gem_pipe, gif_pipe, j2k_pipe, jpeg_pipe, jpegls_pipe, jpegxl_pipe, pam_pipe, pbm_pipe, pcx_pipe, pfm_pipe, pgmyuv_pipe, pgm_pipe, pgx_pipe, phm_pipe, photocd_pipe, pictor_pipe, png_pipe, ppm_pipe, psd_pipe, qdraw_pipe, qoi_pipe, sgi_pipe, svg_pipe, sunrast_pipe, tiff_pipe, vbn_pipe, webp_pipe, xbm_pipe, xpm_pipe, xwd_pipe, libmodplug
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aac" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aif" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aiff" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "m4v" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mov" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp4" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "m4a" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "3gp" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "3g2" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mj2" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp3" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wav" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wv" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "MAD: MPEG Audio Decoder"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp3" for provider "MAD: MPEG Audio Decoder" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "MODPlug"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mod" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "med" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "okt" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "s3m" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "stm" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "xm" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "it" for provider "MODPlug" with priority 3 (default)
Info [Main]: SoundSourceSndFile - Disabling OGG decoding for "libsndfile-1.1.0"
Debug [Main]: SoundSourceProviderRegistry - Registering provider "libsndfile"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aif" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aiff" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "caf" for provider "libsndfile" with priority 2 (lower)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "flac" for provider "libsndfile" with priority 2 (lower)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wav" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProxy - Registering reference SoundSource providers
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org libFLAC"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "flac" for provider "Xiph.org libFLAC" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org OggVorbis"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "ogg" for provider "Xiph.org OggVorbis" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org libopusfile"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "opus" for provider "Xiph.org libopusfile" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "WavPack"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wv" for provider "WavPack" with priority 4 (higher)
Debug [Main]: Mixxx 2.3.3 (git unknown; built on: Nov  1 2022 @ 22:32:22; flags: -pipe;-O3;-ffast-math;-funroll-loops;-fomit-frame-pointer;-mtune=generic;-Wall;-Wextra;$<$<COMPILE_LANGUAGE:CXX>:-Woverloaded-virtual>;-Wfloat-conversion;-Werror=return-type) is starting...
Debug [Main]: Compile time library versions:
Debug [Main]: Qt: 5.15.7
Debug [Main]: libshout: 2.4.1
Debug [Main]: PortAudio: 1246976 PortAudio V19.7.0-devel, revision unknown
Debug [Main]: RubberBand: 3.1.0
Debug [Main]: SoundTouch: 2.3.1
Debug [Main]: TagLib: 1.13.0
Debug [Main]: ChromaPrint: 1.5.1
Debug [Main]: Vorbis: Xiph.Org libVorbis 1.3.7
Debug [Main]: libsndfile: libsndfile-1.1.0
Debug [Main]: FLAC: 1.4.2
Debug [Main]: libmp3lame: 3.100
Debug [Main]: QStandardPaths::writableLocation(HomeLocation): "/home/user"
Debug [Main]: QStandardPaths::writableLocation(DataLocation): "/home/user/.local/share/Mixxx"
Debug [Main]: QCoreApplication::applicationDirPath() "/usr/bin"
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Configuration file is at the current version "2.3.3"
Info [Main]: BroadcastSettings - Found 1 profile(s)
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Found and will use default keyboard preset "/usr/share/mixxx/keyboard/en_US.kbd.cfg"
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Skipping loading of translations because the locale is 'en' or 'en_US'.
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: No fonts directory found in "/usr/share/mixxx/"
Info [Main]: DbConnection - Available drivers for database connections: ("QIBASE", "QSQLITE", "QMARIADB", "QMYSQL", "QMYSQL3", "QODBC", "QODBC3", "QPSQL", "QPSQL7", "QTDS", "QTDS7")
Info [Main]: DbConnectionPool - Cloned thread-local database connection "MIXXX-1" QSqlDatabase(driver="QSQLITE", database="file:///home/user/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Info [Main]: MixxxMainWindow - Connecting to database
Info [Main]: MixxxMainWindow - Initializing or upgrading database schema
Info [Main]: SchemaManager - Database schema is up-to-date at version 32
Debug [Main]: JACK client name set
Debug [Main]: EngineNetworkStream - addWorker: worker added
Debug [Main]: EngineNetworkStream - worker slots used: "1 out of 16"
Debug [Main]: BroadcastManager - addConnection: created connection for profile "Connection 1"
Info [Main]: GlobalTrackCache - Creating instance
Info [Main]: TrackCollection - Connecting database
Info [Main]: TrackCollectionManager - Starting library scanner thread
Debug [LibraryScanner 1]: LibraryScanner - Entering thread
Info [LibraryScanner 1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-2" QSqlDatabase(driver="QSQLITE", database="file:///home/user/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Debug [LibraryScanner 1]: LibraryScanner - Event loop starting
Info [Main]: TrackCollection - Connecting track source
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: PlaylistTableModel(0x5648431c0bc0) select() took 0 ms 0
Debug [Main]: CrateFeature::rebuildChildModel() -1
Debug [Main]: Default quick links: ("/home/user/Music/", "/home/user/Downloads/", "/home/user/Desktop/", "/home/user/Documents/")
Debug [Main]: Appending Quick Link:  "Music" --- "/home/user/Music/"
Debug [Main]: Appending Quick Link:  "Downloads" --- "/home/user/Downloads/"
Debug [Main]: Appending Quick Link:  "Desktop" --- "/home/user/Desktop/"
Debug [Main]: Appending Quick Link:  "Documents" --- "/home/user/Documents/"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Traktor Library Location=[ "/home/user/collection.nml" ]
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlist_tracks"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlists"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_library"
Debug [Main]: Creating Rekordbox library table:  "rekordbox_library"
Debug [Main]: Creating Rekordbox playlists table:  "rekordbox_playlists"
Debug [Main]: Creating Rekordbox playlist tracks table:  "rekordbox_playlist_tracks"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Dropping Serato table:  "serato_playlist_tracks"
Debug [Main]: Dropping Serato table:  "serato_playlists"
Debug [Main]: Dropping Serato table:  "serato_library"
Debug [Main]: Creating Serato library table:  "serato_library"
Debug [Main]: Creating Serato playlists table:  "serato_playlists"
Debug [Main]: Creating Serato playlist tracks table:  "serato_playlist_tracks"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Checking for access to user's library directories:
Debug [Main]: Checking for access to "/home/user/Music" : true
Debug [Main]: TrackAnalysisScheduler - Starting 2 worker threads. Priority:  normal
Debug [AnalyzerThread 1 #2]: AnalyzerThread 1 - Running
Debug [AnalyzerThread 0 #1]: AnalyzerThread 0 - Running
Info [AnalyzerThread 0 #1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-4" QSqlDatabase(driver="QSQLITE", database="file:///home/user/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Info [AnalyzerThread 1 #2]: DbConnectionPool - Cloned thread-local database connection "MIXXX-3" QSqlDatabase(driver="QSQLITE", database="file:///home/user/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Debug [AnalyzerThread 0 #1]: AnalyzerThread - Activated 5 analyzers
Debug [AnalyzerThread 1 #2]: AnalyzerThread - Activated 5 analyzers
Debug [Main]: Creating ControllerManager
Debug [Controller]: ControllerManager:slotInitialize
Debug [Controller]: Extension .midi.xml total 0 presets
Debug [Controller]: Extension .hid.xml total 0 presets
Debug [Controller]: Extension .bulk.xml total 0 presets
Debug [Main]: Set root GL Context widget valid: QGLWidget(0x5648454e89c0) true
Debug [Main]: Created root GL Context valid: 0x5648453e6340 true
Debug [Main]: Root GL Context format:
Debug [Main]: Double Buffering: true
Debug [Main]: Swap interval: 0
Debug [Main]: Depth buffer: true
Debug [Main]: Direct rendering: true
Debug [Main]: Has overlay: false
Debug [Main]: RGBA: true
Debug [Main]: Sample buffers: false
Debug [Main]: Samples: -1
Debug [Main]: Stencil buffers: true
Debug [Main]: Stereo: false
Debug [Main]: "openGLVersionFlags 0xff07f" "4.6 (Compatibility Profile) Mesa 22.3.1" "Intel" "Mesa Intel(R) HD Graphics 520 (SKL GT2)"
Debug [Main]: DBus interface  org.freedesktop.ScreenSaver  not valid
Debug [Main]: DBus interface  org.gnome.ScreenSaver  not valid
Debug [Main]: DBus interface  org.kde.screensaver  not valid
Debug [Main]: RLimit Cur  0
Debug [Main]: RLimit Max  0
Debug [Main]: ControllerManager::getControllerList
Debug [Main]: Key plugin ID: ""
Debug [Main]: LegacySkinParser loading skin: "/usr/share/mixxx/skins/LateNight"
Debug [Main]: Skin is a >=1.12.0 style skin.
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Controller]: Extension .midi.xml total 127 presets
Debug [Controller]: Extension .hid.xml total 13 presets
Debug [Controller]: Extension .bulk.xml total 1 presets
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSearchLineEdit - Background color: QColor(ARGB 1, 0, 0, 0)
Debug [Main]: WTrackTableView::loadTrackModel() HiddenTableModel(0x5648528d3e30)
Debug [Main]: HiddenTableModel(0x5648528d3e30) select() took 0 ms 0
Debug [Main]: WTrackTableView::loadTrackModel() MissingTableModel(0x5648528f12b0)
Debug [Main]: MissingTableModel(0x5648528f12b0) select() took 0 ms 0
Debug [Main]: WTrackTableView::loadTrackModel() PlaylistTableModel(0x5648431c0bc0)
Debug [Main]: Recordings folder set to "/home/user/Music/Mixxx/Recordings"
Debug [Main]: WTrackTableView::loadTrackModel() QSortFilterProxyModel(0x564852a43ac8)
Debug [BrowseThread]: Append last  0
Debug [BrowseThread]: Append last  0
Debug [Main]: WTrackTableView::loadTrackModel() AnalysisLibraryTableModel(0x564852ac3620)
Debug [Main]: AnalysisLibraryTableModel(0x564852ac3620) select() took 0 ms 0
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 0
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 1
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 2
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 3
Debug [Main]: MixxxLibraryFeature::activate()
Debug [Main]: WTrackTableView::loadTrackModel() LibraryTableModel(0x5648431b23d0)
Debug [Main]: LibraryTableModel(0x5648431b23d0) select() took 0 ms 0
Debug [Main]: trying to restore position
Debug [Main]: Created QGLWidget. Context Valid: true Sharing: true
Debug [Main]: Created QGLWidget. Context Valid: true Sharing: true
Debug [Main]: Created QGLWidget. Context Valid: true Sharing: true
Debug [Main]: Created QGLWidget. Context Valid: true Sharing: true
Debug [Controller]: ControllerManager: Setting up devices
Debug [Controller]: Scanning PortMIDI devices:
Debug [Controller]: Scanning USB Bulk devices:
Debug [Controller]: Scanning HID devices:
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler1]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler2]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler3]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler4]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler5]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler6]" QObject(0x0)
Debug [Controller]: ControllerManager::getControllerList
Debug [Controller]: Controller polling stopped.
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler7]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler8]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler9]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler10]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler11]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler12]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler13]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler14]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler15]" QObject(0x0)
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler16]" QObject(0x0)
Debug [Main]: SoundManager::setupDevices()
Debug [Main]: SoundDevicePortAudio::open() "SoundDeviceId(HDA Intel PCH: ALC293 Analog, hw:0,0, 0)"
Debug [Main]: framesPerBuffer: 1024
Debug [Main]: Requested sample rate:  44100 Hz, latency: 23.22 ms
Debug [Main]: Output channels: 2 | Input channels: 0
Debug [Main]: Opening stream with id 0
Debug [Main]: Opened PortAudio stream successfully... starting
Info [Main]: Enabling ALSA real-time scheduling
Debug [Main]: PortAudio: Started stream successfully
Debug [Main]:    Actual sample rate:  44100 Hz, latency: 23.22 ms
Debug [Main]: SoundDeviceNetwork - open: "Network stream"
Debug [Main]: framesPerBuffer: 1024
Debug [Main]: Requested sample rate:  44100 Hz, latency: 23219954 ns
Debug [Main]: Using "HDA Intel PCH: ALC293 Analog (hw:0,0)" as output sound device clock reference
Debug [Main]: 2 output sound devices opened
Debug [Main]: 0 input sound devices opened
Debug [Main]: Displaying main window
Debug [Main]: Running Mixxx
Debug []: SSE: Enabling denormals to zero mode
Debug []: SSE: Enabling flush to zero mode
Debug []: Denormals to zero mode is working
Debug [Main]: GLWaveformRendererSignalShader::loadShaders
Debug [Main]: GLWaveformRendererSignalShader::loadShaders
Debug [Main]: WaveformWidgetFactory::setWidgetType - type already in use
Debug [Main]: 0 ms stopping pending Library tasks
Debug [Main]: Destroying MixxxMainWindow
Debug [Main]: 0 ms saving configuration
Debug [Main]: 0 ms deleting skin
Debug [Main]: ~DlgAutoDJ()
Debug [Main]: 413 ms deleting menubar
Debug [Main]: 424 ms deleting SoundManager
Debug [Main]: 431 ms deleting ControllerManager
Debug [Controller]: Controller polling stopped.
Debug [Controller]: Deleting PortMIDI devices...
Debug [Controller]: Deleting USB Bulk devices...
Debug [Controller]: Deleting HID devices...
Debug [Main]: 432 ms deleting VinylControlManager
Debug [Main]: 432 ms deleting PlayerManager
Debug [Main]: PlayerManager - Destroying
Debug [Main]: TrackAnalysisScheduler - Stopping
Debug [Main]: TrackAnalysisScheduler - Stopping
Debug [AnalyzerThread 0 #1]: AnalyzerWaveform - ~AnalyzerWaveform():
Debug [AnalyzerThread 0 #1]: AnalyzerThread - Exiting worker thread
Debug [AnalyzerThread 1 #2]: AnalyzerWaveform - ~AnalyzerWaveform():
Debug [AnalyzerThread 1 #2]: AnalyzerThread - Exiting worker thread
Debug [AnalyzerThread 1 #2]: AnalyzerThread 1 - Exiting
Debug [AnalyzerThread 0 #1]: AnalyzerThread 0 - Exiting
Debug [Main]: 435 ms deleting Library
Debug [Main]: Wait to finish browser background thread
Debug [Main]: Browser background thread terminated!
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: PlaylistDAO::getHiddenType returns PLHT_UNKNOWN for playlistId  3
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlist_tracks"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlists"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_library"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Dropping Serato table:  "serato_playlist_tracks"
Debug [Main]: Dropping Serato table:  "serato_playlists"
Debug [Main]: Dropping Serato table:  "serato_library"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: 468 ms deleting RecordingManager
Debug [Main]: Delete RecordingManager
Debug [Main]: 468 ms deleting BroadcastManager
Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 0
Debug [Main]: 468 ms deleting EngineMaster
Debug [Main]: 537 ms deleting DlgPreferences
Debug [Main]: 545 ms deleting EffectsManager
Debug [Main]: 566 ms detaching all track collections
Info [Main]: TrackCollectionManager - Stopping library scanner thread
Debug [LibraryScanner 1]: LibraryScanner - Event loop stopped
Warning [LibraryScanner 1]: QSqlDatabasePrivate::removeDatabase: connection 'MIXXX-2' is still in use, all queries will cease to work.
Debug [LibraryScanner 1]: LibraryScanner - Exiting thread
Info [Main]: TrackCollectionManager - Stopped library scanner thread
Debug [Main]: ~TrackDAO()
Info [Main]: TrackCollection - Disconnecting track source
Info [Main]: TrackCollection - Disconnecting database
Debug [Main]: TrackDAO::finish()
Debug [Main]: Clearing played information for this session
Debug [Main]: Cleaning LibraryHashes/track_locations tables.
Info [Main]: GlobalTrackCache - Destroying instance
Debug [Main]: ~TrackDAO()
Debug [Main]: 567 ms closing database connection(s)
Debug [Main]: 568 ms deleting SettingsManager
Debug [Main]: Mixxx shutdown complete with code 0
`

**Comment by fbmoose48** [comment]
`journalctl -b -p 3` outputs

```Dec 20 14:32:28 x260 kernel: x86/cpu: VMX (outside TXT) disabled by BIOS
Dec 20 14:32:28 x260 kernel: x86/cpu: SGX disabled by BIOS.
Dec 20 14:32:28 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:32:28 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:32:28 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:32:28 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:32:28 x260 systemd-udevd[241]: /etc/udev/rules.d/69-mixxx-usb-uaccess.rules:61 Unknown group 'uaccess', ignoring
Dec 20 14:32:28 x260 systemd-udevd[241]: /etc/udev/rules.d/mixxx-usb-uaccess.rules:61 Unknown group 'uaccess', ignoring
Dec 20 14:32:28 x260 kernel: usb 1-2: device not accepting address 4, error -71
Dec 20 14:32:29 x260 kernel: usb 1-2: device not accepting address 5, error -71
Dec 20 14:32:29 x260 kernel: usb usb1-port2: unable to enumerate USB device
Dec 20 14:32:30 x260 bluetoothd[392]: src/plugin.c:plugin_init() Failed to init vcp plugin
Dec 20 14:32:30 x260 bluetoothd[392]: src/plugin.c:plugin_init() Failed to init mcp plugin
Dec 20 14:32:30 x260 bluetoothd[392]: src/plugin.c:plugin_init() Failed to init bap plugin
Dec 20 14:32:32 x260 kernel: Bluetooth: hci0: Malformed MSFT vendor event: 0x02
```
I suspect 
```Dec 20 14:32:28 x260 systemd-udevd[241]: /etc/udev/rules.d/69-mixxx-usb-uaccess.rules:61 Unknown group 'uaccess', ignoring
Dec 20 14:32:28 x260 systemd-udevd[241]: /etc/udev/rules.d/mixxx-usb-uaccess.rules:61 Unknown group 'uaccess', ignoring
```
has something to do with my failure to recognize the controller, any suggestions appreciate

**Comment by fbmoose48** [comment]
https://bbs.archlinux.org/viewtopic.php?id=274415

commenting out
```
# Only some distribuions require the below
#KERNEL=="hiddev*", NAME="usb/%k", GROUP="uaccess"
```
results in `journalctl -b -p 3` outputting
```
Dec 20 14:41:31 x260 kernel: x86/cpu: VMX (outside TXT) disabled by BIOS
Dec 20 14:41:31 x260 kernel: x86/cpu: SGX disabled by BIOS.
Dec 20 14:41:31 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:41:31 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:41:31 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:41:31 x260 kernel: usb 1-2: device descriptor read/64, error -71
Dec 20 14:41:31 x260 kernel: usb 1-2: device not accepting address 4, error -71
Dec 20 14:41:32 x260 kernel: usb 1-2: device not accepting address 5, error -71
Dec 20 14:41:32 x260 kernel: usb usb1-port2: unable to enumerate USB device
Dec 20 14:41:33 x260 bluetoothd[395]: src/plugin.c:plugin_init() Failed to init vcp plugin
Dec 20 14:41:33 x260 bluetoothd[395]: src/plugin.c:plugin_init() Failed to init mcp plugin
Dec 20 14:41:33 x260 bluetoothd[395]: src/plugin.c:plugin_init() Failed to init bap plugin
```
so that's some improvement, but still no detected controller

**Comment by fbmoose48** [comment]
I used the file at [](https://raw.githubusercontent.com/mixxxdj/mixxx/master/res/linux/mixxx-usb-uaccess.rules) as `/udev/rules.d/69-mixxx-usb-uaccess.rules`, but beyond that its not clear to me what if anything the file is telling me needs to be modified for v2.3. Are you referring to "Note that the udev rule must match on the USB device level"?

**Comment by JoergAtGithub** [comment]
This is definetally the wrong file! Use the one from the 2.3 branch instead: https://github.com/mixxxdj/mixxx/blob/2.3/res/linux/mixxx-usb-uaccess.rules

**Comment by fbmoose48** [comment]
> This is definetally the wrong file! Use the one from the 2.3 branch instead: https://github.com/mixxxdj/mixxx/blob/2.3/res/linux/mixxx-usb-uaccess.rules

that was it! thanks
