### ISSUE TITLE
Mixxx failed to setup with error Unpacking failed.

### ISSUE THREAD

**Issue by nnfdnkns** [mixxxdj/mixxx#11150]
### Bug Description

Hi all,

Mixxx failed to setup with error Unpacking failed.  The downloaded archive might be broken, consider removing "F:\gitP\mixxxdj\mixxx\buildenv\mixxx-deps-2.4-x64-windows-245123a.zip" to force redownload. Could you please help look at this issue?

**Repro steps:**
1. git clone https://github.com/mixxxdj/mixxx F:\gitP\mixxxdj\mixxx
2. cd F:\gitP\mixxxdj\mixxx\buildenv
3. set PATH=F:\tools\build2\bin;%PATH%
4. curl https://downloads.mixxx.org/dependencies/2.4/Windows/mixxx-deps-2.4-x64-windows-f9cdab3.zip -O -L 2>&1
5. cd F:\gitP\mixxxdj\mixxx\tools
6. SET PLATFORM=x64
7. SET CONFIGURATION=release
8. windows_buildenv.bat 2>&1
9. cd F:\gitP\mixxxdj\mixxx\build
10. cmake -DBULK=OFF -DFFMPEG=OFF -DHSS1394=ON -DLOCALECOMPARE=ON -DMAD=ON -DMEDIAFOUNDATION=ON -DMODPLUG=ON -DWAVPACK=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="" -DDEBUG_ASSERTIONS_FATAL=OFF -DBATTERY=ON -DBROADCAST=ON -DDOWNLOAD_MANUAL=ON -DHID=ON -DKEYFINDER=ON -DLILV=ON -DOPUS=ON -DQTKEYCHAIN=ON -DVINYLCONTROL=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -L .. 2>&1

**Error info:**
Error: Unpacking failed. The downloaded archive might be broken, consider removing "F:\gitP\mixxxdj\mixxx\buildenv\mixxx-deps-2.4-x64-windows-245123a.zip" to force redownload.
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Chromaprint (missing: Chromaprint_LIBRARY
  Chromaprint_INCLUDE_DIR)

### Version

vs2019

### OS

Windows Server 2019

**Comment by JoergAtGithub** [comment]
These steps are very different than described in Readme.md.
You don't need to download the buildenv manually. windows_buildenv.bat does this for you.

The easiest way to build with VS2019 is to double click on windows_buildenv.bat to execute it, than open VisualStudio and use the Open-Folder menu to open the Mixxx folder.
