### ISSUE TITLE
Typo on Controller Learning Wizard

### ISSUE THREAD

**Issue by tdgalland** [mixxxdj/mixxx#11158]
### Bug Description

When you hit Choose Control > Speed in the second section of the menu it goes

Increase Speed
Increase Speed (Fine)
Decrease Speed
Increase Speed (Fine)

I believe the last Increase Speed should be Decrease Speed since that's what it links to according to the small print below: "_Ready to learn Deck #: Adjust speed slower (fine)_"

### Version

2.3.3

### OS

Windows 10

**Comment by ronso0** [comment]
Indeed, thanks for the report.
The respective code is here
https://github.com/mixxxdj/mixxx/blob/f0c8498dcfbbf98bb9f5f26e75e16e2c5da09ca7/src/controllers/controlpickermenu.cpp#L251-L258

**Comment by Bilsteen** [comment]
Hello there,
My name is Bilal and I am looking forward to work on this issue. Is this issue still open?
It would be really great if I get assigned this issue.
Regards.

**Comment by ronso0** [comment]
It's not closed so it probably is still open...
 just open a PR with the fix.

**Comment by AyushD95** [comment]
@ronso0 Hi Ronso,
I am currently working on it and I will fix this issue

**Comment by AyushD95** [comment]
@ronso Just created pull request
