### ISSUE TITLE
Possible Invalid ID3 Tag Reading

### ISSUE THREAD

**Issue by cheri-imvu** [mixxxdj/mixxx#11166]
### Bug Description

For some MP3 files, Mixxx isn't reading the ID3 tags correctly. It seems to looking at the file name instead of the MP3 tags. I can't attach a sample file, but you can download it from [here](https://triggerless.com/media/sample-mp3.zip). Thanks!

### Version

2.2.3

### OS

Windows 10 22H2

**Comment by uklotzde** [comment]
This file contains both an ID3v1 and an ID3v2 tag:

![image](https://user-images.githubusercontent.com/1474154/210072348-31a7e859-a805-40b7-a530-9224aedc133e.png)

Mixxx simply picks the ID3v2 tag and does not magically collect and merge information from multiple tags. The possibilities would be endless and the strategies for resolving conflicts will never cover all use cases.

Please fix and synchronize your tags with a tag editor.
