### ISSUE TITLE
Deck Waveform: Green background and flickering

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11164]
### Bug Description

The deck waveform changes from a black to a green background after hitting play:

![Screenshot from 2022-12-29 15-09-04](https://user-images.githubusercontent.com/1474154/209965234-30f19ebe-0280-47e8-8502-b7a2a1b741a9.png)

Eventually it switches back to black or even starts to flicker. The flickering occurs when moving the mouse over skin controls.

Mesa Intel® HD Graphics 530 (SKL GT2) on Fedora 37 / Mesa 22.3

### Version

2.4.0

### OS

Fedora 37

**Comment by uklotzde** [comment]
All decks are affected. Seems to be an OpenGL issue with the legacy widgets.

**Comment by scratchmonkeystudio** [comment]
Weirdly I get this behavior (2.3.3 on Fedora 37 X11) but the background is cyan rather than green. Also it goes away if I kill the compositor.

**Comment by uklotzde** [comment]
With mesa 23.0 the RGB (GLDL) waveforms became almost unusable:

![image](https://user-images.githubusercontent.com/1474154/232239271-06eb1c69-d769-4529-9145-ce769cc8cbf1.png)

![image](https://user-images.githubusercontent.com/1474154/232239389-6931bc66-8a2d-4cfa-ad83-ebac85fab0bf.png)

**Comment by uklotzde** [comment]
The coloring issues might be caused by this bug: https://github.com/ValveSoftware/gamescope/issues/356

**Comment by daschuer** [comment]
Which waveforms are exactly effected?

**Comment by Swiftb0y** [comment]
Confirmed. Using Fedora 37, OpenGL 4.3 Mesa Intel (UHD) Graphics (CML GT2). The flickering color changes based on skin, its green on Deere, cyan on Latenight, red/orange (not sure) on Tango and green on Shade. Mixxx 2.3.4 is also affected. Waveform in question are GL and GLSL variants. CPU rendered variants are not affected. waveform introduced in #10989 are also not affected.

**Comment by daschuer** [comment]
We had a similar issue with the recently introduced VU meters an the Tango Skin. 

https://github.com/mixxxdj/mixxx/pull/11430
https://github.com/mixxxdj/mixxx/pull/11422

The issue there is that the transparent GL widget fails to adopt the non GL background piamp and draws green instead. I wonder if this is a regression in our 2.3 branch. 
But anyway. I see a good chance to fix this with the same solution in our stable 2.3. branch.

**Comment by daschuer** [comment]
@Swiftb0y, can you confirm that the waveform itself behaves normal and only the background is affected?

**Comment by Swiftb0y** [comment]
How would I go about that? Comment out the background renderer in the render stack?

**Comment by m0dB** [comment]
Potential fix in https://github.com/mixxxdj/mixxx/pull/11523 
(I can't reproduce the issue, so someone who can, please try)
