### ISSUE TITLE
[4 Decks] LateNight skin has wrong ordering of waveforms

### ISSUE THREAD

**Issue by obsoleszenz** [mixxxdj/mixxx#11174]
### Bug Description

In mixxx 2.3.3 the parallel waveform ordering is wrong for the latenight skin.
From top to bottom the ordering is 3, 1, 2, 4. 

 I will open a pr to fix this.

### Version

2.3.3

### How to reproduce

1. Select LateNight skin
2. Enable [parallel] waveforms
3. Load A track into Deck One
4. Enable 4 Decks
5. Notice that the waveform of the loaded track is not shown in the first row but in the second
6. Load a track in the 3rd deck and notice it's shown in the first row

**Comment by Swiftb0y** [comment]
I'm pretty sure that this is intentional to mirror the 3-1-2-4 layout of the mixer. The only skin that does 1-2-3-4 is Tango afaik...

**Comment by obsoleszenz** [comment]
> I'm pretty sure that this is intentional to mirror the 3-1-2-4 layout of the mixer. The only skin that does 1-2-3-4 is Tango afaik...

Ay you're right. I was always using tango and expected this to be the default. Buuut do only I find this confusing if it's not 1-2-3-4?

**Comment by obsoleszenz** [comment]
This seems to be the default in dj software, so closing this for now. Thanks @robbert-vdh & @Swiftb0y for clarification :)
