### ISSUE TITLE
Music randomly stops

### ISSUE THREAD

**Issue by ligi** [mixxxdj/mixxx#11187]
### Bug Description

It happens (felt randomly) after playing for some (sometimes really long) time with this error:

```
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3355
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3896
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4274
```

In this case I need to restart mixxx.

### Version

2.3.3

### OS

Ubuntu 20.04.5 LTS

**Comment by daschuer** [comment]
I have never seen this issue, on the same OS, however Audacity seems to suffer the same issue: https://github.com/audacity/audacity/issues/396
Which sound hardware do you use?

**Comment by ligi** [comment]
I had this issue on multiple sound hardware - e.g. the Traktor Z1 - or when submitting the issue I was hearing music over a Bluetooth A2DP connection.

**Comment by daschuer** [comment]
I have just checked the portaudio source the line of question has moved here since the Ubunuto Focal release: 
https://github.com/PortAudio/portaudio/blob/master/src/hostapi/alsa/pa_linux_alsa.c#L3397

Can this be a latency issue? Which buffer-size do you use? 

You will bypass this code by using Jack, if you can effort the extra latency from Jack/Pipewire

**Comment by daschuer** [comment]
I think this is a Portaudio issue. Can you report it there as well? https://github.com/PortAudio/portaudio/issues/new/choose

**Comment by ligi** [comment]
Thanks for looking into this!
Where can I find the buffer size setting? Don't see anything here:
![image](https://user-images.githubusercontent.com/111600/211158809-a5bc0d0d-8e88-4026-bcc2-eb0c4f0102b3.png)
I don't feel competent enough in this subject matter to make a issue in PortAudio unfortunately.

**Comment by daschuer** [comment]
All looks good In the preferences. 

I think you can just copy you initial post over to Portaudio an reference this one here in addition.

**Comment by ligi** [comment]
OK - done here: https://github.com/PortAudio/portaudio/issues/758
