### ISSUE TITLE
Can't load m4a files, Windows 7

### ISSUE THREAD

**Issue by lezzzgo23** [mixxxdj/mixxx#11188]
### Bug Description

![image](https://user-images.githubusercontent.com/122188668/211177547-4bd044de-5e72-40b2-9969-bec6ff3ffb5b.png)

### Version

2.3.3

### OS

Windows 7

**Comment by daschuer** [comment]
Windows 7 is discontinued since 2020. We can't really support abandoned OS.

But maybe one has an idea anyway. 
Please start Mixxxx, load the affected file and close is again than post the mixxx.log
https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file#windows

**Comment by MassimilianoN** [comment]
Same problem on Windows 10 with Mixx 2.3.4. 

I've used fre:ac to convert the audio files from webm to m4a.  
The codec details are:

FDK-AAC Encoder v4.0.1
MPEG AAC Enhanced Low Delay
File Format: MP4
File Exstension: m4a
[mixxx.log](https://github.com/mixxxdj/mixxx/files/11071957/mixxx.log)

**Comment by MassimilianoN** [comment]
I've solved the problem. 

I've used mkvtoolnix to extract the audio from the webm files, instead of converting it in m4a. 
This way the audio file is an opus file and I had no problems opening it with MIXXX.
 
Maybe, was it an encoding problem?

I hope it could be helpful.
