### ISSUE TITLE
Focusrite Saffire 6: Hardware does not support requested sample rate

### ISSUE THREAD

**Issue by utoma09** [mixxxdj/mixxx#11184]
### Bug Description

Hi, I got a problem with Mixxx version 2.1.1. and a Focusrite Saffire 6 external soundcard. The operating system is Windows 10, 
64 bit.

Mixxx cannot recognize the soundcard; each time I open the program I get the error message -Hardware does not support requested sample rate-, but gives me the option to reconfigure this in the preferences.  When I change it to the soundcard's value, which is 48000 khz, apply it and request for this device , Mixxx still doesn't recognize it. It's the same with 44100 khz, 

I tried Mixxx version 2.3.3. and got the same error message.

I also got the issue with tractor, which makes me wonder if it has something to do with the port audio interface in Windows.

In window's sound settings, I already unchecked the -apps do have exclusive control over the device- box.

I found solutions resp. command lines to skirt this bug for Linux, but not for windows.

Has anyone else had this problem ? Would be great if someone's got a solution for this. Cheers

### Version

2.1.1.

### OS

Windows 10

**Comment by daschuer** [comment]
Which sound API do you use? Does this issue persist with all APIs? 

Please use Mixxx 2.3.3. Start it, try to configure the soundcard and close Mixxx.
Than attach the resulting mixxx.log here. https://github.com/mixxxdj/mixxx/wiki/Finding-The-Mixxx.Log-File#windows

**Comment by daschuer** [comment]
This seems to be a common with a badly installed the Focusrite Saffire 6 diver. Did you select the correct USB version?

**Comment by utoma09** [comment]
Hi, the Sound API is currently set to ASIO; I tried Windows Direct Sound, but it also didn't work. I wonder why it doesn't give me the ASIO4ALL-Option, because that's the driver I've installed on Windows. In the output settings though, it accepts ASIO4ALL
and saves it.

Btw, I installed Mixxx Version 2.3.3., but got exactly the same error messages. It doesn't seem to depend on the version. In the meantime I've uninstalled 2.3.3. and then re-installled 2.1.1. again, because that version is more to my likings. 

Ok, I've done what you told me and hope that this is the mixxx log that you need, but it's taken from my currently running Version 2.1.1.

Debug [Main]: SoundSourceProxy - Loading SoundSource plugins "C:/Program Files/Mixxx/plugins/soundsource" 
Debug [Main]: SoundSourcePluginLibrary - Dynamically loaded plugin library "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.dll" 
Warning [Main]: SoundSourcePluginLibrary - Failed to dynamically load plugin library "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.exp" : "Cannot load library C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.exp: " 
Warning [Main]: SoundSourceProxy - Failed to load SoundSource plugin "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.exp" 
Warning [Main]: SoundSourcePluginLibrary - Failed to dynamically load plugin library "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.lib" : "Cannot load library C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.lib: " 
Warning [Main]: SoundSourceProxy - Failed to load SoundSource plugin "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.lib" 
Warning [Main]: SoundSourcePluginLibrary - Failed to dynamically load plugin library "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.pdb" : "Cannot load library C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.pdb: " 
Warning [Main]: SoundSourceProxy - Failed to load SoundSource plugin "C:/Program Files/Mixxx/plugins/soundsource/soundsourcemediafoundation.pdb" 
Debug [Main]: "Mixxx" "2.1.1" "(git 2.1 r6743; built on: Jun 11 2018 @ 02:56:46; flags: asan=0 asmlib=0 battery=1 buildtime=1 bulk=0 color=0 coreaudio=0 faad=0 ffmpeg=0 hid=1 hss1394=1 ipod=0 localecompare=1 macappstore=0 mad=1 mediafoundation=1 modplug=0 opengles=0 optimize=portable opus=1 perftools=0 perftools_profiler=0 profiling=0 qdebug=1 qt_sqlite_plugin=0 qtkeychain=0 shoutcast=1 test=1 tsan=0 ubsan=0 vamp=1 verbose=0 vinylcontrol=1 wv=0)" is starting... 
Debug [Main]: Compile time library versions: 
Debug [Main]: Qt: 4.8.7 
Debug [Main]: libshout: 2.4.1 
Debug [Main]: PortAudio: 1246720 PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4 
Debug [Main]: RubberBand: 1.8.1 
Debug [Main]: SoundTouch: 2.0.0 
Debug [Main]: TagLib: 1.10.0 
Debug [Main]: ChromaPrint: 1.3.1 
Debug [Main]: Vorbis: Xiph.Org libVorbis 1.3.5 
Debug [Main]: libsndfile: libsndfile-1.0.26 
Debug [Main]: FLAC: 1.3.1 
Debug [Main]: QDesktopServices::storageLocation(HomeLocation): "C:/Users/user" 
Debug [Main]: QDesktopServices::storageLocation(DataLocation): "C:\Users\user\AppData\Local\Mixxx" 
Debug [Main]: QCoreApplication::applicationDirPath() "C:/Program Files/Mixxx" 
Debug [Main]: Loading resources from  "C:/Program Files/Mixxx/" 
Debug [Main]: Configuration file is at the current version 2.1.1 
Debug [Main]: BroadcastSettings - Found 1 profile(s) 
Debug [Main]: Loading resources from  "C:/Program Files/Mixxx/" 
Debug [Main]: Loading resources from  "C:/Program Files/Mixxx/" 
Debug [Main]: Loading translations for locale "de_DE" from translations folder "C:/Program Files/Mixxx/translations/" : fail 
Debug [Main]: "Error: Unable to import console: no such extension" 
Debug [Main]: "Error: Unable to import svg: no such extension" 
Debug [Main]: Loading resources from  "C:/Program Files/Mixxx/" 
Debug [Main]: Compressor attack per frame:  0.000408163 decay per frame:  4.08163e-05 
Debug [Main]: EngineNetworkStream - addWorker: worker added 
Debug [Main]: EngineNetworkStream - worker slots used: "1 out of 16" 
Debug [Main]: BroadcastManager - addConnection: created connection for profile "Connection 1" 
Debug [Main]: WARNING: AudioInput already registered! 
Debug [Main]: WARNING: AudioInput already registered! 
Debug [Main]: WARNING: AudioInput already registered! 
Debug [Main]: WARNING: AudioInput already registered! 
Debug [Main]: DbConnection - Available drivers for database connections: ("QSQLITE") 
Debug [Main]: DbConnectionPool - Cloned thread-local database connection "MIXXX-1" QSqlDatabase(driver=""QSQLITE"", database=""C:/Users/user/AppData/Local/Mixxx/mixxxdb.sqlite"", host=""localhost"", port=-1, user=""mixxx"", open=true) 
Debug [Main]: MixxxMainWindow - Connecting to database 
Debug [Main]: MixxxMainWindow - Initializing or upgrading database schema 
Debug [Main]: SchemaManager - Current database schema is newer at version 32 and backwards compatible with version 28 
Debug [Main]: LibraryScanner - Starting thread 
Debug [Main]: Library - Connecting database 
Debug [LibraryScanner 1]: LibraryScanner - Entering thread 
Debug [LibraryScanner 1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-2" QSqlDatabase(driver=""QSQLITE"", database=""C:/Users/user/AppData/Local/Mixxx/mixxxdb.sqlite"", host=""localhost"", port=-1, user=""mixxx"", open=true) 
Debug [LibraryScanner 1]: LibraryScanner - Event loop starting 
Debug [Main]: Committing transaction on "MIXXX-1" result: true 
Debug [Main]: CrateFeature::rebuildChildModel() -1 
Debug [Main]: Default quick links: ("C:/Users/user/Music/", "C:/Users/user/Downloads/", "C:/Users/user/Desktop/", "C:/Users/user/Documents/") 
Debug [Main]: Appending Quick Link:  "Music" --- "C:/Users/user/Music/" 
Debug [Main]: Appending Quick Link:  "Downloads" --- "C:/Users/user/Downloads/" 
Debug [Main]: Appending Quick Link:  "Desktop" --- "C:/Users/user/Desktop/" 
Debug [Main]: Appending Quick Link:  "Documents" --- "C:/Users/user/Documents/" 
Debug [Main]: Committing transaction on "MIXXX-1" result: true 
Debug [Main]: Traktor Library Location=[ "C:/Users/user/Documents/Native Instruments/Traktor/collection.nml" ] 
Debug [Main]: Checking for access to user's library directories: 
Debug [AnalyzerQueue 1]: AnalyzerQueue - Entering thread 
Debug [AnalyzerQueue 1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-3" QSqlDatabase(driver=""QSQLITE"", database=""C:/Users/user/AppData/Local/Mixxx/mixxxdb.sqlite"", host=""localhost"", port=-1, user=""mixxx"", open=true) 
Debug [Main]: Creating ControllerManager 
Debug [Controller]: ControllerManager:slotInitialize 
Debug [Main]: screensaver inhibited 
Debug [Main]: ControllerManager::getControllerList 
Debug [Main]: AutoHiDpi::getScaleFactor() 96 
Debug [Main]: VampPluginAdapter - Current VAMP_PATH is: "" 
Debug [Main]: VampPluginAdapter - Setting VAMP_PATH to: "C:\Program Files\Mixxx\plugins\vamp" 
Debug [Main]: VampPluginLoader::listPlugins() returned 4 plugins 
Debug [Main]: Plugin output displayname: "mixxxbpmdetection:0" "SoundTouch BPM Detector (Legacy)" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:0" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:1" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:2" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:3" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-keydetector:0" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:1" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:2" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:3" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:0" "Tempo and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:1" "Tempo and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:2" "Tempo and Beat Tracker" 
Debug [Main]: VampPluginLoader::listPlugins() returned 4 plugins 
Debug [Main]: Plugin output displayname: "mixxxbpmdetection:0" "SoundTouch BPM Detector (Legacy)" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:0" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:1" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:2" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-barbeattracker:3" "Bar and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-keydetector:0" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:1" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:2" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-keydetector:3" "Key Detector" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:0" "Tempo and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:1" "Tempo and Beat Tracker" 
Debug [Main]: Plugin output displayname: "qm-tempotracker:2" "Tempo and Beat Tracker" 
Debug [Main]: DlgPrefKey::loadSettings 
Debug [Main]: Key plugin ID: "qm-keydetector:2" 
Debug [Main]: Set root GL Context widget valid: QGLWidget(0x1fe2a8525f0) true 
Debug [Main]: Created root GL Context valid: 0x1fe2a7e96c0 true 
Debug [Main]: Root GL Context format: 
Debug [Main]: Double Buffering: true 
Debug [Main]: Swap interval: 0 
Debug [Main]: Depth buffer: true 
Debug [Main]: Direct rendering: true 
Debug [Main]: Has overlay: false 
Debug [Main]: RGBA: true 
Debug [Main]: Sample buffers: false 
Debug [Main]: Samples: -1 
Debug [Main]: Stencil buffers: true 
Debug [Main]: Stereo: false 
Debug [Main]: LegacySkinParser loading skin: "C:/Program Files/Mixxx/skins/Deere" 
Debug [Main]: "Error: Unable to import console: no such extension" 
Debug [Main]: "Error: Unable to import svg: no such extension" 
Debug [Controller]: Extension .midi.xml total 110 presets 
Debug [Controller]: Extension .hid.xml total 15 presets 
Debug [Controller]: Extension .bulk.xml total 1 presets 
Debug [Main]: Skin is a >=1.12.0 style skin. 
Warning [Main]: QCssParser::parseHexColor: Unknown color name '#08080'
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 0 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 1 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 2 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true 
Debug [Main]: WaveformWidgetFactory::setWaveformWidget - waveform widget added in factory, index 3 
Debug [Main]: WTrackTableView::loadTrackModel() HiddenTableModel(0x1fe36137e90) 
Debug [Main]: WTrackTableView::loadTrackModel() MissingTableModel(0x1fe36139550) 
Debug [Main]: WTrackTableView::loadTrackModel() PlaylistTableModel(0x1fe1ae74da0) 
Debug [Main]: Recordings folder set to "C:/Users/user/Desktop/Desktop" 
Debug [Main]: WTrackTableView::loadTrackModel() QSortFilterProxyModel(0x1fe373b87b0) 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/angry_red_planet_monster_sequence.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/angry_red_planet_monster_sequence.mp4" 
Debug [Main]: WTrackTableView::loadTrackModel() AnalysisLibraryTableModel(0x1fe361391d0) 
Debug [Main]: BaseTrackCache(0x1fe1dccdab0) updateIndexWithQuery took 0 ms 
Debug [Main]: AnalysisLibraryTableModel(0x1fe361391d0) select() took 1 ms 2 
Debug [Main]: AnalysisLibraryTableModel(0x1fe361391d0) select() took 0 ms 2 
Debug [Main]: DlgAnalysis(0x1fe377289d0, name = "DlgAnalysis") analysisActive false 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/Antik_Watson_VD.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/Antik_Watson_VD.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/black_hole_light_tunnel_sequenz.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/black_hole_light_tunnel_sequenz.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/black_hole_light_tunnel_sequenz_expanded.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/black_hole_light_tunnel_sequenz_expanded.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/colossus.mp3" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/Gantz.O.2016.1080p.BluRay.x264-FOXM.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/Gantz.O.2016.1080p.BluRay.x264-FOXM.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/mandala_clip1.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/mandala_clip1.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/mandala_clip2.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/mandala_clip2.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/mandala_clip3.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/mandala_clip3.mp4" 
Debug [BrowseThread]: Append  10  from  "C:/Users/user/Desktop/Desktop/mandala_clip3.mp4" 
Warning [BrowseThread]: SoundSourceProxy - Failed to import track metadata and embedded cover art from file "file:///C:/Users/user/Desktop/Desktop/mandala_clip4.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/mandala_clip4.mp4" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/Popol_Vuh_Brüder_Des_Schattens_160kb_Cut.wav" 
Debug [BrowseThread]: SoundSourceProxy - Adding missing artist/title from file name "file:///C:/Users/user/Desktop/Desktop/Scott_Lawlor_Dark_Wastelands_Of_The_Alien_Headquarters_1_hr.wav" 
Debug [BrowseThread]: Append  10  from  "C:/Users/user/Desktop/Desktop/thisquietarmy_funeral.flac" 
Debug [BrowseThread]: Append last  1 
Debug [Main]: MixxxLibraryFeature::activate() 
Debug [Main]: WTrackTableView::loadTrackModel() LibraryTableModel(0x1fe1eddc340) 
Debug [Main]: LibraryTableModel(0x1fe1eddc340) select() took 0 ms 2 
Debug [Main]: trying to restore position
Debug [Main]: WSearchLineEdit::restoreSearch( "" ) 
Debug [Controller]: ControllerManager: Setting up devices 
Debug [Controller]: Scanning PortMIDI devices: 
Debug [Controller]:  Found output device # 0 Microsoft MIDI Mapper 
Debug [Controller]:  Found output device # 2 Microsoft GS Wavetable Synth 
Debug [Controller]:  Found output device # 3 5- Saffire 6USB 
Debug [Controller]:  Found input device # 1 5- Saffire 6USB 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler1]" 
Debug [Controller]:     Linking to output device # 3 "5- Saffire 6USB" 
Debug [Controller]: Scanning HSS1394 devices: 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler2]" 
Debug [Controller]:    Nodes detected: 0 
Debug [Controller]: Scanning HID devices: 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler3]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler4]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler5]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler6]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler7]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler8]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler9]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler10]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler11]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler12]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler13]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler14]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler15]" 
Debug [Main]: BaseTrackPlayerImpl::slotLoadTrack "[Sampler16]" 
Debug [Main]: SoundManager::setupDevices() 
Debug [Main]: SoundDevicePortAudio::open() "14, ASIO4ALL v2" 
Debug [Main]: framesPerBuffer: 1024 
Debug [Main]: Requested sample rate:  48000 Hz, latency: 21.3333 ms 
Debug [Main]: Output channels: 2 | Input channels: 0 
Debug [Main]: Opening stream with id 14 
Debug [Controller]: Found "SUYIN" "USB Device" "r1" S/N "" "Interface 1" 
Debug [Controller]: Found "Logitech" "USB Optical Mouse" "r29184" S/N "" "Usage Page 1 Usage 2" 
Debug [Controller]: Found "SUYIN" "USB Device" "r1" S/N "" "Interface 1" 
Debug [Controller]: Found "SUYIN" "USB Device" "r1" S/N "" "Interface 1" 
Debug [Controller]: Found "SUYIN" "USB Device" "r1" S/N "" "Interface 0" 
Debug [Controller]: ControllerManager::getControllerList 
Debug [Controller]: Searching for controller preset "5-_Saffire_6USB.midi.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/5-_Saffire_6USB.midi.xml" 
Debug [Controller]: MidiControllerPresetFileHandler: Input mapping parsing complete. 
Debug [Controller]: MidiPresetFileHandler: Output mapping parsing complete. 
Debug [Controller]: Searching for controller preset "USB_Device__1.hid.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/USB_Device__1.hid.xml" 
Debug [Controller]: Searching for controller preset "USB_Optical_Mouse_.hid.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/USB_Optical_Mouse_.hid.xml" 
Debug [Controller]: Searching for controller preset "USB_Device__1--2.hid.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/USB_Device__1--2.hid.xml" 
Debug [Controller]: Searching for controller preset "USB_Device__1--3.hid.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/USB_Device__1--3.hid.xml" 
Debug [Controller]: Searching for controller preset "USB_Device__0.hid.xml" in paths: "C:/Users/user/AppData/Local/Mixxx/controllers/,C:/Program Files/Mixxx/controllers/" 
Debug [Controller]: Loading controller preset from "C:/Users/user/AppData/Local/Mixxx/controllers/USB_Device__0.hid.xml" 
Debug [Controller]: Controller polling stopped. 
Debug [Main]: Opened PortAudio stream successfully... starting 
Debug [Main]: PortAudio: Started stream successfully 
Debug [Main]:    Actual sample rate:  48000 Hz, latency: 23.375 ms 
Debug [Main]: Compressor attack per frame:  0.000375 decay per frame:  3.75e-05 
Debug [Main]: SoundDeviceNetwork - open: "Network stream" 
Debug [Main]: framesPerBuffer: 1024 
Debug [Main]: Requested sample rate:  48000 Hz, latency: 21333333 ns 
Debug [Main]: Using "ASIO4ALL v2" as output sound device clock reference 
Debug [Main]: 2 output sound devices opened 
Debug [Main]: 0 input  sound devices opened 
Debug [Main]: Displaying main window 
Debug [Main]: Running Mixxx 
Debug [Main]: ControllerManager::getControllerList 
Debug [Main]: Setting input delegate for column 0 QStyledItemDelegate(0x1fe2a7ee520) 
Debug [Main]: Setting input delegate for column 1 QStyledItemDelegate(0x1fe2a7ee240) 
Debug [Main]: Setting input delegate for column 2 QStyledItemDelegate(0x1fe2a7edf40) 
Debug [Main]: Setting input delegate for column 3 MidiOptionsDelegate(0x1fe2a7ee0a0) 
Debug []: SSE: Enabling denormals to zero mode 
Debug []: SSE: Enabling flush to zero mode 
Debug []: Denormals to zero mode is working 
Debug [Main]: Setting input delegate for column 4 ControlDelegate(0x1fe2a852fb0) 
Debug [Main]: Setting output delegate for column 0 QStyledItemDelegate(0x1fe3c173e10) 
Debug [Main]: Setting output delegate for column 1 QStyledItemDelegate(0x1fe3c173b70) 
Debug [Main]: Setting output delegate for column 2 QStyledItemDelegate(0x1fe3c1740d0) 
Debug [Main]: Setting output delegate for column 3 QStyledItemDelegate(0x1fe3c173fd0) 
Debug [Main]: Setting output delegate for column 4 QStyledItemDelegate(0x1fe3c173a30) 
Debug [Main]: Setting output delegate for column 5 ControlDelegate(0x1fe3b967060) 
Debug [Main]: 1 "ASIO4ALL v2" 
Debug [Main]: 2 "14, ASIO4ALL v2" 
Debug [Main]: 1 "ASIO4ALL v2" 
Debug [Main]: 2 "14, ASIO4ALL v2" 
Debug [Main]: screensaver uninhibited 
Debug [Main]: Destroying MixxxMainWindow 
Debug [Main]: 0 ms saving configuration 
Debug [Main]: 1 ms deleting skin 
Debug [Main]: ~DlgAutoDJ() 
Debug [Main]: 1106 ms deleting menubar 
Debug [Main]: 1107 ms deleting SoundManager 
Debug [Main]: 1190 ms deleting ControllerManager 
Debug [Controller]: Controller polling stopped. 
Debug [Controller]: Deleting PortMIDI devices... 
Debug [Controller]: Deleting HSS1394 devices... 
Debug [Controller]: Deleting HID devices... 
Debug [Main]: 2901 ms deleting VinylControlManager 
Debug [Main]: ~CoverArtCache() 
Debug [Main]: 2903 ms deleting PlayerManager 
Debug [AnalyzerQueue 1]: AnalyzerQueue - Exiting thread 
Debug [Main]: AnalyzerWaveform - ~AnalyzerWaveform(): 
Debug [Main]: 2910021100 ns deactivating GlobalTrackCache 
Debug [Main]: 2910 ms deleting Library 
Debug [Main]: Wait to finish browser background thread 
Debug [Main]: Browser background thread terminated! 
Debug [Main]: Committing transaction on "MIXXX-1" result: true 
Debug [Main]: PlaylistDAO::getHiddenType returns PLHT_UNKNOWN for playlistId  16 
Debug [Main]: Library - Disconnecting database 
Debug [Main]: TrackDAO::finish() 
Debug [Main]: Clearing played information for this session 
Debug [Main]: Cleaning LibraryHashes/track_locations tables. 
Debug [Main]: ~TrackDAO() 
Debug [LibraryScanner 1]: LibraryScanner - Event loop stopped 
Warning [LibraryScanner 1]: QSqlDatabasePrivate::removeDatabase: connection 'MIXXX-2' is still in use, all queries will cease to work.
Debug [LibraryScanner 1]: LibraryScanner - Exiting thread 
Debug [Main]: ~TrackDAO() 
Debug [Main]: 2947 ms closing database connection(s) 
Debug [Main]: 2948 ms deleting RecordingManager 
Debug [Main]: Delete RecordingManager 
Debug [Main]: 2948 ms deleting BroadcastManager 
Debug [Main]: DlgPrefBroadcast - broadcastEnabledChanged() 0 
Debug [Main]: 2948 ms deleting EngineMaster 
Debug [Main]: in ~EngineMaster() 
Debug [Main]: 3016 ms deleting DlgPreferences 
Debug [Main]: 3031 ms deleting EffectsManager 
Debug [Main]: 3062 ms deleting SettingsManager 
Debug [Main]: Mixxx shutdown complete with code 0

**Comment by daschuer** [comment]
Mixxx 2.1.1 is no longer supported. If you insist to use it you are on your own.

ASIO4ALL is evil, don't use it unless you know what you are doing. https://manual.mixxx.org/2.3/en/chapters/preferences/sound_hardware.html#sound-api

If the Focusrite Saffire 6 is the only soundcard you like to use, use ASIO with it's native ASIO driver shipped by Focusrite. If you like to use another soundcard like the onboard soundcard as well use directly WDM-KS.
