### ISSUE TITLE
Mixxx crash upon start

### ISSUE THREAD

**Issue by rkleczek457** [mixxxdj/mixxx#11190]
Mixx crashes when starting,logs in AppData are showing nothing. 
Specs:
Processor Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz 
Video Card NVIDIA GeForce RTX 3050 
Operating System Windows 10 64 bit
RAM 16 GB

**Comment by daschuer** [comment]
Which version of Mixxx do you use? 
Please create a Backtrace like described here: 
https://github.com/mixxxdj/mixxx/wiki/Creating-Backtraces#windows

**Comment by daschuer** [comment]
Can you tell us why this is no longer an issue?
