### ISSUE TITLE
No range limits for beatjump_size

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11203]
### Bug Description

While there is a list of allowed values for the beatloop_size, there is no limitation for the beatjumpsize in loopingcontrol.cpp.

If I set the beatjump_size from my controller I can set values, which the UI can't display, e.g. if I double 512, the cotroller display shows 1024 and the UI still 512.

I could change this, but I need to know, what is the intended behaviour:
- A list of dedicated values from 1/32 to 512 as for beatloop_size
- or a limitation to 3 digits (1/99 to 999)

### Version

2.4

### OS

Windows 11

**Comment by ronso0** [comment]
I'd say adopt the beatloop range for consistency.
The display limit is set in WBeatSpinBox https://github.com/mixxxdj/mixxx/blob/a3ad1cd13c9b185a6dc6c7744eba2f7e8e7f1dda/src/widget/wbeatspinbox.h#L15-L16

**Comment by JoergAtGithub** [comment]
I wonder what is the correct behaviour for SpinBox Up and Down buttons. Currently they doesn't clamp. For example, if I enter 300 and press Up in the GUI, the value remains 300:
https://github.com/mixxxdj/mixxx/blob/a3ad1cd13c9b185a6dc6c7744eba2f7e8e7f1dda/src/widget/wbeatspinbox.cpp#L58-L62
This is different to loop_halve/loop_double COs used by the controllers. I personally prefer the clamping behaviour of the COs, because this bring me back to normal potencies of 2 values.

**Comment by ronso0** [comment]
I agree both buttons and COs should be consistent.

> I personally prefer the clamping behaviour of the COs, because this bring me back to normal potencies of 2 values.

I presume a reset is 100% safe only when the deck is stopped or no loop is set.
Otoh pressing loop_double/_halve might happen in an active loop by accident, so the meaasure argument is correct IMO.
I have `beatloop_4_activate` in my mapping, so that'd be my way to reset to 2^n beats, though not all mappings and skins have that control.
So do we actually need such a reset control? Reset to what? Default loop size (4 beats), or round to nearest 2^n beats?

**Comment by JoergAtGithub** [comment]
The behavior for loop_size is now:
GUI-Widget: 300->PressDouble->300
Controller: 300->loop_double->512

The behavior for beatjump_size is now:
GUI-Widget: 300->PressDouble->300
Controller: 300->loop_double->600

I think there should be only one rule, implemented in loopingcontrol.cpp, which applies for both.
My personal favorite would be the behaviour of the loop_double CO, because I never want other values than 2^n and it's easy to apply by a rotary loop encoder. But others might use non 2^n loop and beatjump sizes. Therefore I will adapt the current GUI widget rule.
