### ISSUE TITLE
Audio keeps breaking (on) Linux

### ISSUE THREAD

**Issue by betalars** [mixxxdj/mixxx#11205]
## Overview

Mixxx Audio on Linux is borked when you start the application. It also breaks Audio Playback system-wide while the application is running.

## Steps to Reproduce
1. Start Mixxx
2. Don't configure the Audio
### Expected Result
There's  a reasonable preset, that works good enough and you can change that if you need to.
### Observed Result
Audio Playback does not work in Mixxx at all and all my System Audio no longer works while Mixxx is running.

## Additional Information
I wasn't sure if this is intentional behavior or if this is a bug, but as it works per default on windows, I figured this might be a bug. However, as I have a unusual use-case, you might want some additional info:

I am just a humble DungeonMaster. I use Mixxx to play ambient music because it can
- loop Audio tracks seemlessly, even when they have an opening
- categorise and organise music
- blend between tracks
and more noob-freindly applications like vlc just can't do that.

I see why a DJ would want and need to properly do their audio setup to be able to use Mixxx.

But like ... I don't. Please just let me use pulse like any other application and if that means headphones and all decks all play on the same audio device per default, that sounds like a me-problem. And re-configuring no preset vs re-configuring a weird preset seems like the same amount of work to me, with the difference being Mixxx works more when you have a weird preset.

Ps.: I use pulse most of the time.

### Version

2.3.3

### OS

nixOS (Linux), Arch (Linux)

**Comment by betalars** [comment]
> Just disable the pulseaudio suspender
I think a feature, that breaks all other applications, should really not be enabled by default.

I get that this is a pro thing you'd want to allow people to do. But not by default.

**Comment by ronso0** [comment]
Maybe we can add a second launcher without pasuspender, but I vite against changing the primary.

**Comment by betalars** [comment]
There is a promt, that informs you when you have not set up your audio yet.

Why not make a prompt (upon first startup) explaining, how Syncthing would like to disable playback system-wide to reduce latency and if you are okay with it?

1. Users can easily opt out of this strange behavior.
2. Users can then also understand, that and why this is happening.

**Comment by daschuer** [comment]
We have here a bug suggesting making it a preferences option: https://github.com/mixxxdj/mixxx/issues/10675
This is also related: https://github.com/mixxxdj/mixxx/issues/8285
And this: https://github.com/mixxxdj/mixxx/issues/7828

Is your idea covered by one of them? Else file a new issue.
