### ISSUE TITLE
Mixxx cuts off right side of decks on 4:3 aspect ratio

### ISSUE THREAD

**Issue by mjsir911** [mixxxdj/mixxx#11215]
### Bug Description

See screenshot, bpm slider is cut off the side of the screen

![img](https://i.imgur.com/RiKed7O.png)

### Version

2.3.3

### OS

Gentoo Linux

**Comment by daschuer** [comment]
What is the native resolution of your screen? The screenshot is 2255x1503 with 2 x scaling. What is the native resolution of your screen? 
You may start Mixxx 2.3.3 with 
`QT_SCALE_FACTOR=1.5 ./mixxx`
or us the setting in the Mixxx 2.4-alpha interface settings. 

Alternatively you may pick a smaller skin. You see a warning if the skin does not fit to your screen. Does it happen? 
Normally Mixxx should pick a fitting skin by default. Is this broken?

**Comment by mjsir911** [comment]
I'm using a framework laptop with a screen resolution of `2256x1504`, I think the 2x scaling is coming from my `.Xresources`': `Xft.dpi: 192`

This is what xrandr is reporting:
```
 $ xrandr
Screen 0: minimum 8 x 8, current 8256 x 1504, maximum 32767 x 32767
eDP1 connected primary 2256x1504+0+0 (normal left inverted right x axis y axis) 280mm x 190mm
   2256x1504     60.00*+  48.00  
```

>  QT_SCALE_FACTOR=1.5 ./mixxx

This makes it even bigger. I haven't figured out how to undo screen scaling changes on my machine but I'll look into it later and then try this command again.

> Alternatively you may pick a smaller skin. You see a warning if the skin does not fit to your screen. Does it happen?
> Normally Mixxx should pick a fitting skin by default. Is this broken?

I think this is broken. I haven't been messing with skin settings and this is the default that comes up.

Warnings attached here, I don't see any screen fit issues.
```
 $ mixxx
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-msirabella'
Warning [Main]: failed to resolve JACK name method
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib /var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1/work/alsa-plugins-1.2.7.1/usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib /var/tmp/portage/media-plugins/alsa-plugins-1.2.7.1/work/alsa-plugins-1.2.7.1/usb_stream/pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.7.2/work/alsa-lib-1.2.7.2/src/pcm/pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Warning [Main]: CoverArtDelegate - Failed to load cover  "CoverInfo(METADATA,GUESSED,,0x736d,/home/msirabella/tunes/nanobii/Love Songs/nanobii - Love Songs - 01 Hello.mp3,)"

```

**Comment by ronso0** [comment]
> > QT_SCALE_FACTOR=1.5 ./mixxx
> 
> This makes it even bigger.

So `QT_SCALE_FACTOR=0.75 ./mixxx` or just `mixxx` with 75% in the preferences should get you the desired size,no?

**Comment by mjsir911** [comment]
that fixes it, thank you!
