### ISSUE TITLE
Write Serato Metadata checkbox is ignored when writing track metadata is disabled

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11226]
### Bug Description

I think it would be reasonable to disable and gray out the checkbox in this case. 

### Version

2.3.3

**Comment by tech-bash** [comment]
Exactly what we need to do in it?

**Comment by daschuer** [comment]
This is about the library preferences. 
Did you find both checkboxes? Search the code for the visblevstings an it will lead you to the right location.

**Comment by tech-bash** [comment]
I am not getting anything out of the search.

**Comment by daschuer** [comment]
Oh sorry that was a typo. I mean take a string you see in the GUI and search for it in the code. Make sure to switch the GUI to English-US before to see the strings from the source files.

**Comment by tech-bash** [comment]
What string if I can ask! ;)

**Comment by Holzhaus** [comment]
> What string if I can ask! ;)

The string next to the checkbox in the settings.
