### ISSUE TITLE
Effect preferences: add shortcut to the chains directory

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11240]
### Feature Description

to simplify sharing fx chains

**Comment by tech-bash** [comment]
Can you please elaborate a bit! I would like to see to this.

**Comment by ronso0** [comment]
I thought about a button to open the `effects` directory, like there is at the bottom of the Preferences > Library to open the Mixxx settings directory.

Though, that is actually not required since there are `Import` and `Export` buttons in the Effects > Chains tab already.
