### ISSUE TITLE
Support the `.musicdb` generated by Apple's `Music.app` (which replaces iTunes in newer macOS versions)

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#11256]
### Feature Description

This seems to be a binary format, we might, however, be able to use Objective-C++ (similar to #4809) and could interface with the `iTunesLibrary` Framework to implement this (since this should only be relevant on macOS anyway).

See also:

- https://superuser.com/questions/1491509/is-the-format-schema-of-the-apple-music-library-musicdb-used-in-macos-catalina

**Comment by fwcd** [comment]
Ah, I've just found an issue which this is likely a duplicate of, proposing a similar solution:

- https://github.com/mixxxdj/mixxx/issues/9688

I think the XML iTunes Library is definitely worth keeping around, since even the `Music.app` still supports manually exporting an XML through the menu.

What might be worth investigating is whether the upcoming Apple Music Beta app for Windows 11 will replace iTunes and whether it also uses `Music.app`'s new binary format.

In the future, reverse-engineering the binary format might be an interesting task for cross-platform compatibility, especially if users moving between Macs and e.g. Linux PCs want to read their playlists on the go.

In any case, making use of the first-class `iTunesLibrary` framework on macOS would make sense to me, especially since it seems to be more 'future-proof' against potential future versions and, as long as we make sure not to break anything on other OSes, be purely additive.

**Comment by fwcd** [comment]
So after toying around a bit with the Apple Music Preview for Windows, it seems to be essentially a reskinned app using the same codebase as `Music.app` and presumably iTunes. It uses the new `.musicdb` format, can be used without an Apple Music Subscription or login as a plain old offline music player and even supports the iTunes Store. Thus if Apple intends to deprecate iTunes on Windows eventually, this might become interesting for DJs that use it to manage their local music collection and want to access it through Mixxx.

**Comment by fwcd** [comment]
Implemented in #11353

**Comment by fwcd** [comment]
Related:

- https://superuser.com/questions/1781974/is-apple-music-the-app-not-the-service-for-windows-scriptable
- https://forums.developer.apple.com/forums/thread/729225
- https://forums.developer.apple.com/forums/thread/740837

**Comment by belatar** [comment]
> macOS support is implemented in #11353
> 
> If/when Apple Music for Windows fully replaces iTunes there, we might investigate writing our own parser for `.musicdb` libraries, more details on this in [#11256 (comment)](https://github.com/mixxxdj/mixxx/issues/11256#issuecomment-1423050210). The primary issue I see is that redistributing the encryption key for `.musicdb` files may not be permitted.
> 
> Aside from that, it will also be interesting to see how other DJ programs will handle this scenario, given that iTunes is still a popular choice for library management among DJs and the fact that there is no direct equivalent to the `iTunesLibrary` framework outside of macOS.

hi! i wonder what the status of this on windows is? im looking for a way to read a Library.musicdb file on windows and tried installing the v2.4.1 of mixxx but it didnt offer a way to import / read it.

**Comment by fwcd** [comment]
Currently not implemented, sadly. Parsing the musicdb manually is possible and I have toyed around with implementing [the reverse engineered schema](https://home.vollink.com/gary/playlister/musicdb.html) myself. I don't see Mixxx adopting this, however, since it requires redistributing a proprietary encryption key, which might be legally risky even though it can be found in similar projects online (though I am not a lawyer).

Our best bet would probably be hoping for Apple to expose some kind of API to read the library, like on macOS. As mentioned in https://github.com/mixxxdj/mixxx/issues/11256#issuecomment-1934424923, there seem to be some requests for this and if iTunes for Windows is eventually sunset, my hope is that they offer some migration path given that other popular DJ programs rely on parsing the legacy XML.

If you are interested in this too, I would encourage you to file a suggestion for a local Apple Music API on Windows at https://feedbackassistant.apple.com/. Assuming that DJs are a key demographic among iTunes users that are primarily interested in buying music as opposed to streaming, having enough people file feedback might make them more likely to consider this.

**Comment by belatar** [comment]
thanks for the response, i might actually do that although i dont even have any financial motivation. its only that my mac broke, i only have a file copy of my music library but the windows version of apple music doesnt open the backup file. and now all my playlists compiled over the decades are gone (music files themselves i have). im quite frustrated at the incompatibility and even apple support couldnt help.
