### ISSUE TITLE
Messed up skin without OpenGL

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11286]
### Bug Description

I have revived my eeePC with Ubuntu Bionic to see how  Mixxx 2.3.4 will work. 
Unfortunately OpenGL is no longer working and the skin looks messed up. 

![grafik](https://user-images.githubusercontent.com/1777442/219969724-7f62da67-559c-4283-908c-afaa6b41c6f3.png)
  
OpenGL version is with 1.4 in dead lower than the minimum, but OpenGL ES is with 2.0 should be OK.  

I think we 

### Version

2.3

### OS

Ubuntu Bionic

**Comment by ronso0** [comment]
> I think we

... ?

**Comment by daschuer** [comment]
I think we should default to non GL vumeters when GL is not available. I will also investigate why GL ES is not used.
