### ISSUE TITLE
cannot configure audio output at preference

### ISSUE THREAD

**Issue by thynekong** [mixxxdj/mixxx#11297]
### Bug Description

would like to connect audio panel, bluetooth speakers or headphone. but cannot configure audio output at preference Mixxx 2.3.3

### Version

2.3.3

### OS

MacOS Ventura 13

**Comment by daschuer** [comment]
Fory understanding macOS Ventura 13 is nit yet supported by Mixxx 2.3.3.
This will bring 2.3.4. please try this developer snapshot  https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-150-g0377c61e34-macosintel.dmg
and report your results. 
A screenshot of your Mixxxx sound hardware preferences is also helpfully and you mixxxx.log file https://github.com/mixxxdj/mixxx/wiki/Finding-The-Mixxx.Log-File
