### ISSUE TITLE
Midi for light gets stuck not detecting deck change

### ISSUE THREAD

**Issue by codecat** [mixxxdj/mixxx#11322]
### Bug Description

Sometimes it is possible that the [`Midi_for_light` MIDI script](https://github.com/mixxxdj/mixxx/wiki/midi_clock_output) gets stuck, and stops detecting deck changes, thereby stopping beats from transmitting.

A reliable way to reproduce it:
1. Load 2 tracks into deck A/B and set the crossfader to deck B
2. Enable the MIDI script in the settings now
3. Start playing the track on deck B, note that beat events are transmitted
4. Press Cue on deck B to stop the track
5. Set the crossfader to deck A, note that this does not transmit a deck change event
6. Start playing the track on deck A, note that no beat events are transmitted

### Version

2.3.3

### OS

Windows 11

**Comment by fwcd** [comment]
Fixed in #13513
