### ISSUE TITLE
Add button for Login on the main page

### ISSUE THREAD

**Issue by tech-bash** [mixxxdj/mixxx#11347]
### Feature Description

While using ***Mixxx***, I came across the 'Live broadcasting' feature which requires the credentials of the user, so instead of digging in for login support, maybe we can have a Login button with all the required details on the main page(beside the settings button) for a quick scan!

**Comment by ronso0** [comment]
Currently, the credentials are entered once for each connection in the broadcast peferences. If you want to go live you just need to click a button / hotkey.
What's simpler than that?

**Comment by AyushD95** [comment]
Hi, @ronso0 , I can solve this issue.

**Comment by tech-bash** [comment]
Alright, my bad then ;)
Thanks @ronso0!
