### ISSUE TITLE
Strange flickering in the waveform display

### ISSUE THREAD

**Issue by atskler** [mixxxdj/mixxx#11340]
### Bug Description

With main I observed some strange flickering in the upper waveform display region. I still don't know how to reproduce it because it is really intermittent. It looks like this:

https://www.youtube.com/watch?v=F_MHWPk8AZ0

### Version

main (2.5-alpha-pre)

### OS

OpenSUSE Tumbleweed

**Comment by daschuer** [comment]
Which of the possible waveform types is affected?
What is your display manager, desktop environment, and graphic-card and driver?

**Comment by atskler** [comment]
Probably it happens when tracks are quickly and randomly loaded and unloaded after each other to the two decks. It happens with all the GL and GLSL types except for the new “RGB (QOpenGL) (GLSL)  “ type.

On this video that I recorded for reporting another bug, you can see it suddenly appearing at ~13 sec:
https://www.youtube.com/watch?v=LHlp103QXwk

System info:

```
inxi -GIMSayz
System:
  Kernel: 6.2.1-1-default arch: x86_64 bits: 64 compiler: gcc v: 12.2.1
    parameters: BOOT_IMAGE=/vmlinuz-6.2.1-1-default
    root=/dev/mapper/vlg--mnh-mnh--root splash=silent systemd.show_status=yes
    resume=/dev/vlg-mnh/mnh-swap quiet security=apparmor threadirqs splash=verbose
    plymouth.enable=0 [further not public stuff]
  Desktop: KDE Plasma v: 5.27.2 tk: Qt v: 5.15.8 wm: kwin_x11 vt: 7 dm:
    1: GDM v: 43.0 2: SDDM note: stopped Distro: openSUSE Tumbleweed 20230303
Machine:
  Type: Laptop System: Dell product: Latitude E6520 v: 01
    serial: <superuser required> Chassis: type: 9 serial: <superuser required>
  Mobo: Dell model: 0NVF5K v: A01 serial: <superuser required> UEFI: Dell
    v: A21 date: 03/06/2018
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    vendor: Dell driver: i915 v: kernel arch: Gen-6 process: Intel 32nm
    built: 2011 ports: active: LVDS-1 empty: DP-1, DP-2, DP-3, HDMI-A-1,
    HDMI-A-2, HDMI-A-3, VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0126 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.7 with: Xwayland v: 22.1.8
    compositor: kwin_x11 driver: X: loaded: modesetting dri: crocus gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.00x11.22")
    s-diag: 582mm (22.93")
  Monitor-1: LVDS-1 model: Seiko Epson 0x5448 built: 2010 res: 1920x1080
    hz: 60 dpi: 142 gamma: 1.2 size: 344x194mm (13.54x7.64") diag: 395mm (15.5")
    ratio: 16:9 modes: 1920x1080
  API: OpenGL v: 3.3 Mesa 23.0.0 renderer: Mesa Intel HD Graphics 3000 (SNB
    GT2) direct render: Yes
Info:
  Processes: 278 Uptime: 3h 55m wakeups: 20542 Memory: 15.5 GiB
  used: 4.88 GiB (31.5%) Init: systemd v: 252 default: graphical
  tool: systemctl Compilers: gcc: 12.2.1 alt: 12/13 Packages: pm: rpm pkgs: N/A
  note: see --rpm tools: yast,zypper pm: flatpak pkgs: 6 Shell: Bash v: 5.2.15
  running-in: konsole inxi: 3.3.23
```

**Comment by MarcPlace** [comment]
I also have this issue (that flickering in all GL/GLSL waveforms like in the 2nd video) with recent 2.4 branch (9df9dcb6aa10b44eebd4f7b7e3fd8e7bc513bdc7), so I blamed this version for this and went back to the last working commit I was aware it had worked before. Unfortunately the issue was still there, so I did some further investigation yesterday.
I've noticed that Gentoo has rolled out a newer Version of Mesa as stable a few days before (22.3.6), so I reverted Mesa back to the prior version (22.2.5). Et voila... the flickering has gone at least for me. Not quite sure what they have changed between both Mesa versions.
My Notebook has also an Intel Integrated Graphics (don't know exactly which one, will take a closer look later on when I'm back home), so this issue might be something Intel graphics related as no one else has reported it before.
HTH...
Marco

**Comment by m0dB** [comment]
@atskler 

> except for the new “RGB (QOpenGL) (GLSL) “ type.

I am surprised you are seeing this waveform type. This type was added in pull request, https://github.com/mixxxdj/mixxx/pull/10989 , which as far as I am aware has not been merged into the main branch yet. (Apart from the added waveform type it used a different backend for all GL widgets)

**Comment by atskler** [comment]
@m0dB 
> I am surprised you are seeing this waveform type. This type was added in pull request, #10989 , which as far as I am aware has not been merged into the main branch yet. (Apart from the added waveform type it used a different backend for all GL widgets)

For testing I additionally built a code that includes #10989 ;)

**Comment by m0dB** [comment]
That explains things! Flickering aside, do you notice improved performance, especially when using this new waveform type? Running at 60 fps smoothly?

**Comment by atskler** [comment]
@m0dB in my experience it behaves just as smoothly and jerky as before. It runs quite smoothly, but jerks when the mouse goes above it. I created a video, it captures well its performance and jerking. Set the youtube playback to 1080p60.

0:01 RGB (GLSL)
0:51 RGB (QOpenGL) (GLSL)

https://www.youtube.com/watch?v=Wuyy3-cFKQE

**Comment by atskler** [comment]
This problem seems to be gone in v2.3.5.

**Comment by daschuer** [comment]
Thank you for confirming an thank you @m0dB for the fix in https://github.com/mixxxdj/mixxx/pull/11523
