### ISSUE TITLE
New effects are hidden after upgrade 2.4

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11343]
### Bug Description

After a new installation all build in effects are visible. This is not the case if a use upgrades from a previous version of Mixxx and the new version brings new effects. In this case these new effects are hidden and there is a good chance that they are never discovered/used by the user. 

### Version

2.4

### OS

all

**Comment by ronso0** [comment]
One way to show new effects would be to also write a `HiddenEffects` list to effects.xml.
On start EffectsManager would then check if each (built-in) effect is in `VisibleEffects` or `HiddenEffects` -- if not, it is added to the visible effects list.

**Comment by ronso0** [comment]
Or write only HiddenEffects to be safe.

Question is how to ensure visibility after upgrading.
Reset visible state of **all** effects?
Read version added and show all new effects? I.e. add that tag for all effects added after 2.3.*

**Comment by daschuer** [comment]
I think we need to track hidden effects as well. 
This way we can maintain a three state. Shown/Hidden/New

**Comment by daschuer** [comment]
That should work already according you proposal, or do I miss a point. We can simply show new effects that are in non of both lists.

**Comment by ronso0** [comment]
I was thinking about LV2 plugins, but they're handled differently (if no Visible list exists, only built-in effects are added).
So yeah, comparing Visible and Hidden, then show all effects that are in neither list should work.

Working on it.

**Comment by ronso0** [comment]
Taking a closer look now. I was worried users upgarding from 2.3 would miss new effects but the visible/hidden state isn't migrate from mixxx.cfg anyway, i.e. all built-in effects are visible in 2.4 then.

Hence, storing both hidden and visible effects will indeed do the trick when new effects are added after 2.4.0

**Comment by ronso0** [comment]
Removing from the 2.4 milestone and scheduling to 2.4.1 because that could be the first version with new effects.

**Comment by ronso0** [comment]
> So yeah, comparing Visible and Hidden, then show all effects that are in neither list should work.
>
> Working on it.

Not sure if I'll make in time for 2.5, let alone 2.5-beta.
Wdyt about the **added in version x** check as a bandaid? That will also unhide effects added in 2.4 when upgrading from 2.4.1
We'd need to add that to the manifest of **all** built-in effects.

**Comment by daschuer** [comment]
Sounds good.

**Comment by ronso0** [comment]
> the added in version x check

I'm just tetsing this, but that'll re-show effects (added after 2.3) on every start.
Looks like there's no way around a Hidden list. I'll see if I can finish that for 2.5, have some WIP stuff stashed that might work.

**Comment by JoergAtGithub** [comment]
Can this be closed now, after merging #13326 ?

**Comment by ronso0** [comment]
Yup, will close
