### ISSUE TITLE
Mixxx 2.3.4 win10 hangs while starting.

### ISSUE THREAD

**Issue by SheriBlonde** [mixxxdj/mixxx#11342]
### Bug Description

https://mixxx.discourse.group/t/new-install-of-mixxx-2-3-4-win64-hangs-on-starting/26788/10

Win10 mixxx2.3.4
AMD 5700XT

Mixxx hangs on startup.

### Version

2.3.4

### OS

Windows 10

**Comment by SheriBlonde** [comment]
Mixxx used to work until I upgraded to mixx 2.3.4

Mixxx hangs when I start it.

https://mixxx.discourse.group/t/new-install-of-mixxx-2-3-4-win64-hangs-on-starting/26788/10

When I run .\mixxx.exe --safe-mode

C:\Program Files\Mixxx>.\mixxx.exe --safe-mode

C:\Program Files\Mixxx>AsioDrv::: CAsioDrv()…
AsioDrv::: InitWdmDrv()…
Critical [Main]: ARB::createContext: wglCreateContextAttribsARB() failed (GL error code: 0x0) for format: QSurfaceFormat(version 2.0, options QFlagsQSurfaceFormat::FormatOption(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 1, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 0, colorSpace QSurfaceFormat::DefaultColorSpace, profile QSurfaceFormat::NoProfile), shared context: 0x30000 (The operation completed successfully.)
Critical [Main]: GDI::createContext: wglShareLists() failed. (The specified module could not be found.)






AMD drivers 23.2.1 and 23.2.2 give the same errors.

**Comment by daschuer** [comment]
We have some (152) intermediate builds between 2.3.3 and 2.3.4 here: https://downloads.mixxx.org/snapshots/2.3
It would very helpful to find the first one that introduces the issue. 

This is a candidate: https://github.com/mixxxdj/mixxx/commit/a0ffb6b0a81081f205694193582bb7bd736e188b

Can you try out:
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-52-gaf27d63157-win64.msi
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-53-ga0ffb6b0a8-win64.msi

From there we may crawl up or down by halving the distance to the last known good or bad build.

**Comment by SheriBlonde** [comment]
2.3.3-52 works
2.3.3-53 Hangs

**Comment by SheriBlonde** [comment]
What changed between 22.3.3-52 and 2.3.3-53 that would make it stop working?
I am going to use 22.3.3-52 for now.
I'm also trying to map a Pioneer DDJ-FLX4 to mixxx.

**Comment by SheriBlonde** [comment]
C:\Program Files\Mixxx>.\mixxx.exe --safe-mode

C:\Program Files\Mixxx>Warning [Main]: Configuration file is at version "2.2.4" instead of the current "2.3.3"
AsioDrv::: CAsioDrv()...
AsioDrv::: InitWdmDrv()...
Critical [Main]: ARB::createContext: wglCreateContextAttribsARB() failed (GL error code: 0x0) for format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 1, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 0, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile), shared context: 0x30000 (The operation completed successfully.)
Critical [Main]: GDI::createContext: wglShareLists() failed. (The specified module could not be found.)

**Comment by SheriBlonde** [comment]
I tried looking up stuff on sglShareLists() failed and I don't think I understand what they are talking about.

https://community.khronos.org/t/wglsharelists-failing/42656

**Comment by SheriBlonde** [comment]
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-52-gaf27d63157-win64.msi 

works!

https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-53-ga0ffb6b0a8-win64.msi

Hangs in the starting slash screen!

**Comment by SheriBlonde** [comment]
I have 32 Gigs of memory ...

The error I get is wglShareLists() failed.

**Comment by daschuer** [comment]
2.3.3-53 has the flag "--disableVuMeterGL" that aims to revert the change. Does it fix the issue?

**Comment by daschuer** [comment]
The error message is created here: 
https://github.com/qt/qtbase/blob/4ee4fc18b4067b90efa46ca9baba74f53b54d9ec/src/plugins/platforms/windows/qwindowsglcontext.cpp#L491
and here: 
https://github.com/qt/qtbase/blob/4ee4fc18b4067b90efa46ca9baba74f53b54d9ec/src/corelib/kernel/qsystemerror.cpp#L103
from the windows error code ERROR_MOD_NOT_FOUND.

**Comment by SheriBlonde** [comment]
> 2.3.3-53 has the flag "--disableVuMeterGL" that aims to revert the change. Does it fix the issue?

Yes --disableVuMeterGL 
causes mixxx to load!!! Yaya!!
What is happening here?

**Comment by daschuer** [comment]
I have just noticed that the "--safe-mode" parameter has been introduced with Mixxx 2.4-alpha. In Mixxx 2.3.4 only "--safeMode" is available. Can you check if Mixxx starts with `.\mixxx.exe --safeMode`. My guess is yes. 

To fix this bug, we may either set `--disableVuMeterGL` automatically or find the root cause of the issue. 
Can you please attache a complete mixxx.log form a run with and without `--disableVuMeterGL` ? Hopefully it will reveal some hints we can use for the fix.

**Comment by m0dB** [comment]
We could at least disable VuMeterGL on Windows by default until we figure this out. We have not had similar reports of problems on macOS or Linux, right?

**Comment by m0dB** [comment]
@SheriBlonde in your Preferences dialog, Waveforms tab, do you have the "RGB (GLSL)" waveform listed in the waveform type popup menu? Does it work?

**Comment by daschuer** [comment]
> We have not had similar reports of problems on macOS or Linux, right?

Right, but we have also no one that is confirming this bug. If we good a confirmation, that would rectify a quick fix release for me.

**Comment by SheriBlonde** [comment]
I don't understand what's going on,
I uninstalled 2.3.4 (HEAD) works now.
Maybe it's related to plugging in the DDJ-FLX4 controller?
Not sure what's going on....

**Comment by SheriBlonde** [comment]
// I mean I uninstalled 2.3.3 and installed 2.3.4 ...

**Comment by m0dB** [comment]
I doubt it is related to plugging in the controller. Please let me know if you run into the issue again.

In the mean time, it would be great if you could give the build from my gopengl_renderers  branch  a try. You can find a windows installer at the bottom of this page: 

https://github.com/mixxxdj/mixxx/actions/runs/4337377093

Ideally selecting the RGB (QOpenGL) (GLSL) waveform type.

**Comment by SheriBlonde** [comment]
Plugged in the controller, it works.
One thing I notice is that the line under where it says mixxx on the starting/splash screen is coloured, it used to be gray.

**Comment by SheriBlonde** [comment]
Installed 

https://github.com/mixxxdj/mixxx/actions/runs/4337377093

**Comment by SheriBlonde** [comment]
How do I "Ideally selecting the RGB (QOpenGL) (GLSL) waveform type."

**Comment by m0dB** [comment]
In the preferences dialog (maybe called settings on windows?), waveforms, waveform type drop down. You will not have this RGB (QOpenGL) (GLSL) option with 2.3.4, but it should appear if you installed this version.

**Comment by hsn10** [comment]
Mine 2.3.4 crashing inside _ucrtbase_ here is stack dump. Probably some problems with asio driver.
mixxx --safeMode --developer --disableVuMeterGL do not fix the problem.

is this related?
```
ID vl Adresa           Na               Z                Veli Párty    Komentáře                                   
7908                                                                   
      0000005940D8B4B8 00007FFCDC6631D0 00007FFD1098286E A0   Uživatel ucrtbase.00007FFD1098286E
      0000005940D8B558 00007FFCDC63DBB2 00007FFCDC6631D0 570  Uživatel music maker asio.00007FFCDC6631D0
      0000005940D8BAC8 00007FFCDC633B8F 00007FFCDC63DBB2 1C0  Uživatel music maker asio.00007FFCDC63DBB2
      0000005940D8BC88 00007FFCDC639FB7 00007FFCDC633B8F 50   Uživatel music maker asio.00007FFCDC633B8F
      0000005940D8BCD8 00007FFCDEE4B361 00007FFCDC639FB7 30   Uživatel music maker asio.00007FFCDC639FB7
      0000005940D8BD08 00007FFCDEE486E5 00007FFCDEE4B361 30   Uživatel portaudio.00007FFCDEE4B361
      0000005940D8BD38 00007FFCDEE48321 00007FFCDEE486E5 1070 Uživatel portaudio.00007FFCDEE486E5
      0000005940D8CDA8 00007FFCDEE4AC69 00007FFCDEE48321 C0   Uživatel portaudio.00007FFCDEE48321
      0000005940D8CE68 00007FFCDEE43B5E 00007FFCDEE4AC69 40   Uživatel portaudio.00007FFCDEE4AC69
      0000005940D8CEA8 00007FFCDC63DBEB 00007FFCDEE43B5E 570  Uživatel portaudio.00007FFCDEE43B5E
      0000005940D8D418 00007FFCDC633B8F 00007FFCDC63DBEB 1C0  Uživatel music maker asio.00007FFCDC63DBEB
      0000005940D8D5D8 00007FFCDC639FB7 00007FFCDC633B8F 50   Uživatel music maker asio.00007FFCDC633B8F
      0000005940D8D628 00007FFCDEE4B361 00007FFCDC639FB7 30   Uživatel music maker asio.00007FFCDC639FB7
      0000005940D8D658 00007FFCDEE486E5 00007FFCDEE4B361 30   Uživatel portaudio.00007FFCDEE4B361
      0000005940D8D688 00007FFCDEE48321 00007FFCDEE486E5 1070 Uživatel portaudio.00007FFCDEE486E5
      0000005940D8E6F8 00007FFCDEE4AC69 00007FFCDEE48321 C0   Uživatel portaudio.00007FFCDEE48321
      0000005940D8E7B8 00007FFCDEE43B5E 00007FFCDEE4AC69 40   Uživatel portaudio.00007FFCDEE4AC69
      0000005940D8E7F8 00007FF66B77039C 00007FFCDEE43B5E F0   Uživatel portaudio.00007FFCDEE43B5E
      0000005940D8E8E8 00007FF66B7701AE 00007FF66B77039C 30   Uživatel mixxx.SoundManager::queryDevicesPortaudio+2C
      0000005940D8E918 00007FF66B76D2BC 00007FF66B7701AE 100  Uživatel mixxx.SoundManager::queryDevices+E
      0000005940D8EA18 00007FF66B743991 00007FF66B76D2BC 7F0  Uživatel mixxx.SoundManager::SoundManager+46C
      0000005940D8F208 00007FF66B73DB34 00007FF66B743991 C0   Uživatel mixxx.MixxxMainWindow::initialize+841
      0000005940D8F2C8 00007FF66B7393E9 00007FF66B73DB34 180  Uživatel mixxx.MixxxMainWindow::MixxxMainWindow+384
      0000005940D8F448 00007FF66B73972B 00007FF66B7393E9 2E0  Uživatel mixxx.`anonymous namespace'::runMixxx+19
      0000005940D8F728 00007FF66BB8CDE4 00007FF66B73972B 40   Uživatel mixxx.main+23B
      0000005940D8F768 00007FFD121D7614 00007FF66BB8CDE4 30   Systém   mixxx.__scrt_common_main_seh+10C
      0000005940D8F798 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      0000005940D8F818 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
20864                                                                  
      00000059414FF468 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059414FF768 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059414FF798 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059414FF818 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
3100                                                                   
      00000059413FF8F8 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059413FFBF8 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059413FFC28 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059413FFCA8 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
1192                                                                   
      00000059416FF4A8 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059416FF7A8 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059416FF7D8 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059416FF858 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
14368                                                                  
      00000059410FF8A8 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059410FFBA8 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059410FFBD8 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059410FFC58 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
8540                                                                   
      00000059411FFB28 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059411FFE28 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059411FFE58 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059411FFED8 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
14824                                                                  
      00000059417FFA68 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059417FFD68 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059417FFD98 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059417FFE18 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
21896                                                                  
      00000059412FF8A8 00007FFD13082E17 00007FFD130D0B14 300  Systém   ntdll.00007FFD130D0B14
      00000059412FFBA8 00007FFD121D7614 00007FFD13082E17 30   Systém   ntdll.00007FFD13082E17
      00000059412FFBD8 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059412FFC58 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
22116                                                                  
      00000059415FF898 00007FFD10A60590 00007FFD130CDC14 2F0  Systém   ntdll.00007FFD130CDC14
      00000059415FFB88 00007FFD12C13426 00007FFD10A60590 290  Systém   kernelbase.00007FFD10A60590
      00000059415FFE18 00007FFD12C132A0 00007FFD12C13426 50   Systém   combase.00007FFD12C13426
      00000059415FFE68 00007FFD12C130B0 00007FFD12C132A0 60   Systém   combase.00007FFD12C132A0
      00000059415FFEC8 00007FFD12C13039 00007FFD12C130B0 30   Systém   combase.00007FFD12C130B0
      00000059415FFEF8 00007FFD121D7614 00007FFD12C13039 30   Systém   combase.00007FFD12C13039
      00000059415FFF28 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059415FFFA8 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
7684                                                                   
      00000059418FFC58 00007FFD10A3306E 00007FFD130CD144 A0   Systém   ntdll.00007FFD130CD144
      00000059418FFCF8 00007FFCD5E9B10B 00007FFD10A3306E 50   Uživatel kernelbase.00007FFD10A3306E
      00000059418FFD48 00007FFCD5E9B176 00007FFCD5E9B10B 30   Uživatel qt5core.00007FFCD5E9B10B
      00000059418FFD78 00007FF66B8578CC 00007FFCD5E9B176 60   Uživatel qt5core.00007FFCD5E9B176
      00000059418FFDD8 00007FFCD5E95FA1 00007FF66B8578CC 30   Uživatel mixxx.EngineWorkerScheduler::run+16C
      00000059418FFE08 00007FFD121D7614 00007FFCD5E95FA1 30   Systém   qt5core.00007FFCD5E95FA1
      00000059418FFE38 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059418FFEB8 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
17812                                                                  
      00000059419FF848 00007FFD10A3306E 00007FFD130CD144 A0   Systém   ntdll.00007FFD130CD144
      00000059419FF8E8 00007FFCD5E9B10B 00007FFD10A3306E 50   Uživatel kernelbase.00007FFD10A3306E
      00000059419FF938 00007FFCD5E9B176 00007FFCD5E9B10B 30   Uživatel qt5core.00007FFCD5E9B10B
      00000059419FF968 00007FF66B8119B1 00007FFCD5E9B176 210  Uživatel qt5core.00007FFCD5E9B176
      00000059419FFB78 00007FFCD5E95FA1 00007FF66B8119B1 30   Uživatel mixxx.EngineSideChain::run+1C1
      00000059419FFBA8 00007FFD121D7614 00007FFCD5E95FA1 30   Systém   qt5core.00007FFCD5E95FA1
      00000059419FFBD8 00007FFD130826A1 00007FFD121D7614 80   Systém   kernel32.00007FFD121D7614
      00000059419FFC58 0000000000000000 00007FFD130826A1      Uživatel ntdll.00007FFD130826A1
```

**Comment by daschuer** [comment]
Since this is a crash it seems to be unrelated to the original issue. Can you file another bug and describe your Audio setup there?

**Comment by daschuer** [comment]
@hsn10 can you file a new issue for your crash?

**Comment by daschuer** [comment]
@SheriBlonde I can imagine your issue was related to a missing DLL so that it has ben fixed by the new installation. 
Can you confirm that you are now able to run Mixxx from the start menu without any command line flags? 

Can you than try to rename the libEGL.dll or the libGLESv2.dll in `C:\program files\mixxx` and try if you are able to reproduce the issue?
