### ISSUE TITLE
Memory Drain

### ISSUE THREAD

**Issue by Hunterforce23** [mixxxdj/mixxx#11354]
### Bug Description

I am currently running 2.3.4 and since upgrading i have had total crashes throughout my set causing total shutdown of the program, when looking at task manager i have noticed that Mixxx is using massive amount of ram, my system is set up with 32GB
This screen shot shows how much is being used
https://gyazo.com/d30a4d33af8689175714c2c8ee77496d
this is what happens after i close Mixxx
https://gyazo.com/14bfe544fa739385642dfff730981690
So i know its Mixxx thats draining my resorces
This shows how much CPU its using 
https://gyazo.com/878f9b3bdfb7e646a01eac916d64da8f
I can only the crashes down to the amount of memory its using, i dj in second life

### Version

2.3.4

**Comment by ronso0** [comment]
Which Windows version are you running?

**Comment by Hunterforce23** [comment]
Windows 11

**Comment by Hunterforce23** [comment]
https://gyazo.com/54ef46f585b433305ad404dea2eb575d

**Comment by ronso0** [comment]
FYI you can paste screenshots directly into the message box.

**Comment by daschuer** [comment]
The screenshots show that Mixxx is constantly eating memory. This is definitely not correct.  I am using Linux and Mixxx consumes ~700 MB RAM at max.  

Is Mixxx 2.3.3 not affected by the memory eating? 
It would be interesting with which intermediate version the eating has started
We have 152 builds between 2.3.3 and 2.3.4 here: https://downloads.mixxx.org/snapshots/2.3

We have another pending Windows issue that has started with Version 2.3.3-53 
https://github.com/mixxxdj/mixxx/issues/11342

Can you try out:
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-52-gaf27d63157-win64.msi
https://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-53-ga0ffb6b0a8-win64.msi

**Comment by ronso0** [comment]
@Hunterforce23 
> FYI you can paste screenshots directly into the message box.

or just describe what's happening, so others can see at a glance what's going on (instead of having to open another website).
Thanks!

**Comment by daschuer** [comment]
OK, so both are affected. 
Can you double check that [mixxx-2.3.3-1](http://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-1-g8facfb6075-win64.msi)
is not affected? 

Than please try to find the first version form https://downloads.mixxx.org/snapshots/2.3 that shows this issue by halving the build number. So the next would be [mixxx-2.3.3-27](http://downloads.mixxx.org/snapshots/2.3/mixxx-2.3.3-27-g9dfbca44a2-macosintel.dmg)

**Comment by daschuer** [comment]
@Hunterforce23 do you have any news? I think we should urgently fix this issue and release 2.3.5 on a short notice.

**Comment by atskler** [comment]
Checking the screenshots actually just one tells how much memory is used by Mixxx, and on that it is 757.7 MB.
Others screenshots just shows how much memory used by everything in total so they are meaningless for troubleshooting.

**Comment by daschuer** [comment]
@Hunterforce23 Do you still suffer this issue? we need you help to fix this with the 2.3.5 release.

**Comment by JoergAtGithub** [comment]
No response from reporter -> Close it
