### ISSUE TITLE
Fix redirect links

### ISSUE THREAD

**Issue by tech-bash** [mixxxdj/mixxx#11358]
### Bug Description

On **Set up with [Qtcreator](https://github.com/mixxxdj/mixxx/wiki/QtCreator)** page, the link "Compiling on linux" is redirecting to the Wiki's home page instead of[ this page.](https://github.com/mixxxdj/mixxx/wiki/Compiling%20on%20Linux)

**Comment by daschuer** [comment]
Fixed

**Comment by daschuer** [comment]
Thank you.
