### ISSUE TITLE
Switching to a broken skin can crash Mixxx

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11360]
### Bug Description

I just tried to debug the VU meter issue with **[Traktmixxx](https://mixxx.discourse.group/uploads/short-url/87LxtFu1oAb2ATL1vSE88MxXip1.zip)** skin reported [here](https://mixxx.discourse.group/t/2-3-4-causes-black-squares-on-level-meter-traktmixxx-skin/26808)

This makes Mixxx crash:
* copy Traktmixxx to ressource dir (here /usr/share/mixxx/skins/), actually not recommended
* start Mixxx with a new config dir
* boots with LateNight
* open preferences, select Traktmixxx
* skin seems to load, but crashes immediatley after
___
This way, however, I can start with Traktmixxx and it seems to work (at least not crash after some basic testing, track load, play etc):
* copy Traktmixxx to ressource dir (here /usr/share/mixxx/skins/), actually not recommended
* start Mixxx with a new config dir
* boots with LateNight
* switch skin or color theme so that `ResizableSkin [skin]` is written to `mixxx.cfg`
* close
* open `mixxx.cfg`, set `ResizableSkin Traktmixxx`
* start Mixxx
* works

**BUT**
* start with Traktmixxx as described
* switch to LateNight
* switch back to Traktmixxx
* CRASH
___

Backtrace:
[backtrace-LateNight-to-Traktmixxx.txt](https://github.com/mixxxdj/mixxx/files/10952268/backtrace-LateNight-to-Traktmixxx.txt)
btw, since when are gdb backtraces this huge? 13869 lines???

### Version

2.3.4

### OS

Ubuntu Studio 20.04 / X11 / xfce 4.14 / Qt 5.12.8

**Comment by ronso0** [comment]
maybe the cause is the same that led to this segfault?
https://github.com/mixxxdj/mixxx/pull/10893#issuecomment-1245195458

**Comment by ronso0** [comment]
starting with `--disableVuMeterGL` doesn't avoid the crash btw.

**Comment by ronso0** [comment]
I updated the description:
starting with Traktmixxx by writing it to mixxx.cfg manually works, but any following switch (to another skin and) back to Traktmixxx crashes Mixxx.

@m0dB Do you have any idea? Can you read anything from that backtrace?

**Comment by daschuer** [comment]
I can see the same segfault, original reported here: 
https://github.com/mixxxdj/mixxx/pull/10893#issuecomment-1250139458
And analyzed here: 
https://github.com/mixxxdj/mixxx/pull/10893#issuecomment-1262274554
and workaround here: 
https://github.com/m0dB/mixxx/pull/2/commits/c9af1e05b1a41aef568f76990650158e36bc2505

```
#0  0x0000000000000000 in  ()
#1  0x00007fffeb04f7e2 in QXcbWindow::handleNativeEvent(xcb_generic_event_t*) (this=<optimized out>, event=0x7fffe40e43c0) at qxcbwindow.cpp:1696
#2  0x00007fffeb03d404 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) (this=this@entry=0x5555563ce3c0, event=event@entry=0x7fffe40e43c0) at qxcbconnection.cpp:562
#3  0x00007fffeb03d78a in QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555563ce3c0, flags=flags@entry=...) at qxcbconnection.cpp:1027
#4  0x00007fffeb068327 in xcbSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at qxcbeventdispatcher.cpp:103
#5  0x00007ffff28dd17d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff28dd400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff28dd4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff3ceb435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555556480b20, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#9  0x00007ffff3c923ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdce0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#10 0x00007ffff3c9a116 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#11 0x000055555570ac42 in (anonymous namespace)::runMixxx (args=..., app=0x7fffffffdd70) at ../../src/main.cpp:37
#12 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../../src/main.cpp:112
```

**Comment by ronso0** [comment]
I removed all VU meters and all spinnies from Traktmixxx and still Mixxx crashes when switching to it.
Maybe worth noting: there are 6 Waveform widgets created per deck.

The end of the backtrace looks exactly like @daschuer's above.
Full backtrace
[bt Traktmixxx without vumeters and spinnies.txt](https://github.com/mixxxdj/mixxx/files/11288923/bt.Traktmixxx.without.vumeters.and.spinnies.txt)

**Comment by daschuer** [comment]
Unfortunately I can no longer reproduce the issue. 
Is this really a critical bug for the 2.3.5 milestone or can we proceed without a fix?

**Comment by ronso0** [comment]
I labeled it critical because user data must not crash Mixxx, but it's not clear if this is a 2.3.4 regression, and a fix is not in sight. So let's proceed!

**Comment by ronso0** [comment]
Update: Traktmixxx doesn't crash Mixxx 2.4

I'll close this for now.
