### ISSUE TITLE
Tooltip for "lower pitch temporarily" references incorrect page in Preferences

### ISSUE THREAD

**Issue by dragos240** [mixxxdj/mixxx#11384]
### Bug Description

In the "lower pitch temporarily" tooltip, it says to go into Preferences -> Interface to change the step size.
![image](https://user-images.githubusercontent.com/704081/225908413-5ea7410b-28f0-43f7-b6e4-d323b23af12d.png)

This is incorrect, as the setting is in Preferences -> Decks
![image](https://user-images.githubusercontent.com/704081/225908565-318c1337-af36-49a5-972a-39ac16bfbad2.png)

The tooltip should point to the correct page in Preferences.

### Version

2.3.4

### OS

Windows 10

**Comment by Swiftb0y** [comment]
Thank you, the corresponding string is at `src/skin/legacy/tooltips.cpp:326`

**Comment by manulpatel** [comment]
Hello @Swiftb0y! I am new to mixxx and want to contribute to solve this issue. Could you please guide or assign the issue to me?

**Comment by Swiftb0y** [comment]
We don't use the assign feature. Just setup a development environment, read our docs and open a pull request with a fix. The pages on our Wiki should get you started: https://github.com/mixxxdj/mixxx/wiki#developer-documentation
