### ISSUE TITLE
WDM-KS not working with Numark Mixtrack Pro FX

### ISSUE THREAD

**Issue by iamjackg** [mixxxdj/mixxx#11393]
### Bug Description

I picked up Mixxx again after a few years, and I'm still having some issues with my Numark Mixtrack Pro FX.

See #10186 and https://mixxx.discourse.group/t/mixxx-stopped-being-able-to-open-wdm-ks-devices/20791.

The behaviour seems to be somewhat different since back then: WDM-KS works fine with my built-in Realtek audio interface, but if I try to select my Mixtrack Pro FX I get an "Invalid device" error.

I tried with different sample rates, different buffer settings, but nothing works. I turned on debug mode, and the log didn't say anything useful: it just reported an "Invalid device" failure in `SoundDevicePortAudio::open`.

```
Debug [Main]: SoundDevicePortAudio::open() "SoundDeviceId(Speakers (MixTrack Pro FX), 29)"
Debug [Main]: framesPerBuffer: 1024
Debug [Main]: Requested sample rate:  44100 Hz, latency: 23.22 ms
Debug [Main]: Output channels: 4 | Input channels: 0
Debug [Main]: Opening stream with id 29
Warning [Main]: Error opening stream: Invalid device
```

Note that WASAPI does work fine.

### Version

2.3.4

### OS

Windows 10

**Comment by daschuer** [comment]
We use in our stable 2.3 branch Portaudio "2020-02-20" You may try the latest 2.4-alpha, that comes with "19.7" and check if that makes a difference. You find it here: https://downloads.mixxx.org/snapshots/main/mixxx-2.4-alpha-1421-g060b0e95d8-win64.msi

**Comment by daschuer** [comment]
Does using 48000 make a difference?

**Comment by JoergAtGithub** [comment]
@iamjackg Could you test if the issue still occurs with the following build (from https://github.com/mixxxdj/mixxx/pull/11451) : https://github.com/mixxxdj/mixxx/actions/runs/4637080755

**Comment by daschuer** [comment]
Fixed since https://github.com/mixxxdj/mixxx/pull/11451
