### ISSUE TITLE
v2.3.4 waveform displays are a bit glitchy on win7

### ISSUE THREAD

**Issue by travstone** [mixxxdj/mixxx#11429]
I know this is an old OS, but just to log the issue...

Updated a couple of days ago from 2.3.3, which has been working fine. Upon updating, the large (stacked) waveform displays are glitchy, sometimes not rendering anything, sometimes rendering screen content from "behind" mix (e.g. the desktop). Sometimes the playhead is just an empty grey square. I was *sometimes able to bump it into (temporarily) working correctly by changing the skin.

The deck waveform displays are also occasionally glitchy, rendering the entire track in the first 3/4 of the width with empty space after (when normally the entire waveform display would be occupied). I was *often able to un-glitch this by reloading the track.

Am downgrading back to v2.3.3, because not being able to see the track/beatgrid/cue points in realtime can be anywhere from inconvenient to a complete stopper depending on the circumstance.

EDIT: after reinstalling 2.3.3, everything's working normally, so seems likely a regression of some kind

**Comment by JoergAtGithub** [comment]
Could you try to start Mixxx.exe with the command line option `--disableVuMeterGL`
Does this option help?
Could you provide information about your system, especially graphics driver, number of monitors and monitor resolution.

**Comment by Aryan-Mishra24** [comment]
just finished with this issue  Fix crash when switching Keylock/Pitch-B Engine at 96kHz#11433, #11440 open   open to more work mind if i take a swing at this issue if no one else in intrested

**Comment by travstone** [comment]
Just to follow up, so far it seems like 2.3.5 has fixed the regression for me. Many thanks!

**Comment by daschuer** [comment]
Thank you for confirming
