### ISSUE TITLE
Show WASAPI loopback device

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11427]
### Feature Description

Audacity also PortAudio based allows to use it. In Mixxx it is not shown. 
We should change that. 
This should allow to capture the System sound of Firefox/Spotify and forward it to the DJ soundcard via the Mixxx mixer.

**Comment by EchoCoder1729** [comment]
https://github.com/PortAudio/portaudio/pull/672#issuecomment-1246877921
portaudio's current master is using the loopback devices patch.
I think we will get the Loopback devices using WASAPI if we replace mixxx's PortAudio DLL with their current release.

**Comment by Aryan-Mishra24** [comment]
update the PortAudio DLL in the Mixxx repository replace it with the latest version from the PortAudio project

**Comment by daschuer** [comment]
Fixed since https://github.com/mixxxdj/mixxx/pull/11451
