### ISSUE TITLE
Change History tree to show "Z to A" dated playlists instead of "A to Z" (current)

### ISSUE THREAD

**Issue by nPrevail** [mixxxdj/mixxx#11447]
### Feature Description

I noticed that the "History" tree shows a "playlist history" of songs based on the playlist's date. However, the History tree also orders these playlists to be shown as "A to Z," showing the "oldest" playlist first, and putting the "latest/newest" playlist at the very bottom.

I think it'd be more helpful if DJs could see the "latest/newest" playlist at the top, especially if a DJ had to prematurely shutdown or had a computer crash, or had to restart Mixxx, and if they had to play the last song they just played. This would also minimize the need to "scroll to the bottom" just to get to the latest playlist.

Honestly, I don't need to delete history as I don't mind the documentation, but it's more relevant to show your latest history, than your oldest history

For example: Mixxx currently shows History trees as A to Z:

History
  2022-09-26
  2022-09-27
  2022-11-29
  2022-12-17 **(newest playlist)**

If we did Z to A, history would show up as:

History
  2022-12-17 **(newest playlist)**
  2022-11-29
  2022-09-27
  2022-09-26

I think more DJs would prefer Z to A than having to scroll down the entire History list of playlists.

**Comment by ronso0** [comment]
The history was already overhauled by #2996 for Mixxx 2.4
Please test that and let us know if that's what you had in mind.
