### ISSUE TITLE
Waveforms dissapear after window resized

### ISSUE THREAD

**Issue by philwilkinson** [mixxxdj/mixxx#11460]
Hi, on my M2 mac the waveform is visible (in all themes that show it). But as I resize the window or make it full screen the waveform is replaced by a white background. The vertical grid lines and markers are visible. Resizing it smaller and the waveform re-appears.

<img width="2425" alt="image" src="https://user-images.githubusercontent.com/8225012/230790866-fa44940b-b065-4e50-ad66-0457f666abf5.png">

This is for Mixxx 2.3.4 on MacOs Ventura 13.3.1, on a M2 Macbook Pro.

**Comment by daschuer** [comment]
Has this issue happened on 2.3.3 before?

**Comment by philwilkinson** [comment]
The same thing happens in 2.3.3.
However the problem only happens when I put mixxx on any of my 2 4k external displays at the medium scale (medium text) setting to smallest scale (smaller text) setting AND the laptop is closed (operating in camshell mode), so the built in display is off.
If open the laptop, so the laptop screen is displaying, mixxx on the other 4k screen seems to get sorted out, in that there is no white background, however, when i close the laptop again, the right side of the wave form isn't displayed on the 4k monitor! 
The laptops built in display has no problem displaying waveforms in mixxx, even at the smallest scale (smaller text) setting (although the laptop resolution is less than 4k).

**Comment by daschuer** [comment]
Are all waveform types affected? Do you see issues whit the spinnies or Vu-Meters during resizting? 
Are loop markers and the end of track warning still there?

**Comment by philwilkinson** [comment]
I tried many combinations of `Waveform type` and _Waveform overview type_, and sometimes they would work and sometimes they wouldn't, there was no consistent combination that always worked.

The default is `RGB (GLSL)` - _RGB_ - This shows blank white initially.
If I change to `RGB (GL)` - _RGB_ - It worked fine.
Changing to `RGB (GL)` - _HSV_ - It went blank white.
back to `RGB (GL)` - _RGB_ - its still blank white.

There are no issues with the spinnies and the VU meters (which don't resize) and the loop and end of track markers also visible always.

**Comment by m0dB** [comment]
@philwilkinson could you try with the macOS arm64 build from this page 

https://github.com/mixxxdj/mixxx/actions/runs/5098639997?pr=10989

and select one of the (allshaders) waveform types.

**Comment by philwilkinson** [comment]
Thanks @m0dB

It works for...
`Filtered (GL), Filtered (all shaders) (GLSL) , RGB (GL), RGB (all-shaders) (GLSL), RBG L/R (all-shaders) (GLSL), Simple (GL), Simple (all-shaders) (GLSL)`

It doesn't work (still get blank white background) for...
`Filtered (GLSL), RGB (GLSL), RGB Stacked (GLSL)`

The result is the same for RGB,HSV and Filtered waveform overview type.
I hope this is what you expected.

**Comment by JoergAtGithub** [comment]
> The result is the same for RGB,HSV and Filtered waveform overview type.

Can you please elaborate this - because Overview Waveforms have no technical relationship to the Waveform implementation.

**Comment by m0dB** [comment]
Thanks for testing, @philwilkinson . Nice to hear the new "(all-shaders)" waveform types are working correctly. Our intention is that this (https://github.com/mixxxdj/mixxx/pull/10989) will be part of the 2.4 release, so that should solve your issue (which is pretty strange!)

**Comment by philwilkinson** [comment]
Great, thanks, so I guess this issue can be closed then as I can see that It'll work fine for all-shaders. Cheers.

**Comment by JoergAtGithub** [comment]
Fixed by #10989
