### ISSUE TITLE
GNOME 44: No drag&drop of tracks from table view to decks and sidebar

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11481]
### Bug Description

Shows the prohibit sign.

### OS

Fedora 38 / GNOME 44

**Comment by ronso0** [comment]
Are you already looking into this yourself?

If no, which Mixxx version? Are there any clues in the log?

**Comment by uklotzde** [comment]
> Are you already looking into this yourself?
> 
> If no, which Mixxx version? Are there any clues in the log?

- I only tested `main` so far.
- No suspicious logs.
- I am not planning to look into it.

**Comment by ronso0** [comment]
Are you dragging from a file browser or from within Mixxx? (just in case that makes a difference)
I preume these tracks play fine if you load them from a library feature?

**Comment by uklotzde** [comment]
> Are you dragging from a file browser or from within Mixxx? (just in case that makes a difference) I preume these tracks play fine if you load them from a library feature?

Within Mixxx. Drag & drop to the sidebar (e.g. Analysis) also doesn't work.

**Comment by uklotzde** [comment]
Works when using Wayland instead of XWayland (`-platform xcb`). But that causes other issues.

**Comment by uklotzde** [comment]
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2013235

**Comment by ywwg** [comment]
Looks like a fix has been committed and will be released with Mutter 44.2

**Comment by camelpunch** [comment]
I can confirm that with latest Mutter, this is resolved.
