### ISSUE TITLE
Clang 15/16 on Linux: MathUtilTest.Denormal (Failed)

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11484]
### Bug Description

Built with `-DOPTIMIZE=native`.

```
Note: Google Test filter = MathUtilTest.Denormal
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MathUtilTest
[ RUN      ] MathUtilTest.Denormal
/home/uk/volumes/Build/cpp/mixxx/src/test/mathutiltest.cpp:68: Failure
Expected: (0.0f) != (fDenormal), actual: 0 vs 0
/home/uk/volumes/Build/cpp/mixxx/src/test/mathutiltest.cpp:71: Failure
Expected: (0.0) != (dDenormal), actual: 0 vs 0
[  FAILED  ] MathUtilTest.Denormal (0 ms)
```

**Comment by daschuer** [comment]
The test discovers that denormals are flushed to zero even if it is not desired.
Can you post the verbose compile call of the test source file to see all compile flags that are used? 

Does it also fail with clang?

**Comment by uklotzde** [comment]
> Can you post the verbose compile call of the test source file to see all compile flags that are used?

Local build, no extra flags.

Full rebuild with Clang takes a long time. Not planned right now.

**Comment by daschuer** [comment]
I nee only the command line parameters of fidlib.c using GCC 13. You can output them without a full rebuild during the cmake configure step like: `cmake ../.. -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON`

In my case it is: 
```
{
  "directory": "/home/daniel/workspace/mixxx/build/Debug",
  "command": "/usr/bin/cc -DT_LINUX  -g -fvisibility=hidden   -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -mtune=generic -o CMakeFiles/fidlib.dir/lib/fidlib/fidlib.c.o   -c /home/daniel/workspace/mixxx/lib/fidlib/fidlib.c",
  "file": "/home/daniel/workspace/mixxx/lib/fidlib/fidlib.c"
},
```

**Comment by uklotzde** [comment]
"command": "/usr/lib64/ccache/clang++ -DMIXXX_USE_QOPENGL -DUSE_PTHREADS -Dkiss_fft_scalar=double -isystem /home/uk/volumes/Build/cpp/mixxx/lib/qm-dsp -isystem /home/uk/volumes/Build/cpp/mixxx/lib/qm-dsp/include  -fdiagnostics-color=always -g -std=gnu++20 -fvisibility=hidden -fvisibility-inlines-hidden -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -mtune=generic -o CMakeFiles/QueenMaryDsp.dir/lib/qm-dsp/maths/MathUtilities.cpp.o -c /home/uk/volumes/Build/cpp/mixxx/lib/qm-dsp/maths/MathUtilities.cpp",

"command": "/usr/lib64/ccache/clang++ -DMIXXX_BUILD_DEBUG -DMIXXX_DEBUG_ASSERTIONS_ENABLED -DMIXXX_DEBUG_ASSERTIONS_FATAL -DMIXXX_USE_QOPENGL -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_TABLET_SUPPORT -DQT_TESTCASE_BUILDDIR=\\\"/home/uk/volumes/Build/cpp/mixxx/build\\\" -DQT_TESTLIB_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -D__AOIDE__ -D__BATTERY__ -D__BROADCAST__ -D__BULK__ -D__CUSTOM_TAGS__ -D__ENGINEPRIME__ -D__EXTRA_METADATA__ -D__FFMPEG__ -D__HID__ -D__KEYFINDER__ -D__LILV__ -D__LINUX__ -D__MAD__ -D__MODPLUG__ -D__OPUS__ -D__QTKEYCHAIN__ -D__SNDFILE__ -D__SQLITE3__ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__UNIX__ -D__VINYLCONTROL__ -D__WV__ -Dx86_64 -I/home/uk/volumes/Build/cpp/mixxx/build/mixxx-test_autogen/include -I/home/uk/volumes/Build/cpp/mixxx/src -I/home/uk/volumes/Build/cpp/mixxx/build/src -I/home/uk/volumes/Build/cpp/mixxx/build/lib/libdjinterop-install/include -I/usr/include/ffmpeg -I/home/uk/volumes/Build/cpp/mixxx/lib/benchmark/src/../include -isystem /home/uk/volumes/Build/cpp/mixxx/lib/fidlib -isystem /home/uk/volumes/Build/cpp/mixxx/lib/googletest/googletest/include -isystem /home/uk/volumes/Build/cpp/mixxx/lib/portaudio -isystem /home/uk/volumes/Build/cpp/mixxx/lib/rigtorp/SPSCQueue/include -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /home/uk/volumes/Build/cpp/mixxx/lib/libshout-idjc/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtQuickWidgets -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtQmlModels -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtTest -isystem /usr/include/qt5/QtXml -isystem /home/uk/volumes/Build/cpp/mixxx/lib/googletest/googletest -isystem /home/uk/volumes/Build/cpp/mixxx/lib/googletest/googlemock/include -isystem /home/uk/volumes/Build/cpp/mixxx/lib/googletest/googlemock -isystem /usr/include/lilv-0  -fdiagnostics-color=always -g -std=gnu++20 -fvisibility=hidden -fvisibility-inlines-hidden -pipe -O3 -ffast-math -funroll-loops -fomit-frame-pointer -mtune=generic -Wall -Wextra -Woverloaded-virtual -Wfloat-conversion -Werror=return-type -Wformat=2 -Wformat-security -Wvla -Wundef -Werror -fPIC -o CMakeFiles/mixxx-test.dir/src/test/mathutiltest.cpp.o -c /home/uk/volumes/Build/cpp/mixxx/src/test/mathutiltest.cpp",

**Comment by uklotzde** [comment]
After another rebuild with the same settings the tests are passing again :shrug:

**Comment by uklotzde** [comment]
Strange things are happening. Switching from `native` to `portable` and vice versa doesn't seem to work reliably even when deleting the `build` directory in between. Now the behavior of `ccache` also seems to be suspicious.

**Comment by uklotzde** [comment]
After multiple rebuilds with previously wiping the `ccache` cache it turns out that this only affects Clang.

**Comment by daschuer** [comment]
I am not able to confirm that with: 
https://godbolt.org/z/66ao5ErEs

Can you find a setting that makes it fail?

**Comment by uklotzde** [comment]
Execution: Clang 16.0.0 + `-ffast-math`

https://godbolt.org/z/nYe48Mx4z

**Comment by daschuer** [comment]
I got a solution. With -ffast-math the division is done in the preprocessor and flushed to zero. 
https://godbolt.org/z/4zTKW5Ed9
