### ISSUE TITLE
Playhead in the wrong position (and wrong positioning of Cues and Intro Start marker)

### ISSUE THREAD

**Issue by hapst3r** [mixxxdj/mixxx#11486]
### Bug Description

When DJ'ing the last time I was wondering why there was a difference between the deck's waveform overview and the actual waveform display.

Today, I noticed the same: sometimes, when loading a song (I'm speaking about 1-2 when opening >500), it seems like all information related to the deck's waveform overview is shifted, which results in a divergence in relation to the actual waveform display.

When re-loading the same song, this problem disappears.

Below you find an image showing the divergence I am talking about.
![Mixxx buggy display](https://user-images.githubusercontent.com/55704994/232563912-c1c3ad25-d35e-482a-a856-eb315c7f9c32.jpg)

For reference, this is what it should look like
![Mixxx correct display](https://user-images.githubusercontent.com/55704994/232564031-f84c7dcc-fdb9-4c62-9481-79ac2c11dc54.jpeg)

### Version

2.3.4 (built from this repo using 2.3.4 HEAD)

### OS

openSUSE Tumbleweed, up to date

**Comment by ronso0** [comment]
Maybe symptom of the same bug related to changed track length which was fixed by #11479?

Can you build the 2.3 branch and test that?

**Comment by hapst3r** [comment]
Is there any specific way I can "force"-check this bug? 

Other than that, I will try to use both 2.3 and 2.3.4 in the upcoming days when DJ'ing and try to pay attention to when/how/if that happens...

**Comment by ronso0** [comment]
Just build 2.3.5-beta and load that track Mefjus - Expedition. If there's still an offset in the overview it's a different bug.

**Comment by hapst3r** [comment]
> Just build 2.3.5-beta and load that track Mefjus - Expedition. If there's still an offset in the overview it's a different bug.

I tried to build `2.3.5-alpha` but the build failed, see the log: [230418-2.5-build.log](https://github.com/mixxxdj/mixxx/files/11266549/230418-2.5-build.log).

It is possible that the build failure is due to a dependency on `ms-gsl` which I had to download from a somewhat foreign repo and where I don't know the proper version (the version in the repo was 4.0.0 and actually related to telegram).

**Comment by daschuer** [comment]
This is the error message: 
```
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
  (Required is at least version "3.11")
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSQLite3.cmake:52 (find_package_handle_standard_args)
  CMakeLists.txt:120 (find_package)
```
It is interesting, because the sqlite dependency has not changed since you last successful build. 
Do you have an idea what may have changed?

**Comment by Swiftb0y** [comment]
The issue has been mentioned as fixed in https://github.com/mixxxdj/mixxx/issues/11409#issuecomment-1524006058

Lets close this for now. Feel free to reopen if you encounter it again.
