### ISSUE TITLE
AutoDJ shortcut (SHIFT+F12) and "symbol" turns on, but feature doesn't turn on due to "two decks playing at the same time."

### ISSUE THREAD

**Issue by nPrevail** [mixxxdj/mixxx#11494]
### Bug Description

I'm using the LateNight PaleMoon skin.

Prerequisites to replicating the problem:
1. Have two decks play music
2. Enter the "AutoDJ" section from the library tree
3. Have a keyboard that can enable/disable the AutoDJ feature by pressing SHIFT+F12

Procedure:
When two decks are both playing music, AutoDJ cannot be enabled from the on-screen gui "AutoDJ button."
However, pressing SHIFT+F12 while two decks are playing songs will allow the AutoDJ symbol to turn on, but the AutoDJ feature will remain off despite the symbol staying on (as if the feature was on and working).

Recommendation:
If the AutoDJ feature cannot turn on due to two songs playing, the AutoDJ symbol should not turn on until the feature parameters are met.

The video below demonstrates the bug. The cursor will demonstrate and highlight these concerns.
[Screencast from 2023-04-17 18-25-17 (converted).webm](https://user-images.githubusercontent.com/57690587/232711557-31900ccf-d419-47f6-8931-f124db60438e.webm)

### Version

2.3.4

### OS

Fedora Linux

**Comment by ronso0** [comment]
Confirmed, working on it.
