### ISSUE TITLE
Deere skin - Flickering green background on the first track's waveform when mixer is shown

### ISSUE THREAD

**Issue by JPenuchot** [mixxxdj/mixxx#11507]
### Bug Description

Hello,

I'm having an issue with the Deere skin where the background of the first track's waveform flickers when the mixer is shown. Here's a video capture showing the artifact:

https://user-images.githubusercontent.com/852191/234014220-437b50af-db6e-418d-8e3f-50593addd4e4.mp4

I hope it's descriptive enough, please let me know if more input is needed.

Regards,
Jules

### Version

2.3.4

### OS

Arch Linux with i3wm, no compositor

**Comment by uklotzde** [comment]
Duplicate: #11164

**Comment by JPenuchot** [comment]
Didn't search well enough, sorry about that

**Comment by Swiftb0y** [comment]
Interesting that it vanishes when the mixer is hidden. As a workaround, you can use the non-GL/-GLSL waveforms.

**Comment by ronso0** [comment]
> Interesting that it vanishes when the mixer is hidden.

The mixer holds the GL VU meters, probably that's it.

**Comment by ronso0** [comment]
Sure, but issues arose with the GL meters IIUC
