### ISSUE TITLE
Mixxx doesn't play very long track (9h)

### ISSUE THREAD

**Issue by DerEber** [mixxxdj/mixxx#11504]
### Bug Description

I am having a very long track in my collection that does not play in Mixxx.
It's 9h05 long. After mixxx analysed the track it doesn't show any waveform and refuse to play it.
Even it says it's ready. 
Also it shows the wrong tracklength in the desk. Library length shows correctly in opus or m4a format.
Same track in AAC shows wrong filelength in the library too.

My Mixxx version is 2.3.3. (HEAD)
Kubuntu 22.04

![mixxx-long tracks](https://user-images.githubusercontent.com/99741952/233774879-888c3f29-a3f6-4186-9300-28f3a7578728.png)

### Version

2.3.3.

### OS

Kubuntu 22.04

**Comment by DerEber** [comment]
This is one of the tracks:
https://we.tl/t-VypWAtpMNL

**Comment by ronso0** [comment]
Please provide more info:
> After mixxx analysed the track it doesn't show any waveform and refuse to play it

If you eject and reload that track, and click play what happens?
Is the button toggled and just no output / playhead/timepos change?

Please attach the log file of a session where you only try to play such a failing track.

Maybe I manage to test the track you linked next days but I can't promise that.

Btw, current stable version is 2.3.4 It's at least worth a try to see if it works with that version.

**Comment by DerEber** [comment]
> If you eject and reload that track, and click play what happens? Is the button toggled and just no output / playhead/timepos change?

Nothing happens. No waveform shown and no playhead shown or playhead-change.
I don't see the play button being toggled. 
Also the cue button does not light up like it is on normal ready tracks.
If I click on the cue button it lights up for a very short moment.

I'll try to provide the log file you asked soon. 
Now it's Sunday time :)
Greetings!

**Comment by daschuer** [comment]
This is an integer overflow issue. I am working on a fix.

**Comment by DerEber** [comment]
Good morning, here is the logfile.
Best greetings from Munich :)

**Comment by ronso0** [comment]
@DerEber forgot to attach the log? ;)

**Comment by DerEber** [comment]
[mixxx.log](https://github.com/mixxxdj/mixxx/files/11320602/mixxx.log)

Upload failed. Now it's there. ;)

**Comment by daschuer** [comment]
With https://github.com/mixxxdj/mixxx/pull/11511 the attached track can be played.

**Comment by DerEber** [comment]
Great news!
I'm looking forward to the next release. :)

**Comment by daschuer** [comment]
Fixed by https://github.com/mixxxdj/mixxx/pull/11511
