### ISSUE TITLE
Similar Tracks using search

### ISSUE THREAD

**Issue by kek001** [mixxxdj/mixxx#11515]
### Feature Description

this is wish for using search, if writing to the  search field, "Similar", mixxx will find similar tracks using BPM and Key or other parameters, like treshold +- 10 BPM ... and using harmonic mixing rules for key +1+2+4+5 only from Major to Minor etc...

no idea how complex is to do sql staement inside mixxx for key and bmp.

It could be much more elegant if doing inside mixxx than polling current playing track from tittle, and using external applications.

I love and like Mixxx so much and dont want use external applications, and want keep most of the work and task inside mixxx and not need other applications, like if i use hammer i want use nails and not want change screwdriver for having a drinking while trying to think my set.

Thank you all developers mixxx is best. I love it more and have found how excellent way the control script mapping has done it, when i started learn it. such a versatility cant find.

and sure I understand there are much more important things where using your valuable time.

**Comment by ronso0** [comment]
IIRC this will be available in Mixxx 2.4
"Related Tracks"
https://github.com/mixxxdj/mixxx/blob/main/CHANGELOG.md#240-unreleased
