### ISSUE TITLE
 Errors in speed and pitch 

### ISSUE THREAD

**Issue by UserMen14** [mixxxdj/mixxx#11517]
In the Denon MС6000 in the first Decree, the handles of volume and equalizer do not work. Although before that they worked. To update.

~~And when the program was renewed, the pace accelerated greatly when playing. Although the pitch is at the same level.~~

OS Ubuntu Studio 22.04. LTS
MIXXX 2.5-alpha-26-g6b1844e469

**Comment by daschuer** [comment]
Do you know which version still works?

**Comment by UserMen14** [comment]
> 

Previous

**Comment by daschuer** [comment]
Which previous exactly?

**Comment by UserMen14** [comment]
> Which previous exactly? Maybe you find the version in old mixxx.log files with a number prefix.

Alpha Version that was before.

**Comment by ronso0** [comment]
I removed this
> And when the program was renewed, the pace accelerated greatly when playing. Although the pitch is at the same level.

from the description since it's a separate issue.
Please file a new one and try to describe in more detail what's wrong. Thanks!

**Comment by ronso0** [comment]
> Which previous exactly? Maybe you find the version in old mixxx.log files with a number prefix.

@UserMen14 If you already started Mixxx 10 times or more with the new version you won't have any logs from the previous version. Anyway, please take a look at your oldest log `mixxx.log.10`, see
https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file

**Comment by UserMen14** [comment]
After updating the MIXXX program, I changed discredit from 48 hz to 44 and then on 48. And the speed seemed to be leveled. But here the handles on the mapping still do not work in the first left deck. And the scratch does not twist on the left decree with the controller
