### ISSUE TITLE
Possible crash with faulty mp3 files  

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11531]
### Bug Description

On Linux libmad is patched with some additional guards against memory overflows. 
This have been introduced because of a crash with a faulty mp3 file: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=287519

I have added the patches also to our vcpkg environment... just in case. 
https://github.com/mixxxdj/vcpkg/pull/68 2.3
https://github.com/mixxxdj/vcpkg/pull/66 2.4

Is this is a 2.3 candidate. I vote for yes. 

### Version

2.3

### OS

Windows

**Comment by Swiftb0y** [comment]
So what needs to be done to fix this? Just upgrade the vcpkg env?

**Comment by daschuer** [comment]
Yes. It is prepared here: https://github.com/mixxxdj/mixxx/pull/11535
