### ISSUE TITLE
Updating Star rating in track properties clears other unsaved properties

### ISSUE THREAD

**Issue by RadioDM** [mixxxdj/mixxx#11540]
### Bug Description

Clicking on any of 5 stars in file/track properties inside Mixxx, will revert unsaved changes in all other fields.
I think this bug lasted for long, but never reported it since.

To reproduce:
In library right mouse click on any track > properties >  type anything in any input field/s > click on star class. (doesn't matter the initial star value) > unsaved changes reverted.

Let me know if backtrace log is needed

### Version

2.4-alpha-1467-g425ad1e47a

### OS

Windows 10 Pro 21H2

**Comment by ronso0** [comment]
Working on it, since I added the star rating there.

The challenge is not fixing the issue but keeping both DlgTrackInfo and WStarRating clean...

**Comment by daschuer** [comment]
This issue also happens in 2.3.5

**Comment by ronso0** [comment]
Oh. In that case I'll try to rebase #11565
