### ISSUE TITLE
Spinny can't be "moused" on the left deck, right deck works (v2.3.5)

### ISSUE THREAD

**Issue by atskler** [mixxxdj/mixxx#11543]
### Bug Description

Spinny can't be "moused" on the left deck, right deck works.

### Version

2.3.5

### OS

openSUSE Tumbleweed

**Comment by atskler** [comment]
Changing the skin made it work. I can't reproduce it anymore.

**Comment by daschuer** [comment]
Which skin was affected?

**Comment by atskler** [comment]
LateNight: PaleMoon

It was the first tart after building it, using already existing /home/user/.mixxx config (with which I already tested different Mixxx builds beforehand).

**Comment by daschuer** [comment]
I cannot confirm the issue with Ubuntu Focal. Can you still confirm that or can we close this bug?

**Comment by atskler** [comment]
I tried to reproduce it also with an older backup, but it works correctly.
This bug can be closed.
