### ISSUE TITLE
mixxx-test critical error on arm64-osx

### ISSUE THREAD

**Issue by dwgero** [mixxxdj/mixxx#11551]
### Bug Description

Running on a recent MacBook Pro 16 with M2 Max (8 performance cores, 4 efficiency cores), 96 GB RAM, latest Xcode (14.3, Apple clang 14.0.3, clang-1403.0.22.14.1).
build1-error.txt has an issue because std::result_of<> has been replaced by std::invoke_result<> in c++20.
qobjectdefs.h.diff is a patch file to fix it.
build2-warnings.txt shows 5 warnings because bitwise ops on differing enums is deprecated in c++20.
mixxx-test-run.txt has critical error.
[arm64-osx-issue.tar.gz](https://github.com/mixxxdj/mixxx/files/11471956/arm64-osx-issue.tar.gz)

### Version

2.5.0-alpha

### OS

macOS Ventura 13.3.1

**Comment by Swiftb0y** [comment]
Seems like our Qt5 backports don't quite work with C++20? @daschuer

**Comment by daschuer** [comment]
It looks like. I think this patch is missing: 
https://github.com/qt/qtbase/commit/fb6acf08bbd7a68d027282251747620b942bd1d6
I will prepare a PR.
