### ISSUE TITLE
GNOME 44 (Wayland): Context menu on tree items in side bar closes immediately

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11576]
### Bug Description

Right clicking on any tree item in the side bar has no effect. **Update:** It actually appears for a split second, but disappears immediately without further interaction.

Opening the context menu with a right click works for tracks in the table view.

Qt 5.15.9 on a single screen.

### Version

2.3.5, 2.4, main

### OS

Fedora 38 / GNOME 44 on Wayland

### Workaround

Start _GNOME on Xorg_ instead of using Wayland as the display server. This bug only seems to affect the XWayland backend.

**Comment by uklotzde** [comment]
The right click itself is received as the following debug log (custom code) proves:

```
debug [Main] aoide LibraryFeature - onRightClickChild QModelIndex(0,0,0x226e7250,SidebarModel(0x470fff0))
```

**Comment by Swiftb0y** [comment]
I can partly confirm the issue. The context menu does open sometimes if you're lucky.

**Comment by ronso0** [comment]
One difference between [`WLibrarySidebar::contextMenuEvent`](https://github.com/mixxxdj/mixxx/blob/7f79194df0a53987816b4e47e34067e3eb12361d/src/widget/wlibrarysidebar.cpp#L35-L45) (doesn't work) and [`WTrackTableView::contextMenuEvent`](https://github.com/mixxxdj/mixxx/blob/7f79194df0a53987816b4e47e34067e3eb12361d/src/widget/wtracktableview.cpp#L500-L514) (works)is that in the latter the event is accepted.
Can you test if accpeting the event in the sidebar makes a difference?

**Comment by uklotzde** [comment]
> One difference between [`WLibrarySidebar::contextMenuEvent`](https://github.com/mixxxdj/mixxx/blob/7f79194df0a53987816b4e47e34067e3eb12361d/src/widget/wlibrarysidebar.cpp#L35-L45) (doesn't work) and [`WTrackTableView::contextMenuEvent`](https://github.com/mixxxdj/mixxx/blob/7f79194df0a53987816b4e47e34067e3eb12361d/src/widget/wtracktableview.cpp#L500-L514) (works)is that in the latter the event is accepted. Can you test if accpeting the event in the sidebar makes a difference?

Unfortunately, that doesn't make a difference :disappointed: But the accept() calls are nevertheless missing, also for the column headers that seem to react only when clicking twice sometimes.

**Comment by ronso0** [comment]
Does this also occur if the mouse is not moved between press and release?
If no, appearanty this was fixed in Qt6 but not backported to Qt5 :|
https://codereview.qt-project.org/c/qt/qtbase/+/310743/3/src/widgets/widgets/qmenu.cpp

**Comment by uklotzde** [comment]
> Does this also occur if the mouse is **not** moved between press and release? If no, appearanty this was fixed in Qt6 but not backported to Qt5 :| https://codereview.qt-project.org/c/qt/qtbase/+/310743/3/src/widgets/widgets/qmenu.cpp

Not moving the mouse doesn't fix it. I am not able to access any context menus in the side bar tree.

**Comment by uklotzde** [comment]
And even it would be backported it would not arrive before a year or so has passed. This is a shit show.

**Comment by uklotzde** [comment]
This issue also seems to affect Zoom, so probably not Mixxx's fault. Trying to open the user's profile menu in the upper right corner shows a similar behavior recently, i.e. it closes itself immediately and is inaccessible.

**Comment by ronso0** [comment]
fwiw there was a simular issue on macOS a few years back with the skin settings toggle https://github.com/mixxxdj/mixxx/issues/9461

**Comment by Swiftb0y** [comment]
> This issue also seems to affect Zoom, so probably not Mixxx's fault. Trying to open the user's profile menu in the upper right corner shows a similar behavior recently, i.e. it closes itself immediately and is inaccessible.


Fyi the same occurs in VSCode, so yeah, probably not a mixxx issue per se.

**Comment by daschuer** [comment]
Is there an upstream bug report we can reference? 
Is one of you able to single step through the Qt source to hunt down the issue?

**Comment by daschuer** [comment]
What is the situation here? Is the issue still happening? 
Can we implemendva band aid?

**Comment by Swiftb0y** [comment]
Its still happening and I can reproduce it but I'm not sure where to start debugging.

**Comment by daschuer** [comment]
I am afraid this is a mayor bug. Do you have a personal workaround? 

Since we blame Gnome 44, there must be something different in how right clicks are handeled.

Maybe a glitch with touch events around Qt::WA_AcceptTouchEvents. 

Maybe we have another workaround that is no longer necessary? 

This? 
https://github.com/mixxxdj/mixxx/blob/02feca805fd457898131df5de9cc6463da3bf391/src/library/sidebarmodel.cpp#L323

Is it possible, to set a breakpoint when the menu is closed and investigate the source of the closing event? Maybe in   QMenu::~QMenu() and QMenu::hideEvent()

**Comment by Swiftb0y** [comment]
> I am afraid this is a mayor bug. Do you have a personal workaround?

Not really, it works every 10-20th try, so often I just right click until it works, so the issue is definitely racy. I agree that its a major bug, I just didn't find the time and motivation to look into it yet.

**Comment by Swiftb0y** [comment]
Interestingly, triggering `QMenu::hideEvent` on other context menus (such as the one spawned on tracks) still triggers a hideEvent "early" but it doesn't cause the menu to be hidden, it will only get hidden after a second `hideEvent` when you actually move the mouse away from the menu. That second hideEvent does not occur with the sidebar context menu.

**Comment by Swiftb0y** [comment]
Soo, I can reproduce the problem with a 60 line minimal demo. I also can't reproduce the issue when we're omitting `-platform xcb` (the new all-shaders allow us that now without any noticable regressions as far as I can tell). So I see two options:
1. file the issue upstream with the example, question is: what upstream Qt or GNOME (what part of GNOME?)
2. omit the explicit specification and fall back to Qt's default (I assume wayland on XWayland desktops?)

Just doing 1. will probably take a lot of time to get fixed. Just 2. is a little risky this late into the beta period. I propose to report upstream and switch to wayland in the meantime, reverting if we get reports of regressions. What do you think?

**Comment by Swiftb0y** [comment]
Caveat for 2. is that it obviously would leave 2.3 in a broken state since it can only be applied to 2.4

**Comment by Swiftb0y** [comment]
Caveat for 1. is that the problem doesn't seem to occur under Qt6, so it probably doesn't make much sense to report to Qt.

**Comment by ronso0** [comment]
Are you sure this is unrelated to submenus? (tracks view context menu)

How does the track menu in decks perform?
I think the menus are triggered differently in different places, mousePressEvent vs ContextMenuEvent.

**Comment by daschuer** [comment]
Why not report to both with a reference to each other? 

Unfortunately the back trace does not directly reveal a bug. Do you have an die how the first signal is ignored on the working config? Would it be a workaround to ignore the first signal in a QMenu child class?

**Comment by Swiftb0y** [comment]
> Are you sure this is unrelated to submenus? (tracks view context menu)

I didn't look into the submenus. I just compared the context menu of the sidebar with the context menu of a track. 

> How does the track menu in decks perform?

as expected from a UI perspective, but looking at the triggered breakpoints, the double hideEvent in which the first/premature one is ignored is super weird. 

>  I think the menus are triggered differently in different places, mousePressEvent vs ContextMenuEvent.

Very likely, the stacktrace of the track menu call is only 26 frames deep while the buggy sidebar one is double that. To me it almost looks like there is a nested event loop running, but I don't know enough about Qt internals to judge really whats going on here. See the `bt full` stacktrace I posted earlier. 

> Unfortunately the back trace does not directly reveal a bug. Do you have an die how the first signal is ignored on the working config? Would it be a workaround to ignore the first signal in a QMenu child class?

No idea, that could work but I doubt it would work for long. There is definitely something weird going on under XWayland with `-platform xcb`. 

Doing the same inspection under Xorg works as expected (only a single hideEvent at the correct time).

**Comment by Swiftb0y** [comment]
> Why not report to both with a reference to each other?

Sure, where should I report to in gnome, `mutter`?

**Comment by Swiftb0y** [comment]
Found something very similar upstream: https://gitlab.gnome.org/GNOME/mutter/-/issues/2886

**Comment by Swiftb0y** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/2949
https://bugreports.qt.io/browse/QTBUG-115848

lets see and wait.

**Comment by daschuer** [comment]
Can we recommend `QT_QPA_PLATFORM=wayland` as workaround and continue with the 2.3.6 release?

**Comment by Swiftb0y** [comment]
yes, but that only applies to 2.4. We must stick to `xcb` for 2.3, otherwise the waveforms will be broken.

**Comment by daschuer** [comment]
Ok, than it is kind of good news to have an 2.4 soon. 
Can we move this to the 2.4.1 milestone than?

**Comment by Swiftb0y** [comment]
Yes, I think thats a good decision.

**Comment by uklotzde** [comment]
Does no longer occur. Probably a Qt5 issue on Wayland that won't be fixed.
