### ISSUE TITLE
Delete Track File: Buttons in confirmation dialog are inaccessible

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11577]
### Bug Description

Trying to delete 75 files is not possible. The windows of the confirmation dialog with the track list is not resizable and I cannot access the buttons below the list.

All I see is this at the bottom of my screen:

![image](https://github.com/mixxxdj/mixxx/assets/1474154/305ffe2f-d5c6-4d3e-b7b0-0f6cdf3721bb)

### Version

~~2.3.5~~, 2.4, main

### OS

Fedora 38, GNOME 44, Qt 5.15.9

**Comment by uklotzde** [comment]
Text in progress dialog is also broken:

![Screenshot from 2023-05-22 18-28-08](https://github.com/mixxxdj/mixxx/assets/1474154/60ae2730-4ab3-4813-9caa-d95c05c11ad0)

**Comment by ronso0** [comment]
Okay, so limiting the list widget to 90% of the screen height is not enough when there are toolbars at the top/bottom. Can confirm that, though idk what changed because I tested this a lot.

Let's try 75%, or maybe I find a (simple) way to calculate the available space without toolbars.
