### ISSUE TITLE
Searching + Scrolling + Clicking selects wrong track

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11585]
### Bug Description

- Perform a search with many results
- Scroll down in the track table view
- Left or right click on a track

Sometimes the track view table then jumps back to a completely different track and causes unwanted behavior. Very annoying and unpredictable.

**Update:** The table view scrolls back to the top before recognizing the click. The track that lands under the mouse pointer gets selected instead of the track that was visible while clicking.

Not tested with 2.3. I can't use that version without mixing up all my column selections and orders.

### Version

2.4, main

### OS

Fedora 38, GNOME 44, Qt 5.15.9

**Comment by ronso0** [comment]
> Not tested with 2.3. I can't use that version without mixing up all my column selections and orders.

Use a copy of your settings dir?

Would be good to know whether this is a 2.4 regression or an Qt/desktop-related issue.

**Comment by uklotzde** [comment]
Not reproducible anymore.
