### ISSUE TITLE
Compiling does not work

### ISSUE THREAD

**Issue by daprose-dotcom** [mixxxdj/mixxx#11597]
### Bug Description

The compiling instructions crash on cmake ..

$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .

-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Chromaprint (missing: Chromaprint_LIBRARY
  Chromaprint_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindChromaprint.cmake:68 (find_package_handle_standard_args)
  CMakeLists.txt:1947 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Sysop/source/repos/mixxx-2.3/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Sysop/source/repos/mixxx-2.3/build/CMakeFiles/CMakeError.log".

---------------- CMakeError.log

  CheckIncludeFile.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_afc89.dir\Debug\\" /Fd"cmTC_afc89.dir\Debug\vc142.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\Sysop\source\repos\mixxx-2.3\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

C:\Users\Sysop\source\repos\mixxx-2.3\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Sysop\source\repos\mixxx-2.3\build\CMakeFiles\CMakeTmp\cmTC_afc89.vcxproj]

### Version

2.3.5

### OS

Windows 10, Visual Studio Community 2019

**Comment by ronso0** [comment]
A Mixxx dependency is missing.
Are you **sure** you followed the steps from https://github.com/mixxxdj/mixxx/wiki/Compiling%20on%20Windows ?

**Comment by JoergAtGithub** [comment]
The Mixxx buildenv is not found - Chromaprint_LIBRARY is the first library from the buildenv.

Did you execute .\tools\windows_buildenv.bat before calling cmake?
