### ISSUE TITLE
Numark DJ2GO2 Touch missing part of mapping for pad 2 in manual loop mode for the right deck

### ISSUE THREAD

**Issue by r0d0dendr0n** [mixxxdj/mixxx#11592]
### Bug Description

When I try to make a manual loop with the right deck I can easily set the start marker (pad 1), but setting the end marker does not work at all. When I try to make a manual loop with the left deck everything works as expected with the default configuration profile.

I fiddled with the midi learning and narrowed the problem to a missing `<key>DJ2GO2Touch.rightDeck.loopOut.input</key>` section in the `Numark_DJ2GO2_Touch.midi.xml` file. The left deck two entries for loopOut, but the right deck has only one. Here's the diff:
```
747a748,756
>         <key>DJ2GO2Touch.rightDeck.loopOut.input</key>
>         <status>0x95</status>
>         <midino>0x22</midino>
>         <options>
>           <script-binding/>
>         </options>
>       </control>
>       <control>
>         <group>[Channel2]</group>
```

I've attached the fixed [full version](https://github.com/mixxxdj/mixxx/files/11569627/Numark_DJ2GO2_Touch.midi.xml.gz) of the file.

Should I make a pull request or discuss it here first?

BTW thanks for an awesome piece of software!

### Version

2.3.4

### OS

Arch Linux

**Comment by ronso0** [comment]
I can confirm the second input mapping for the right deck is missing.
Please create a PR with the fix. You'll find a how-to intro here https://github.com/mixxxdj/mixxx/wiki/Bugfix%20Workflow, which also links to https://github.com/mixxxdj/mixxx/wiki/Using-git (incl. pre-commit setup)

Thank you!

**Comment by r0d0dendr0n** [comment]
I've made a [pull request #11594](https://github.com/mixxxdj/mixxx/pull/11594).
