### ISSUE TITLE
Shade: Audio Latency Meter broken in 2.4 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11599]
### Bug Description

The Audio Latency meter is broken since we merge the GLSL VU-Meter. 

It appears white without any function

![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/a8a9242c-ec47-46dd-b1ff-3c5d8cc8cd5a)

QOPENGL:BOOL=OFF fixes the issue. 

### Version

2.4-alpha

### OS

Ubuntu Focal

**Comment by daschuer** [comment]
A workaround is here: 
https://github.com/mixxxdj/mixxx/pull/11601

**Comment by JoergAtGithub** [comment]
Did https://github.com/mixxxdj/mixxx/pull/11722 fix this?

**Comment by daschuer** [comment]
Yes

**Comment by daschuer** [comment]
This is OK on Ubuntu Focal, but still broken on Ubuntu Jammy :-(
![image](https://github.com/mixxxdj/mixxx/assets/1777442/9e2a95fa-f888-471f-a3dc-29d680ab93d9)

**Comment by ronso0** [comment]
Focal uses Qt 5.12.8, which version is s provided hy Jammy? Or did you use a universal deb?

**Comment by Holzhaus** [comment]
> Focal uses Qt 5.12.8, which version is s provided hy Jammy? Or did you use a universal deb?

5.15.3

https://packages.ubuntu.com/jammy/qtbase5-dev

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/pull/11601 fixes it.
