### ISSUE TITLE
Dark border around VU-Meter GLGS widgets in 200 % scale   

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11600]
### Bug Description

Since https://github.com/mixxxdj/mixxx/pull/10989 the VU-Meter widgets have a black border. 

![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/701b4647-183c-4759-b6cf-be9cce8cb9ea)

![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/2bcf60a3-7599-4861-b83c-8c785de88f1d)

![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/b0e85f08-9252-4861-b5c7-81264bef52bb)
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/1ad2e462-3b26-43e5-946a-83f36ca20250)

### Version

2.4-alpha

### OS

Ubuntu Focal

**Comment by daschuer** [comment]
@m0dB do you have an idea? Maybe it is related to the issue that the widget thinks it is painted on black and we see antialiasing.

**Comment by m0dB** [comment]
@daschuer it was something silly, in src/util/texture.cpp I was using 
```
pTexture->setWrapMode(QOpenGLTexture::ClampToBorder);
```
instead of
```
pTexture->setWrapMode(QOpenGLTexture::ClampToEdge);
```

What is the correct procedure to create a PR for a specific issue? Do I give the branch a specific name? Do I just mention the issue in the description?

**Comment by ronso0** [comment]
> Do I just mention the issue in the description?

:+1: 
> Do I give the branch a specific name?

Whatever works best for you, though I find that handy while collaborating on a certain branch, it's just easier to remember and easier to spot in a `git branch` list.

**Comment by daschuer** [comment]
I can confirm that the suggested change fixes the issue. Thank you.

**Comment by daschuer** [comment]
I have added the fix here: https://github.com/mixxxdj/mixxx/pull/11601

**Comment by JoergAtGithub** [comment]
Did https://github.com/mixxxdj/mixxx/pull/11722 fix this?

**Comment by daschuer** [comment]
Yes, I can confirm it is fixed: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/554e5249-6c79-4cd0-8d92-e805c661e182)

**Comment by daschuer** [comment]
This one is also back on Ubuntu Jammy :-(

![image](https://github.com/mixxxdj/mixxx/assets/1777442/bbeb72ae-defb-4429-8eda-10ce759b46e6)

**Comment by m0dB** [comment]
Strange. I'll look into it.

**Comment by daschuer** [comment]
The fix already lives in https://github.com/mixxxdj/mixxx/pull/11601, I will verify and reopen it.
