### ISSUE TITLE
Deere: Laggy GUI when Spinnies are moved out of the desktop area

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11602]
### Bug Description

Since https://github.com/mixxxdj/mixxx/pull/10989 and with the QOPENGL=ON the whole GUI becomes laggy when the main window is moved out of the desktop area and the Spinnies are no longer visible. 
The refresh rate drops to 1 FPS in that case. It returns to 60 after moving the window back. 
QOPENGL=OFF fixes the issue. 

### Version

2.4-alpha

### OS

Ubuntu Focal

**Comment by robbert-vdh** [comment]
For me Mixxx is always running at single digit frames per second with with QOPENGL=ON` regardless of skin on KDE Plasma, Xorg, NVIDIA. Is this already being tracked anywhere? Configuring with `-DQOPENGL=OFF` fixes the issue for me.

**Comment by daschuer** [comment]
This sounds like a new issue. Can you file an extra Bug for it with the dirtro version in addition?

**Comment by atskler** [comment]
I can't reproduce the main issue on my system.
I can't reproduce the issue mentioned by robert-vdh.

current openSUSE Tumbleweed

inxi -ACGIMSamyz
System:
  Kernel: 6.2.12-1-default arch: x86_64 bits: 64 compiler: gcc v: 13.0.1
    parameters: BOOT_IMAGE=/vmlinuz-6.2.12-1-default
    root=/dev/mapper/vlg--mnh-mnh--root splash=silent systemd.show_status=yes
    resume=/dev/vlg-mnh/mnh-swap quiet security=apparmor threadirqs
    [...] [...] splash=verbose
    plymouth.enable=0 [...]
  Desktop: KDE Plasma v: 5.27.5 tk: Qt v: 5.15.9 wm: kwin_x11 vt: 7 dm:
    1: GDM v: 44.1 2: SDDM note: stopped Distro: openSUSE Tumbleweed 20230529
Machine:
  Type: Laptop System: Dell product: Latitude E6520 v: 01
    serial: <superuser required> Chassis: type: 9 serial: <superuser required>
  Mobo: Dell model: 0NVF5K v: A01 serial: <superuser required> UEFI: Dell
    v: A21 date: 03/06/2018
Memory:
  System RAM: available: 15.49 GiB used: 6.45 GiB (41.6%)
  RAM Report: permissions: Unable to run dmidecode. Root privileges required.
CPU:
  Info: model: Intel Core i5-2540M bits: 64 type: MT MCP arch: Sandy Bridge
    gen: core 2 level: v2 built: 2010-12 process: Intel 32nm family: 6
    model-id: 0x2A (42) stepping: 7 microcode: 0x2F
  Topology: cpus: 1x cores: 2 tpc: 2 threads: 4 smt: enabled cache:
    L1: 128 KiB desc: d-2x32 KiB; i-2x32 KiB L2: 512 KiB desc: 2x256 KiB
    L3: 3 MiB desc: 1x3 MiB
  Speed (MHz): avg: 2981 high: 3046 min/max: 800/3300 scaling:
    driver: intel_cpufreq governor: schedutil cores: 1: 2851 2: 3046 3: 3007
    4: 3023 bogomips: 20752
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf mitigation: PTE Inversion; VMX: vulnerable
  Type: mds status: Vulnerable; SMT vulnerable
  Type: meltdown status: Vulnerable
  Type: mmio_stale_data status: Unknown: No mitigations
  Type: retbleed status: Not affected
  Type: spec_store_bypass status: Vulnerable
  Type: spectre_v1 status: Vulnerable: __user pointer sanitization and
    usercopy barriers only; no swapgs barriers
  Type: spectre_v2 status: Vulnerable, IBPB: disabled, STIBP: disabled,
    PBRSB-eIBRS: Not affected
  Type: srbds status: Not affected
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics
    vendor: Dell driver: i915 v: kernel arch: Gen-6 code: Sandybridge
    process: Intel 32nm built: 2011 ports: active: LVDS-1 empty: DP-1, DP-2,
    DP-3, HDMI-A-1, HDMI-A-2, HDMI-A-3, VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0126 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_x11 driver: X: loaded: modesetting dri: crocus gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.00x11.22")
    s-diag: 582mm (22.93")
  Monitor-1: LVDS-1 model: Seiko Epson 0x5448 built: 2010 res: 1920x1080
    hz: 60 dpi: 142 gamma: 1.2 size: 344x194mm (13.54x7.64") diag: 395mm (15.5")
    ratio: 16:9 modes: 1920x1080
  API: OpenGL v: 3.3 Mesa 23.0.3 renderer: Mesa Intel HD Graphics 3000 (SNB
    GT2) direct-render: Yes
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio
    vendor: Dell driver: snd_hda_intel v: kernel bus-ID: 00:1b.0
    chip-ID: 8086:1c20 class-ID: 0403
  Device-2: Roland Rubix24 driver: snd-usb-audio type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-1.2.1:5 chip-ID: 0582:01e0
    class-ID: fe01
  API: ALSA v: k6.2.12-1-default status: kernel-api with: aoss
    type: oss-emulator tools: alsactl,alsamixer,amixer
  Server-1: JACK v: 1.9.22 status: off with: a2jmidid status: off
    tools: cadence,jack_control,qjackctl
  Server-2: PulseAudio v: 16.1 status: active with: pulseaudio-alsa
    type: plugin tools: pacat,pactl,pavucontrol
Info:
  Processes: 300 Uptime: 15h 35m wakeups: 13412 Init: systemd v: 253
  default: graphical tool: systemctl Compilers: gcc: 13.1.1 alt: 12/13
  Packages: pm: rpm pkgs: N/A note: see --rpm tools: yast,zypper pm: flatpak
  pkgs: 6 Shell: Bash v: 5.2.15 running-in: konsole inxi: 3.3.27

**Comment by JoergAtGithub** [comment]
Duplicate of https://github.com/mixxxdj/mixxx/issues/8836 ?

**Comment by JoergAtGithub** [comment]
Could you please test if this is fixed after merging: https://github.com/mixxxdj/mixxx/pull/11722

**Comment by daschuer** [comment]
I cannot longer confirm the issue.
