### ISSUE TITLE
My music wont play at all.

### ISSUE THREAD

**Issue by WillAsh29** [mixxxdj/mixxx#11613]
### Bug Description

I've tried Rebooting my system, Restarting Mixxx, I even Reinstalled it. Nothing.  I'm lost, It worked find but then just stopped.
If someone could help me I'd be grateful.

### Version

2.3.5

### OS

Linux Mint/ ubuntu

**Comment by WillAsh29** [comment]
As a addon I checked troubleshooting, nothing helped.

**Comment by ronso0** [comment]
Please post a screenshot of your Mixxx audio preferences.

**Comment by WillAsh29** [comment]
As in, it wont even show up on the wavers

**Comment by WillAsh29** [comment]
![image](https://github.com/mixxxdj/mixxx/assets/135047960/c37c786d-9baa-4c99-abe2-660e7e18bd65)

**Comment by WillAsh29** [comment]
It's nothing with the Audio, Its hard to explain. https://youtu.be/vNBNnO8Bb9M

**Comment by ronso0** [comment]
I think it _is_ related to the audio: I had this issue when my configired sound device was n/a or occupied by another thread.
I suggested
> Try selecting your desired main output device explicitly.

because it might be either no device is linking to "default", or the inked device is occupied.

**Comment by WillAsh29** [comment]
Alright, I'll try, Also apologies for the late reply I just got up.

**Comment by ronso0** [comment]
Which device did you select?

**Comment by WillAsh29** [comment]
default, aka polaroid 162 soundbar

**Comment by ronso0** [comment]
"default" or "polaroid 16" soundbar"?

Either way, try another one.
Btw if you use only one output you can also set Multi-soundcard syncronization to Off

**Comment by daschuer** [comment]
Thank you for confirming.
