### ISSUE TITLE
Too many waveform options

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11615]
### Bug Description

As a regular user without a technical background I would no be able to choose the right waveform for my system. Especially on macOS this selection is crucial.

I suggest to delete all non-essential renderers that don't add value for users or that need to be deprecated (soon) anyway for the migration to Qt 6. Doing so would also reduce the maintenance burden.

### Version

2.4

**Comment by Swiftb0y** [comment]
We could discuss hiding the non-all-shader versions behind a flag. I don't think it makes sense to remove them outright in case we don't discover all issues with the all-shaders before the stable release.

**Comment by daschuer** [comment]
We have already removed the waveforms that have performance issues. So I don't think the user does crucial decision. If you have issue with one particular waveform please report that separate.

**Comment by daschuer** [comment]
This issue duplicates https://github.com/mixxxdj/mixxx/issues/6428

I think the main issue is to pick a reasonable defaults. We need to check if this is still the case. 
Related: https://github.com/mixxxdj/mixxx/issues/8639

**Comment by uklotzde** [comment]
Even with all the background information I am overwhelmed with the multitude of choices. Mixxx should offer only 2 or 3 alternatives that provide a different views. Users should not be bothered with all the technical implementation details.

**Comment by Swiftb0y** [comment]
As I said, fully agreed and something we should definitely enforce once we can be sure that the all-shaders approach works for everyone (which I'm fairly certain about but you never know with GPUs and their drivers).

**Comment by uklotzde** [comment]
I don't even have a clue what "all-shaders" means. This term should not appear in the UI.

**Comment by uklotzde** [comment]
As a user I might be able to guess the *non-accelerated* could be used a fallback if *accelerated* doesn't work for me. But that's all what I want to see. Anything else is confusing.

That would be my opinion as a product manager.
