### ISSUE TITLE
Mapping for Denon S3700 is not working

### ISSUE THREAD

**Issue by wtrz** [mixxxdj/mixxx#11624]
### Bug Description

Upgraded from 2.3.5 to 2.4 
--
Midi mapping stopped working immediatly on startup of the mixxx application. 
[image](https://pasteboard.co/d3QbwweHtjge.png)

mapping: [link](https://github.com/wtrz/mixxx-Denon-DN-S3700-hybrid)

### Version

2.4

### OS

Windows 11

**Comment by ronso0** [comment]
The error message is helpful. Looking at line 719 and above I notice there's a semicolon missing at the end if line 711 https://github.com/wtrz/mixxx-Denon-DN-S3700-hybrid/blob/009b2f034e80d5c9cb062185bd70611718eb9df3/Denon-DN-S3700-hybrid-scripts.js#L711

Seems the 2.4 mapping scrupt engine is more strict with small errors like this.

Fyi: it's helpful to put the controller name in the Issue title / description.
And actually, please only file bugs for Mixxx official mappings.
