### ISSUE TITLE
Tracks disappear from Library

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11628]
### Bug Description

I have replaced some track files with different versions and edited tags with an external tag editor.

After rescanning some of those files were marked as missing. I didn't take notice, because this happens often when files get renamed after re-generating their path with beets. But here, in most cases, the file name didn't change at all.

Those missing and then purged tracks remain absent from the library. Rescanning does not discover them again, although the files still exist. The same is true for the missing tracks that have have not been purged yet.

The synchronization between file system and database is permanently stuck in an inconsistent state.

I have no clue when this malfunctioning started or how to reproduce it reliably.

Manual repair:

- Clear the `LibraryHashes` table
- Rescan Library

### Version

main

### OS

Fedora 38

**Comment by uklotzde** [comment]
Only files that I have touched during the last 2 weeks are affected and reappeared after manually cleaning the database as described above.

I don't remember when I re-fetched and rebuilt the code with the latest changes. If a code recent code change caused this behavior then probably a commit that has been merged during the last 4 weeks.

**Comment by uklotzde** [comment]
Not a Unicode issue, the paths of some affected files are pure ASCII.

**Comment by ikr83** [comment]
Hi,

II encountered the same issue, and the solution was to modify certain fields in the mixxxdb.sqlite database. In the "track locations" table, check the paths in the "directory" column. In my case, the paths of the "deleted" tracks ended with "/", while the ones that were kept did not have "/" at the end of the directory name. Therefore, I removed the "/" and replaced the value "1" in the "fs_deleted" column with the value "0" for the relevant rows.

**Comment by uklotzde** [comment]
@ikr83 This was not the case here, I don't see any directories with trailing a slash character `/`.

But your hint was very helpful! I have noticed that after relocating my library (manually) I forgot to update some directory names in the library. Those in `track_locations.directory` contain the old path, which is still accessible through a symbolic link.
