### ISSUE TITLE
bpm lock icon rendered incorrectly on QT6 (no QML)

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/mixxx#11630]
### Bug Description

The bpm column does not look correct on QT6:

![image](https://github.com/mixxxdj/mixxx/assets/888940/9466c250-4e70-4cf8-89f6-a4aefc4205cc)

The custom lock icon we use is not being drawn.

### Version

HEAD

### OS

Ubuntu 22.04

**Comment by ronso0** [comment]
Maybe just an error in the SVG? How does it look like in PaleMoon?

`/res/skins/LateNight/classic/buttons/btn__lib_bpm_locked_orange.svg` is not optimized / cleaned up. Can you try saving it as 'Optimized SVG' with default settings (which should remove unused tags and collapse groups)?

**Comment by daschuer** [comment]
I can confirm the issue with all skins. However only if the row is not selected. In selected case everything looks fine.

**Comment by ronso0** [comment]
Can you try the explicit `!selected` selector? LateNight Classic:
```
#LibraryBPMButton::indicator:!selected:checked,
#LibraryBPMButton::indicator:selected:checked {
  image: url(skin:/classic/buttons/btn__lib_bpm_locked_orange.svg);
}
#LibraryBPMButton::indicator:!selected:unchecked,
#LibraryBPMButton::indicator:selected:unchecked {
  image: url(skin:/classic/buttons/btn__lib_bpm_unlocked_grey.svg);
}
```

**Comment by ywwg** [comment]
no, that does not work for me. weird.

**Comment by ronso0** [comment]
So the `WTrackTableView::indicator` (played column) rules (applied to all QCheckBox indicators) are not overwritten by the `#LibraryBPMButton::indicator` rules.

https://github.com/mixxxdj/mixxx/blob/d763be606148a1047522b21a8840d50d882cf1c2/src/library/bpmdelegate.cpp#L63-L94

Can you try some other explicit selector, for example `WTrackTableView QCheckBox::indicator`?

**Comment by ronso0** [comment]
Oh, I think I  got it (but it's surprising this worked before...):
the LibraryBPMButton rule
https://github.com/mixxxdj/mixxx/blob/d763be606148a1047522b21a8840d50d882cf1c2/res/skins/LateNight/style_classic.qss#L2588-L2595
is **after** the general indicator rule
https://github.com/mixxxdj/mixxx/blob/d763be606148a1047522b21a8840d50d882cf1c2/res/skins/LateNight/style_classic.qss#L2113-L2119

Please try the other way around.

**Comment by ywwg** [comment]
still no luck.  (qt bug?)

I am not sure I am doing this right because even if I comment out all of the indicator:checked / unchecked qss items and anything referencing btn__lib_checkmark_orange, I still see the unselected rows with the orange check.

**Comment by ronso0** [comment]
So it's probably the default QCheckBox indicator style.
You can try resetting the library text color by disabling
```
WTrackTableView,
WTrackTableView::indicator,
```
in style_classic.qss#L1104-L1105 and check if the checkmark color is also reset.

FWIW in res/skins/default.qss we use the `QPushButton#LibraryBPMButton:checked` selector, so maybe try
`QPushButton#LibraryBPMButton:checked` and
`QPushButton#LibraryBPMButton::indicator:checked` in LateNight/style_classic.qss ?

**Comment by ywwg** [comment]
Would it be possible to work up a draft PR? I am getting a little lost in these files and what changes I should be making to test this

**Comment by ronso0** [comment]
Try adding this snippet at the bottom of style_classic.qss
```
QPushButton#LibraryBPMButton::indicator:checked:!selected,
QPushButton#LibraryBPMButton::indicator:checked:selected,
QPushButton#LibraryBPMButton::indicator:checked {
  image: url(skin:/classic/buttons/btn__lib_bpm_locked_orange.svg);
}
QPushButton#LibraryBPMButton::indicator:unchecked:!selected,
QPushButton#LibraryBPMButton::indicator:unchecked:!selected,
QPushButton#LibraryBPMButton::indicator:unchecked {
  image: url(skin:/classic/buttons/btn__lib_bpm_unlocked_grey.svg);
}
```
If that doesn't fix it I'll take another look and create PR.

**Comment by JoergAtGithub** [comment]
On Windows the padlock symbol appeared, but off center and smaller than it should be.

**Comment by ronso0** [comment]
Please post a screenshot.

**Comment by ronso0** [comment]
@JoergAtGithub Could you test if disabling this part in WLibraryTableView makes a difference?
https://github.com/mixxxdj/mixxx/blob/37a71a9410ba39d5cc7d4f95000de3cfe711ece3/src/widget/wlibrarytableview.cpp#L227-L232

**Comment by JoergAtGithub** [comment]
> Please post a screenshot.
Windows 11:

![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/fd92859b-fd75-4ed2-887c-98f63c99d54b)

**Comment by ronso0** [comment]
I didn't build with Qt6 yet so someone else needs to debug this. Above are some hints, maybe also try `outline: none`.

**Comment by ronso0** [comment]
affected macOS with qt 6.5.2 #11900

**Comment by foss-** [comment]
Adding macOS screenshot. When track is highlighted the icons are displayed fine, although a bit too small, Skin is LateNight, PaleMoon:

![1](https://github.com/mixxxdj/mixxx/assets/5708172/5fd5bc49-bfa4-4e04-be54-ba2dbb0e2160)

**Comment by fwcd** [comment]
@ronso0 Removing that does indeed fix the issue for me (on macOS), but causes the lock and custom checkmark to render at roughly double the size:

![image](https://github.com/mixxxdj/mixxx/assets/30873659/b237deb2-2794-4efd-9c64-81db0c71fb73)

My guess is that the checkmarks still render underneath, but simply aren't visible anymore.

**Comment by ronso0** [comment]
Could someone who can reproduce try adding
`qproperty-icon: none;`
the both BPM button selectors here
https://github.com/mixxxdj/mixxx/blob/03d0ce7e06915084b649bc95b36cf6b5f1a365fe/res/skins/LateNight/style_palemoon.qss#L2604-L2609

**Comment by fwcd** [comment]
Doesn't seem to change anything, unfortunately

**Comment by fwcd** [comment]
I've found that setting a border on the _item_ actually fixes the issue:

```
#LibraryBPMButton::item {
  border: 0px;
}
```

<img width="186" alt="image" src="https://github.com/mixxxdj/mixxx/assets/30873659/4805a02e-4e8e-408e-83da-fbf3f9191bf9">

Similarly, adding

```
WTrackTableView::item {
  border: 0px;
}
```

fixes the issue for the play count too:

<img width="216" alt="image" src="https://github.com/mixxxdj/mixxx/assets/30873659/11356e35-53db-4c48-95cb-ad8099e989ce">
