### ISSUE TITLE
2.4 doesn't start with QT_OPENGL=angle on Windows

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11641]
### Bug Description

@m0dB :
I tried to start Mixxx with the environment variable QT_OPENGL set to angle. It fails to start:
```
debug [Main] Set root GL Context widget valid: WInitialGLWidget(0x19544c9bb10) false
critical [Main] Failed to load libEGLd (Das angegebene Modul wurde nicht gefunden.)
warning [Main] QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
debug [Main] Displaying main window
debug [Main] Running Mixxx
critical [Main] Failed to load libEGLd (Das angegebene Modul wurde nicht gefunden.)
warning [Main] QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
warning [Main] QOpenGLWindow::beginPaint: Failed to create context
warning [Main] QOpenGLWindow::beginPaint: Failed to make context current
```

### Version

2.4.0

### OS

Windows11

**Comment by JoergAtGithub** [comment]
With QT_OPENGL=software I get:
```
debug [Main] Set root GL Context widget valid: WInitialGLWidget(0x1be773ba7c0) false
debug [Main] Displaying main window
debug [Main] Running Mixxx
debug [Main] "4.6.0 Compatibility Profile Context 22.20.28.15.230324" "ATI Technologies Inc." "AMD Radeon(TM) Graphics"
debug [Main] QOpenGLContext surface format version: 2 1
```
and with QT_OPENGL=desktop just:
```
debug [Main] Set root GL Context widget valid: WInitialGLWidget(0x176b2a1efe0) false
debug [Main] Displaying main window
debug [Main] Running Mixxx
```

**Comment by m0dB** [comment]
Aren't libEGL.dll and libEGLd.dll somewhere in your Qt folder? Might simply be a matter of copying them next to mixxx.exe

**Comment by m0dB** [comment]
And it's not clear to me if with QT_OPENGL=software or QT_OPENGL=desktop mixxx does open or not?

**Comment by JoergAtGithub** [comment]
The files are there. I even tried to replace this two DLLs with the working versions from 2.3.5. Didn't help.

With software and desktop the waveforms work flawless for me - but I don't see a difference between desktop and software.

**Comment by m0dB** [comment]
Here https://musescore.org/en/node/276246 they suggest you have to copy both libEGL.dll and libGLESv2.dll (I guess in your case, with a debug build, libEGLd.dll, libGLESv2d.dll ?)

**Comment by JoergAtGithub** [comment]
We copy them https://github.com/mixxxdj/mixxx/pull/3370

**Comment by m0dB** [comment]
Are you sure they are 64 bit? (Assuming mixxx.exe is 64 bit)

It might be interesting to build against the official Qt binaries and copy the dlls from there to see if that makes a difference.

**Comment by JoergAtGithub** [comment]
Yes, this is guaranteed by the VCPKG system. All dependencies will be build together  for the same target platfom. And it's the same with Mixxx 2.3.5,

**Comment by m0dB** [comment]
Hm, but clearly something is wrong if the dlls can't be opened...

**Comment by JoergAtGithub** [comment]
This could be https://github.com/microsoft/vcpkg/issues/31954

**Comment by daschuer** [comment]
Maybe it is related. I will have a look. 

Interesting is also the Qt6 angle patch. Can this be a fallback for legacy devices that do not fulfill the Qt6 requirements?

**Comment by JoergAtGithub** [comment]
VCPKG seems to contain a patch that Qt6 runs with ANGLE.
But since Qt6 requires a rather new Windows10 version to run, I think these old graphic adapters are not relevant in practice.

**Comment by daschuer** [comment]
I have just confirmed that the libEGL.dll libGLESv2.dll are installed

"libEGLd" indicates that the debug version is expected. 

We can change our CMake Script to use Config mode to do it always right.  

This bug seems to be related: 
https://github.com/mixxxdj/mixxx/issues/11929

**Comment by daschuer** [comment]
Older Version 2.4-alpha-1118-g1b688f2d40 without QOPENNGL works: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/8f010060-74dd-48ee-8fb0-d47ab75dcd9d)
Even when I replace the angle dlls form the most recent install.
