### ISSUE TITLE
regression: waveforms look wrong when enabling / disabling fullscreen

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/mixxx#11646]
### Bug Description

This is a regression since the waveform widget rewrite.  

![image](https://github.com/mixxxdj/mixxx/assets/888940/bb4df682-f065-4700-b986-9dfe592ec072)

Resizing the window fixes it:

![image](https://github.com/mixxxdj/mixxx/assets/888940/225b2e18-b0f7-43c3-87bf-ff97605b64d7)

This doesn't always happen, but does reproduce on startup (I have mixxx start up in fullscreen mode).

I tried tweaking the [resize event](https://github.com/mixxxdj/mixxx/blob/2.4/src/widget/wglwidgetqopengl.cpp#LL52C1-L52C1) but it didn't help 

### Version

2.4 

### OS

Ubuntu 22.04

**Comment by m0dB** [comment]
Does it also happen with the allshaders waveform types?

**Comment by ywwg** [comment]
also broken with the allshaders type: 
![image](https://github.com/mixxxdj/mixxx/assets/888940/f2335a19-e5c7-4ccd-91ab-2d52c1e7acad)

**Comment by ywwg** [comment]
to me it looks like this is not an issue of the size of the widget, but the position. The waveform appears to get the wrong x,y origins.

**Comment by m0dB** [comment]
I can't reproduce this on macOS, but I feel like I am missing something. So to be sure, are these the scenarios?

1) You are in non-fullscreen, you load a track which is shown correctly, you select full screen, waveform is now displaced
2) You are in fullscreen, you load a track which is shown correctly, you select full screen, waveform is now displaced
3) You start the app in fullscreen, you load a track, waveform is displaced

Where 1 and 2 do not always happen, but 3 does. Is that correct?

**Comment by foss-** [comment]
Also unable to reproduce on macOS 13.4.1.

Maybe Linux only bug?
Is the problem reproducible in all skins or limited to a specific skin?
Is the problem reproducible with all waveforms or limited to a specific waveform?

**Comment by m0dB** [comment]
From the screenshots I get the impression that it actually behaves slightly different depending on the waveform type.

I will try to reproduce and debug this with Linux somewhere next week.

**Comment by Swiftb0y** [comment]
> also broken with the allshaders type: ![image](https://user-images.githubusercontent.com/888940/244988724-f2335a19-e5c7-4ccd-91ab-2d52c1e7acad.png)

what distribution is this? The window decoration looks like Windows 10...

**Comment by JoergAtGithub** [comment]
Do you have libEGL.dll and libGLESv2.dll in your Mixxx program directory? Could you try to replace these two file with the version from Mixxx 2.3.5?

**Comment by ywwg** [comment]
It's ubuntu 22.04.

**Comment by JoergAtGithub** [comment]
@ywwg You seem to be the only user experiencing this issue. Could you provide any additional information to reproduce it?

**Comment by ywwg** [comment]
I believe I have seen this with both the qt6 / opengl flags and without, which leads me to believe this is not a regression and is just a quirk on my system / OS.  If no one else can reproduce, I am ok closing the bug.  It is cosmetic and not hard to work around.

**Comment by ywwg** [comment]
closing as not-reproducible for anyone else
