### ISSUE TITLE
Numark DJ2GO2 Touch controller script has incorrect sysex message

### ISSUE THREAD

**Issue by burnsak** [mixxxdj/mixxx#11658]
### Bug Description

The current sysex message does not retrieve the control settings from the controller since it is using the wrong manufacturer and device id. I have the correct sysex message tested under Windows 11 and Ubuntu 22.04.2 which I will create a pull request for when assigned to me.

It isn't a critical bug but it is annoying. The file with the problem is: res/controllers/Numark_DJ2GO2_Touch_scripts.js

### Version

2.3.5

### OS

Windows11 and Ubuntu 22.04.2

**Comment by uklotzde** [comment]
Bugs are not assigned to anyone. Just open a PR with the fix and link this issue.
