### ISSUE TITLE
Mixxx 2.3.5-1~bionic missing libgcc-s1

### ISSUE THREAD

**Issue by DrNI** [mixxxdj/mixxx#11675]
### Bug Description

Trying to install Mixxx 2.3.5-1~bionic from the PPA on Kubuntu 18.04, getting this:

```
no@fuchur:~$ LANG=EN_en sudo apt-get install mixxx 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mixxx : Depends: libgcc-s1 (>= 3.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Turns out this package does not exist, yet the file libgccc-s1 is installed on my system. Apparently the package by that name was introduced in Ubuntu 20.04.

Mixxx 2.3.4 didn't have this issue when installed from the PPA.

### Version

2.3.5

### OS

Kubuntu 18.04

**Comment by DrNI** [comment]
Adding to this: On another machine with Kubuntu 18.04 I have Mixxx 2.3.4 running, installed from the PPA. It however does not update to 2.3.5, saying package mixxx is held back. Probably for the same reason.

**Comment by Swiftb0y** [comment]
@daschuer I guess we need to remove 2.3.5 from the 18.04 PPA?

**Comment by daschuer** [comment]
Ubuntu Bionic is end of life since 2023-05-31.
Please update your computer. 

It looks the missing package was from:
http://ppa.launchpadcontent.net/ubuntuhandbook1/build-tool/ubuntu bionic/main amd64 libgcc-s1 amd64 11.3.0-1ubuntu1~18.04.sav0 [41.7 kB]

```
sudo add-apt-repository ppa:ubuntuhandbook1/build-tool
sudo apt update
```

Unfortunately I do not find it anymore. By luck is is still somewhere?
