### ISSUE TITLE
Mute Speakers when mic imput turns on

### ISSUE THREAD

**Issue by djdavek** [mixxxdj/mixxx#11672]
### Feature Description

I would love to be able to listen to my music on monitor speakers.  Unfortunately, the mic comes through the speakers too. I would like the talk button to mute the speakers but, when you disengage the talk button the speaker output would resume.

Thank you

**Comment by ronso0** [comment]
quotung from the manual https://manual.mixxx.org/2.3/en/chapters/microphones.html#using-microphones
> If you would prefer to not hear the microphone input, you can set the Microphone Monitor Mode option to Direct monitor (recording and broadcasting only). This will still mix the microphone input with your recorded and broadcasted mixes, but it will not mix the microphone with the Master output.

**Comment by daschuer** [comment]
There is another aspect, that the mic will pick up the music from the monitor speaker that may create an echo in the final mix. 

@djdavek Can you confirm that this issue it is fully resolved? If not please reopen and rephrase if required. Thank you.
