### ISSUE TITLE
KDE Plasma, Xorg, NVIDIA: Mixxx is always running at single digit frames per second with with QOPENGL=ON`

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11683]
For me Mixxx is always running at single digit frames per second with with QOPENGL=ON` regardless of skin on KDE Plasma, Xorg, NVIDIA. Is this already being tracked anywhere? Configuring with `-DQOPENGL=OFF` fixes the issue for me.

_Originally posted by @robbert-vdh in https://github.com/mixxxdj/mixxx/issues/11602#issuecomment-1572792796_

**Comment by JoergAtGithub** [comment]
@robbert-vdh Could you please test with #11681 if this fixes this issue on your system.

**Comment by robbert-vdh** [comment]
The problem seems to be gone on the latest master branch with `-DOPENGL=ON`.
