### ISSUE TITLE
Can not set up soundcard

### ISSUE THREAD

**Issue by MaexPow** [mixxxdj/mixxx#11682]
### Bug Description

I had Mixxx running on my laptop. Due to a system crash by updating the version to Ubunut 22.04 i had to reinstall ubuntu from scratch. Now I installed Mixxx again and i can not get the sound hardware working.

When I start Mixxx i get the message that there are no output devices set up. 
In the preferences I can choose ALSA and OSS. I know OSS is outdated. When I choose ALSA and I want to asign output devices in the dropdown boxes I get no choices to choose for any of the boxes. I can not set a master Out, neither a headphone out, etc.

Is there a solution. How can Mixxx detect my soundcard which is working fine with any other programm on my laptop.

**Comment by ronso0** [comment]
How did you install Mixxx?
And which version?

**Comment by MaexPow** [comment]
I installed Mixx trought the software center from Ubuntu, my version is 2.3.5.

**Comment by ronso0** [comment]
It seems there's a community-created Snap version of Mixxx, though it's not as plug'n'play as the deb version from the official Mixxx ppa.
If the software page of the Mixxx version you installed looks like this, you have the Snap version.
![image](https://github.com/mixxxdj/mixxx/assets/5934199/315030bf-c57a-46ed-a91e-4378683be8d8)

If yes, I suggest to remove that and install the deb version as explained on the download page
https://mixxx.org/download/#stable-ubuntu

Or, if you want to stick with the Snap vesion, you obviously need run the snap commands listed on the app page:
`https://mixxx.org/download/#stable-ubuntu`
`https://mixxx.org/download/#stable-ubuntu`

**Comment by MaexPow** [comment]
installing the ppa worked. 
I did not know about the issue with the version from software center.

**Comment by Swiftb0y** [comment]
According to https://snapcraft.io/mixxx-community you can reach the author of the snap version via email at jesus.soto@canonical.com. Please communicate with them to get the snap version fixed.

**Comment by ronso0** [comment]
> I did not know about the issue with the version from software center.

It's not really an issue, you just need to follow the specific instructions. If these don't work for you contact the maintainer as @Swiftb0y suggested.
