### ISSUE TITLE
searchbox clearing behaviour

### ISSUE THREAD

**Issue by gui-lux** [mixxxdj/mixxx#11700]
### Feature Description

Hi,
when searching, finding and loading a track from a rather big playlist and finally clearing the search field, I would find pretty convenient that the playlist would scroll at the place where the freshly loaded track is located in the playlist.

Please let me know if this isn't clear enough
Thanks

**Comment by ronso0** [comment]
Please test 2.4-beta ; )

**Comment by gui-lux** [comment]
Hi,
the build fails (DietpiOS/Rpi4).
Need more debug right here or should I open another issue ?

Thanks

**Comment by daschuer** [comment]
Please file a new bug about the building issue. Thank you.

**Comment by gui-lux** [comment]
Thank you daschuer, looks like I had just forgotten to execute the debian_buildenv script. :)
Currently building, I get back to you very soon.

**Comment by gui-lux** [comment]
OK, successfully built and yes the behavior is really nice, 100% what I was looking for.

However, I noticed two things :
- UI becomes unresponsive (40s) when loading a 1k items playlist. Meanwhile, audio still ok but for example, bass/mid/treble knobs do not work as long as the UI becomes responsive again.
- Some columns settings have been overwritten but not a problem at all

Please let me know if it's safe to make uninstall and go back to 2.3.x

Thanks

**Comment by ronso0** [comment]
Great. so we can close this.

> UI becomes unresponsive (40s) when loading a 1k items playlist. Meanwhile, audio still ok but for example, bass/mid/treble knobs do not work as long as the UI becomes responsive again.

please file an bug report for separate issues.

> Please let me know if it's safe to make uninstall and go back to 2.3.x

There are no efforts made to make downgrading safe, there may be issues with the database.
Usually you back up your settings & library before testing betas and nightlies ; ) https://github.com/mixxxdj/mixxx/wiki/Testing
I suggest you do the same before going back to 2.3
