### ISSUE TITLE
waveform randomly disappears if shifting a loop backwards in pre-roll

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11732]
https://github.com/mixxxdj/mixxx/assets/5934199/09811685-9095-483f-bf1a-fac1c3005c2e

wavefrom is RGB (GLSL)

**Comment by daschuer** [comment]
I cannot confirm it on Ubuntu Focal using the latest 2.4

**Comment by ronso0** [comment]
Weird, can't reproduce it anymore.
I'll reopen this if I notice it again.
