### ISSUE TITLE
DEBUG_ASSERT in SettingsDAO::setValue

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11738]
### Bug Description

occurs when starting with a new profile, and on every subsequent start
```
warning [Main] SettingsDAO - Failed to set "mixxx.db.model.missing.ColumnsSorting" = QVariant(QString, "artist 1 ") QSqlError("5", "Unable to fetch row", "database is locked")
DEBUG ASSERT: "!"Failed query"" in function bool SettingsDAO::setValue(const QString&, const QVariant&) const at /src/library/dao/settingsdao.cpp:76
```

### Version

2.4-beta 10dba8f4ac6c4e00595869f9e38c0f83da692f6f

### OS

Ubuntu Studio 20.04.5 with xfce4

**Comment by ronso0** [comment]
If I disable the DEBUG_ASSERT (too lazy to rebuild as `Release` or with `-DMIXXX_DEBUG_ASSERTIONS_FATAL` off)...
Mixxx starts just fine and mixxxdb `settings`>`mixxx.db.model.missing.ColumnsSorting` is `artist 1` as it should be :shrug:

**Comment by ronso0** [comment]
100% reproducible when I select a huge music folder during first start.
Active library scanner causing `"database is locked"`?

**Comment by uklotzde** [comment]
#10876 ...and probably more.

All these sporadic or spurious database failures are expected. Not fixable without a major rewrite. The architecture is broken.

Btw, 1.6k issues are ridiculous for such a small project. No one will ever look at them. Instead new issues like this are created over and over again. Advice from an expert: https://twitter.com/allenholub/status/1676367019078488066

**Comment by ronso0** [comment]
so duplicate of #10876, and basically #6631
