### ISSUE TITLE
update LateNight 64 screenshots with more samples

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#11763]
### Bug Description

.

### Version

2.4

**Comment by ywwg** [comment]
![image](https://github.com/mixxxdj/mixxx/assets/888940/1e6d3eea-fb7b-46f5-9ed5-ad74da144ad5)
how about this

**Comment by ywwg** [comment]
(if that works I can make a PR)

**Comment by daschuer** [comment]
Yes that works for me. We need also one for PaleMoon. 
@ronso0? 

Maybe you can "randomize" the position of the loaded samplers a bit. But I don't have a strong opinion, actually.

**Comment by ronso0** [comment]
Yeah, randomize the samples a bit, and I think we don't need to fill the bottom row just to show it's 64 samplers.

For PaleMoon just use the same state and switch to PaleMoon?

**Comment by daschuer** [comment]
@ywwg How is your state here? Will you open a PR soon?

**Comment by ywwg** [comment]
I'll move some things around and get shots of both versions of the skin

**Comment by ywwg** [comment]
the ones at the bottom are there on purpose, they were for a set I did years ago

**Comment by ywwg** [comment]
are the screenshots for the website or for the examples in the app?

**Comment by ywwg** [comment]
https://github.com/mixxxdj/mixxx/pull/12792

**Comment by ywwg** [comment]
done
