### ISSUE TITLE
Parallel waveform display bug

### ISSUE THREAD

**Issue by djbartelby** [mixxxdj/mixxx#11779]
### Bug Description

Hi !

I have nothing except some random display where there should normally be the parallel waveform. 
![Capture d’écran du 2023-08-01 07-01-07](https://github.com/mixxxdj/mixxx/assets/141109927/445f41b5-f86c-4893-9cf4-be6029384dab)

Here is my computer settings :
Dell Inc. Latitude 7480
Intel® Core™ i7-6600U × 4
Mesa Intel® HD Graphics 520 (SKL GT2)
Debian GNU/Linux 12 (bookworm)

I really have no idea how to solve this problem. Thanks !

### Version

2.3.3

### OS

Debian GNU/Linux 12 (bookworm)

**Comment by daschuer** [comment]
Mixxx 2.3.3 is outdated. We are currently at 2.3.6 does this make a difference? 
Are all waveform affected?
What is the open GL Status reported in at the bottom of the Waveform preferences? 

We have overhauled the waveforms in 2.4-beta. Is your issue fixed with it?

**Comment by daschuer** [comment]
Mixxx 2.3.3 is outdated. We are currently at 2.3.6 does this make a difference? 
Are all waveform affected?
What is the open GL Status reported in at the bottom of the Waveform preferences? 

We have overhauled the waveforms in 2.4-beta. Is your issue fixed with it?

**Comment by djbartelby** [comment]
Thanks for the answer, I didn't succeed to update to Mixxx 2.3.6 when I try I have this message : 
![Capture d’écran du 2023-08-02 10-57-16](https://github.com/mixxxdj/mixxx/assets/141109927/669f97de-f1eb-4854-8d3e-6da1dfcbec36)
It's only the parallel one that is affected, I don't have any problem with the waveforms that are on the bottom corners on the first screenshot.
The GL Status : 
![Capture d’écran du 2023-08-02 10-59-28](https://github.com/mixxxdj/mixxx/assets/141109927/f8507095-16ee-4d94-8c0b-0a5445038bd8)

Thanks

**Comment by Swiftb0y** [comment]
have you made sure to start mixxx with `-platform xcb`?

**Comment by djbartelby** [comment]
Thanks, it works like this !
