### ISSUE TITLE
FX dry/wet value on startup

### ISSUE THREAD

**Issue by gui-lux** [mixxxdj/mixxx#11773]
### Bug Description

Hi,
it seems v2.4 always resets dry/wet FX value at startup.

I'm not 100% sure but I think 2.3.x used to store this value and apply it again at startup.

Thanks !

### Version

2.4

### OS

DietPiOS (debian bullseye based)

**Comment by Swiftb0y** [comment]
Issue also affects the Super Knob

**Comment by gui-lux** [comment]
Makes me think I forgot to tell my controller (denon mc4000) has FX dry/wet mapped on an endless knob, that could be the issue.

**Comment by Swiftb0y** [comment]
Highly doubt it. If it was mapped to a finite knob then the knob could change when mixxx asks the controller for its knob positions but an endless encoder doesn't have an absolute position, so this case applies even less. Regardless, I was also able to reproduce this without any hardware attached, this is likely a regression from the large rewrite of the controller system as part of 2.4 (#4467).

**Comment by gui-lux** [comment]
Fair enough ! Just wanted to describe the issue as much as I can.
Thanks

**Comment by Swiftb0y** [comment]
I highly appreciate that. :+1: I don't think the fix we'll be difficult. I'm looking into it.

**Comment by Swiftb0y** [comment]
@gui-lux you can test a fixed version at the bottom of this page (assuming you're logged in): https://github.com/mixxxdj/mixxx/actions/runs/5741200120

**Comment by gui-lux** [comment]
Isn't there any sources, just debs ? And not sure which one I should pick, qt6 or plain ?

**Comment by gui-lux** [comment]
Just spotted another smallish issue on startup, seen a few times, and I don't know yet how to reproduce.
Pitch sliders seem sometimes to be picking up a wrong value : just started mixxx with controller, both pitch sliders were just a little above zero, pitch sliders into mixxx display respectively +29.79 and +30.37 and give weird zoom on waveforms. One slider touch makes it go back to normal but I've never seen this behavior on 2.3.x.
Related or new issue ?

About the fixed version : is it ok to build from a zip at this url : https://github.com/mixxxdj/mixxx/tree/9720413070eefc4f69bad007d1d476fd66c149b4

**Comment by daschuer** [comment]
Yes.

**Comment by Swiftb0y** [comment]
> Pitch sliders seem sometimes to be picking up a wrong value : just started mixxx with controller, both pitch sliders were just a little above zero, pitch sliders into mixxx display respectively +29.79 and +30.37 and give weird zoom on waveforms. One slider touch makes it go back to normal but I've never seen this behavior on 2.3.x.
Related or new issue ?

Very likely new issue, though that could be related to your controller hardware. Please try disabling any controllers in the mixxx preferences and see if the issue still occurs. If so, please open a new issue.

**Comment by gui-lux** [comment]
The fix works. Tried different knob positions, all good.
Thx very much dev team !
