### ISSUE TITLE
Export playlist not exporting the correct one

### ISSUE THREAD

**Issue by NightyEve** [mixxxdj/mixxx#11774]
### Bug Description

When right clicking directly on a unselected playlist, it export the previously selected playlist.

Need to first make sure to select the playlist and see all the track are visible on the right.

### Version

2.3.5

### OS

Windows 11

**Comment by ronso0** [comment]
Thanks for your report. This is already fixed in Mixxx 2.4 (for playlists and crates). Please test 2.4-beta from https://mixxx.org/download/#beta and reopen this Issue in case it doesn't work for you.
