### ISSUE TITLE
GLSL Waveforms disappear on resize

### ISSUE THREAD

**Issue by tgucio** [mixxxdj/mixxx#11786]
### Bug Description

When resizing the window on a large 4k display on a MacBook Pro M1, beyond certain size the waveforms disappear:

![mixxx-waveform](https://github.com/mixxxdj/mixxx/assets/72562119/dbb514ba-4b13-4df4-b67a-591c2ba6dd81)

HW: MacBook Pro 14", 2021 (Apple M1 silicon), macOS Ventura 13.4.1 (c) (22F770820d)
Mixxx version: 2.4-beta-70-g2e3d72f479 

### Version

2.4-beta-70-g2e3d72f479 (Apple silicon build)

### OS

macOS Ventura 13.4.1 (c) (22F770820d) (Apple M1 silicon)

**Comment by JoergAtGithub** [comment]
@m0dB Could you've a look

**Comment by m0dB** [comment]
Hi, I am on holidays and not near a system where I can try to reproduce this. @tgucio are you building mixxx yourself and able / willing try out some things? I would like to know which of the layers (aka renderers) that make up the waveform display cause this issue. But first of all: does this happen with all waveform types?

**Comment by tgucio** [comment]
@m0dB The problem with building is that I don't have an Intel silicon Mac to build on - I take it building on M1/M2 is still not supported officially (I'm getting some failures building [fwcd/m1xxx](https://github.com/fwcd/m1xxx) now).

I've experimented a bit with waveform types and here's what I see:

NOK:
- Filtered (GLSL)
- RGB (GLSL)
- RGB Stacked (GLSL)

OK (not reproduced):
- Filtered (GL)
- Filtered (all-shaders) (GLSL)
- RGB (GL)
- RGB (all-shaders) (GLSL)
- RGB L/R (all-shaders) (GLSL)
- Simple (GL)
- Simple (all-shaders) (GLSL)

**Comment by foss-** [comment]
Another data point: Can't reproduce on
macOS 13.5 (Intel mac)
2.4-beta-75-gc3df3da55d
Tried all three NOK waveforms and resizing on an external 4k monitor.

**Comment by m0dB** [comment]
Seeing that the "all-shaders" waveforms behave fine, I don't see a reason to investigate this further. Instead, we should just recommend (and default to) the all-shaders waveform types, at least on macOS.

**Comment by daschuer** [comment]
We will remove the legacy GLSL Waveforms soon.
