### ISSUE TITLE
Low FPS when G-SYNC is enabled and application is focused

### ISSUE THREAD

**Issue by dan-giddins** [mixxxdj/mixxx#11789]
### Bug Description

When I have G-SYNC enabled, and Mixxx is the focused window, the FPS for the whole application drops to about 10 FPS. I can avoid this by either un-focusing Mixxx, or disabling G-SYNC, either system wide, or just for Mixxx.exe. Mixxx is the only application that I have this problem with, and I play various different video games.

### Version

2.3.5

### OS

Windows 11

**Comment by Swiftb0y** [comment]
Please try the mixxx version at the bottom of this page: https://github.com/mixxxdj/mixxx/actions/runs/5755964677

**Comment by dan-giddins** [comment]
> Please try the mixxx version at the bottom of this page: https://github.com/mixxxdj/mixxx/actions/runs/5755964677

Nice, this fixes it!

**Comment by Swiftb0y** [comment]
Thanks for confirming
