### ISSUE TITLE
Strange color after Linux Mint Update

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#11797]
### Bug Description

Hello, after uptdate my Linux Mint Cinnamon (newest version) i have a strange look of the waveforms.

If in deck 1 is loaded a song, all normal.
If not, (but only in deck 2) the waveform has a blue background (look screenshots)

The following Waveform Types are working without error. (the other make the problem you see on the screenshot below)
Gefiltert
HSV
HSV-Qt
RGB

![Bildschirmfoto vom 2023-08-07 13-19-34](https://github.com/mixxxdj/mixxx/assets/96744684/8bdef961-97af-47f1-913d-5a4f189f7b7a)
![Bildschirmfoto vom 2023-08-07 13-19-17](https://github.com/mixxxdj/mixxx/assets/96744684/b6708873-d8e3-48f5-aba4-51252d0d24dd)

btw: I added this for getting always the latest beta, but it seems it’s not working (or my alpha is the most resent beta…?)

```
$ sudo add-apt-repository ppa:mixxx/mixxxbetas
$ sudo apt update
$ sudo apt install mixxx
```

### Version

2.4 alpha 1403

### OS

Linux Mint 21.2 Cinnamon

**Comment by Swiftb0y** [comment]
The cyan background has been reported in #11164 and fixed for 2.4. if you use the new "(all-shaders)" versions of the waveforms.
In regards to being stuck on an old version, I don't know enough about our PPA for that. @daschuer can probably help you.

**Comment by ronso0** [comment]
Re the ppa, you might try to disable/remove the nightlies ppa and force-update from the beta ppa.

**Comment by stefan-franz** [comment]
How do i force an update from the beta ppa? I thought, if i add the code lines Linux Mint make it's self automatically....hmmm...?

I deactivated the nighties entry and added the ppa of the betas yesterday. Linux Mint installed after this only a library. But not the most recent Mixx 2.4.xx Beta

![PPAs](https://github.com/mixxxdj/mixxx/assets/96744684/3b9416e7-379d-4cc6-91ca-4756ea65b6b9)
![PPA Betas](https://github.com/mixxxdj/mixxx/assets/96744684/7ee54f7a-541b-4750-a36d-6a74f1763b58)

**Comment by daschuer** [comment]
Normally a alpha should be considered as older that the beta. Maybe there is a reason that this is not the case after the Mint update. 
Please post the output of: 
`apt list mixxx -a`

**Comment by daschuer** [comment]
Ah, I see: 
`dpkg --compare-versions 2.4.0~alpha2~1403~g770773c963-1~jammy lt 2.4~beta~77~gb4a40b876c-1~jammy  && echo true`
Does not return true. 

We suffer here the issue that we have dropped the trailing zero from the alpha and beta version. 

This means you have to explicit select the beta version, or reinstall and reinstall mixxx. Your library and settings will remain. 
(A backup is anyway recommended)

**Comment by stefan-franz** [comment]
You were faster than me. 
On question off topic: I worked good with the alpha versions of Mixxx. Are the improvements of the 2.4 beta version you made in the future automatically improved in the 2.5 alpha over this github system or not?
Is there anywhere a information, what improvements/new features in the alpha 2.5 version made after a new version comes out?

**Comment by daschuer** [comment]
Yes, but this is a manual process. You will find merge commits like "Merge remote-tracking branch 'upstream/2.4 into main" 
We keep also manually a change log: https://github.com/mixxxdj/mixxx/blob/main/CHANGELOG.md currently a bit aged.
