### ISSUE TITLE
Mixxx isn't findable in the startmenu of Linux Mint anymore

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#11820]
### Bug Description

I have a shortcut on the desktop but now i'm confused, why i don't find Mixxx in the startmenu. Neither is there a shortcut in the Start menu, nor does the search find Mixxx via the Start menu.

### Version

2.4 beta 85

### OS

Linux Mint 21.2 Cinnamon

**Comment by ronso0** [comment]
Can confirm (somehow): the launcher is listed in the apps list on xfce but it can't be excuted.

Reason: missing clising quote, regression from #11805.
working on it.

**Comment by ronso0** [comment]
#11826
