### ISSUE TITLE
Add a control to clear the temp loop (keep saved loops)

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#11825]
### Feature Description

I had with loop just a "machine" gun:
Imagein a saved Loop from Beat 100 (Loop in) to Beat 108 (Loop Out)
During the track were played i set on Beat 107 Loop in. And immediately the loop plays from 107-108 - the result was a 1 beat machine gun. 
I would wish to have an option to delete the loop (maybe long right click to the Loop in or Loop out

**Comment by ronso0** [comment]
the track menu has a Reset submenu which allows to remove the loops

**Comment by stefan-franz** [comment]
Ah - ok. Maybe in the future comes an option in the skin.....

**Comment by ronso0** [comment]
Note that the track menu is also available via right-click on track labels.

Anyway, a `clear_temp_loop` control may indeed be useful (don't touch saved loops). I changed the bug title accordingly.

Though I don't see a where we could add this to skins: all loop controls already have a right-click action.
Like any other control it could be added to the keyboard mapping in case it is required on a regular basis.

**Comment by stefan-franz** [comment]
Delete in the skin possibility: Hold >2 sec the Loop out button (or to delete the Loop in, the same system)
In the skins of VD often used this for deleting something.

**Comment by ronso0** [comment]
Yes, IRRC from a similiar attempt, such a special longpress action requires a lot of work in the WPushButton class.

For hotcues there's Shift + right-click, we can try to add a Shift+click action to Beatloop button.
Though that also requires work in WPushButton, but probably less than the longpress solution if we consider to only allow assigning toggle controls to Shift+click.
