### ISSUE TITLE
When mixxx is working, breaks other audio-related programs

### ISSUE THREAD

**Issue by ejgutierrez74** [mixxxdj/mixxx#11835]
### Bug Description

In Ubuntu 22.04.3 LTS with latest updates.
Mixxx:2.3.6

I launch mixxx.

For example in firefox  i have Udemy courses: they broke the video playing.
Or in other tab i have Twich open: Twich stream stops working, both sound and video. 

I exit Mixxx, and all works fine again.

Thanks

### Version

2.3.6

### OS

Ubuntu 22.04

**Comment by Swiftb0y** [comment]
duplicate of #11305
