### ISSUE TITLE
Cannot delete a large song list from AutoDJ.

### ISSUE THREAD

**Issue by GuyMZ** [mixxxdj/mixxx#11857]
### Bug Description

I have a library of several thousand songs. I loaded them all into the AutoDJ song list and then discovered that trying to delete them using Ctrl-A and then the Del button crashed Mixxx. Had to delete the AppData/Local/Mixxx folder and then redo the setup. 

Should be some notice of the maximum songs permitted in the AutoDJ list, or ideally, deleting should work regardless of the number of songs.

### Version

2.4-beta-95-ga5bdd6f60a

### OS

Windows 11 Pro

**Comment by Swiftb0y** [comment]
Please do not file duplicate issues. If you want us to help you. Please respond to our questions in #11858
