### ISSUE TITLE
Trying to delete too large an AutoDJ song list crashes Mixxx

### ISSUE THREAD

**Issue by GuyMZ** [mixxxdj/mixxx#11858]
### Bug Description

I have a library of several thousand songs. I loaded them all into the AutoDJ song list and then discovered that trying to delete them using Ctrl-A and then the Del button crashed Mixxx. Had to delete the AppData/Local/Mixxx folder and then redo the setup. 

Should be some notice of the maximum songs permitted in the AutoDJ list, or ideally, deleting should work regardless of the number of songs.

### Version

2.4-beta-95-ga5bdd6f60a

### OS

Windows 11 Pro

**Comment by Swiftb0y** [comment]
Thank you for reporting your issue. Please understand that in order for us to be able to properly debug this, we need a backtrace. Have a look at the wiki for finding out how to create one: https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

**Comment by ronso0** [comment]
Also, please describe in detail why you 
> Had to delete the AppData/Local/Mixxx folder and then redo the setup.
