### ISSUE TITLE
Interface displaying issue

### ISSUE THREAD

**Issue by Fahazavana** [mixxxdj/mixxx#11866]
### Bug Description

All the buttons are not showing correctly:

![image](https://github.com/mixxxdj/mixxx/assets/68125192/4724c23f-c561-4b9a-bb08-ac8eb324eb81)

![image](https://github.com/mixxxdj/mixxx/assets/68125192/95dcc1be-8e39-49b4-88bb-1c8ef0771394)

I am using a HP ProBook 440 G4 14".

### Version

2.3

### OS

Debian 12

**Comment by Swiftb0y** [comment]
Hey there. How have you started mixxx? Terminal or desktop shortcut? Have you tried Mixxx 2.4?
Likely duplicate of #11164

**Comment by spazztula** [comment]
This bug insists even with the Flatpack version 2.3.6 on both Debian 12 and Testing.
Mixxx 2.4 how is there a testing branch, because the latest is 2.3.6

**Comment by Fahazavana** [comment]
> Hey there. How have you started mixxx? Terminal or desktop shortcut? Have you tried Mixxx 2.4? Likely duplicate of #11164

No, but I noticed that after install okular (I am on gnome, so without the recommend to no t install kde stuff) all the button appear correctly, but a there are some glitch on the top (the black box)
![image](https://github.com/mixxxdj/mixxx/assets/68125192/176c66ad-78c7-4883-8864-866fa82efb46)

Also, it was not the only app having that problem (I think), but this solved partially the problem.

**Comment by Fahazavana** [comment]
I used apt.
