### ISSUE TITLE
UI lag on macOS

### ISSUE THREAD

**Issue by peiniau** [mixxxdj/mixxx#11876]
### Bug Description

Mixxx UI is lagging to great extent on my MacBook Pro.

3,3 GHz Intel Core i7 double core
16 Go 2133 MHz LPDDR3
Intel Iris Graphics 550 1536 Mo

It takes between 2 to 3 seconds for any click on the interface to operate.

### Version

2.3.6

### OS

macOS Monterey 12.6.8

**Comment by Swiftb0y** [comment]
That is a known issue and has been fixed in Mixxx 2.4. Please try that and reopen this issue if it still occurs for you under 2.4. Thank you.

**Comment by peiniau** [comment]
Works like a charm :-D

Thank you !

Cheers
