### ISSUE TITLE
Problems loading/updating waveforms in Vinyl mode (Mixxx 2.4)

### ISSUE THREAD

**Issue by robi970** [mixxxdj/mixxx#11885]
### Bug Description

the latest releases of Mixxx 2.4 have some more problems than the previous ones (always Mixxx 2.4), with the use of DVS:

1- when loading a track, the waveform is not always loaded on the deck.
2- more frequently than point 1, Mixxx doesn't load the sliding waweform
3- (sliding waweform) even if it is loaded, it is not updated if, for example, a Loop or a HotCue is inserted.

in all cases, Mixxx updates as soon as it hears the timecode (when the stylus is placed on the record, or when "start" is pressed on the turntable with the stylus already in place)

POV: I also point out, for information only, that, at least with the use of DVS, Mixxx 2.4 still crashes too often.

### Version

2.4

### OS

Win10 pro 64bit - AMD ryzen 5 3600; 16GB ram; AMD radeon R9 200 series

**Comment by JoergAtGithub** [comment]
Could you please provide more details:

- Which Mixxx 2.4 builds worked for you and which not
- Provide data about the crashes: https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

Without this information it might be impossible for a developer to reproduce and fix this.

**Comment by Swiftb0y** [comment]
> at least with the use of DVS, Mixxx 2.4 still crashes too often.

fyi I Can't reproduce this with my DVS setup. None of the crashes (which have all just been debug asserts) were vinyl related.

**Comment by robi970** [comment]
> Quali build Mixxx 2.4 hanno funzionato per te e quali no

every time I use Mixxx 2.4 I first go to download the update that I find on the Download page.
today I used the 2.4.beta.100.
the previous time I was at 96..
But I'm not able to tell you from which release I got the feeling that Mixxx got worse for loading waweforms.
I can tell you that version 50 I seem to remember didn't have all these Waweforms loading problems.
Perhaps, until the release between 75 and 85 there were fewer problems.
Version 50 is the one that allowed me to start testing Mixxx2.4, as the previous ones gave me problems with the AMD video card and OpenGL.
But most of the time Mixxx2.4 is open on my PC, it's to adjust the XML and JS files to the new features

**Comment by JoergAtGithub** [comment]
Which AMD video driver version do you use?

**Comment by robi970** [comment]
I'm posting a screen where, I think, you can extrapolate all the details you need.
Microsoft tells me the drivers are up to date

![Radeon R9 200](https://github.com/mixxxdj/mixxx/assets/135370043/138a21dd-5174-44a2-8326-ee4b1e8d3738)

**Comment by JoergAtGithub** [comment]
Please ensure to use the latest graphic drivers: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-5-2

**Comment by robi970** [comment]
I installed the drivers you suggested.

I've finished my summer vacation so I can't use Mixxx for more than a few minutes.
Mixxx seems to be doing better, but it's hard to say whether that's because of the new drivers or because the problem was fixed.
For now that's fine.

Mixxx keeps closing (crashes?) when I turn off the mixer (with integrated DVS sound card)

doubt:
Can Mixxx crash due to old corrupt tracks?

**Comment by Swiftb0y** [comment]
>  Can Mixxx crash due to old corrupt tracks?

While rare afaik, it can happen. If thats the case we usually want to know about it and would like to have a copy of the corrupted file if posible. If you can reproduce the crash, please [collect a backtrace](https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces) and post it in a separate issue.

**Comment by ronso0** [comment]
> Mixxx keeps closing (crashes?) when I turn off the mixer (with integrated DVS sound card)

IIRC that is to be expected if you unplug the main output, or at least Mixxx will become super slow and unable to recover.
