### ISSUE TITLE
Wayland: No window decorators when leaving full screen

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11898]
### Bug Description

The screenshot in #11897 shows the issue.

Only Wayland is affected, X11 works as expected.

Both Qt5 and Qt6 are affected.

### Version

main

### OS

Fedora 38

**Comment by Swiftb0y** [comment]
Can't reproduce with either Qt versions under XWayland (mutter 44.4).

**Comment by uklotzde** [comment]
> Can't reproduce with either Qt versions under XWayland (mutter 44.4).

I am using the native Wayland backend, not `xcb` that has recently been retired.

**Comment by Swiftb0y** [comment]
yes, I meant running with the native wayland backend (`-platform wayland`), just under an xwayland compositor (eg mutter, instead of a pure wayland-only implementation eg sway). I apologize for the confusion.

**Comment by Swiftb0y** [comment]
yes. Can you confirm that it only affects Deere?

**Comment by uklotzde** [comment]
The window placement was the issue. The decorators were hidden behind the desktop top bar. After moving the application window once I am no longer able to reproduce this state when switching between full screen and window.
