### ISSUE TITLE
Qt6/Deere: No library view

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11897]
### Bug Description

![Screenshot from 2023-08-30 23-46-12](https://github.com/mixxxdj/mixxx/assets/1474154/cc1b3edb-3e55-4289-b4ed-80e62adeb4d7)

Qt 6.5.2

### Version

main

### OS

Fedora 38

**Comment by uklotzde** [comment]
Occurs on both X11 and Wayland.

**Comment by Swiftb0y** [comment]
Can only reproduce under Deere. Latenight, Shade and Tango work fine.

**Comment by uklotzde** [comment]
Confirmed. Only Deere is affected.

**Comment by ronso0** [comment]
@uklotzde Does removing the first line
```
<!DOCTYPE template>
```
from Deere/library.xml fix the issue?

Apart from that I can't spot an obvious difference in skin.xml and library.xml templates in Deere and LateNight :shrug:

**Comment by uklotzde** [comment]
> @uklotzde Does removing the first line

Unfortunately that didn't help.

**Comment by uklotzde** [comment]
@ronso0 The missing library widgets (both sidebar tree and table view) become visible when switching to *Maximize Library* and disappear when switching back to the normal view.

**Comment by Holzhaus** [comment]
@ronso0 maybe the issue is not in the XML, but in the CSS?

**Comment by ronso0** [comment]
Which object fills/is the gap? WWidgetGroup or WSplitter?

You can try changing the vertical size policy `max` -> `me` here https://github.com/mixxxdj/mixxx/blob/03cb99cb917b3a96123ca30d360fd5323128e972/res/skins/Deere/skin.xml#L205-L207
In LateNight it's `me,me` and that's working fine, right?

**Comment by uklotzde** [comment]
Neither `min, me` nor `me, me` work.
