### ISSUE TITLE
crash when moving selection in 'Computer' feature

### ISSUE THREAD

**Issue by d1skjokey** [mixxxdj/mixxx#11909]
### Bug Description

Hello, referring to this issue: https://mixxx.discourse.group/t/mixxxcontrol-s-not-found-error-and-crashing-with-numark-mixtrack-pro/27938

Selected mapping: "Numark MixTrack Pro" (Author: Matteo, James Ralston, D. J. Freije)
Controller: Numark Mixtrack Pro

Step by step what I did:
1. load a track
2. press play
3. go to a folder
4. scroll up and down
5. Mixxx freezes and crashes

(let me know if there's something wrong with the attachments, I've never done this stuff)

[mixxx.log.2.txt](https://github.com/mixxxdj/mixxx/files/12503757/mixxx.log.2.txt)
[Initializing wait objects....txt](https://github.com/mixxxdj/mixxx/files/12503702/Initializing.wait.objects.txt)

### Version

Mixxx 2.3.6

### OS

Windows 11

**Comment by Swiftb0y** [comment]
Hey there, thank you for your backtrace, unfortunately it has been taken at the wrong time. The debugger stopped the program right at the start and the backtrace contains the snapshot of mixxx at that time. Instead we need a snapshot (backtrace) at the point of the crash to debug this further.

**Comment by d1skjokey** [comment]
> Hey there, thank you for your backtrace, unfortunately it has been taken at the wrong time. The debugger stopped the program right at the start and the backtrace contains the snapshot of mixxx at that time. Instead we need a snapshot (backtrace) at the point of the crash to debug this further.

Hi,
I tried doing it again exactly in the order specified here: https://github.com/mixxxdj/mixxx/wiki/Creating-Backtraces
Just in case I'll outline what I did again:
1. opened x64dbg, 2. clicked "recent files -> mixxx.exe", 3. launched Mixxx, 4. in x64dbg clicked "debug -> run" three times (? as instructed), 5. switched to Mixxx and did everything the same (except I went to the folder before loading a track etc.) until crash, 6. did instructions 9-12, 7. relaunched Mixxx and copied the log

[Initializing wait objects....txt](https://github.com/mixxxdj/mixxx/files/12503909/Initializing.wait.objects.txt)
[mixxx.log.1.txt](https://github.com/mixxxdj/mixxx/files/12503910/mixxx.log.1.txt)

**Comment by ronso0** [comment]
> went to the folder

What does that mean?
Open a directory in Library -> "Computer" feature?

**Comment by d1skjokey** [comment]
> > went to the folder
> 
> What does that mean? Open a directory in Library -> "Computer" feature?

Yeah, a directory in the track library box in Mixxx.

**Comment by Swiftb0y** [comment]
> Just in case I'll outline what I did again.

Seems to me (I'm not familiar with debugging on windows) like you did everything correctly, yet the "initializing wait objects" txt does not contain a backtrace of crash.

Controller mappings usually can't crash mixxx by themselves. Can you try to crash mixxx without your controller, just using the GUI and keyboard presses?

**Comment by d1skjokey** [comment]
> Can you try to crash mixxx without your controller, just using the GUI and keyboard presses?

I had already tried this earlier but I tried again and actually yes, I was able to crash it like this with no controller plugged in. On my first try I used a mouse to scroll the tracks and it didn't crash, but this time I tried using the arrow keys and after a while it did. The controller crashes it faster.

I started suspecting if this was the Nvidia graphics card problem mentioned in the troubleshooting wiki, but I tried reinstalling my driver and Mixxx still crashed the same so no luck there.

Well, whatever it is if anyone could help me do the backtrace right that would be great. 
(and those instructions might need some updating)

**Comment by moretocome** [comment]
I have s similar issue with a Numark Mixtrack Platinum controller.

The error message:

>MixxxControl(s) not found - One or more MixxxControls specified in the outputs section of the loaded mapping were invalid. Some LEDs or other feedback may not work correctly.

is shown when opening Mixxx.

The issue seem to have begun after upgrading to Mixxx 2.4.

On 2.3 I never got the error message and saw no issues.

Running Mixxx Linux on a Raspberry Pi 4 and the latest Raspberry OS.

**Comment by moretocome** [comment]
The issue (at least for my part) is not present in 2.3.6.

**Comment by Swiftb0y** [comment]
The crash from interacting with the library and the "MixxxControl(s) not found" message are two different issues. Please open a separate issue for the latter one so we don't get confused. 

@JoergAtGithub can you do me a favor and look into why we have trouble capturing a proper backtrace? I'm not sure what we're doing wrong.

**Comment by d1skjokey** [comment]
Bringing this subject back up, is there anyone who can instruct on doing the backtrace properly to possibly solve this crash?

As @Swiftb0y said I seemed to do it right based on the wiki, so I feel like those instructions should really be updated. I think some kind of walkthrough (with images or video) might also be a helpful foresight for those less involved in this stuff. Should a separate issue be opened for suggesting this?

**Comment by ronso0** [comment]
ping @JoergAtGithub

**Comment by d1skjokey** [comment]
I don't think he's answering.

**Comment by JoergAtGithub** [comment]
Sorry, I'm currently busy with other things. But I will come back to you.

**Comment by ronso0** [comment]
@d1skjokey Until someone double-checks the backtrace instructions, could you please check whether the crash occurs with
* directories on a specific drive (try different built-in disk and removable drives)
* directories outside the music directories specified in Preferences > Library

and: is simply **clicking** on tracks also causing the crash, or just moving the selection with arrow keys?

Maybe that helps narrowing down the issue.

**Comment by d1skjokey** [comment]
@ronso0 Just got around to checking these points.

My computer only has one disk drive, I tried using a USB drive and it crashed all the same. However, 

I looked at the directories in Preferences > Library, which the only one there was "C:/.../Music" wherein the folder with all my tracks in it is located. Just for a test I tried to add the specific folder to the list, though after doing so it still only showed the same "C:/.../Music" without the /_folder_. After this I moved on to test the clicking vs. moving the selection thing and I couldn't get it to crash.

I was confused, because obviously it looked like nothing happened with the directories but the crashing seemed to have stopped. So then I tried adding the folder from the USB drive I mentioned to the directories, which showed up on the list as "D:/_folder_", and that one stopped crashing too.

I'll try and test more thoroughly if the crashing really stopped when I have the time. One thing worth noting is that the screen still stuttered very slightly when I performed any actions, even though the CPU meter was low.

**Comment by Holzhaus** [comment]
> One thing worth noting is that the screen still stuttered very slightly when I performed any actions, even though the CPU meter was low.

I think this is normal. File system access is slow. We batch send groups of 10 rows to the GUI, and wait 20 msecs in between to give the GUI time to redraw, but it can still stutter a bit.

**Comment by d1skjokey** [comment]
I just recently had time to test this more; as I explained earlier, adding the specific folder to the Library directories seems to have stopped it's crashing entirely. Looks like it's working great now.

**Comment by ronso0** [comment]
Okay, thanks for the update.

Nevertheless, the crash must not happen, we still need a backtrace.
@JoergAtGithub Do you mind taking a look whether the backtrace instructions need to be updated or if it's something else?

**Comment by ronso0** [comment]
@d1skjokey Since creating a backtrace doesn't work, let's try to narrow it down with manual testing. May be a bit tedious but doable. Your help is very muh appreciated!

So, to reiterate:
* you had that only music directory `C:/.../Music` set as library directory
* you opened a specific sub-directory in the 'Computer' feature (that with the directory tree)
   * change track selection with arrow keys or with the select knob on your controller
   * Mixxx crashes
* then you added that specific directory to the library dirs (nothing actually changed in the GUI because it's a subdirectory of a an already-listed directory)
*  try track selection again and Mixxx didn't crash anymore



This indicates the crash is related to directories being considered part of your library or not.
To verify, can you try to reproduce the crash with two new directories  **inside** `C:/.../Music` (copies of existing directories will do):
1. add/create the first one "copy1"
   1.1. start Mixxx, **don't** rescan your library (before: make sure "Rescan on startup" is unchecked in the preferences)
   1.2. open the new directory in  'Computer', try to make Mixxx crash
   1.3. note the track you try to select just before Mixxx crashes
2. add/create the second one "copy2"
   2.1. start Mixxx, **rescan** your library
   2.2. open the new directory in  'Computer', try to make Mixxx crash
   2.3. note the track you try to select just before Mixxx crashes

If you can reproduce the crash you may try with yet another directory, this time with tracks that don't contain any Serato tags (because that was mentioned in the last logged lines of the crash log you posted), for example tracks from the test directory https://github.com/mixxxdj/mixxx/tree/main/src/test/id3-test-data

Hopefully these tests make sense and give some more insight.

**Comment by ronso0** [comment]
@d1skjokey Did you find time to do the test I posted?

@JoergAtGithub Do you mind taking a look whether the backtrace instructions need to be updated or if it's something else?

**Comment by JoergAtGithub** [comment]
I just updated the https://github.com/mixxxdj/mixxx/wiki/Creating-Backtraces page. I guess the problem was, that this debugger breaks by default on each system event and never reached the point of interest.

**Comment by ronso0** [comment]
Oh, okay, thank you very much!

@d1skjokey It would be great if you could check the updated backtrace instructions and follow them step by step, then do that test with a folder copy.

**Comment by ywwg** [comment]
If we can't confirm or reproduce this crash I would say we shouldn't block the release on it.

**Comment by JoergAtGithub** [comment]
Let's give the reporter some days of time for response. We just sent out the corrected instructions, on how to collect a backtrace today.

**Comment by d1skjokey** [comment]
Sorry for the delay, I didn't realize it's been a month since @ronso0 asked to do the manual test. Should I still do that, or just the new backtrace? Anyways, I'll try to get it done soon.

**Comment by JoergAtGithub** [comment]
If you could generate a backtrace, this would be the most helpful! Maybe it's enough alone, maybe we need additional information.

**Comment by ronso0** [comment]
@d1skjokey Any news on this?
