### ISSUE TITLE
beat grid changing without pressing the beat grid adjust button?

### ISSUE THREAD

**Issue by m0dB** [mixxxdj/mixxx#11907]
### Bug Description

I have seen the beat grid changing without me pressing the beat grid adjust button (but exactly as if I did).

I have seen this happening three times now but I don't know what I did to trigger this. Maybe anybody else has seen the same or maybe it rings some bells? I would say this has been introduced very recently.

### Version

2.4

### OS

macOS Monterey

**Comment by Swiftb0y** [comment]
Never seen that myself. If it happens semi-regularly, could you try starting mixxx in a debugger, setting a breakpoint in the related code and capturing a backtrace so we have a chance of knowing where spurious signals like this are coming from?

**Comment by daschuer** [comment]
We have three things that may change, the beat, the loops/cues and the waveform. Does anything change with the beats? In the past we had some occurrences of audio decoder offsets, steady or floating offsets. Can this be such an issue? Is one track or track type affected?

**Comment by m0dB** [comment]
No, just the beats. The hot cues and loops stayed unaffected (I remember this, because I used a hot cue to put the beat markers back to their original location). It happened to two different tracks, maybe three, all mp3.

Now, it happened three times in many hours and it hasn't happened since. But I wanted to open the issue just in case anybody else has seen it. @Swiftb0y's suggestion to place a breakpoint is a good idea. In fact, I'll add an assert(false);

**Comment by m0dB** [comment]
I have not seen this happen again so I'm closing this.
