### ISSUE TITLE
macOS: display of played checkbox and lock icon has artifacts

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#11900]
### Bug Description

macOS 13.5.1
Mixxx 2.5-alpha-84-gde4e2cca61 (main)
Qt 6.5.2

Display of played checkbox and lock icon has artifacts. It looks as if there was an additional checkbox behind the UI icon used for Mixxx indicating on | off for the checkbox.

![1](https://github.com/mixxxdj/mixxx/assets/5708172/1bee4510-b58f-48e0-bbed-28a2c20b8805)

### Version

2.5-alpha

### OS

macOS 13.5.1

**Comment by ronso0** [comment]
Looks like a duplicate of #11630
