### ISSUE TITLE
Qt6/Deere: Played checkmark is rendered twice

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#11908]
### Bug Description

![image](https://github.com/mixxxdj/mixxx/assets/1474154/d4de8338-c1c6-4757-a502-baed6689c871)

### Version

main

**Comment by foss-** [comment]
Reported as well https://github.com/mixxxdj/mixxx/issues/11900 and was set to dupe of https://github.com/mixxxdj/mixxx/issues/11630
