### ISSUE TITLE
Waveform combobox looks cluttered 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11915]
### Bug Description

See: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/fafefdf7-18fa-487a-8ca8-04474fdd8952)

There are to many words in braces 

The non accelerated types are IMHO not legacy. 

How is the state of discussion to drop legacy GLSL types? 
Is "deprecated" a better word for the types that will be removed in the next version?

### Version

2.4-beta

**Comment by ronso0** [comment]
We could group the types by (meta)type, and add plain separators, or non-selectable labels (e.g. "Deprecated:", "CPU-accelerated:")

**Comment by Holzhaus** [comment]
Can't we only losz the different waveforms (RGB, HSV, Filtered,...) and determine the proper rendering variant automatically depending on what is available? Most users have no idea what to select anyway.

**Comment by daschuer** [comment]
For me, a minimal 2.4.0 solution is to get rid of the double (..) works:
RGB (GLSL)
RGB 
RGB (legacy GL)
RGB (legacy GLSL)

The grouping idea sounds appealing. I would call CPU "accelerated" though. We may relpace GLSL by accelerated instead.

**Comment by Swiftb0y** [comment]
We're discussing polishing something that will be unnecessary by 2.5 anyways. Lets just keep as is to get the release out. This issue will resolve itself with the removal of the GL and GLSL types soon anyways.

**Comment by Swiftb0y** [comment]
sure...

**Comment by ronso0** [comment]
As noted by others before, there are still way too many choices for beginners, and even advanced users I'd say. 🤪
A '?' hyperlink to a manual chapter with some (basic) explanation may be helpful (like the one for the Cue mode in Pref -> Decks).

Not sure if it's worth the effort for 2.4.x if we drop legacy waveforms in 2.5 anyway.

**Comment by daschuer** [comment]
The mandatory part of this issue is now fixed. Do we want to close this or just remove or change the milestone?

**Comment by ronso0** [comment]
IMO polishing the list can happen anytime, so let's move it to 2.4.1 in case someone wants to take care of it.
(just don't want to dump the ideas I posted)

**Comment by acolombier** [comment]
> RGB (GLSL)
> RGB
> RGB (legacy GL)
> RGB (legacy GLSL)

Are we okay to only display the "best" rendering backend available so we can remove the `(..)` entirely? Perhaps list them all if `--developer` is passed, like for the `VSyncTest`?

**Comment by daschuer** [comment]
Since this affects the user interface it is not a 2.4.1 issue. I will remove the milestone.
