### ISSUE TITLE
cmake error:  Could not find a package configuration file provided by "QT" (requested version 5.12) 

### ISSUE THREAD

**Issue by Zhaojun-Liu** [mixxxdj/mixxx#11916]
### Bug Description

I tried to build the Mixxx with msvc on Windows, it failed with below error, could anyone help look this issue? Thanks.
```
CMake Error at buildenv/mixxx-deps-2.5-x64-windows-705eb0d/scripts/buildsystems/vcpkg.cmake:855 (_find_package):
  Could not find a package configuration file provided by "QT" (requested
  version 5.12) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:2369 (find_package)
```
Repro steps：
1. git clone https://github.com/mixxxdj/mixxx F:\gitP\mixxxdj\mixxx
2. git -C "F:\gitP\mixxxdj\mixxx" reset --hard 50675965e79caa7abdda07107f1d06a719ecbe51
3. Open VS2022 x64 Native Tools command.
4. cd F:\gitP\mixxxdj\mixxx\tools
5. SET PLATFORM=x64
6. SET CONFIGURATION=release
7. windows_buildenv.bat 
8. cd F:\gitP\mixxxdj\mixxx\build
9. cmake -DBULK=OFF -DFFMPEG=OFF -DHSS1394=ON -DLOCALECOMPARE=ON -DMAD=ON -DMEDIAFOUNDATION=ON -DMODPLUG=ON -DWAVPACK=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="" -DDEBUG_ASSERTIONS_FATAL=OFF -DBATTERY=ON -DBROADCAST=ON -DDOWNLOAD_MANUAL=ON -DHID=ON -DKEYFINDER=ON -DLILV=ON -DOPUS=ON -DQTKEYCHAIN=ON -DVINYLCONTROL=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -L .. 

### Version

main branch, and commit is 5067596

### OS

Windows server 2022 21H2

**Comment by Holzhaus** [comment]
You need to pass `-DQT6=ON` when building `main`.

**Comment by Zhaojun-Liu** [comment]
> You need to pass `-DQT6=ON` when building `main`.

Thanks for your quickly reply.  Passing `-DQT6=ON`, it works. Thank you 😃.
