### ISSUE TITLE
Cover art not being displayed 

### ISSUE THREAD

**Issue by GuyMZ** [mixxxdj/mixxx#11928]
### Bug Description

Most of my library of MP3’s has album art, but  this art does not appear in the Mixxx library “Cover Art” column. I have to sort by the Album column, then manually mark the artist entries, right-click the selection, and go through "Metadata>Cover Art>Choose new cover" to add the art manually. Afterward, the art appears in the column and will show up as larger cover art in the lower left corner. 

### Version

2.4 Beta Build 121 (and previous)

### OS

Windows 11 Pro

**Comment by JoergAtGithub** [comment]
Could you please start mixxx with log output by calling `mixxx.exe --developer` from comand line, assign Cover Art to one track as described above, close Mixxx and attach the log output to this issue.

**Comment by ronso0** [comment]
@GuyMZ So the cover arts you expect are images that reside in the directory of the respective track files?
Can you try Mixxx 2.3.6 to clarify whether this is a regression?
