### ISSUE TITLE
Regression: Audio buffer size UI shows `inf ms` on macOS

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#11949]
### Bug Description

Mixxx reports bogus audio latencies with the Core Audio backend (though it still seems to work fine):

![image](https://github.com/mixxxdj/mixxx/assets/30873659/7899dad0-1345-451a-ae16-8e3b5a162dd8)

According to my regression finder, this was introduced between 8d0ded74be (good) and e4f2e050db (bad), see [this diff](https://github.com/mixxxdj/mixxx/compare/8d0ded74be240f1249500b8b9484c00031e22f3e...e4f2e050dbf793fb195902328413ced50d1a46aa). Looking at the commits it seems as if it was introduced by
- #11904

cc @Holzhaus 

### Version

2.5-alpha-98-gf4692aa5ea (Qt 6.5.2)

### OS

macOS 13.5

**Comment by Holzhaus** [comment]
I'm currently traveling but I'll try to have a look tomorrow.
