### ISSUE TITLE
add a link to the camelot wheel in the interface

### ISSUE THREAD

**Issue by macrophone** [mixxxdj/mixxx#11950]
### Feature Description

I've started to work more with the camelot wheel, and I have now a picture in a folder that I open when I prepare my sets. 
It would be useful to have a button (at the top?) in the interface that can open a picture of the camelot wheel.

As a workaround, I'm planning to create an empty track and insert the camelot picture as a cover art.

**Comment by macrophone** [comment]
sorry, same as #1695

**Comment by ronso0** [comment]
FYI (not sure you noticed): #1695 is the implementation of what you requested, not another feature request.

**Comment by macrophone** [comment]
Ok great! That's for 2,4, right ?

**Comment by ronso0** [comment]
I'm not sure. You'll find it in the View menu, and the action has a hotkey IIRC
