### ISSUE TITLE
Auto DJ Icon not consistent

### ISSUE THREAD

**Issue by AlrightHector** [mixxxdj/mixxx#11954]
### Bug Description

In MIXXX 2.3.5 the Auto DJ icon that indicates if it is running is not consistent in both places. There is one at the top of the screen and one at under the Decks. If a keyboard shortcut is used to activate and deactivate Auto DJ, the Icon under the Decks isn't refreshing unless the display is refreshed (ie the cursor is moved over that section of the screen). This can lead to confusion as to whether or not Auto DJ is running. This issue does not occur in MIXXX 2.3.3
<img width="1256" alt="Screenshot 2023-09-10 at 17 34 39" src="https://github.com/mixxxdj/mixxx/assets/144615550/25806969-a03c-447f-ace6-bdfba07856b7">

### Version

2.3.5

### OS

Mac OS 10.14.6

**Comment by ronso0** [comment]
Thank you for this report.
Please try current stable version 2.3.6 and let us know if the issue persists.

**Comment by AlrightHector** [comment]
The issue is still there in 2.3.6. The icon in to top centre responds to the Keyboard command to activate/deactivate and shows the correct state but the icon below the decks only responds when pressed using the mouse.

**Comment by ronso0** [comment]
Alright, thanks, I'll take a look.
For reference: I fixed a similiar issue in #11495, maybe it's related.

**Comment by ronso0** [comment]
I tested with 2.4 (there won't be another 2.3 bugfix release) and indeed the GUI update is broken somehow:
* on first keyboard trigger (Off -> On) (`[AutoDJ],enable`) both the button on 'Auto DJ' feature and the indicator in the toolbar are turned on
* turning off also updates the GUI correctly
* 2nd On trigger however does not reliably turn on the GUI button & indicator

I'll investigate what's wrong.

**Comment by ronso0** [comment]
I added debug output at relevant points in the signal chain CO change request -> GUI update and I can't reproduce aynmore :shrug: 

Note that this is not the first time I notice that adding debug output to affects signal/slot timing or other mechanisms that were appearantly unreliable beforehand.

**Comment by daschuer** [comment]
I cannot reproduce the issue with Ubuntu Focal and the latest 2.4-beta. 
@AlrightHector Does this issue still occur on MacOS?

**Comment by AlrightHector** [comment]
The issue seems to be resolved in the 2.4 Beta.

**Comment by daschuer** [comment]
Thank you for confirming. Please reopen the issue if it ever happens again.
