### ISSUE TITLE
UI Regression: Inconsistent spacing in focused sidebar items

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#11957]
### Bug Description

Just a tiny thing I've noticed, focusing a sidebar item adds some padding that disappears once the item loses focus:

### Expected 

https://github.com/mixxxdj/mixxx/assets/30873659/71000925-794f-4a83-9c66-7b6ae2822414

### Current

https://github.com/mixxxdj/mixxx/assets/30873659/38179552-0fdd-4f9a-86cd-4c210cf191be

According to my regression finder, this was introduced between 393ddc4f21bcef6d2cf99789bc8eb8adb5948762 (last good) and 7f79194df0a53987816b4e47e34067e3eb12361d (first bad), i.e. [in this diff](https://github.com/mixxxdj/mixxx/compare/393ddc4f21bcef6d2cf99789bc8eb8adb5948762...7f79194df0a53987816b4e47e34067e3eb12361d).

cc @ronso0 

### Version

2.5-alpha-98-gf4692aa5ea (Qt 6.5.2)

### OS

macOS 13.5

**Comment by ronso0** [comment]
Are both videos recorded with Qt6 builds?
Can you reproduce with Qt5? (I can't, using Ubuntu 20.04)

**Comment by fwcd** [comment]
I can reproduce this with Qt 5.12.5 on the most recent `main` branch too.

**Comment by ronso0** [comment]
I can't reproduce on `main` either, I assume it's some `margin: 0px;` missing :man_shrugging: 
I'll post a test PR soonish.

**Comment by ronso0** [comment]
Or you try adding
```
margin: 0px;
padding: 0px;
```
yourself here https://github.com/mixxxdj/mixxx/blob/03d0ce7e06915084b649bc95b36cf6b5f1a365fe/res/skins/LateNight/style_palemoon.qss#L2559-L2566

Please check whether it still looks as expected when  increasing the library row height in Pref > Interface.

**Comment by fwcd** [comment]
Unfortunately, neither the QSS patch nor the library row height seem to affect this.

**Comment by fwcd** [comment]
Did a more fine-grained bisect and found that b576824ef4313486ec19b85055a5445c4d013a20 introduced the regression.

**Comment by fwcd** [comment]
Removing `border: 0px;` from `WLibrarySidebar::item:selected:focus` fixes it.
