### ISSUE TITLE
No Filename in Taglib Error Message 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#11964]
### Bug Description

During debugging of https://github.com/mixxxdj/mixxx/issues/11131 this error hides the real issue of the Windows API I guess. 

### Version

2.4-beta

### OS

Windows 10 (Vbox)

**Comment by Swiftb0y** [comment]
I don't understand the bug here. What taglib error message?

**Comment by daschuer** [comment]
This is the message: 
`warning [Thread (pooled)] TagLib - Cannot read audio properties from inaccessible/unreadable/invalid file:`
The bug is that there is nothing after the colon.

**Comment by Swiftb0y** [comment]
Thank you. I was missing a reference to the line in the code.

**Comment by Swiftb0y** [comment]
fixed by #11965
