### ISSUE TITLE
mixxx 2.4 skin problem

### ISSUE THREAD

**Issue by xtuki** [mixxxdj/mixxx#11986]
### Bug Description

when i tried to put the area of the beat visualisation bigger i ended up having the skin still showing the way it was and at the same time also the bigger visualisation and the mixer and library beeing moved down. weird image.
update: in the time i wrote this it fixed itself... meaning it's probably some issue of my macbook being too slow.
by the way i had problems with the responsivity in version 2.3.6 which were resolved by updating to 2.4.! great work!!
keep on going!!!

### Version

2.4

### OS

macos 10.13.6

**Comment by ronso0** [comment]
So you had redraw issues with the waveform section with Mixxx 2.3.6 which are now gone?

**Comment by xtuki** [comment]
Sent: Friday, September 15, 2023 at 5:49 PM
