### ISSUE TITLE
the GUI crashes and/or slows down when the music is playing

### ISSUE THREAD

**Issue by matheus011sp** [mixxxdj/mixxx#11997]
### Bug Description

This is happening with macbooks from 2015 and earlier, I tested it on mine and my friend's (2012 macbook) and whenever we are playing with or without midi devices connected, the graphical interface simply freezes or slows down and we are unable to perform any command within of the application, not even being able to pause the music, when we disable the waveforms there is a reasonable improvement but the problem still happens again, I think it could be something related to the processors' integrated video driver, I think I could find a better graphics engine lightweight or more optimized for the app.

my setup:

macbook pro 13 inch 2015
intel core i5 2,7 ghz - dual core
8gb ram ddr3
Intel Iris Graphics 6100 1536 MB

### Version

2.3.5

### OS

macOS Monterey 12.6.5

**Comment by ronso0** [comment]
This is probably a known issue, fixed in Mixxx 2.4 (beta)
https://mixxx.org/download/#beta

**Comment by matheus011sp** [comment]
thank u!!!!

**Comment by ronso0** [comment]
Great, so I'll close this. Probably dulicate of #11450 and others
