### ISSUE TITLE
Undocumented applocal in .msi installer (ANGLE DLLs)

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#11992]
### Bug Description

I noticed, that the `applocal` introduced in #11935 is not as hidden as intended. It became an optional installation component in the .msi installer, which the end user can deselect.
Therefore should give it a meaningful name/description like ANGLE OpenGL fallback driver. That the user understands, what he can select/deselect.

### Version

2.4.0

### OS

Windows

**Comment by daschuer** [comment]
So it means `set(CPACK_COMPONENT_applocal_HIDDEN TRUE)` is broken? 
The idea was to have this installed by default because the user will have only a little chance to know forehead if it is required or not.
