### ISSUE TITLE
Shader Waveforms have filled lead in/out 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#12015]
### Bug Description

Normally we have only the outlines of the triangles. With the GLSL types the triangles are filled. Not a real bug, but maybe it hides another issue: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/4631f0a6-c13e-4c19-b691-05f0752a9be6)
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/12d7783d-f7c0-41ae-ad6f-e904ac6924d4)

### Version

2.4-alpha

### OS

Ubuntu

**Comment by daschuer** [comment]
@m0dB do you have an idea why this is the case?

**Comment by JoergAtGithub** [comment]
This is an intended visual improvement. We discussed this in the PR review and decided to keep it this way.

**Comment by m0dB** [comment]
To be fair, initially it was laziness, as drawing a filled triangle is much simpler than drawing only the outline. But I found I actually liked it much better, visually, so I kept it like this.

So, to put your mind at ease, @daschuer , it doesn't hide another issue.

**Comment by daschuer** [comment]
Ok thank you for confirm.

**Comment by Holzhaus** [comment]
IMHO waveforms should be consistent, so I'd like to keep this open until the other renders are adapted or the fill is removed.

**Comment by m0dB** [comment]
Since @Holzhaus insisted, but also because I thought of an approach that is much nicer implementation-wise (a single triangle drawn into an texture which is then repeated pattern-wise in the shader instead of in c++), I have fixed this is https://github.com/mixxxdj/mixxx/pull/12100

**Comment by m0dB** [comment]
<img width="340" alt="Screenshot 2023-10-13 at 17 27 28" src="https://github.com/mixxxdj/mixxx/assets/79429057/304334ce-5bc9-4a99-a51c-96e85aec80f9">

**Comment by m0dB** [comment]
@Holzhaus after some discussion, I went with a slightly different look then legacy, using a semi-transparent fill. So, not 100% "consistent" as you requested, but given the 50% transparency of the fill, and 100% match of the outline, I would say at least 50% consistent ;-)

Check out the PR for some screenshots.
