### ISSUE TITLE
Load playlist file into autoDJ or crate from command line

### ISSUE THREAD

**Issue by gNovp** [mixxxdj/mixxx#12039]
### Feature Description

I've seen this feature mentionned in an old request, but it would be great to just give a .m3u (or other) in the command to start Mixxx to autoload all the contents of the playlist file to the AutoDJ (or import the playlist to Mixxx).

Combined with some new command line switches, this would allow again for very simple automation of Mixxx...

**Comment by ronso0** [comment]
This is a duplicate of #11178

There is WIP here #11211 (stale) and @QtKaii picked it up here #11618

Re "some new command line switches", please file separate feature requests to simplify brainstorming and tracking PRs.
Thank you!
