### ISSUE TITLE
RTE when engine.setValue("[Library]", "MoveVertical", delta) is called during startup

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12065]
### Bug Description

The line `engine.setValue("[Library]", "MoveVertical", delta);` in my Traktor Z2 mapping results in a runtime exception in recent versions of Mixxx 2.4 - the unmodified mapping worked some time ago:
![MixxxStartUpExecption](https://github.com/mixxxdj/mixxx/assets/64457745/ca626933-8e4b-4187-829a-7f0c3a4913d4)
The same issue was also reported here from a Ubuntu user: https://github.com/mixxxdj/mixxx/pull/3038#issuecomment-1712587674

Reloading the mapping after startup does not result in the RTE

### Version

2.4.0

### OS

Windows 11 & Ubuntu

**Comment by JoergAtGithub** [comment]
This is a regression introduced by:
https://github.com/mixxxdj/mixxx/commit/19a1bdc8639c7bf2dd5d2019bcbe925949e29d55
Reverting this change prevents the RTE.

**Comment by ronso0** [comment]
Could you please share a link to your Z2 script?

**Comment by JoergAtGithub** [comment]
It's this line, which triggers the RTE, if I comment it out, Mixxx starts up without RTE:
https://github.com/mixxxdj/mixxx/blob/34662d1aad43a0d002dfad0dc543fcf21e8b2a1a/res/controllers/Traktor-Kontrol-Z2-hid-scripts.js#L1036

**Comment by JoergAtGithub** [comment]
The RTE happens always, without touching the knob. The value of the knob encoder is read during initialisation, this triggers an event. I will clean up this in the mapping as well.
