### ISSUE TITLE
MIDI Learning Wizard allow modifier (shift) keys

### ISSUE THREAD

**Issue by FrancescSunol** [mixxxdj/mixxx#12068]
### Feature Description

I have a feature request that would be very much appreciatted for those users who want to map a controller but don’t know javascript.

The MIDI learning wizard it’s excellent to map faders, buttons knobs etc to Mixxx functions, but currently you can’t map modifier (shift) keys and platter rotations.

There are controllers that even have "supershift" modifiers (those accessed by pressing two modifiers + a midi key/control)

It would be great to be able to map those functions using the MIDI learning wizzard in Mixxx.

**Comment by ronso0** [comment]
I'll close this as duplicate since both aspects are already tracked.
Please comment if you think some significant detail is not covered by the issues linked below.

Jog wheel learning:
#7584

Learning shift combos:
#10179
