### ISSUE TITLE
a single table cell is drawn as selected when selecting a previous search query

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12064]
Noticed this a few times while testing #12063 (no changes to tracks table or search box, just searchqueryparser).

Can not reproduce but this is what I did IIRC
* type a query, hit Return to save it
* go to tracks table, select tracks, change selection, edit tags etc.
* clear search
* select a previous query
* the top-left table cell is drawn like if it was selected (coloured background)
* switching to the tracks table selects the entire row with the previously 'selected' cell being focused (white border)

This shouldn't be possible since we `setSelectionBehavior(QAbstractItemView::SelectRows);` in WLibraryTableView.
My Qt version didn't change either (still on 5.12.8) :man_shrugging:

**Comment by ronso0** [comment]
Could reproduce it:
* start Mixxx
* go to searchbox, type `played:N` (adjust N to get some results), don't hit Enter to not jump to the tracks table
* wait for the debounce timer to expire, search results are displayed
* change query to `played:=N`, wait
* top-left cell is selected

Probably a regression from 400bb8f1af93010e7e15dd6bee035b8170dcdb01/a381d33f4ad246077bf216fed320b0d6c4400643

**Comment by Holzhaus** [comment]
Maybe we need to reset the selection Model.
