### ISSUE TITLE
Mixxx 2.4.0-beta: BPM not displayed for FLAC/MP3 files in library

### ISSUE THREAD

**Issue by deejaygirl** [mixxxdj/mixxx#12077]
### Bug Description

The BPM column of the library is not filled in when using FLAC files.

![afbeelding](https://github.com/mixxxdj/mixxx/assets/147284581/a7aa44af-c761-40cc-a494-a382e6164a11)

Also no BPM for MP3 files.

![afbeelding](https://github.com/mixxxdj/mixxx/assets/147284581/56feba53-677b-4570-bbc8-eda310673bb0)

### Version

Mixxx 2.4.0-beta

### OS

Windows 10

**Comment by ronso0** [comment]
Did you analyze your library?
Is this a screenshot of the Tracks view or some directory in the Computer view?

**Comment by deejaygirl** [comment]
A  directory in the Computer view

**Comment by ronso0** [comment]
Please read the manual first.
This https://manual.mixxx.org/2.3/en/chapters/getting_started#importing-your-audio-files, and the Analyze chapter below.
> Mixxx automatically analyzes tracks the first time you load them in a deck. This allows you to run beatgrid, key, and ReplayGain detection on tracks in advance. It also prepares the waveform overviews, detects file corruption, and calculates the BPM values.

**Comment by deejaygirl** [comment]
OK I u,nderstand
