### ISSUE TITLE
Mixxx 2.4.0-beta: hotcues 3 and 4 not displayed correctly (HiDPI / Retina scaling to 175 %)

### ISSUE THREAD

**Issue by deejaygirl** [mixxxdj/mixxx#12083]
### Bug Description

See screenshot. For some reason hotcues 3 and 4 are not displayed correctly. Also hotcue 8 seems to not fully drawn at the right.

1. Set HiDPI / Retina scaling to 175 %
2. Restart Mixxx
3. When you go to skin settings and disable/enable "hotcues" (8), it looks like this

![afbeelding](https://github.com/mixxxdj/mixxx/assets/147284581/f39a7e57-f7f8-4715-8a14-b80cbf975444)

### Version

Mixxx 2.4.0-beta

### OS

Windows 10

**Comment by deejaygirl** [comment]
It seems to work fine when HiDPI / Retina scaling is set to 100 %. So it has something to do with HiDPI / Retina scaling I think.

**Comment by ronso0** [comment]
I assume with 175% the skin simply doesn't fit your screen.
Do you see a warning icon in Preferences> Interface?

If no:
Do you have the skin settings open? If yes, this menu is not supposed to remain open permanently to avoid exactly the squeezed GUI you see.

**Comment by deejaygirl** [comment]
> If no:
> Do you have the skin settings open? If yes, this menu is not supposed to remain open permanently to avoid exactly the squeezed GUI you see.

Yes, I was testing but didn't know you have to close the settings again.
It's working fine now when settings is closed!
