### ISSUE TITLE
feature request: wavpack support

### ISSUE THREAD

**Issue by deejay-girl** [mixxxdj/mixxx#12090]
### Feature Description

Hi

I would like to request wavpack support. It's open source and cross platform so it fits mixxx I think.

https://www.wavpack.com/

**Comment by daschuer** [comment]
Mixxx already has wavpack support.
Maybe it is not enabled or broken with your build?
Which OS do you use? What happen if you try to load a WV file? It there anything suspicious in the mixxx.log?

**Comment by deejay-girl** [comment]
I made this feature request because I saw wavpack is not in the manual. It works fine but I didn't expect it to be supported if it's not in the manual.

https://manual.mixxx.org/2.3/en/chapters/library#compatible-file-formats

See this issue please

https://github.com/mixxxdj/mixxx/issues/12092
