### ISSUE TITLE
feature request: remove all hotcues

### ISSUE THREAD

**Issue by deejay-girl** [mixxxdj/mixxx#12096]
### Feature Description

**Problem:**
If you want to start all over with adding hotcues (and you don't need any hotcue anymore), it would be very handy to have a button (or other widget?) to clear ALL hotcues of a track.
Currently you need to right click them all and click the recycle bin button to do this.

**Solution:**
Not sure if this is the right place for the button, but I think it's usable.
What about adding a button "delete all hotcues" in the right click window that appears when right clicking a hotcue in either the hotcue button/waveform hotcue? It should ask "Do you really want to delete all hotcues from this track?"

![afbeelding](https://github.com/mixxxdj/mixxx/assets/147563220/12e0b1de-5214-41d4-99c7-83717a9fba69)

**Comment by deejay-girl** [comment]
I close this issue because it's already possible by using right click menu in the library.

**Comment by ronso0** [comment]
This menu is also available via right click on any track (text) label, though it's not documented in the manual, yet.

Do you want to add it?
Instructions how to contribute to the manual are on the main page:
* edit via Github GUI https://github.com/mixxxdj/manual/tree/2.3#editing-the-manual-using-git-recommended
* edit via command line (recommended) https://github.com/mixxxdj/manual/tree/2.3#editing-the-manual-using-git-recommended

**Comment by deejay-girl** [comment]
Sorry I don't understand anything about it :(
But i now have an account on transifex to translate!
Please see my question on the forum about it
