### ISSUE TITLE
Waveform preview images in Preferences > Waveforms?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12113]
### Feature Description

Just to take the hassle of selecting and then closing the preferences, opening preferences again, and repeating to try all the waveform styles.

**Comment by ronso0** [comment]
What hazzle?
Select a waveform typ: instantly applied
Select an overview type: 'instantly' applied (skin is reloaded which takes a few seconds)
You don't even need to click apply (which is a UX inconsistency in Preferences, one amongst many).
Just position the Preferences so you can see the waveforms.

Doesn't this work on your machine?

**Comment by deejay-girl** [comment]
I think the user didn't realize the setting is applied immediately.
I can confirm it work on Windows (2.4 Beta).

**Comment by mxmilkiib** [comment]
It does change instantly, I didn't realise that was the case as I hadn't a track loaded at that point!

Not knowing this implicit knowledge (without reading the manual) tripped me up!

While not the most ideal UX, I'm going to close this issue because there are far greater problems to deal with.

**Comment by mxmilkiib** [comment]
#12226 issue ref re related bug
