### ISSUE TITLE
Remember the state of the "Large VU meter" setting?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12125]
### Feature Description

It resets to the defauly small on restarting the app.

Edit: not related to issue 10122

**Comment by ronso0** [comment]
Deere skin I assume, which Mixxx version is it?

#10122 is unrelated (xfader reset was by design)

**Comment by ronso0** [comment]
Confirmed.
Reason was the missing 'persist' flag. I pushed the fix directly to 2.4, and merged 2.4 into main (2.5-alpha currently).
