### ISSUE TITLE
Show track suggestions based on BPM, key and other metadata.

### ISSUE THREAD

**Issue by nk22** [mixxxdj/mixxx#12198]
### Feature Description

Similar to the "related tracks" feature in rekordbox, it would be great to have a menu showing suggestions for which tracks to play next during a live DJ set

**Comment by ronso0** [comment]
Duplicate of #6106 I'd say?

FWIW in Mixxx 2.4 there is the "Search related Tracks" submenu in the track context menu. It has actions to trigger certain search queries.

And there is #10860 (WIP, stale) which parses last.fm for track suggestions and displays them in a track table.

**Comment by nk22** [comment]
Yea, I agree that this is a duplicate of 6106. Let's continue there.
