### ISSUE TITLE
SOS!!! - EQ doesn't work! 

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#12196]
### Bug Description

With the 2.4 Beta the Deck EQ doesn't not work. Can anyone repair that fix until today evening or help me what to do?

### Version

2.4 beta 195

### OS

Linux Mint 21.2 Cinnamon

**Comment by stefan-franz** [comment]
Filter is working. But not the 3 band EQ

**Comment by stefan-franz** [comment]
![EQ setting](https://github.com/mixxxdj/mixxx/assets/96744684/4e77ede7-b54a-41c7-8c57-4fa0f6145e5b)

Found the solution in the EQ settings. The hook was checked in the Option "Equalizer Effektverarbeitung umgehen". 
I think somewhere a bug in the default settings. 

My set works now.

**Comment by ronso0** [comment]
already fixed https://github.com/mixxxdj/mixxx/commit/e39db38375e4be6372dffd6c09ab0be7fd05daf0
