### ISSUE TITLE
Unknown control ([EffectRack1], num_effectunits)

### ISSUE THREAD

**Issue by gqzomer** [mixxxdj/mixxx#12204]
### Bug Description

I'm currently working on a mapping for the reloop mixage controller series together with @HorstBaerbel. He previously made a pull request  for version 2.3 #10892. I started work on refactoring the mapping to include the new features of the upcoming 2.4 release. However I ran into a problem when trying to get the number of effect units for `[EffectRack1]`

In my mapping I enable the `show_focus` parameter in the init function for each effect unit in `[EffectRack1]`.
To accomplish this I call `engine.setValue("[EffectRack1_EffectUnit"+effectUnit+"]", "show_focus", 1);` in a for loop where I use the `engine.getValue("[EffectRack1]", "num_effectunits");` to loop over the available effect units.

In mixxx 2.3.7 the `engine.getValue("[EffectRack1]", "num_effectunits");`  returns 4
The same call returns 0 in a local built of the 2.4 branch, it shows the following error in the log
```
warning [Controller] ControlDoublePrivate::getControl returning NULL for ( "[EffectRack1]" , "num_effectunits" )
controller.reloopmixageiemidi1:warning [Controller] "Unknown control ([EffectRack1], num_effectunits) returning 0.0"
```

Was the `num_effectunits` control removed or somehow changed in the 2.4 release? It should still be available according to the [documentation](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1]-num_effectunits)

### Version

2.4-beta-197-ga19cae2545

### OS

Fedora 38

**Comment by ronso0** [comment]
Indeed, it was removed by #4467 (#2618). It's a constant now: 4.
Someone needs to update the controls documentation, see https://github.com/mixxxdj/manual/issues/501
Do you think you could do that? Simply removing `num_effectunits` would be a good start.

**Comment by gqzomer** [comment]
Thanks for the quick response.
I might look into updating the documentation once we've finished work on the mapping.
