### ISSUE TITLE
Download page provides as Windows 2.4 beta only outdated/broken version 193

### ISSUE THREAD

**Issue by Abdull** [mixxxdj/mixxx#12245]
### Bug Description

I just downloaded the `2.4-beta-193-gbc776e07a9` release from https://mixxx.org/download/#beta and ran into issue #12196.

**Additionally to the problem of EQs/equalizers not changing the sound, I noticed that the crossfader incorrectly is inverted in version `193`: only when activating the "Reverse crossfader (Hamster Style)" option (Preferences > Mixer > Crossfader Curve) will the fader *not* be inverted.**

In that issue, the solution is to update to a higher release; but as per https://downloads.mixxx.org/snapshots/2.4/ , for Windows, `193` is the most recent version.

Whereas, according to https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas , Ubuntu already is at `206`.

Could you provide up-to-date beta releases for Windows? This will help in beta testing on Windows, and avoid reporting bugs that have already been fixed.

As always, thank you very much for making Mixxx even more awesome.

### Version

2.4 beta

### OS

Windows 10

**Comment by Holzhaus** [comment]
> Could you provide up-to-date beta releases for Windows? This will help in beta testing on Windows, and avoid reporting bugs that have already been fixed.

Sorry, we currently have issues with expired code signing certificates on macOS and Windows. Werl are working on fixing them, but we cannot give an ETA.

**Comment by Abdull** [comment]
Until a more recent 2.4 beta is available for Windows, maybe it makes sense to replace the `193` download link with an earlier Windows 2.4 beta version (`< 2.4-beta-193`) which does not have these issues?

I don't know if the flipped/inverted crossfader and EQ checkbox logic is/was only affecting upgrading users (i.e. users with existing Mixxx configuration settings) or affecting all users including new users; but either way **IMHO it is better to provide as the Windows beta download link an older working beta release rather than this broken `193` version (which anyways is outdated compared to other platforms' installers).**

The problem is that users (both new/onboarding as well as experienced) which got motivated to beta-test will be testing a broken version.
They will get a totally wrong, outdated image of Mixxx' great software quality, and may incorrectly think that such bugs and UX are considered normal and deemed as a minor issue (quote: "_To our knowledege all major issues should be fixed in the latest Beta snapshots_"). When they do take the effort of reporting an issue, there is a likelihood that this issue is already fixed, in that case having wasted their (and the maintainers') time - see #12196 as an example.

Such an experience likely makes beta testers (which the Mixxx project spends effort on acquiring) jump off beta testing.

E.g. https://mixxx.discourse.group/ keeps on motivating to beta test: 
> Reminder to test the Mixxx 2.4 Beta snapshots
>
> We are coming closer to the Mixxx 2.4 release. To our knowledege all major issues should be fixed in the latest Beta snapshots, but there might be issues that do only appear with particular platforms or hardware setups. To get aware of such issues, we need you to test the Beta snapshots in advance of the release.

![image](https://github.com/mixxxdj/mixxx/assets/529862/19e97499-73b7-423d-854f-c85febff2bc2)

Further beta testing CTAs:
* https://mixxx.org/download/ 
  > Beta Snapshots (2.4)
  > A great way to contribute to Mixxx is testing the upcoming version before it is being released. The Mixxx team relies on a significant number of users switching to the beta version and using it at home.
* https://github.com/mixxxdj/mixxx/wiki#community-resources 
  > Please help us test the latest code and report bugs. We try to make sure code is reasonably stable before including it in these, but only use development builds if you are comfortable using bleeding edge software.
* https://mixxx.org/news/2023-05-31-mixxx-2-4-beta-released/ 
  > In order to get 2.4 stable, we need lots of people testing this beta release, the more, the better. Please download it and report any bugs you find on our bugtracker.

I for example noticed that (at least on my Windows installation) Mixxx beta-2.4's waveforms are moving in a pixelated, flickering way (aliasing during subpixel animations); c.f. to older 2.3 where it looks smooth/anti-aliased/good. **But it doesn't make sense to report this issue, as it may have disappeared in a more recent beta release not available to Windows.**

So maybe it further makes sense to give add a disclaimer next to the Windows 2.4-beta installer download link, which notes that this is an outdated version containing issues no longer present in more recent versions not available to the Windows platform.

I'm happy to help out with fixing the code signing issue; would a donation help, e.g. for contributing to the costs of new code signing certificates? I donated to Mixxx in the past, but right now I cannot find information about how to donate on the Mixxx website.

**Comment by Abdull** [comment]
*This* issue got resolved in the meantime. E.g. the current (as of this writing) [`mixxx-2.4-beta-475-g1709873314-win64.msi` installer](https://downloads.mixxx.org/snapshots/2.4/mixxx-2.4-beta-475-g1709873314-win64.msi) ([build log](https://github.com/mixxxdj/mixxx/actions/runs/7913161076/job/21600240656) ) is up to date (*Thu 15 February 2024 08:51*) and is signed with a valid certificate (serial number `3300004bf0e4f0286a365617a7000000004bf0`) from Mixxx's @daschuer .

Windows 10 installs this signed installer smoothly without certificate warnings.

Thanks to the Mixxx team!
