### ISSUE TITLE
SSL certificate expired for dependencies archive when running setup script on macOS

### ISSUE THREAD

**Issue by tonell-m** [mixxxdj/mixxx#12276]
### Bug Description

Hi everyone!

I tried setting up mixxx locally on my mac to start contributing but when running the macos setup script I'm getting an expired SSL certificate error from curl (see stacktrace)

```
Build environment mixxx-deps-2.4-x64-osx-min1012-0309294 not found in mixxx repository, downloading it...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
shasum: /Users/{user_name}/Dev/mixxx/buildenv/mixxx-deps-2.4-x64-osx-min1012-0309294.zip: No such file or directory
ERROR: Download did not match expected SHA256 checksum!
Expected 3f2174fa7945bb42759c8678efe9e45e447db4609e57d174a1bbfeee20371547
Got
```
Manually adding the `-k` solved the issue but it's not really straightforward for newcomers. I would be glad to help resolve this if I can but I'm not entirely sure how 🙁 

I'm using zsh as shell but I don't think it has anything to do with it, I tried this on both `main` and `2.4` branches.

### Version

2.4.0

### OS

macOS Monterey 12.6.7

**Comment by Holzhaus** [comment]
I cannot reproduce this. The SSL certificate is valid and expires on Jan 09, 2024.

**Comment by tonell-m** [comment]
Hi, I've dug deeper into this after seeing your comment, and it turns out the issue was on my side, my bad!

I've fixed my issue following the steps listed in [this thread](https://stackoverflow.com/questions/69521959/ssl-certificate-problem-certificate-has-expire-in-macos) if anyone also faces this problem 🙂

**Comment by tonell-m** [comment]
Hi, I've dug deeper into this after seeing your comment, and it turns out the issue was on my side, my bad!

I've fixed my issue following the steps listed in [this thread](https://stackoverflow.com/questions/69521959/ssl-certificate-problem-certificate-has-expire-in-macos) if anyone also faces this problem 🙂
