### ISSUE TITLE
CROSSFADER AUTOMATIC RESET

### ISSUE THREAD

**Issue by tlibra10** [mixxxdj/mixxx#12270]
### Bug Description

I have mentioned this before a long time ago.
I am currently using version 2.3.2 because it’s the one with the auto crossfader reset when the auto DJ is deactivated. That has been removed form any other releases that followed. Maybe This could be re-enstated then I could use newer releases. And if it stays there I can keep Up with new releases.
It is such a handy system to have.
Thank You.

**Comment by Holzhaus** [comment]
This isn't a bug, it's a feature request.

**Comment by tlibra10** [comment]
Oh Sorry I didn't know who I where I was supposed to send this message to.

**Comment by ronso0** [comment]
Duplicate. https://github.com/mixxxdj/mixxx/issues/11571

Please stop posting the same request on the forum and here over and over again.
