### ISSUE TITLE
Database Re-Scan after moving tracks doesn't work - still a problem

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#12275]
### Bug Description

I have 2 path: 
The title is since about 1 Week not in the /Music/Audacity directory - but Mixxx doesn't clean the database. 

![Mixxx don't clean the database](https://github.com/mixxxdj/mixxx/assets/96744684/aec64b5f-90e7-4208-a7d3-bdc9b4c1cf8d)

### Version

2.4 beta 216

### OS

Linux Mint 21.2 Cinnamon

**Comment by ronso0** [comment]
Could you please create a log file of a rescan? Hopefully this provides more insights.
* start Mixxx
* rescan
* close Mixxx

**Comment by stefan-franz** [comment]
Enjoy my logfile
[mixxx.log](https://github.com/mixxxdj/mixxx/files/13297253/mixxx.log)

**Comment by ronso0** [comment]
Is it correct that `/Music/Audacity ` is not one of your library directories (Preferences > Library)?

If yes, IIUC the scanner does only scan those directory for changed files and doesn't consider other tracks you added manually (via drag'n'drop or via Computer feature) even though they are technically in your library.

**Comment by stefan-franz** [comment]
No. Its the 2nd main library folder. But you wrote Music with c - and in german its shown so: - /home/stefan/Musik/Audacity
![Library](https://github.com/mixxxdj/mixxx/assets/96744684/5a05efe7-4cb0-428d-904c-1fc933e461c3)

**Comment by ronso0** [comment]
Alright, so the scanner somehow missed that file and now thinks the directory didn't change. That's a bug.
so the bottom line is what Uwe wrote here https://github.com/mixxxdj/mixxx/issues/12239#issuecomment-1785739145
I guess we can close this one since it's a dupe.
