### ISSUE TITLE
The problem with setting dec.

### ISSUE THREAD

**Issue by UserMen14** [mixxxdj/mixxx#12287]
### Bug Description

Linux OS Ubuntu Studio 22.04.4 LTS

Mixxx 2.5.0-alpha
2.5-alpha-82-gffc617f4f3 (main)
5.15.3

Also, the problem with the decks is not eliminated. When I remove the checkmark, it increases the speed. After the restart, the checkbox stands again.

### Version

2.5.0-alpha

### OS

Ubuntu Studio 22.04.4 LTS

**Comment by ronso0** [comment]
Thanks for your report.
Please be more specific: which checkbox do you refer to?
If it works in 2.4 it may just be a matter of merging the 2.4 branch into main (2.5).

**Comment by UserMen14** [comment]
> Thanks for your report.
> Please be more specific: which checkbox do you refer to?
> If it works in 2.4 it may just be a matter of merging the 2.4 branch into main (2.5).

![Снимок экрана_2023-11-12_11-34-53](https://github.com/mixxxdj/mixxx/assets/132085696/e1d33273-431d-4d64-b1b5-a4feaaa39113)

**Comment by daschuer** [comment]
I cannot confirm this with the latest main on Ubuntu Focal. 
Such Issue happens when Mixxx is crashing unnoticeable during shutting down. 
Please start Mixxx, change the preferences option and close it. Than attache you ~/.mixxx/mixxx.log here. 
Maybe it reveals something.

**Comment by UserMen14** [comment]
> Thanks for your report.
> Please be more specific: which checkbox do you refer to?
> If it works in 2.4 it may just be a matter of merging the 2.4 branch into main (2.5).

![Снимок экрана_2023-11-12_11-34-53](https://github.com/mixxxdj/mixxx/assets/132085696/e1d33273-431d-4d64-b1b5-a4feaaa39113)

**Comment by ronso0** [comment]
@UserMen14 Any more info? Issue resolved?
