### ISSUE TITLE
Precompiled heades (PCH) should be opt-in and not opt-out

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#12316]
### Bug Description

Pre-compiled headers seem to cause more issues than benefits.

Requiring to explicitly opt-out by specifying `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON` is not intuitive.

**Comment by daschuer** [comment]
Please describe your issues. 
Is this a duplicate of https://github.com/mixxxdj/mixxx/issues/12081?
