### ISSUE TITLE
Mic and Aux buttons showing above library, no option to hide those

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#12319]
### Bug Description

Have not been following Mixxx development closely lately and macOS main builds where gone for a few months, so it is hard to say when this was introduced. Checked the Settings for `LateNight > PaleMoon` but couldn't find a setting to hide those buttons.

![Screenshot 2023-11-20](https://github.com/mixxxdj/mixxx/assets/5708172/9aa067db-b780-4fc7-b430-ce08b3acd6e5)

### Version

2.5-alpha-159-gc1665e50e9 (main), Qt 6.5.3

### OS

macOS 13.6.1

**Comment by ronso0** [comment]
Take a look at the tool bar at the top, left side, right-most button : )
O `View` > `Show Microphone Section`

IIRC I/we decided against a menu toggle because the skin settings menu already occupied the available height (at minimum size)

**Comment by ronso0** [comment]
I think new users would first discover the tool bar, and maybe the settings menu later on if they are actively looking for customization options.
We could put it there if we decide to either increase the minimum size or make the settings menu scrollable (putting it into a `WScrollable` widget).

**Comment by foss-** [comment]
OK, well I never used or saw the buttons previously and had not needed them in the past. Find it an odd default to show them. They showed up in the recent main builds for macOS after the CI was gone for a while, so I was slightly confused. Thanks for pointing out the obvious :)
