### ISSUE TITLE
Searchbox drop-down list is not styled

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12323]
### Bug Description

![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/54b89fcd-bf18-4ed1-9327-cf93d3f80b9d)

### Version

2.4

### OS

Windows 11

**Comment by ronso0** [comment]
Can you try adding
`WSearchLineEdit QAbstractScrollArea,`
here https://github.com/mixxxdj/mixxx/blob/e261b0b780d7bed2107be5faa15a6be4a1462e21/res/skins/LateNight/style_palemoon.qss#L1330 ?

**Comment by JoergAtGithub** [comment]
Yes, now it became readable:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/78edd7d8-186f-431a-9ade-c5edcfaba4f2)
But the blue highlight color looks odd.

**Comment by ronso0** [comment]
Is this with Qt5? 
Has it always been like this, or is this some regression?
Did you upgrade Qt recently?

I'm not surprised that quirks are required for Windows, I just can't belive it hasn't been noticed until now.

Good to see it can be addressed without bending over. I'll prepare a PR. Appearantly it's just that `WSearchLineEdit QAbstractScrollArea` does not inherit the styles from `WSearchLineEdit`.

**Comment by ronso0** [comment]
When you took the selection screenshot, did you hover the item with the mouse or did you select it with the keyboard / controller?

Do the effect selectors (standard units and QuickEffects) look okay?

**Comment by JoergAtGithub** [comment]
Effect dropdowns look Ok, except that the blue highlight color from the general desktop theme is used:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/744fc569-ec67-408c-9bfc-69aa10e6ccf1)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/da080dc5-193e-4ac7-9e4d-da297b67fa32)
This is 2.4 with the Qt5 version from VCPKG, which we haven't changed for some months. I can't say if the search query dropdown changed over time.

**Comment by ronso0** [comment]
Okay, thanks.
How does AutoDJ's fade mode combobox look like?

I think we need to use selectors like this `WEffectSelector QAbstractItemView` like we do for the tracks table.
Please test if adding this
```
  WEffectSelector QAbstractItemView,
  WEffectChainPresetSelector QAbstractItemView,
  WSearchLineEdit QAbstractItemView,
  #fadeModeCombobox QAbstractItemView {
    selection-color: #fff;
    selection-background-color: #2c454f;
    border-radius: 1px;
    border: 0px;
    outline: none;
  }
```
here https://github.com/mixxxdj/mixxx/blob/e261b0b780d7bed2107be5faa15a6be4a1462e21/res/skins/LateNight/style_palemoon.qss#L3001
fixes the styling.

**Comment by JoergAtGithub** [comment]
Indeed, this works. Now it looks like this:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/1235d596-2e31-4835-bf63-8878682b56cd)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/65bf0dc1-8f52-45dd-8e17-e8e088eb6eeb)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/4abee4b1-93cd-4696-9ee1-0df0a62cae44)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/be844c39-941c-4fea-a81c-3d80c3ad653d)

**Comment by ronso0** [comment]
okay, great.
This was LateNight, could you please check those 3 comboboxes in the other skins? Seqrch, effects, fade mode

**Comment by JoergAtGithub** [comment]
Deere:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/54ab3a39-8530-4567-a81d-8659874c3760)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/c80cff25-64b1-4429-a3c1-ea7cf332ad00)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/53919ca5-6183-4e8f-86e0-fb022e214a6a)

Shade:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/dbe43b2e-2fdc-4c07-aaed-a971822ee9c3)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/3d518c8c-484f-42d6-bf61-5e1f97b54067)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/3e2e5cbd-17b7-485f-b519-70af078b9ced)

Tango:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/a70d5e84-8f25-45a3-b96b-84eff1c1dbec)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/c9aaf20f-42bf-4182-b5f9-b888be272b92)
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/026a4df6-3e03-4f67-91b0-f11de5d1db3d)
