### ISSUE TITLE
Cursor issue when using Mixxx in "Window mode"

### ISSUE THREAD

**Issue by nPrevail** [mixxxdj/mixxx#12332]
### Bug Description

[Screencast from 2023-11-21 10-21-30.webm](https://github.com/mixxxdj/mixxx/assets/57690587/2ba1c688-c12d-464a-84e3-5a2093a924fe)

When Mixxx is in full screen, and the entire cursor is hovering over the UI, the cursor works. But when Mixxx is in Window mode, and the cursor is partially off the screen, the cursor fails to register.

This is most evident when you're trying to scroll your library with your cursor, using only left click to scroll through the library tree (scroll bar is on the right side of Mixxx's UI, just briefly touching the desktop.

I was able to get it to scroll a few times, but I had to ensure the entire cursor was within the UI window.

### Version

2.4.0 beta

### OS

Fedora 39 GNOME 45
Wayland

**Comment by uklotzde** [comment]
Confirmed. I have never used Mixxx in Window mode, always fullscreen.

The library scrollbars can't be grabbed while in Window mode if not maximized. This affects version 2.4.0 beta with Qt5 using the Wayland backend (default).

Workaround: Switch back to xcb/XWayland. We probably need to patch the .desktop file as it is unlikely that these issues will get resolved for Qt5.

2.5.0 alpha with Qt 6.6.0 on Wayland currently works flawlessly on Fedora 39.

**Comment by uklotzde** [comment]
Should be fixed by [mixxx-2.4.0-0.8.beta.20231119git3223a75.fc39](https://koji.rpmfusion.org/koji/taskinfo?taskID=618780) soon.

**Comment by nPrevail** [comment]
> I have never used Mixxx in Window mode, always fullscreen.

Neither do I, except that I started using auto-tiling (Forge) on GNOME, and occasionally Mixxx will just auto-resize when other windows open. That's how I found out that the cursor+click scrolling doesn't work well when using Mixxx in window mode.

**Comment by ronso0** [comment]
@nPrevail Is this a new issue with 2.4?
If not let's remove the milestone so we have a clear view of what's still to fix for the release.

**Comment by uklotzde** [comment]
This is a Qt5 issue and cannot be fixed by Mixxx. As a workaround we use the XWayland backend, which resolves the issue.

I did a quick check with the [most recent build](https://koji.rpmfusion.org/koji/buildinfo?buildID=27526) and it still doesn't work.

Qt6 is not affected.

I suggest to close this issue.

**Comment by Swiftb0y** [comment]
fyi I can also no longer reproduce this. Relevant because rpmfusion still caries a patch for this. https://github.com/rpmfusion/mixxx/blob/master/desktop-file-qpa-platform-xcb.patch

https://github.com/user-attachments/assets/770712de-9303-4d89-9bd2-08a49a5cac98
