### ISSUE TITLE
Slow Tempo/Speed when using Apple Headset

### ISSUE THREAD

**Issue by jchoukair** [mixxxdj/mixxx#12374]
### Bug Description

I have MIXXX V2.3.4, when I connect my Apple Headset it slows down the tempo/speed of my play, I did not have this issue under older version, is it fixed in V2.3.6 new version? or is it a setting issue? then how can I fix this ?

### Version

2.3.4

### OS

Windows 11

**Comment by jchoukair** [comment]
It is a Bluetooth EarPods Apple Headsets

**Comment by fwcd** [comment]
> Bluetooth EarPods Apple Headsets

I assume you mean AirPods? In general DJing with Bluetooth headphones is not recommended due to the high latency. That being said...

> I did not have this issue under older version

Could you check what the last Mixxx version was that didn't have the issue? (was it 2.3.3 or earlier?)

Please also check if the issue is fixed under the latest [2.4 beta](https://mixxx.org/download/#beta) or [2.5 development snapshots](https://mixxx.org/download/#testing).

**Comment by jchoukair** [comment]
Yes AirPods. 
(Will check the rest)

**Comment by daschuer** [comment]
Are you able to record the slowed down sound? 
Please explain how it sounds. 
I cannot imaginev why our pitch shifting engine is involved, so I guess that is related to the multiple sound card syncing or some windows magic that tries to workaround drop outs. 

Which sound API dou you use with which buffer size?
You may try a long buffer and all available APIs.
You may also adjust the delay values or the soundcard sync mode.

**Comment by jchoukair** [comment]
Thanks for the feedback info & Questions.
current API = Windows DirectSound
Agree, I find it very strange for any App performance to be impacted by which Audio Output is used.
By the way, one additional info correction: My old Mixxx was V2.0.0,used on old laptop. I think I was using a hardwired headphone, not Apple AirPods. I will try to connect the Airpods to my old laptop and see if Mixxx does the same issue. 
My new Surface Laptop does not have an option to connect a hardwired headphone, I have to use AirPods So now cannot use Mixxx with my AirPods and w/o bothering others around me, I can only hear it well using laptop speakers

**Comment by jchoukair** [comment]
Attached are my API options, which one to try?
![1-Mixxx API Options](https://github.com/mixxxdj/mixxx/assets/152412745/a33369fe-5241-43d4-9de3-66fb5bb05f20)

**Comment by jchoukair** [comment]
Ah, I found the solution ... !!!   (see attached picture)
Changed the Audio Buffer from 23.2 => to 92.9    .....  all set, hey !!
![image](https://github.com/mixxxdj/mixxx/assets/152412745/32975747-c38a-410b-bb81-bbb9b12a06c3)

**Comment by jchoukair** [comment]
![image](https://github.com/mixxxdj/mixxx/assets/152412745/2c75594b-e3bf-4c1c-b4f6-bd49c8f6ee93)

**Comment by ronso0** [comment]
Re API
https://manual.mixxx.org/2.3/en/chapters/preferences/sound_hardware#sound-api
