### ISSUE TITLE
Looping between the upper and lower part of the library

### ISSUE THREAD

**Issue by FrankwaP** [mixxxdj/mixxx#12379]
### Feature Description

Hi!

I like to sort my library using the Lancelot/Camelot keys, so it's very smooth to look for tracks that are will make a harmonic transition. 

However this not the case when moving between  the 1A/1B keys and the 12A/12B keys.

I think allowing the library to loop between the upper (1A/1B) and lower (12A/12B) part of the library would be neat!

**Comment by ronso0** [comment]
You mean if press Down on the last it wraps around, i.e. jumps to the top line?

If yes, that is already implemented in Mixxx 2.4-beta (which you can get from the download page > Beta).

**Comment by FrankwaP** [comment]
Yes that's what I meant!
I've just installed the beta version, and it looks great, thanks for the great work (which made me remember to donate :-p )
