### ISSUE TITLE
DDJ-SB3 not woring with Mixxx 2.4.0-beta

### ISSUE THREAD

**Issue by FrankwaP** [mixxxdj/mixxx#12384]
### Bug Description

After upgrading to the "2.4.0-beta" version (from "2.3.6 (HEAD)"), Mixxx raises an error regarding my DDJ-SB3 controller: 
```
The mapping for your controller "DDJ-SB3 MIDI 1" is not working properly.
The script code needs to be fixed.
The functionality provided by this controller mapping will be disabled until the issue has been resolved.

Details:
Uncaught exception: file:///usr/share/mixxx/controllers/Pioneer-DDJ-SB3-scripts.js:280: Error: Invalid timer callback provided to engine.beginTimer. Valid callbacks are strings and functions. Make sure that your code contains no syntax errors.
Backtrace: @file:///usr/share/mixxx/controllers/Pioneer-DDJ-SB3-scripts.js:280
```

The line in question:
```
    if (PioneerDDJSB3.twinkleVumeterAutodjOn) {
        PioneerDDJSB3.vuMeterTimer = engine.beginTimer(100, PioneerDDJSB3.vuMeterTwinkle());
    }
```

I've checked: this file did not change between "2.3.6 (HEAD)" and "2.4.0-beta"...

### Version

Mixxx 2.4.0-beta

### OS

Ubuntu 22.04.3 LTS

**Comment by FrankwaP** [comment]
I confirm that it fixed the problem! :-)

**Comment by ronso0** [comment]
Let's keep this open until the fix has been merged, i.e. is available for every user ; )

**Comment by ronso0** [comment]
Shouldn't we scan **all** scripts for this pattern and do a mass-fix, maybe in conjunction with the other, related ~fix~ workaround you proposed in https://github.com/mixxxdj/mixxx/issues/12369#issuecomment-1830423622?

**Comment by FrankwaP** [comment]
@Swiftb0y  Yes I can contribute with a pull request.

@ronso0 
Here's the command to look for other files with the same issue: 
```bash
grep -Rl "vuMeterTwinkle()" /usr/share/mixxx/controllers/*.js 
```
Which gives (knowing SB3 is already fixed on my PC):  
> /usr/share/mixxx/controllers/Pioneer-DDJ-SB2-scripts.js
> /usr/share/mixxx/controllers/Pioneer-DDJ-SX-scripts.js

So there are only 3 files concerned, no big deal.
