### ISSUE TITLE
Played checkbox in unchecked state not correctly displayed

### ISSUE THREAD

**Issue by foss-** [mixxxdj/mixxx#12419]
### Bug Description

The problem is limited to the 2.4. 2.3.6 and 2.5 do display the checkbox as expected.
2.4-beta-283-g695e9f594b
macOS 13.6.1 (intel mac)

2.3.6
![2 3 6](https://github.com/mixxxdj/mixxx/assets/5708172/a77c8ba1-235e-4bdd-a415-8ac50956d68e)

2.4 2023-12-10
![2 4 2023-12-10](https://github.com/mixxxdj/mixxx/assets/5708172/d9d44066-974a-4f41-a85d-c3a3c8d947c6)

2.5 2023-12-10
![2 5 2023-12-10](https://github.com/mixxxdj/mixxx/assets/5708172/c3f0d475-cbcf-41e1-9166-a37719a6ce18)

The code in main was touched october 2023: https://github.com/mixxxdj/mixxx/pull/12050 polite ping @fwcd 

see also https://github.com/mixxxdj/mixxx/issues/10721

### Version

2.4-beta-283-g695e9f594b

### OS

macOS 13.6.1 (intel mac)

**Comment by fwcd** [comment]
What do you mean by "not correctly displayed"? The box does render in your 2.5 screenshot (like in your 2.3 screenshot), it is just pretty faint. Here is a brightened up version:

![image](https://github.com/mixxxdj/mixxx/assets/30873659/f2ea3573-f9fa-427c-b976-8fdf69f8465c)

Or do you mean that you expected the boxes to be checked?

**Comment by fwcd** [comment]
Do you mean the slightly accentuated top/left border? My guess is that this is some change between Qt 5 and 6 in the way they render checkboxes, which presumably also caused #11908. Since it's only a minor stylistic glitch, I am not sure if it is worth fixing, given that we want to move to Qt 6 anyway. Unless, of course, the fix is trivial and doesn't break the styling on Qt 6.

cc @ronso0

**Comment by foss-** [comment]
I am fine if you think this is expected for Qt 5. Was slightly surprised as 2.3.6 shows the checkbox as expected and does not use that fake 3D checkbox style 🙈.

Please don't let this delay 2.4 especially since 2.5 looks great.

**Comment by ronso0** [comment]
Seems to be a special macOS Qt bug.
FWIW on Linux I couldn't reproduce any of the checkbox issues.

@foss- Does it look like that in all skins?
Do it change it you use another system style scheme (don't know how much custmization is possible in macOS), do the checkboxes look like other checkboxes in macOS, e.g. in preferences or other apps?

Just trying to understand what's happening. @fwcd do you also run macOS 13.6.1?

**Comment by foss-** [comment]
There are no schemes in macOS. System Settings > Appearance allows Light | Dark | Auto along an accent and highlight color, done. But those don't affect the checkbox UI.

2.4-beta-283-g695e9f594b

- [x] Deere
- [x] Shade
- [x] Tango
- [ ] LateNight > PaleMoon or Classic

Interestingly only LateNight is affected. This is how the checkbox looks for Deere:
![1](https://github.com/mixxxdj/mixxx/assets/5708172/65fa4815-97a1-4aa4-a45f-7b7b4b6bedcd)

Probably fair to keep it open and let it sit for a while.

**Comment by ronso0** [comment]
@foss- From the screenshots' size I assume you don't have a Retina display / don't use Retina scaling on the Mixxx screen?
If yes, this is a regression from #12407

**Comment by foss-** [comment]
Hmm - this is a 2017 retina MacBook Pro however I was running Mixxx on an external screen. So you are indeed onto something.

Running Mixxx without external display results in the expected checkbox on the laptop screen.

With a large external 43" 4k monitor the checkbox shows in the unexpected form. Just moving the window is sufficient to make the checkbox change its appearance.

**Comment by ronso0** [comment]
> With a large external 43" 4k monitor the checkbox shows in the unexpected form. Just moving the window is sufficient to make the checkbox change its appearance.

So you just move the window a little, or to the laptop screen?
Are you launching Mixxx on the second display, or on te primary one and then move it to the external one?

However, as long as it only affects the external screen and all other icons are rendered fine we should not do anything IMO.

**Comment by foss-** [comment]
I move the open window and as soon as I am on the external window the checkbox UI is wrong. Move window back to laptop screen -> checkbox is fine. Doesn't matter on which monitor Mixxx is first opened.
Ok, lets close this and I'll probably move to main, to get this sorted.
