### ISSUE TITLE
"Deere (64 Samplers)/icon/ic_unfold_more_48px.svg" "missing" x8

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12439]
### Bug Description

I'm seeing
```
 qt.svg:warning [Main] Cannot open file '/usr/share/mixxx/skins/Deere (64 Samplers)/icon/ic_unfold_more_48px.svg', because: No such file or directory
```
8 times in the terminal when switching to the "Deere (64 Samplers)" skin.

### Version

2.4-alpha-1578-gc47f67985d (makepkg)

### OS

Arch

**Comment by ronso0** [comment]
Already fixed in 2.4-beta
