### ISSUE TITLE
Sync button does not work as expected on Numark Mixtrack Pro 3 Controller

### ISSUE THREAD

**Issue by ridicux** [mixxxdj/mixxx#12460]
### Bug Description

Hi,

Long-pressing the sync buttons on my Numark Mixtrack Pro 3 Controller is supposed to lock bpm on the respective deck. However, nothing happens instead.
If I do a short press on the sync buttons, the bpm sync happens, but at the same time, the respective deck starts playing, which is unexpected.
Sometimes, the following error is thrown when I press the sync button:
<img width="748" alt="Screenshot 2023-12-22 at 21 47 46" src="https://github.com/mixxxdj/mixxx/assets/154633625/ddc349eb-5c59-4650-8e95-a3aecfd6dd55">

### Version

2.4-beta-301-geeb6412862

### OS

MacOS 14.2.1

**Comment by Swiftb0y** [comment]
confirmed previously in https://github.com/mixxxdj/mixxx/issues/12369#issuecomment-1835700452

**Comment by Swiftb0y** [comment]
@ridicux can you try the mapping changes in made in #12468 (the two line changes made [here](https://github.com/mixxxdj/mixxx/pull/12468/files#diff-5d2c8b5f78f741322b10411269ca08a6cdc0417a8d3f58458f9f1e4fa7bfeb45)) and confirm whether these fix the issue for you?

**Comment by shuda** [comment]
> @ridicux can you try the mapping changes in made in #12468 (the two line changes made [here](https://github.com/mixxxdj/mixxx/pull/12468/files#diff-5d2c8b5f78f741322b10411269ca08a6cdc0417a8d3f58458f9f1e4fa7bfeb45)) and confirm whether these fix the issue for you?

![image](https://github.com/mixxxdj/mixxx/assets/4147559/af8a26ee-2303-49e9-803e-210a0a30a756)

numark mixtrack pro 3 script missing 2 ".bind(this)" in line 579,583 but apart from this https://github.com/mixxxdj/mixxx/pull/12468 works well using numark mixtrack 3 pro

**Comment by Swiftb0y** [comment]
Yup, I missed those. PR is updated. Thanks for testing.

**Comment by ronso0** [comment]
fixed by #12468
