### ISSUE TITLE
Right click on a playlist exports previous playlist

### ISSUE THREAD

**Issue by nvdl** [mixxxdj/mixxx#12472]
### Bug Description

Mixxx 2.3.6
Git Version: 2.3.6
Date: Tuesday, August 15, 2023 7:47:16 AM CEST
Platform: Linux x86_64

Right click on an entry in the "Playlists", select "Export Playlist".

Current behavior: A previous playlist selected with a **left click** gets exported.
Expected behavior: Currently selected playlist should get exported.

### Version

2.3.6

### OS

Debian 11

**Comment by ronso0** [comment]
Thanks for your report.
This and related issues are already  fixed in 2.4-beta, for example by #11208 and #11332
