### ISSUE TITLE
Default value (using right click) for "Moog filter"

### ISSUE THREAD

**Issue by nvdl** [mixxxdj/mixxx#12479]
### Bug Description

Mixxx 2.3.6
Git Version: 2.3.6
Date: Tuesday, August 15, 2023 7:47:16 AM CEST
Platform: Linux x86_64

**I don't know if it is a bug or not.**

Right clicking on the knob of "Moog filter" resets the knob to the far left.
Shouldn't it be **centered** where it has the minimal effect on the sound?

### Version

2.3.6

### OS

Debian 11

**Comment by Swiftb0y** [comment]
Yup, though the problem is not effect specific, rather issue is that right clicking the super knob of an effect unit always resets it to 0 rather than the default. In 2.4, rightclicking the filter knob with an effect (such as the moog-filter) resets it to the correct value.

**Comment by Swiftb0y** [comment]
Ah, my mistake... the difference is that the `super1` control behaves correctly but `meta` doesn't...

Found the culprit.
https://github.com/mixxxdj/mixxx/blob/bbf51e90e2092caa932a67dd6c2286c5c516658b/src/effects/effectslot.cpp#L122-L135

The `setDefaultValue` must not hardcode a value and instead make it dependent on the loaded effect. Not sure when if/when I'll be able to provide a fix. Someone else feel free to pick this up.

**Comment by nvdl** [comment]
I can help with it but it looks like I have to go through some coding guidelines for the code etc.

What solution do you suggest here?
Set both lines (131 and 132) to a mid value? What numeric range are the knobs using?

**Comment by Swiftb0y** [comment]
No worries, I think I got it. just waiting for the compile so I can test right now. In the meantime could you confirm whether #14257 fixes the issue for you? You should be able to download a deb from the bottom of https://github.com/mixxxdj/mixxx/actions/runs/7360936261 once it finished building.

**Comment by nvdl** [comment]
Works as expected. Cheers!

**Comment by Swiftb0y** [comment]
Thanks for also confirming. There won't be another 2.3 release so its only fixed in 2.4 newer.
