### ISSUE TITLE
Tracks lag when sound output are bluetooth devices

### ISSUE THREAD

**Issue by Nisond** [mixxxdj/mixxx#12485]
### Bug Description

Hello,
When I play tracks regularly in Mixxx things work fine but when I connect bluetooth devices (I tried two different devices) and play through them, the tracks lags. It plays slower and stutters. This happens consistently. When I play through the soundcard on my laptop everything works as expected. Restarting does not seem to help. When I play music through the bluetooth devices using Windows Media Player or VLC instead of Mixxx it works as fine.

### Version

2.3.6

### OS

Windows 10

**Comment by ronso0** [comment]
Did you try larger audio buffers?

Also, in case you use more than one soundcard, you can try different multi-soundcard sync settings, maybe that has an effect.

**Comment by Nisond** [comment]
I didn't and using larger audio buffers did the trick. Thanks
