### ISSUE TITLE
Sync Leader (Crown)-Button changes tempo of deck

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12483]
### Bug Description

When I've two decks playing out of sync and click on the crown button, I expect that this deck become sync leader and keeps it's tempo - but it takes over the tempo of the other deck, which is not synced.

https://github.com/mixxxdj/mixxx/assets/64457745/4357f0fe-5948-459d-ae70-2b5c615f1e01

### Version

2.4

### OS

Windows 11

**Comment by Holzhaus** [comment]
Pinging @ywwg as he is the Sync expert 🙂

**Comment by ywwg** [comment]
pr posted

**Comment by daschuer** [comment]
Thank you
