### ISSUE TITLE
Mixxx 2.4 fails to build with make

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/mixxx#12505]
### Bug Description

The current 2.4 branch fails to build on my machine. Using a clean build dir:

    $ cmake -DQT6=OFF -DCMAKE_BUILD_TYPE=Debug -DWARNINGS_FATAL=ON -DDEBUG_ASSERTIONS_FATAL=ON .. && cmake --build . && ctest -j 16
    ...
    [  9%] Built target mixxx-proto
    make[2]: *** No rule to make target 'lib/keyfinder-install/lib/libkeyfinder.a', needed by 'CMakeFiles/mixxx- 
    lib_autogen_timestamp_deps'.  Stop.
    make[1]: *** [CMakeFiles/Makefile2:1392: CMakeFiles/mixxx-lib_autogen_timestamp_deps.dir/all] Error 2
    make: *** [Makefile:166: all] Error 2

### Version

2.4 @ 0291eb24257c95ebedd75d9641a6f9f25a8d8d70

### OS

Arch Linux

**Comment by daschuer** [comment]
https://github.com/mixxxdj/mixxx/pull/12518 fixes this issue.

**Comment by ywwg** [comment]
merged that in, should be fixed

**Comment by Holzhaus** [comment]
I can confirm that latest 2.4 and HEAD builds fine with make. :+1:
