### ISSUE TITLE
Holding loop_out stops waveform 

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#12513]
### Bug Description

I am afraid the new waveform code for loop position is not aware of the "Holding loop out" case. 
The waveform already displays the position after releasing the button, which is loop-In. 
In this situation the waveform stops, but the sound is still playing at the moving loop-out position

### Version

2.4-beta

### OS

Ubunti 20.4 Focal

**Comment by ronso0** [comment]
Is #12506 a symptom of this?

**Comment by ywwg** [comment]
this also seems like a significant release-blocker
