### ISSUE TITLE
Mixxx 2.4 .msi Installer installs qml directory, containing unsigned DLLs

### ISSUE THREAD

**Issue by JoergAtGithub** [mixxxdj/mixxx#12524]
### Bug Description

The following directories appear in a Mixxx 2.4 installation:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/3c31a4c9-183b-4461-ad2b-236c5c9a70f5)
The qml directory tree is not needed for 2.4, but contain a lot of unsigned DLLs.

### Version

2.4

### OS

Windows11

**Comment by daschuer** [comment]
Does https://github.com/mixxxdj/mixxx/pull/12539 fixes this issue?

**Comment by JoergAtGithub** [comment]
> Does #12539 fixes this issue?

No, it doesn't fix this!

**Comment by daschuer** [comment]
Ok, I will take second look. Is https://github.com/mixxxdj/mixxx/pull/12539 otherwise OK?

**Comment by JoergAtGithub** [comment]
> Ok, I will take second look. Is #12539 otherwise OK?

I didn't notice any difference to 2.4.
