### ISSUE TITLE
2.5-alpha won't start on Uuntu 22.04 due to missing Qt platform plugins

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12525]
### Bug Description

reported here https://mixxx.discourse.group/t/ubuntu-22-04-update-mixxx-not-working/28743

Similiar reports exist for other apps and it was fixed by installing some xcb packages.
Do we need to update dependencies?

### Version

2.5-alpha

### OS

Ubuntu 22.04

**Comment by naught101** [comment]
Related? https://github.com/mixxxdj/mixxx/pull/12284

**Comment by naught101** [comment]
A work around for me was removing the mixxx-nightlies repos, adding https://launchpad.net/~mixxx/+archive/ubuntu/mixxxbetas, and downgrading to 2.4.0-beta-whatever.

**Comment by ronso0** [comment]
So, since
* similiar issues where reported for other Qt apps much earlier
* 2.5-alpha worked until recently for @stefan-franz @naught101 and other alpha testers

I assume it's not an Qt update / Qt packaging issue but indeed related to #12284 

Everyone affected: please test the CI build from #12545 
Instruction for testing and backing up your data are here https://github.com/mixxxdj/mixxx/wiki/Testing

**Comment by daschuer** [comment]
This is the warning from the original report: 
```
azz@Dazz-VPCEH3N6E:~$ mixxx
Using preferences ScaleFactor 1
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin “xcb” in “”
qt.qpa.plugin: Could not find the Qt platform plugin “wayland” in “”
```

**Comment by daschuer** [comment]
Does starting via 
```
QT_DEBUG_PLUGINS=1 mixxx
``` 
Reveals an issue?

**Comment by daschuer** [comment]
Normally 'QT_DEBUG_PLUGINS=1 mixxx' should produce extra log info like this: 

```
...
Got keys from plugin meta data ("ico", "cur")
QFactoryLoader::QFactoryLoader() looking at ...
Found metadata in lib ...
metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jpg",
            "jpeg"
        ],
        "MimeTypes": [
            "image/jpeg",
            "image/jpeg"
        ]
    },
    "className": "QJpegPlugin",
    "debug": true,
    "version": 329993
}
...
```

Is this info shown with --developer, or does the crash happen before the debug info is generated?

**Comment by daschuer** [comment]
I just found this new warning in Qt v6.7.0-beta1 
`"From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.";`
https://github.com/qt/qtbase/blob/5b9ce5d1298f5dffd986b422857cd1624693cabd/src/gui/kernel/qguiapplication.cpp#L1254

This is interesting, because your crash happens with Qt 6.2 so probably another issue?

**Comment by daschuer** [comment]
This is not our issue because the error does not state "even though it was found"

**Comment by daschuer** [comment]
Oh, form Qt6 the xcb plugin is bundled to `qt6-qpa-plugins`
https://packages.ubuntu.com/jammy/qt6-qpa-plugins
