### ISSUE TITLE
Fetched cover art from "MusicBrainz" is auto applied

### ISSUE THREAD

**Issue by nvdl** [mixxxdj/mixxx#12532]
### Bug Description

Mixxx 2.4.0-beta
Git Version: 2.4-beta-314-g71dceb27ba
Platform: Linux x86_64
OS: Debian 11

**Preferences -> Library -> "Synchronize library track metadata from/to file tags" is checked (enabled).**

When fetching tags from "MusicBrainz", cover art is also fetched after selecting one of the suggestions.
Clicking on "Apply" auto applies the cover art along with the tags without requiring a click on "Apply Cover".

After manually clearing the auto applied cover art (which I do not want), the downloaded image is still in the filesystem and not removed.

Shouldn't "Apply" be renamed to "Apply Tags" and its functionality changed to only apply tags?
How can I only apply the tags without applying the suggested cover art?

**Comment by ronso0** [comment]
In #11938 I tried to keep the impact minimal, i.e. keep the existing translations.
I feared this would introduce UX issues :| We didn't consider the use case to apply **tags only**, rather focused on updating the **cover only**.

Let me figure out how we can fix this.

**Comment by ronso0** [comment]
> After manually clearing the auto applied cover art (which I do not want), the downloaded image is still in the filesystem and not removed.

That is a separate issue, I filed #12534

**Comment by ronso0** [comment]
I see two options:
1. rollback the entire cover fetcher and release it in Mixxx 2.5
2. add checkboxes next to Apply:
`[Next] [Previous]                          [ ] Tags  [ ] Cover  [Apply] [Close]`

1 would be a pity
2 would introduce new translation strings with are probably not translated until we release 2.4 soonish.

**Comment by daschuer** [comment]
IMHO this is not such a big problem that it rectifies a complete rollback. We may even consider this issue as a feature request. 
I like the proposal of 2. It has a limited scope and can be a 2.4 fix. 
However it should not delay the release ...

**Comment by ronso0** [comment]
I already have 2) ready, very easy fix.
I'll open a PR this evening.

**Comment by ronso0** [comment]
I suggested two solutions
* #12543 two checkboxes
* #12542 Apply button only applies tags (optionally rename it)

Let's discuss the pros and cons in #12543

**Comment by nvdl** [comment]
I vote for the "two checkboxes" solution as it is one-click based and visually more aligned.

Just checking:
If no cover art is found and "Cover" is checked, it should not create an empty/strange image in the filesystem.

**Comment by daschuer** [comment]
Especially because the checkboxescare equal "leveled" 
The button version is in the current state confusing, because the cover tag is also a tag. 

Are the checkboxes persistent?

**Comment by ronso0** [comment]
Nope, or at least not yet. May write that to config.
Also, currently one can press Apply while the boxes are unchecked.
