### ISSUE TITLE
Initial tempo after connecting Roland DJ-505 is set to very high BPM

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#12569]
### Bug Description

This happens on both decks after I select the midi mapping for the already connected Roland DJ-505
A track with 138 BPM is then set to about 1264 BPM and thus cannot be played back. After connecting the controller, I always have to move the tempo fader a bit back and forth in the center position and then the BPM are set correctly once the change is picked up

### Version

2.3.6, 2.5 built today

### OS

Debian 12, macOS 14 (both with all the latest updates)

**Comment by Holzhaus** [comment]
Yes, noticed that as well. I suppose it should be fixed with #13463.

**Comment by Holzhaus** [comment]
I suppose it makes sense to verify this and then add a hint to the controller manual.

**Comment by Swiftb0y** [comment]
I guess try a new 2.4 or 2.5 build @spotlesscoder? Should be fixed then I'm pretty sure.

**Comment by Swiftb0y** [comment]
I'll close for now. Feel free to reopen if its not fixed.
