### ISSUE TITLE
Analyzing waveform takes ages on M1 Macbook Pro compared to way older Thinkpad X270 with i5-6300U

### ISSUE THREAD

**Issue by CodingSpiderFox** [mixxxdj/mixxx#12568]
### Bug Description

The thinkpad with debian 12 and latest mixxx stable release just takes a few seconds to analyze a song and render the waveform.
The same song took almost a minute on latest macOS 14 on a M1 Macbook Pro

### Version

2.3.6. Installed with brew

### OS

macOS 14

**Comment by CodingSpiderFox** [comment]
Also tried the alpha 2.5 native arm version built today ... same behaviour

**Comment by CodingSpiderFox** [comment]
I think the once analyzed waveforms should be persisted next to the sound files like reaper DAW seems to do this with the .reapeaks files

**Comment by daschuer** [comment]
Maybe there is a decoder issue? Does the mixxx.log reveal something? 
https://github.com/mixxxdj/mixxx/wiki/Finding-the-mixxx.log-file

An interesting test would be to compare the performance of the latest 2.4-beta on both devices. Can you make a copy and rename of one affected audio file and put it on both machines. Than start Mixxx, drag and drop the track into a deck and wait until the analysis is complete. Measure the time the analysis takes close Mixxx and attache both mixxx.log files to this bug report.

**Comment by CodingSpiderFox** [comment]
I managed to resolve the issue by taking these steps

* Restart the mac
* Delete the mixxx settings folder contents entirely and copy over the settings files I backed up from the Thinkpad
* Start mixxx 
* Relink the sound library folder which is on my usb drive

Now all previously analyzed waveforms load immediately when putting a track on a deck and analyzing a newly added song also is at most 5 seconds

As I don't want to break the now working setup, I am sorry I cannot assist you with testing right now as I only have one Macbook
