### ISSUE TITLE
Put "Adjust BPM" submenu entries in literal ratio order?

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12579]
### Feature Description

I'm dyscalculic and I'm having trouble registering and processing the Adjust BPM submenu. They're not in ratio change order, and they're only displayed as fractions.

 ![image](https://github.com/mixxxdj/mixxx/assets/108225/ee7e0813-d6ce-4497-a4d1-f51ce0de0ac5)

Currently
* Double
* Half
* 2/3
* 3/4
* 4/3
* 3/2

If they were instead in the order;
* Half
* 2/3
* 3/4
* 4/3
* 3/2
* Double

it would be easier to register. What do folks think?

**Comment by ronso0** [comment]
Yes, that makes sense.

We could even append the decimal number without touching the translations:
* Half
* 2/3 (0.666)
* 3/4 (0.75)
* 4/3 (1.333)
* 3/2 (1.5)
* Double

Idk if that would help, or if it's just noise.

**Comment by ronso0** [comment]
Oh, we already figured the preview value would be best.

**Comment by ronso0** [comment]
That's a good starter bug. Something in between "coffee break" and "weekend", depending on c++ skills and familiarity with the Mixxx code ; )

**Comment by mxmilkiib** [comment]
I guess this can be closed as completed now? Thanks again 😁
