### ISSUE TITLE
Center level meter (main output) doesn't work

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/mixxx#12597]
### Bug Description

All is in the title.

### Version

Beta 2.4

### OS

Windows 11, Ubuntu 22.04

**Comment by ronso0** [comment]
> All is in the title.

Hmm, not quite.
Which skin do you use?
Which exact version is broken? You'll find that info in the About dialog.

**Comment by RafaelFrance** [comment]
Sorry,

Tango skin
Version : 2.4-beta-341-gd01d841f63
Platform Linux x86_64

**Comment by ronso0** [comment]
Oh, indeed!
Apparently that slipped through during the last control renaming. I'll fix this soonish and let you know when test builds are available.
Thanks for reporting!

**Comment by ronso0** [comment]
I pushed a fix directly to 2.4
New builds should be availbale in the ppa in a few hours.

**Comment by RafaelFrance** [comment]
Solved

Thanks
