### ISSUE TITLE
Waveforms: Filtering and RGB color mapping is not accurate for mixing

### ISSUE THREAD

**Issue by uklotzde** [mixxxdj/mixxx#12609]
### Feature Description

The filtering and color mapping used by Mixxx seems to differ greatly from what other applications like Rekordbox are using:

https://codeberg.org/moire/moire/pulls/129#issuecomment-1528014

The green parts of the tested track indicate beatless parts with instrumentals and vocals. These are not visible in Mixxx.

**Comment by Swiftb0y** [comment]
related to #10123 and #11833 ?

**Comment by uklotzde** [comment]
Thanks for the hint. Duplicate of #11833.

A more generic and concise title would help.
