### ISSUE TITLE
Add support for motorized jog wheels 

### ISSUE THREAD

**Issue by christophehenry** [mixxxdj/mixxx#12603]
### Feature Description

I remember reading something about this issue somewhere but I can't find where. So please excuse me if an issue already exist for that feature or if it has already been implemented in-between.

The Denon DN-S3700 has a motorized jog wheel with a button to switch between still/bend mode and vinyl mode for scratching. The vinyl mode periodically send a midi signal when the jog spins a certain angle.

The current implementation plays the song too slowly.

**Comment by ronso0** [comment]
There is no official mapping for the DN-S3700, so I'll close this.
Please ask the mapping creator for help.

However, which mapping exactly do you use? I presume somewhere in the script file there's a constant to scale the wheel ticks or something.
