### ISSUE TITLE
waveforms move wobbly at HiDPI != 100%

### ISSUE THREAD

**Issue by toszlanyi** [mixxxdj/mixxx#12601]
### Bug Description

With HiDPI scales other than 100% the scrolling waveforms are flickering / wobbly. This behaviour is seen regardless of the waveform type or frame rate set in Preferences -> Waveform. The visible effect becomes more obvious with higher waveform zoom level. 

An example with HiDPI scaling at 125% is here
https://github.com/mixxxdj/mixxx/assets/58949409/c127316b-1d65-41fb-bbf3-da575f6d5d5b

My system:

Operating System: EndeavourOS 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.7.0-AMD-znver2 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 4800U with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics

OpenGL core profile vendor: Mesa
OpenGL core profile renderer: llvmpipe (LLVM 16.0.6, 256 bits)
OpenGL core profile version: 4.5 (Core Profile) Mesa 23.3.2-arch1.2
OpenGL core profile shading language version: 4.50

### Version

2.4.0

### OS

Linux (EndeavorOS)

--
see also: https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Waveform.20flickering.20with.20HiDPI.20scaling

**Comment by m0dB** [comment]
I can't reproduce this on macOS, because the HiDPI scaling value doesn't have any effect. I don't know if this is a bug or if this is expected on macOS.

Looking at the video it looks like the OpenGL viewport is sized with unscaled pixels,  and when this gets displayed at the  scaled pixels the image is interpolated, which results in the wobbly effect. If any linux developer can debug this and log and report some values (width and height of the widget, of the OpenGL window, of the viewport, of the device pixel ratio, of the actual size in pixels on the screen), I might be able to figure this out.

This is labelled a regression, so do I understand correctly that it doesn't happen with 2.3.6 ?

**Comment by m0dB** [comment]
Okay, if I run with ```QT_SCALE_FACTOR=1.25 ./mixxx``` the scale factor does take effect. It doesn't like as weird as in the video, but I do see a shimmering. I will look into this, but I don't have much time, so if anybody else can look into this too, that would be great.

**Comment by toszlanyi** [comment]
> Are you building 2.4 yourself?

I gonna build your PR myself and test it during today. Thanks

**Comment by daschuer** [comment]
It looks like as if the waveform is rendered to 100% and later updated to 125%. Can't we always render in native resolution (or the nearest integer factor) and adjust the waveform zoom instead?

**Comment by m0dB** [comment]
I am not quite sure how the upscaling works, and maybe it's different on Linux. On macOS I see the following: The size given to the widget and openglwindow stays the same, independent of the QT_SCALING_FACTOR, which is applied to the devicePixelRatio (on my MacBook with retina, so a base devicePixelRatio of 2, a QT_SCALING_FACTOR of 1.25 results in a devicePixelRatio of 2.5). The waveform renderes then render at width*devicePixelRatio pixels.

**Comment by daschuer** [comment]
I can confirm the issue with Mixxx 2.4.6 on Ubuntu Focal as well when starting Mixxx with 
`QT_SCALE_FACTOR=1.25 mixxx`

So it is not a regression. Can you confirm that and can we remove this issue from the 2.4.0 Milestone?

**Comment by daschuer** [comment]
The overlays are fixed here: https://github.com/mixxxdj/mixxx/pull/12731. 
The signal issue is a bit more complicate, because the 125 % does not fit to the factor 100 we use during analysis.
We need to make sure that the displayed position is always rounded to the same chunk of samples.

**Comment by toszlanyi** [comment]
> The overlays are fixed here: https://github.com/mixxxdj/mixxx/pull/12731. 


Thanks a lot @daschuer. I can build and test your PR during tomorrow. Gonna report back here or comment directly to the PR. Cheers!

**Comment by daschuer** [comment]
Since this is no regression, lets move it to 2.4.1

**Comment by toszlanyi** [comment]
Just built and tested #12731 -> Unfortunately, I can not spot any difference this PR would make.

**Comment by daschuer** [comment]
Without the patch and in 125 % selected in the interface preferences, I see some beatmarkers with two and some with one pixel width. With the PR all beat markers are equal width. Can you see that?

**Comment by toszlanyi** [comment]
the bars still seem to flicker but it could be an optical illusion with the stacked waveform. Switching to RGB (GLSL) the bar markers seem to be okay. Cheers!

https://github.com/mixxxdj/mixxx/assets/58949409/b4579316-0840-4138-86d6-779bdcbbdab9

**Comment by daschuer** [comment]
I can confirm the issue. The RGB stack is rendered by the old rendered where the issue has not been fixed.

**Comment by daschuer** [comment]
The beats of the RGB stack type are solved here: https://github.com/mixxxdj/mixxx/pull/12678

**Comment by daschuer** [comment]
The wobbling of the GLSL waveforms is now also solved with https://github.com/mixxxdj/mixxx/pull/12731

**Comment by toszlanyi** [comment]
> The wobbling of the GLSL waveforms is now also solved with #12731

Awesome! This looks really great now for RGB (GLSL)
