### ISSUE TITLE
simplify setting hot cue inside a loop from the GUI

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12618]
### Bug Description

I don't think it's possible currently; creating one will make it be at the start of the loop as a loop;

![image](https://github.com/mixxxdj/mixxx/assets/108225/1185409c-c826-4730-8213-c8afa598de76)

### Version

2.4-beta

**Comment by ronso0** [comment]
There are explicit `hotcue_N_setcue` controls for this purpose.

With the GUI this is indeed not possible right away.
You'd need to deactivate the loop, set the cue and reactivate the loop. Admittedly, in live situations this may be tricky with short loops.

Though, we may prohibit setting redundant hotcues at loop in.

**Comment by Swiftb0y** [comment]
> Though, we may prohibit setting redundant hotcues at loop in.

I think that will cause opposition. People already use that strategy as a workaround for the fact that you can't jump to loopcues when you haven't passed the loop yet.

**Comment by ronso0** [comment]
That work(around) flow is not affected. See #12623 

Clarification: don't (remotely) set a another identical **loop** cue at loop start from another position inside an active loop.
And currently such a loop cue would be 100% identical since it adopts the active loop which was saved already.

**Comment by ronso0** [comment]
Fixed by #12623
