### ISSUE TITLE
No title on Preview Deck using LateNight Classic

### ISSUE THREAD

**Issue by idcmp** [mixxxdj/mixxx#12629]
### Bug Description

Apologies if this is fixed in a later version. I've been using this version as my daily driver and I'm too chicken to upgrade quite yet.

![image](https://github.com/mixxxdj/mixxx/assets/165614/f9be5eff-12d1-4364-aaf9-074727c7449d)

### Version

2.4-beta-328-gf610d58a25

### OS

macOS arm64

**Comment by ronso0** [comment]
Thanks or reporting this.
This slipped through in #12004. I pushed the fix directly to the 2.4 branch, it should be available in a few hours.
