### ISSUE TITLE
toggle hotcue type (point | loop cue) in hotcue menu

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12645]
### Feature Description

Could a simple checkbox `Loop [ ]` that allows
* turning a hotcue into a loop cue
   * either use current temp. loop if its start point is the hotcue position
   * use current beatloop size (spinbox)
* loop cue -> hotcue

This would avoid

**Comment by Swiftb0y** [comment]
that would also imply being able to set the length via the hotcue menu, right? At least thats what would make sense.

**Comment by ronso0** [comment]
Fixed by #13215
