### ISSUE TITLE
Button for duration of transition adjustement in Auto DJ not visible

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/mixxx#12653]
### Bug Description

Tango Skin.

The "Up" boutton (triangle) is visible only when the mouse is over it. Otherwise, only the  "Down" button is visible.
![Up button not visible](https://github.com/mixxxdj/mixxx/assets/51053041/ceaf86e1-e2bc-4969-a0be-8ed033fa010a)
![Down button visible when mouse is over](https://github.com/mixxxdj/mixxx/assets/51053041/d8afb3b2-7777-4428-9b1d-9a602ff9134d)

### Version

2.4-beta-395-g1b9870852d

### OS

Linux Ubuntu 22.04LTS

**Comment by ronso0** [comment]
I noticed that as well  yesterday, then I checked the 2.4 branch and it was fixed already 🤷 
https://github.com/mixxxdj/mixxx/blob/59ca3a25b768c44ac0934ed4cb4504cac52bde54/res/skins/Tango/style.qss#L1156

Please update and test again.
Thank you!

**Comment by RafaelFrance** [comment]
Mixxx updated. 2.4-beta-396-g0299924f47

No change.

**Comment by ronso0** [comment]
Oh, what I linked was the main branch.
I just pushed a fix to 2.4, it'll be available in new builds in a few hours.
