### ISSUE TITLE
HiDPI: Beat markers are not scaled with new GL Waveforms

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#12679]
### Bug Description

It looks like that at 200 %: 
New GLSL:
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/1c898c6c-e952-41eb-ab7d-cd863efb7663)
Legacy GLSL
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/a94b2b7b-2797-409b-a57a-bf584c829e72)

### Version

2.4-beta

### OS

Ubuntu Focal

**Comment by m0dB** [comment]
On it.

**Comment by m0dB** [comment]
I can't reproduce this on macOS:

<img width="128" alt="Screenshot 2024-01-30 at 19 13 48" src="https://github.com/mixxxdj/mixxx/assets/79429057/30b21a7b-4ffb-4f36-aa57-6e3e7507470f">

<img width="137" alt="Screenshot 2024-01-30 at 19 14 03" src="https://github.com/mixxxdj/mixxx/assets/79429057/62452673-4dea-43e0-acf8-61e0b03aa458">

**Comment by m0dB** [comment]
the alpha transparency is different, but the pixel with is the same.

**Comment by daschuer** [comment]
Ah, it is the transparency only.
Than we can close it. Thank you for confirming.
