### ISSUE TITLE
Controller headphone output does not work but works with other DJ software

### ISSUE THREAD

**Issue by bverkron** [mixxxdj/mixxx#12710]
### Bug Description

Using a Numark MixTrack Pro FX on a Macbook Pro M1 and I cannot get sound from the headphone output in the controller.

It worked in previous version of Mixxx and on an older Intel based Macbook and works in other DJ software like Serato Lite on this laptop but I cannot get any output when using Mixxx.

I tried wiping the Mixxx config and reinstalling a fresh copy and starting from scratch and no change. I've attached the log for reference but I did not get any errors in the UI during this fresh setup.

I opened Mixxx, went into settings and selected the controller, chose the appropriate mapping, set the Sound Hardware > Output as follows and only get sound from the speakers (plugged into the Dell monitor) but not the headphones plugged into the Numark controller. Cue is enable on the controller and I can see it's also enabled in Mixxx

<img width="1321" alt="controller mappings" src="https://github.com/mixxxdj/mixxx/assets/19174503/70e862ea-f702-4740-badf-0cc591ce76ea">

<img width="1321" alt="sound output settings" src="https://github.com/mixxxdj/mixxx/assets/19174503/6a8f42a1-de34-4fe2-8aa5-302f463e0678">

<img width="2672" alt="main interface" src="https://github.com/mixxxdj/mixxx/assets/19174503/ad7311a2-1d3e-4f9f-be63-e9652c4bbbd0">

[mixxx.log](https://github.com/mixxxdj/mixxx/files/14135444/mixxx.log)

### Version

2.4-beta-432-g82c0ba2102

### OS

macOS Ventura 13.6.1 (22G313)

**Comment by bverkron** [comment]
Well that's a very "doh" moment for me. I read the doc and somehow missed the 3-4 for that setup. I did read the right section but may have had 1-2 burned in my brain from skimming past a bunch of "1-2" in the preceeding sections and the 
"1-2" right above that for the Main out. 🤦🏻‍♂️

It's pretty clear in the docs when I actually read it properly, thanks.

> ### [3.4.1. Controllers with an integrated soundcard](https://manual.mixxx.org/2.0/en_gb/chapters/setup#controllers-with-an-integrated-soundcard)
> ...
> ####  **Using a controller with an integrated multi-channel soundcard**
>
> 1. Open Preferences ‣ Sound Hardware
> 1. Select the Output tab
> 1. From the Master drop-down menu, select your controller’s soundcard, then Channels `1-2`
> 1. **From the Headphones drop-down menu, select your controller’s soundcard, then Channels `3-4`**
> 1. Click Apply to save the changes.

**Comment by Swiftb0y** [comment]
No worries. Have fun mixing.
