### ISSUE TITLE
Same title appears for different song

### ISSUE THREAD

**Issue by yokota101010** [mixxxdj/mixxx#12717]
### Bug Description

Given

- use Mixxx 2.4.0-beta

When

- add library

Then

- Same title appears for different song. like this...

![SameTitleDifferentSong](https://github.com/mixxxdj/mixxx/assets/49588152/db01eab5-a7b1-4848-b175-542640c6b5a0)
These three MJs are actually different songs.

### Version

2.4.0-beta

### OS

Windows 11

**Comment by ronso0** [comment]
Mixxx reads the file tags of those songs. Please verify with an external tag viewer/editor that the tags are **not** what you see in Mixxx.

**Comment by yokota101010** [comment]
When I looked it in File Explorer, the title was the same. It wasn't a bug.
![SameTitleDifferentSongInExplorer](https://github.com/mixxxdj/mixxx/assets/49588152/55433df7-919d-43d6-8e00-006a7e5ac609)

**Comment by ronso0** [comment]
Thanks for checking, closed as invalid.
