### ISSUE TITLE
Add spell checker to CI/CD pipeline

### ISSUE THREAD

**Issue by CodingSpiderFox** [mixxxdj/mixxx#12727]
### Feature Description

The spell checker in my vs code goes crazy because of unknown words like "playpos" etc. and I already found at least one real typo

I suggest adding cspell or something else to the project to reduce the likelihood of spelling mistakes in the projects.

At work I do this all the time as I have seen so many bugs caused by typos.
For example
* typos in customer facing texts (which is not that big of a problem most of the time but a bit ugly)
* config settings not being applied because of typing mismatch in expected config variable name and actual variable name (correct in ENV, wrong in code)
* especially when using JavaScript / TypeScript, you might even lose data because of wrong spelling of object properties

**Comment by Holzhaus** [comment]
We already have this in the form of the [codespell](https://github.com/codespell-project/codespell) hook for the [pre-commit](https://pre-commit.com/) framework. These checks also run on CI. 

See https://github.com/mixxxdj/mixxx/wiki/Using-Git#set-up-automatic-code-checking for details how to set it up.

**Comment by CodingSpiderFox** [comment]
Can I inspect the output of the codespell check?

It seems not to have caught this https://github.com/mixxxdj/mixxx/pull/12726

**Comment by Holzhaus** [comment]
You can check it by setting up pre-commit locally and then trying to commit a typo or use `pre-commit run -v`. On CI you won't see output unless a hook fails. 

In that case the issue is likely due to https://github.com/codespell-project/codespell/issues/196.
