### ISSUE TITLE
Feature: add default colors for cue points 1-8 (make this the default behaviour)

### ISSUE THREAD

**Issue by CodingSpiderFox** [mixxxdj/mixxx#12721]
### Feature Description

I want to make the cue points pads more accessible by allowing the user to assign a different color for the pads 1-8 so that whenever a cue point is created, it has the same color depending on the number of the pad pressed

**Comment by ronso0** [comment]
Is "By hotcue number" not working for you?
![image](https://github.com/mixxxdj/mixxx/assets/5934199/03894bcd-3a4b-4782-8d4f-35568e5394fb)

**Comment by CodingSpiderFox** [comment]
Totally overlooked that setting. Will try it right now

**Comment by CodingSpiderFox** [comment]
yes. Exactly that.
IMHO this should be the default setting

**Comment by ronso0** [comment]
Hmm, I'm not sure about the default.
IIRC when discussing hotcue colors we assumed this might be distracting.
IMO anyone interested in hotcue colors will find the Color preferences.

**Comment by CodingSpiderFox** [comment]
I think this would be more intuitive for users coming from Serato or something similar

Maybe we can implement a little onboarding wizard to new users where they can choose between "default palette, single color or custom palette" in one of the steps

**Comment by ronso0** [comment]
Yeah, a wizard would be awesome!

**Comment by Holzhaus** [comment]
Yeah, if we are super-ambitious we could even detect other DJ software and offer to import some settings like rate range, etc.

**Comment by CodingSpiderFox** [comment]
That would be really awesome :)

**Comment by CodingSpiderFox** [comment]
Did a quick search in the existing issues - should we continue the discussion regarding the wizard in https://github.com/mixxxdj/mixxx/issues/10257 ?
