### ISSUE TITLE
Configuring default settings for effects

### ISSUE THREAD

**Issue by mYnDstrEAm** [mixxxdj/mixxx#12723]
### Feature Description

I'd like to configure an effect and save that as default. Currently the effect settings are reset every time one switches to the effect and back.

If that is added, it would probably be useful if one could reset the default effect setting to its default (the default settings of effect after just installing mixxx).

This may be related to #8860

**Comment by ronso0** [comment]
Please try Mixxx 2.4 and play with the new effects implementation.
Each of the standard effect units has an effect chain menu button where you can adjust and show/hide effetc parameters, store, load effect chains etc.
Not sure if effect defaults are permanent or saved per chain preset.

**Comment by ronso0** [comment]
> Not sure if effect defaults are permanent or saved per chain preset.

Yep, if you
* re-arrange paramters (drag'n'drop) and/or set knob positions
* then open the chain menu > effect > "Save Snapshot"
* that state will be the new default whenever you select that effect anywhere else

**Comment by mYnDstrEAm** [comment]
Great if that's already possible. Seems like I can't install 2.4.0 from Debian repos. Would be nice if that version could be in backports...is that possible somehow?
It would also need a button to reset to default-default. A way to save and quickly load labeled snapshots would be useful too.

Once these two things are possible too I think the next step that would be tremendously useful would be having a way to quickly browse through effects and for example have a 6 effects view where one can quickly swap the upper effects with the bottom one if one doesn't have as many effects knobs on the mixer. Then all that would be left is more effects...I don't think there already are effects addons that add additional effects or are there?

**Comment by ronso0** [comment]
> Seems like I can't install 2.4.0 from Debian repos.

The recommeded way to install Mixxx on (debian-based) linux is via the Mixxx ppa
> Note: Ubuntu also provides a version of Mixxx which can be installed directly from the Ubuntu Software Centre. This version is usually woefully out of date; therefore using the PPA is advised.

https://mixxx.org/download/

Mixxx can use LV2 effects (if they#re installed in defaut locations).

**Comment by mYnDstrEAm** [comment]
I get this output when running `sudo add-apt-repository ppa:mixxx/mixxx`:
```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```

I meant effects usable with the effect knobs. What are LV2 effects...how to install them? I somehow found something to install that now shows under LV2 plugins but it's greyed out there and can't be used with effect knobs.

**Comment by ronso0** [comment]
> I get this output when running sudo add-apt-repository ppa:mixxx/mixxx:

The internet is your friend https://askubuntu.com/questions/1480616/adding-opencpn-repository-attributeerror-nonetype-object-has-no-attribute

**Comment by ronso0** [comment]
Mixxx supports LV2 effects that don't bring their own GUI, for example the Calf or Invada suit.

**Comment by mYnDstrEAm** [comment]
>E: The repository 'https://ppa.launchpadcontent.net/mixxx/mixxx/ubuntu bookworm Release' does not have a Release file.
>N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>N: See apt-secure(8) manpage for repository creation and user configuration details.
Well it doesn't work. This is after running just the command to install the PPA. If I should replace `bookworm` in the file `kwrite /etc/apt/sources.list.d/mixxx-ubuntu-mixxx-bookworm.list` that it generated, I don't know what to replace it with and I don't know [if it would create a FrankenDebian](https://wiki.debian.org/DontBreakDebian) by installing newer versions of dependencies.

> for example the Calf or Invada suit

Amazing! Thanks, they don't seem simple to use. How people are supposed to learn about this and find the plugins to install though? I think this should be part of the docs and linked to from the LV2 plugins page in the settings which could be referred to in the Effects page (like "If you want more effects, you can use LV2 plugins or develop and effects addon").

**Comment by ronso0** [comment]
Indeed, the only mention of LV2 in the manual is in some old changelog.

But, JACK is mentioned (it's one of the available sound APIs), and you get create pretty advanced routings with it.
https://manual.mixxx.org/2.4/en_gb/chapters/advanced_topics.html#effects-via-jack-rack-on-gnu-linux

https://github.com/mixxxdj/manual/issues/606
