### ISSUE TITLE
Feature: add tooling suggestions to contributing.md

### ISSUE THREAD

**Issue by CodingSpiderFox** [mixxxdj/mixxx#12725]
### Feature Description

I am not very experienced in C++ and Qt development

It would be helpful if some recommended VS Code extensions are listed in the contributing.md to help a new contributor start implementing something with a low entry barrier

**Comment by daschuer** [comment]
We already have that in our wiki: 

https://github.com/mixxxdj/mixxx/wiki/Visual-Studio-Code

I don't think that the contributing.md is the right place. There are many variants of development environments and many different personal preferences.

**Comment by CodingSpiderFox** [comment]
Please at least add a link to that wiki page in the contributing.md ;)

**Comment by daschuer** [comment]
We already have a link to the wiki. This does not mean the situation cannot be improved. We are happy to receive a pull request with suggestions. 

One pending issue is the read only access to the wiki because of spam and more serious attacks. If you have suggestion for a wiki update, pleas just mail it to me and I will update the wiki.

**Comment by CodingSpiderFox** [comment]
What is the IDE used by
a) the majority of the core team
b) the majority of the individual contributors?

I suggest adding these two IDEs more prominently as links in the contributing.md as I expect that the most commonly IDEs in the project have a higher chance of someone being able to offer help when someone has a problem getting started with that IDE

**Comment by Holzhaus** [comment]
No idea what the others are using but I'm using Vim with ctags + [ALE](https://github.com/dense-analysis/ale) in a terminal emulator ([alacritty](https://alacritty.org/)).

**Comment by CodingSpiderFox** [comment]
Added a poll in the Zulip

I think there could be quite a lot of people using VS Code

Anyways - what would be good is to either add the default config as suggested by the wiki to the git OR add the cbuild directory and .vscode directory to .gitignore because right now my git stage is polluted with the build config files I needed to add according to the wiki.

This is a bit annoying when I want to commit something because I always have to pay attention not to accidentally add the build config files to the commit

**Comment by ronso0** [comment]
> This is a bit annoying when I want to commit something because I always have to pay attention not to accidentally add the build config files to the commit

That's what a local gitignore is for.

**Comment by Holzhaus** [comment]
> Anyways - what would be good is to either add the default config as suggested by the wiki to the git OR add the cbuild directory and .vscode directory to .gitignore because right now my git stage is polluted with the build config files I needed to add according to the wiki.

The IDE is personal preference and doesn't belong into the project git. And since these VSCode-specific files are unrelated to the project, they don't belong into the project's gitignore file either. 

You should consider adding them to your global gitignore file instead, then you won't have that issue with any project: https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

We mention that in out gitignore file, too: https://github.com/mixxxdj/mixxx/blob/main/.gitignore#L1

**Comment by CodingSpiderFox** [comment]
Yes, that will work but it would be nice to have this also in the repo - at least my workflow is that I create a new VM for new OSS projects I discover and want to contribute. Usually I only do a minimal install of VS Code and sync the VS Code settings using my Github account - so I usually don't even install my dotfiles.

I don't know whether this has been an issue in the past but if people accidentally commit the config files of their IDEs that might be annoying in PRs when they don't realize this before creating a PR because then the PR needs avoidable rework

**Comment by Holzhaus** [comment]
> I don't know whether this has been an issue in the past but if people accidentally commit the config files of their IDEs that might be annoying in PRs when they don't realize this before creating a PR because then the PR needs avoidable rework

Hmm, it hasn't really been an issue in the past. Might have happened from time to time, but then people learn about the global gitignore feature😉

> at least my workflow is that I create a new VM for new OSS projects I discover and want to contribute. Usually I only do a minimal install of VS Code and sync the VS Code settings using my Github account - so I usually don't even install my dotfiles.

Interesting setup, have you considered setting up you VSCode + global gitignore and then making a snapshot of the VM before cloning the repo? Then you could just fork off that snapshot and even skip the tedious setup step every time you find an interesting project.
