### ISSUE TITLE
Feature: make controller mapping rows more accessible

### ISSUE THREAD

**Issue by CodingSpiderFox** [mixxxdj/mixxx#12720]
### Feature Description

I want to make the controller mappings list better accessible with a simplistic search feature ("string contains", case-insensitive)

When I enter a search term in the input / output mappings it should only display the rows with a matching text

**Comment by ronso0** [comment]
Already implemented in Mixxx 2.4 with #11165 
Please test 2.4-beta and open a new feature request in case this needs more tuning.

Thank you!
