### ISSUE TITLE
BPM mutliplier should be using the current deck BPM rather than the file BPM

### ISSUE THREAD

**Issue by acolombier** [mixxxdj/mixxx#12738]
### Bug Description

# How to reproduce

Here is the usecase:
- Deck A has a track with a BPM of 80
- Deck B has a track with a BPM of 128

- Adjust the BPM of deck A and B to 110 (using tempo fader)
- Enable sync using `sync_enable` or `beatsync_tempo`

## Expected 

The BPM multiplier should be `1`, and both track should keep the exact same BPM value (110 in the example)

## Actual

The non-sync master (of the channel calling `beatsync_tempo`)  BPM of the non deck gets set to 55 (if it's A) or 220 (if it's B)

# Fix options

1. In [synccontrol.cpp](https://github.com/mixxxdj/mixxx/blob/85d3d96f25e112e4b76b71f30d517b87bfe809d2/src/engine/sync/synccontrol.cpp), `SyncControl::slotControlBeatSyncTempo` and `SyncControl::reinitLeaderParams` could use `getBpm()` instead of `fileBpm()` if valid
2. Add new CO to ignore the multiplier, e.g `beatsync_tempo_absolute` and `absolute_sync_enable`

While `1.` feels like a better fix, I guess it may also be a breaking change in some cases so I thought I will mention `2.` although it definitely feels sub-optimal 

### Version

2.4.0

### OS

All

**Comment by daschuer** [comment]
This is a feature. We consider the smallest bpm change as the optimum to avoid chipmunk voices. 
55/80 = -30 % 110/80 = +38 %

**Comment by acolombier** [comment]
Yes, that makes sense in the case you simply want to match track's BPM effortlessly, however if you have already adjusted the BPM manually previously and want them to remain in-sync going forward (if you change the PM of one), wouldn't it make sense for it to consider the  adjusted BPM instead, rather then make a big jump from 110 to 55 as soon as you enable the sync? If not as default, would you consider as a configurable behaviour?

**Comment by daschuer** [comment]
I can imagine to add an extra rule that uses a snap region for this case. A preferences option will be to strict probably. 
What are reasonable borders for this new behaviour in corner cases?

**Comment by acolombier** [comment]
Somewhere around 5% should be more than enough to address my usecase.
I am wondering if it wouldn't be more natural for the user to use the current BPM of the deck in case it has been adjusted manually (e.g via `rate`, not using any of the `(beat)sync_*` COs)

**Comment by ronso0** [comment]
How would that work in the unattended AutoDJ case?
Would it be possible with a certain track set that this lowers (raises) the rate slider until we hit the boundary?

**Comment by acolombier** [comment]
I'm not sure I understand the usecase, does AutoDJ uses the `rate` CO directly? If yes, I guess the implementation could have some extra logic to detect `rate` adjusting orchestrated by AutoDJ and consider it automatic as well?

**Comment by daschuer** [comment]
If we look to the transition of these tracks in Auto-DJ: 
A 110 : Rate 0 % = 110 
B 80 :   Rate -31 %  = 55  
A 120 : Rate  - 8 % = 110  
B 180 (played at -31 % = 124): Rate  -38 %  = 110  

For the last track with 180 220 BPM would be better Rate + 22% 

You see that applying the current BPM will not work well in case of Auto DJ. 
 

But it seems we have actual an an issue in the initial case: 
80 :   Rate +38 %  = 110 
120 : Rate +83 % = 220  

+83 % rate slider is definitely to high. I will have a look.

**Comment by acolombier** [comment]
I feel like you might have misunderstood the bug I'm reporting. The other day, I was playing those two tracks together, and I wanted to increase the global BPM back to 128. As both track were already manually synch'ed (to 110) using the tempo fader, I made one of the deck sync leader, and as soon as I enabled sync on the other deck, the rate divide by two, before  I even had time to adjust increase the plating rate of leader as I was hoping to do in my routine, making the mix very weird as that vocal (the following deck was a vocal) suddenly was playing twice as slow.

I think the current multiplier logic makes complete sense as it is currently, but hopefully you will agree that the behavior I am describing is a bug.

Currently, this is how I have fixed in my dev branch, and it still to work still fine with the normal sync behavior you are describing. It is defintely flawed and I would assume it needs more work.
```
diff --git a/src/engine/sync/synccontrol.cpp b/src/engine/sync/synccontrol.cpp
index 66655a3465..6bb2496255 100644
--- a/src/engine/sync/synccontrol.cpp
+++ b/src/engine/sync/synccontrol.cpp
@@ -279,7 +279,11 @@ void SyncControl::reinitLeaderParams(
         kLogger.trace() << "SyncControl::reinitLeaderParams" << getGroup()
                         << beatDistance << baseBpm << bpm;
     }
-    m_leaderBpmAdjustFactor = determineBpmMultiplier(fileBpm(), baseBpm);
+    auto currentBpm = getBpm();
+    if (!currentBpm.isValid()) {
+        bpm = fileBpm();
+    }
+    m_leaderBpmAdjustFactor = determineBpmMultiplier(currentBpm, baseBpm);
     updateLeaderBpm(bpm);
     updateLeaderBeatDistance(beatDistance);
 }
@@ -434,7 +438,11 @@ void SyncControl::slotControlBeatSyncTempo(double value) {
         return;
     }
 
-    double multiplier = determineBpmMultiplier(fileBpm(), target->getBaseBpm());
+    auto bpm = getBpm();
+    if (!bpm.isValid()) {
+        bpm = fileBpm();
+    }
+    double multiplier = determineBpmMultiplier(bpm, target->getBaseBpm());
     m_pRateRatio->set(target->getBpm() * multiplier / localBpm);
 }
```

**Comment by daschuer** [comment]
> +83 % rate slider is definitely too high. I will have a look

It turns out that it is correct. When I sync the 120 bpm track to 80 it is shifted to 160, which is correct. When I now increase the tempo to from 80 110, the 120 bpm track is consequently playing at 220 bpm. This is really an extreme edge case.

**Comment by daschuer** [comment]
It looks like a simple patch works for you. 
```
--- a/src/engine/sync/synccontrol.cpp
+++ b/src/engine/sync/synccontrol.cpp
@@ -279,7 +279,7 @@ void SyncControl::reinitLeaderParams(
         kLogger.trace() << "SyncControl::reinitLeaderParams" << getGroup()
                         << beatDistance << baseBpm << bpm;
     }
-    m_leaderBpmAdjustFactor = determineBpmMultiplier(fileBpm(), baseBpm);
+    m_leaderBpmAdjustFactor = determineBpmMultiplier(fileBpm(), bpm);
     updateLeaderBpm(bpm);
     updateLeaderBeatDistance(beatDistance);
 }
```

It fixes my surprising rate of +83 % at least.

**Comment by acolombier** [comment]
Sorry @daschuer I missed the notification.
I remember your fix was also where I started, but I remembered only this was breaking other usecase (can't remember what sadly) 
I'll try an work on comprehensive patch
