### ISSUE TITLE
Ability to set and activate a beatloop from the end marker

### ISSUE THREAD

**Issue by acolombier** [mixxxdj/mixxx#12737]
### Feature Description

The usecase is the following: imagine you have a track about to finish and you don't have an extro in point set/hotcue. A great option would be to have a way to set a loop backward, by setting the end point rather than start point. This way, you can quickly set a 16 or 32 beats loop.

In order to be usable, this would also require to allow adjusting the beatloop length via `beatloop_size` even if the loop would go beyond the end of the track. The [logic](https://github.com/mixxxdj/mixxx/blob/fd41a3ad3f1a5f4b5fd21b09f953e3e8f3af37e9/src/engine/controls/loopingcontrol.cpp#L1476) in `LoopingControl::slotBeatLoop` could take into the account if a loop currently enable.

(Please help me finding a better title, I couldn't put words on my thoughts...)

**Comment by daschuer** [comment]
I can confirm that. 

Limiting the beat size in the beatloop box is anyway inconsistent, because you can put lets say 32 beats, and let the track play until no 32 beats are left.  

Loop out, has already tricked me, because it immediately jumps to Loop-In and that can be surprising, so I can imagine to use that somehow. Ideas?

**Comment by daschuer** [comment]
> slotBeatLoop could check if the loop would fit in between playpos and track end, and if not shift it in a way so it fits.

In many cases this will loop the garbage at the end of the track. We may cooperate with outro-end, but probably to much magic. 

The revers loop will also help to fix another issue, I have stumbled over. Sometimes tracks have a short intro that should need to be extended. Without being well prepared you may place a 16 beat loop that ends in the vocals or other unwanted sounds. With the back loop you have already listened to the loop portion and the result will be less surprising.

**Comment by daschuer** [comment]
What is the use case for loop out, when you not have placed a loop in just before? If there is no loop in before, nothing happens. If you have placed one, the desired thing happens. When you not placed one, the last loop-in probably form and old loop is used, which gives an undesired result. Is this single loop out, good for a revers beat loop? 
Maybe I have missed an important use case though?

**Comment by ronso0** [comment]
>  If you have placed one, the desired thing happens.

Uff, that might be the Loop In of a long-passed loop, potentially stretching over the entire track.

**Comment by acolombier** [comment]
> Loop out, has already tricked me, because it immediately jumps to Loop-In and that can be surprising, so I can imagine to use that somehow. Ideas?

Perhaps we could add a new CO similar to `beatloop_activate`, which would set a loop with `start=(current pos - beats),end=current pos`?
As I was glancing through the code fro loops, I came across [this](https://github.com/mixxxdj/mixxx/blob/fd41a3ad3f1a5f4b5fd21b09f953e3e8f3af37e9/src/engine/controls/loopingcontrol.cpp#L1458) and I'm wondering if this feature could somehow already exist. Obviously, it wouldn't be exactly as needed as this would me having the reverse the track temporarily and [disable](https://github.com/mixxxdj/mixxx/blob/cfca585c089a8b8366ab52800d0f30c71b708253/src/engine/controls/ratecontrol.cpp#L304) the slip mode right after, so not really an easy routine.

Let me know if you would like me to get started with a new CO implementation

**Comment by daschuer** [comment]
This would be a natural solution, go ahead. 
The issue which is still pending is how to present it on the skin and controllers.
