### ISSUE TITLE
Add hotcue #1 to track load point options

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#12740]
### Feature Description

I remember this has been requested before, and now again on the forums https://mixxx.discourse.group/t/newbie-to-mixxx-help-please/28933

Should be easy to implement.

**Comment by daschuer** [comment]
Using hot cue 1 as load cue seems to be a good idea. At least we will not have mapping issues. 

The main issue is the transition. If you have a library with many track, many will not have a hot cue 1 at a load position. So I think it needs a track by track decision. 

How about setting an option in the deck preferences that newly set  hot cue 1,  become a load cue?

**Comment by ronso0** [comment]
I'd expect that option to be simple: choose 'Hotcue #1' and make sure tracks have that set.
If not, use track start as fallback, like the other options.

**Comment by ronso0** [comment]
Just my 2 cents, I'm only relaying the request from the forums.

**Comment by daschuer** [comment]
The user is coming form Serato. How do they handle that? Do we have to respect something in the Serato Metadata?

**Comment by daschuer** [comment]
@Holzhaus Reading trough our Serato cue code it looks like we do not import a load cue. Does Serato have that?

**Comment by Holzhaus** [comment]
> @Holzhaus Reading trough our Serato cue code it looks like we do not import a load cue. Does Serato have that?  

It has a temp cue, but it's not saved in the metadata as far as I know. 

This is in line with the documentation on "Temporary Cues":

> The temp cue function allows you to set a temporary cue point in a track that is not saved to the file. This is useful for finding a point in a track and then being able to easily start again from this point as you get your mix right. By default, this is set to the beginning of the audio file. 

https://support.serato.com/hc/en-us/articles/233435527-Temporary-Cue
