### ISSUE TITLE
introduction of 'wait-list' or 'selection-list' (easy access, easy add files, accessible for auto DJ)

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12752]
### Feature Description

introduction of 'wait-list' or 'selection-list' (easy access, easy add files, accessible for auto DJ)
this is a live preparation list, order can be changed, tracks added (requests, ideas)
- easy access in the left -list column
- order is important (so playlist-type)
- possibility for decks to load the next song in the list automatic
- possivility to leave the songs in the list (no remove after playing, now I have to activate the repeat but then the tracks are moved to the end of the list.)
- possibility to enable auto dg
While Using Mixxx Istarted using auto dj as my preparation list because of the possibility to start the auto-dj ;-

**Comment by Eve00000** [comment]
**How great is it that I can answer my own issue now: (1year)**

I'd like to invite you to take a look at PR https://github.com/mixxxdj/mixxx/pull/14350 Preparation Window + Preparation Lists.
With a second window in library it's possible to D&D tracks from Playlists & Crates to Auto DJ / .Playlists & Crates (and preparation lists)
All loaded tracks to any player are automatically saved in 'today's Preparation List", you can also add last second ideas. The preparation list can stay opened in the second library window above the standard library view containg the siidebar and the known library view.
I'm keen on feedback.

**Comment by ronso0** [comment]
So why did you close this as "Not planned" then?

**Comment by Eve00000** [comment]
you did ;-)

![Image](https://github.com/user-attachments/assets/1ff8d029-571d-42ec-808a-588ae8b52c7b)

**Comment by ronso0** [comment]
Hehe whoopsy got confused in the mobile view.
