### ISSUE TITLE
Mixxx crashes

### ISSUE THREAD

**Issue by Txus2019** [mixxxdj/mixxx#12759]
### Bug Description

Devices attached: none. Using sysdefault as "Main" only.

I use AutoDJ continuously.
Sometimes Mixxx exits itself without apparent reason; the window closes and Mixxx restarts but other times it does not restart automatically. This happens sometimes, so I don't know the reason of the crash.

### Version

2.3.6 (HEAD)

### OS

Linux Mint 21.3 Virginia

**Comment by Swiftb0y** [comment]
Thank you for reporting your issue. Please understand that in order for us to be able to properly debug this, we need a backtrace. Have a look at the wiki for finding out how to create one: https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces
