### ISSUE TITLE
Sampler: possibility to save/load a selection of samples that can be started/stopped with keypad.

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12757]
### Feature Description

Sampler: possibility to save/load a selection of samples that can be started/stopped with keypad.
Of some songs an a capella version can be found, it's nice to play with samples of this song over another song.
example = Samplelist = song a; 1 = line 1; 2 = line 2..... easy start / stop is important (no mouse)

**Comment by ronso0** [comment]
Not sure what exactly you are requesting here.
You can customize the keyboard mapping to cover as many samplers as the skin provides an interface for.

There is also `[Sampler],SaveSamplerBank` and `[Sampler],LoadSamplerBank` which you can map to keys.
https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#global-sampler-controls

**Comment by Eve00000** [comment]
Thank you for your response, 
I've found out (via google search, not in wiki) that sampler controls are:
[Sampler1] 
play 
hotcue_1_activate 
this item can be closed, if a propper description is added to 
16.1. Keyboard mapping table[](https://manual.mixxx.org/2.4/en/chapters/appendix/keyboard_mapping_table.html#keyboard-mapping-table)
thank you
