### ISSUE TITLE
Possibility to add a key-shortcut for prelistening. (space = start stop selected track;  left/right = scroll in selected track)

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12754]
### Feature Description

Possibility to add a key-shortcut for prelistening selected track. (space = start/stop selected track;  left/right = scroll in selected track)

**Comment by ronso0** [comment]
There are keys for previewing, and the have been updated recently.
#12639 
P
Shift+P
Alt+Left/Right

Is there anything else that can be improved?

**Comment by ronso0** [comment]
also you can customize your keyboard mapping
https://manual.mixxx.org/2.4/en/chapters/advanced_topics#advanced-keyboard

Please check the manual and the existing Issues before posting feature requests, checking / cleaning up bugs / feature requests uses developer time that would better be spent onf actual features and bug fixes.
Thank you!

**Comment by Eve00000** [comment]
the custom sampler controls were not in the manual....
