### ISSUE TITLE
playlist - count and totaltime not updated when adding a song

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12761]
### Bug Description

When adding a song to a playlist the playlist - count and -totaltime are not updated, both dragging song to playlist and right click.
After restart of Mixxx the counter and time are right.

extra, after de-selection (other song) and re-slecting song  the playlist is bold (=song is in playlist) 

### Version

2.5-alpha-229-g7b3e48544a (main)

### OS

Win 10

**Comment by ronso0** [comment]
Can confirm the playcount issue, repaint on selection change (bold) works though.

Crates are not affected, so it's probably some issue in [PlaylistFeature::slotPlaylistTableChanged](https://github.com/mixxxdj/mixxx/blob/7b3e48544a5a5475553742678115951179c41526/src/library/trackset/playlistfeature.cpp#L326) and/or [PlaylistFeature::constructChildModel](https://github.com/mixxxdj/mixxx/blob/7b3e48544a5a5475553742678115951179c41526/src/library/trackset/playlistfeature.cpp#L284)

**Comment by m0dB** [comment]
(Thanks @ronso0 for spotting the duplicate bug report)

As I have been watching this behaviour closely while working on https://github.com/mixxxdj/mixxx/pull/12020 , I am sure this was working correctly not too long ago.

**Comment by m0dB** [comment]
I am removing the Qt6 tag, as I am sure it worked correctly with Qt6, so I doubt it is Qt version related.

**Comment by ronso0** [comment]
Damn, stupid typo :man_facepalming: 
https://github.com/mixxxdj/mixxx/pull/12494/commits/8b7927822c1c12961d203bd6d3985e0c41b974c5

I'll push a fix asap

**Comment by ronso0** [comment]
but something else is wrong... I'll take a look.

**Comment by m0dB** [comment]
Thanks for looking into this, @ronso0. If you get stuck, let me know; while I am certainly not an expert on this part of the code base, I have been looking at it quite a bit recently :-)

**Comment by Eve00000** [comment]
Oh, there(s something going on here  :-)
not as easy as you thought?

**Comment by ronso0** [comment]
I'm still not sure how this broke (currently bisecting), but a simple `m_pSidebarModel->triggerRepaint()` after updating the tree item label fixes it. Seems setting the label does not make the model emit `dataChanged(index)`.
