### ISSUE TITLE
Strange text in log-files : "FUCK YOU MOTHERFUCKERS\nfuck you" , 1

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12770]
### Bug Description

Reading the logfiles I found following text

Warning [Main] QString::arg: Argument missing: "FUCK YOU MOTHERFUCKERS\nfuck you" , 1

on different timestamps, in total (10 logfiles together) +/- 3000 times.
Can Somebody explain please?

### Version

2.5-alpha-229-g7b3e48544a (main)

### OS

Win 10

**Comment by JoergAtGithub** [comment]
It seems somebody spamed our translation files with this: https://github.com/mixxxdj/mixxx/blob/b8adc2181d241caaae5dac96eed85636a1c8fef9/res/translations/mixxx_nl.ts#L742

**Comment by Eve00000** [comment]
Can I enter a translation, I am a native dutch speaker.

**Comment by JoergAtGithub** [comment]
> Can I enter a translation, I am a native dutch speaker.

In general yes: https://github.com/mixxxdj/mixxx/wiki/Internationalization

But since this is just vandalsim overwriting the original translation strings, it would be better, if we find a way to just restore the original strings.

**Comment by Eve00000** [comment]
When I enter the dutch translation, how do I have to save my work?

**Comment by Eve00000** [comment]
> > Can I enter a translation, I am a native dutch speaker.
> 
> In general yes: https://github.com/mixxxdj/mixxx/wiki/Internationalization
> 
> But since this is just vandalsim overwriting the original translation strings, it would be better, if we find a way to just restore the original strings.

I imagine you have a tracelog so you can block the one who did this....

**Comment by ywwg** [comment]
thank you! It looks like the spammer only changed strings that were "unfinished" in the original translation files so we don't have proper text to revert to.  We would greatly appreciate your contribution.  

https://github.com/mixxxdj/mixxx/wiki/Internationalization
https://explore.transifex.com/mixxx-dj-software/mixxxdj/

**Comment by ywwg** [comment]
Please do the work in transifex, that's where the spam came from.  We'll lock down that system. Our github tree is secure.

**Comment by Eve00000** [comment]
I followed the Internationalization - manual, I signed up to transifex. I joined the translation team.
Fo I have to wait for authorisation? I can't see where to enter a translation.

**Comment by ronso0** [comment]
oh, smells like Deejaygirl trouble :/

**Comment by mxmilkiib** [comment]
Or that one who couldn't fix the hamster crossfader for their controller.

**Comment by Eve00000** [comment]
It took some time to get the transiflex working pffft ..... Now I can't find the spamed text.

**Comment by Eve00000** [comment]
No, I found them and I am correcting them now

**Comment by Eve00000** [comment]
I corrected all lines where in the translation 'FUCK YOU MOTHERFUCKERS fuck you" could be found in https://github.com/mixxxdj/mixxx/blob/40be3fe23524982a47931c6e6d7bfc71b314371d/res/translations/mixxx_nl.ts#L718-L71.

Is it so easy to adapt / screw the software?
I hope you can make a BU.

**Comment by daschuer** [comment]
Thank you for your help. Now all FUCK is gone from Transifex and our repro.

**Comment by Eve00000** [comment]
I(ve seen that all Dutch translations still need to be aproved. Who does this?
How can I see in/for witch screen/function/knob;  a 'to translate' sentence occurs/is used?

**Comment by daschuer** [comment]
I think I have already integrated your translations. I will heave a second look. Is there a specific string that requires approval? I am German and can't do it maybe @m0dB 

Are you from the Netherlands? There is also the issue that we like to drop the redundant nl_NL translation, but we are afraid to loose some work. You may help by comparing differences and pick the best for both. Once nl_NL and nl are equal we can drop nl_NL. I recommend to use a diff tool like Meld or Notepad++ and edit the ts filed directly. 
https://raw.githubusercontent.com/mixxxdj/mixxx/2.4/res/translations/mixxx_nl.ts
https://raw.githubusercontent.com/mixxxdj/mixxx/2.4/res/translations/mixxx_nl_NL.ts

**Comment by daschuer** [comment]
I have double checked with "Afbeelding ophalen" it is pending for approval but already part of Mixxx. So it looks like the approval is not mandatory.

**Comment by Eve00000** [comment]
I am a Belgian, native Dutch speaker (also French / English / German / Italian). I(ve seen there are nl, nl_NL nl_BE ...
In the transiflex I could see there around 300 sentences of the 3000 to be translated and all of them need to be aproved (transiflex stuff).
I am glad I could help and add a little bit so If I can help with comparing and completing the Dutch translation, with pleasure..
I will compare nl, nl_BE and nl_NL and as a result I will send you the nl.ts Correct?

I see it's for 2.4, is that correct? (I did the translations and corrections for 2.5 I think).

**Comment by daschuer** [comment]
Transiflex has proposed your translations also for the 2.4 branch and I have adopted them. 

Yes, send me the unified ts file, than I can upload it. 
Thank you again n advance. 

Just out of curious, are there Belgium-Dutch words only used in Belgium?

**Comment by Eve00000** [comment]
In transiflex I saw there was a team for every language with eammanagers ... I thought they had to approve the translations.
It is not so that the Mixxx-community exists of dunfreds of peole? With lots of volunteers taking part of the translation etc?

There's a difference between the Dutch language in the Netherlands, Belgium, Suriname, Antils .... They are all a kind of dialect, like French in (South) Belgium differs from French in France/Switzerland, Africa, Quebec / Like German Deutsch / Hoch Deitsch is not the same as Swiss Deutsch / North-Italian Deutsch / Deutsch in Austria 
But the standard language / official language / technical (computer) language is the same, for every language. 
So Dutch speaking people from Belgium / The Netherlands .... will all understand the standard Dutch translation.

extra: I've seen a lot of strange translations, made by people not knowing where they were talking (writing) about. They tried to make a construction of words that is quite similar to the English sentence but their writing had no sense at all.
In my opinion not ever word has to be translated.  The English words 'Song' 'Player' 'History' can be used in Dutch, in German .... Those are international words, a translation can make it more difficult to understand. Certainly DJ's are use listen to English songs, can read English manuals ....

**Comment by Eve00000** [comment]
Good [evening,](url)
I had a free day today and instead of cleaning the house I translated, checked, corrected....
Once I started I wanted to finish it.

I just finished the Dutch translation-file.
ok_NL.ts can replace nl.ts, nl_BE.ts and nl_NL.ts
I think that 
- 2/3 of the previous translations were made by Google translate, 
- 2/3 of the translations were made by people completely odd to DJ-ing / Music / Sound hard- and software
- A lot of people translated sentences without checking other translations.
- 20% of the Translations were very strange in Dutch, , Theu were much more clear in English.
So...
- checked all translations, re-translated about 70 - 75¨%
- added missing translations.
- I've put some continuity in the translations (vocabulary, construction of sentences, typography)

There could be some errore or mistakes, my apologies upfront.
I've learned some extra's about Mixxx today, especially concerning Effect-processing.

I had to add a .txt extension because a  *.ts file was not accepted here
[ok_NL.ts.txt](https://github.com/mixxxdj/mixxx/files/14250007/ok_NL.ts.txt)
Have a good evening,
Eve

**Comment by daschuer** [comment]
Thank you very much Eve. I have updated the nl translation and deleted nl_BE and nl_NL. 
Unfortunatly there where some issues which file encoding and mass renaming. I have fixed that. Hopefully I did not messed up anything. Please verify.
