### ISSUE TITLE
Changing controller mapping preset made waveform vastly shrink in height

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12777]
### Bug Description

I was changing from my Reloop Beatmix 4 user preset back to the default to test for https://github.com/mixxxdj/mixxx/pull/12769 and the waveform height jumped from looking like a normal track to ![image](https://github.com/mixxxdj/mixxx/assets/108225/4b3c7d33-60e1-400b-8095-2c6801423215).

I can't 100% be sure it was when the default preset was selected, my memory is bad, it might have been on Apply.

I've tried changing back and forth a few times since, not sure how to reproduce..

### Version

2.4-beta

**Comment by ronso0** [comment]
Is it just the decks' pregain being reduced?

**Comment by mxmilkiib** [comment]
Yes. I forgot my controller can report the status of paramaters!
