### ISSUE TITLE
Hotcues: first time a UI button is clicked, it turns black

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12778]
### Bug Description

As title really. The next button is clicked, the new one goes black and the last one goes the right colour. Delete a hotcue then remake and the colours ir correct. Using Deere-custom and original.

I guess related to https://github.com/mixxxdj/mixxx/pull/12733?

### Version

2.4-beta

**Comment by daschuer** [comment]
A fix is here: https://github.com/mixxxdj/mixxx/pull/12785
