### ISSUE TITLE
Highlight the full line of the track, in the track list, when preview a track

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/mixxx#12789]
### Feature Description

I is difficult to read the data of a track when preview, in the track list. Only Preview icon change to red color, but it does not help to read data in columns far away from right.

If the full line of preview is highlighted, it is a lot more easy, like when I click on another column in the track list.

**Comment by ronso0** [comment]
What kind of highlight do you propose?
It should not conflict with track colors, and we need to consider that users may have a custom library font (bold, italic etc.)

**Comment by RafaelFrance** [comment]
I thing about the current highlight when I click on any column (excepted Preview) of a track in the track list. It is perfect, nothing more is needed.

**Comment by ronso0** [comment]
You mean you expect the row to be selected when you click the button in the Preview column?

If yes, that sounds reasonable. At least it would be consistent with clicks in any other column.
And I can't imagine why one would like to keep the current selection when clicking the preview button. On the contrary, that would simplify loading that track to a deck (with Return key if double-click is configured accordingly in the Library preferences, Mixxx 2.4)

**Comment by ronso0** [comment]
That was easy: #12791

**Comment by RafaelFrance** [comment]
_"You mean you expect the row to be selected when you click the button in the Preview column?"_

Yes.

Thanks
