### ISSUE TITLE
Move playhead on waveforms from center to left

### ISSUE THREAD

**Issue by SephReed** [mixxxdj/mixxx#12814]
### Feature Description

I'd like to be able to see further in the future, and I don't care much about waveforms that have already passed.

It would be nice if I could have the playhead moved to the left, instead of being in the center.
<img width="1397" alt="image" src="https://github.com/mixxxdj/mixxx/assets/14002040/e17e25b0-1759-48f1-8071-7145ddaa9707">

**Comment by ronso0** [comment]
Take a look at the Waveform preferences, there's a slider for exactly this purpose ; )

**Comment by SephReed** [comment]
No idea how I missed it.  Mixxx is the best!

<img width="898" alt="image" src="https://github.com/mixxxdj/mixxx/assets/14002040/a9c3bc9c-f367-4143-873d-c410ebe620b3">
