### ISSUE TITLE
Undo BPM Grid Change

### ISSUE THREAD

**Issue by SephReed** [mixxxdj/mixxx#12816]
### Feature Description

I've messed up a few bpm grids by clicking something I didn't mean to.  There's no way to go back.  Sometimes I can never get them back to where my cues line up with the lines.

**Comment by SephReed** [comment]
I've also deleted cues off the wrong track multiple times, or set cues on the wrong track, or set cues at the wrong time

**Comment by mxmilkiib** [comment]
This is kind of the same as #12774 I think, storing the state of BPM+beatgrid for undo purposes

**Comment by ronso0** [comment]
The question is which beat state should be stored:
* the state from the database when Mixxx is started (wouldn't cover newly loaded / unanalyzed tracks)
* the state when the track is loaded (wouldn't cover library actions on unloaded tracks)
* the last beat change? might be the beat shift, so any state before the last change that would be lost

**Comment by ronso0** [comment]
> or set cues on the wrong track, or set cues at the wrong time

> or move knobs and not liking the change.

Well, how exactly should Mixxx help with user 'errors'?

**Comment by mxmilkiib** [comment]
Regarding library actions made on a track without loading it; is that "loading" as in to a deck? I.e. not the "loading" of it into memory/an analysis algorithm?

The case of reanalysing an entire, say, 50GB (or very much likely more in some cases) library is something to ponder about how an undo mechanism might work in relation to. (Aside from the other issues you raise, Ronso.) I.e. a *lot* of memory use, or a *lot* of disk writes, or both in the case of paging/swap.

This is certainly not a non-trivial thing, as handy as it would be!

**Comment by m0dB** [comment]
Ideally it should be a stack with undoable (and redoable) actions.

**Comment by ronso0** [comment]
I'll close this as fixed, now that #12954 has been merged.

> I've also deleted cues off the wrong track multiple times, or set cues on the wrong track, or set cues at the wrong time, or move knobs and not liking the change.

I think this is covered by #13307
