### ISSUE TITLE
URGENT: On stage right now, where do I invert the polarity of a single channel for balanced output?

### ISSUE THREAD

**Issue by SephReed** [mixxxdj/mixxx#12837]
### Bug Description

Invert one channel.  How?

### Version

2.4

### OS

MacOS

**Comment by SephReed** [comment]
I have 20 minutes.  Please tell me this feature exists.

**Comment by ronso0** [comment]
Nope, this is not a feature Mixxx provides.
You should look into your sound card / sound server configuration instead.

Please explain why exactly that would be required, never heard that would be done in a music app.

**Comment by ronso0** [comment]
Btw for support there are the forums https://mixxx.discourse.group, not the bug tracker.

**Comment by SephReed** [comment]
To connect to a soundboard.  I don't understand.  Has nobody ever plugged their laptop headphone jack into a soundboard that expects balanced inputs using mixxx?

**Comment by ronso0** [comment]
AFAIK DJ / studio mixers that can handle balanced line inputs can also deal with unbalanced inputs.
I don't understand why you need to invert a channel?

What exact device are plugging into? And how?

**Comment by ronso0** [comment]
Quick fix:
select Mono mixdown in Mixxx preferences and pick a mono input on the mixer.

**Comment by mxmilkiib** [comment]
You might use a DI box to connect a laptop to a mixer that only accepts balanced XLR connections. Kinda strange if it's wanting balanced quarter inch jacks. What a strange mixer, that it doesn't have RCA phono input. Unfortunate that the venue can't help, or that there was no technical rider.

**Comment by SephReed** [comment]
First of all, sorry to jump this on here in the wrong place.  But I was in a pickle and this seemed like the quickest way to find help.

Secondly, I put in a feature request: https://github.com/mixxxdj/mixxx/issues/12838

> select Mono mixdown in Mixxx preferences and pick a mono input on the mixer.

Tried this, and it did as expected: both channels were exact copies and when one was flipped at the mixer they added up to nothing.

In the end, I was able to run home and grab a tool to make it work.  Unfortunately, that tool is not something I can carry around with me when I start traveling Asia.  Even the smallest external tools are huge (https://www.amazon.com/s?k=balanced+to+unbalanced+audio+converter&crid=14ME1G5KFINGB&sprefix=balanced+to+un%2Caps%2C183&ref=nb_sb_ss_ts-doa-p_1_14).

It's also just... so ridiculous the idea of having to buy special equipment to multiply a signal by -1.  It's literally a one-bit difference per sample (float).  The fact this feature doesn't exist yet blows my mind to the point it gives me paranoia.  Like... this can't be real.  This is surely a shitty simulation running on minimum power.  There is no way I'm special by understanding it's possible to connect a laptop directly to any input on a mixer with nothing more than a cord as long as you can output a balanced signal.  How could this happen?  Or are people just proud of their DI boxes and big equipment?  Perhaps minimalists are such a minority, we aren't even on the radar.

I dunno.  Just hard to believe.

**Comment by mxmilkiib** [comment]
DI boxes are one of the most common items kit, universally used. They're that big to be robust. These things are likely to get kicked by accident, and they have to survive getting unpacked and packed many times during a tour and being transported around in boxes that might get agitated/dropped/etc. For size, they're not much bigger than a guitar pedal. Maybe there is a more compact form that's lighter for an individual to lug around the world with. Let's check thomman.de; they're in PA Equipment, PA Accessories (that subcategory uses them for its image); https://www.thomann.de/gb/di_boxes.html?ls=100 180 types available, I'm surprised but not shocked. I guess some might have preamps too(?). SOS, the biggest long running audio engineering magazine, at least in the UK; https://www.soundonsound.com/sound-advice/di-boxes-why-we-need-them article published 98, cos the principle and essential form of these things really isn't going to change. For active, don't rely on all venues having desks with phantom power, and have a backup 9V battery or two! Also; https://old.reddit.com/r/audioengineering/search/?q=%22di+box%22+laptop for anecdotal ins and outs. Directly searching for "compact robust DI box", and you get ones that look like USA sticks of butter (I think); heres another audio mag I bought several times many years ago; https://musicradar.com/news/best-DI-boxes "The humble DI box is arguably one of the most overlooked pieces of musical equipment on the stage or in the studio - many players don't even know they need one." Looking at the Moose Micro DI, that has cabinet simulation, which I didn't think of; DIs are used for guitars when you're not micing up a cab.
