### ISSUE TITLE
Icecast2 audio stream sound choppy since update

### ISSUE THREAD

**Issue by jmfergeau** [mixxxdj/mixxx#12859]
### Bug Description

The sound rendering from mixxx when connecting to an icecast2 server has the sound rendering choppy every 10 seconds averagely. No problem happens with the previous version 2.3.6.

Sorry if it has been posted already, i haven't checked.

### Version

2.4.0

### OS

Arch Linux with LTS kernel

**Comment by daschuer** [comment]
Does the ~/.mixxx/mixxx.log contain any problems? Which sound API do you used? What is your Engine clock and buffer size?

**Comment by jmfergeau** [comment]
> Does the ~/.mixxx/mixxx.log contain any problems?

I checked the logs made but my basic knowledge of logs didn't made me spot errors or anything relevant. Here's hte complete log: 
[mixxx.log.zip](https://github.com/mixxxdj/mixxx/files/14376509/mixxx.zip)

> Which sound API do you used? 

I haven't checked but, if the update didn't change it (knowing it resetted my UI) it's ALSA.

> What is your Engine clock and buffer size?

Soundcard clock and audio buffer at 5.8 ms if, as above, it didn't change with the update.

**Comment by daschuer** [comment]
I see s probably unrelated warning: 
```
Warning [Main] -60 dB Sound Cue ends after track end in: "/home/max/Musique/DJplaylist/they_call_me_sonic-eurobeat_mix.mp3" Using the last sample instead.
``` 
If you did not edit the track with a third party tool, this is an indicator for a decoding issue, that may have been introduced when fixing an other issue. Reanalyzing will fix the issue.  

I don't see anything else concerning.

**Comment by jmfergeau** [comment]
Thanks. I did what you said and made some new tries and the problem doesn't seem to occur again after 20 mins of test. To be sure, i reinitialized all the tracks. I'm surprised the problem could be that...

Keeping it open just in case it reappears, though. Feel free to close it after a few days if I don't add updates. :p

**Comment by ronso0** [comment]
We'll likely forget about, so let's do it the other way around ; )
Reopen if you encounter it again.
