### ISSUE TITLE
track count and total duration of tracklists not updated in sidebar

### ISSUE THREAD

**Issue by m0dB** [mixxxdj/mixxx#12865]
### Bug Description

When adding tracks to a playlist or crate, the amount of tracks and the total duration as shown in the sidebar is not updated. Only after restarting the application it is.

I first noticed this in my branch https://github.com/mixxxdj/mixxx/pull/12020 , but it is also broken in main. I am sure it used to work correctly not too long ago.

### Version

2.5-beta

### OS

macOS 14.1.2

**Comment by ronso0** [comment]
Is this a dupe of #12761?

**Comment by m0dB** [comment]
It sure is. I will close this one.

**Comment by m0dB** [comment]
Closed as duplicate.
