### ISSUE TITLE
Usability: Improved Beat Counting Visibility

### ISSUE THREAD

**Issue by daliaabbruciati** [mixxxdj/mixxx#12879]
### Problem Description
Currently, the beat counting in the mixing program is not adequately highlighted, making it challenging to count accurately during track playback.

### Improvement Proposal
I request the implementation of a notable visual enhancement to clearly highlight beats in the program's timeline. This will make beat counting easier and more immediate during mixing.

### Additional Details
- Context: I am using version 2.3.6 of the program on operating system macOS Sonoma (14.2.1).
- Screenshot: I am attaching a screenshot illustrating the issue and how it could appear with the proposed improvement (visible white bars).
<img width="1450" alt="SCR-20240226-tzpv" src="https://github.com/mixxxdj/mixxx/assets/48596560/4ddf59d2-632d-411d-b296-fdb559802c52">

### Expected Outcome
After implementing the proposed enhancement, beats should be clearly visible, facilitating precise counting during mixing.

Thank you for your attention and for your ongoing commitment to improving this excellent tool!

**Comment by ronso0** [comment]
I think you're referring to _bars_ or _downbeats_, not beats.
There is work in progress, incl. anvanced beatgrid editing capabilities #12343

**Comment by daliaabbruciati** [comment]
yeah @ronso0 I was thinking in terms of bars but I wrote beats :/ 
By the way, thank you for your reply.
