### ISSUE TITLE
History labels do not expand when renamed

### ISSUE THREAD

**Issue by idcmp** [mixxxdj/mixxx#12880]
### Bug Description

(I tried to search for this, but I didn't know the right words.)

1. Go into History, right click on one and pick Rename.
2. increase the length of the name (add 10 X's at the end), click Save.

Label shows up with ellipses ("2024-02-25 XX..."), even when the sidebar is wide enough. I don't know if it matters, but I'm on LateNight Classic.

### Version

2.4.0 (HEAD)

### OS

macOS arm64

**Comment by imanbadaui** [comment]
I'm experiencing a similar issue on Windows, but found that double right-clicking on it expands the name.

**Comment by ronso0** [comment]
I can confirm this on Linux.
Looks a bit like #12761 where no repaint was triggered (and right-click would update the label as expected)

I'll take a look.
