### ISSUE TITLE
Un-eject / un-replace does not respect "Loading a track when deck is playing" setting

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#12906]
### Bug Description

- Dubbelclick on "Load/EjectSwitch" of a Deck does not clone Deck, even when the option is selected  in settings
- Switching 2 - 4 Decks and back (multiple times) and between the switching clicking on "Load/EjectSwitch" of a playing Deck  causes "Ejecting" of the playing track, 
-  I suppose the option "disable load a track to a playing deck"  means also disable the possibility to eject a track while playing (as it is in 2.3.6)
-> I'm testing the main from 29/2/2024

### Version

2.5-alpha-255-g2d2d5f304b

### OS

Win10 / Win 11

**Comment by ronso0** [comment]
> "Load/EjectSwitch"

What control are you referring to?

The Clone option in the Decks preferences refers to buttons mapped to `[ChannelN],LoadSelectedTrack`. There is no GUI implementation of this control (in official skins), so this applies mostly to controller mappings.
How did you trigger this control?

FYI the Eject button has special behaviour, too. It does un-eject and un-replace, depending on whether a track is loaded or not. See https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-eject

**Comment by Eve00000** [comment]
- with controller double tap on load-knob
- with mouse in fui drag and drop playing track to other deck
- > eject button on controller / little eject button in gui, aftr a couple of times pressing on of the two the track unloads.
- > while there's a warning on exit; still playing track / iwhile it's mpossible to load a track to a playing deck, I think it should also be impossible to eject / unload a playing track. Don't you agree?

**Comment by ronso0** [comment]
> I think it should also be impossible to eject / unload a playing track. Don't you agree?

Explicit eject while playing is not possible (neither in 2.4 nor main).
So your request is to also suppress cloning if over-load/eject is suppressed? (that is not quite clear to me from your initial description)

**Comment by Eve00000** [comment]
No no, try it yourself, you need some actions... cloning, switching between 2 - 4 decks and back. Then at a certain point you can eject a playing track.  (as I wrote in my original post)
Really! Try ;-)
If you can't replicate it, I will make a video of it this evening.

**Comment by ronso0** [comment]
> switching between 2 - 4 decks and back

In the GUI, or in your controller mapping (1/3, 2/4 switches)?

**Comment by ronso0** [comment]
Can't reproduce with the GUI switch, this has no impact on the engine at all.

**Comment by Eve00000** [comment]
In the Gui, I don't have it yet on my controller.... still working on it.
I tried this also without a controller connected or mapped. On 2 different pc's

**Comment by ronso0** [comment]
Okay, please make a screencast then.

**Comment by ronso0** [comment]
Thanks for the video, but I still can't reproduce with current main.

Please go to Preferences -> Decks
Check if 'Loading a track when deck is playing' is set to reject.
If it already is, select another option, Apply.
Re-select 'Reject', Apply.
Redo the test. No playing deck should be ejected.

**Comment by Eve00000** [comment]
Hi ronso,I checked it again, with restart after change of the option. (it was my original post)
As you could see in the video loading a playing deck was not possible even the eject of a playing track was prohibited.
Only after a couple of switches and cloning it can happen.
There must be a combination of cloning and deck that does not reset a flag, Did you try it also without controller connected?
Maybe even a combination with cue-modus, track load .....

**Comment by ronso0** [comment]
Which cue mode / track load point have you selected?

**Comment by Eve00000** [comment]
I've tested with all of them, I prefer Mixxx-mode without flickering; I tried with intro-start on/off, track load ....
I know whattesting is about, 
I think it's something with the settings of a deck after being cloned / being a clone, maybe a variable that is copied wrongly, or that does not have a value.....

**Comment by ronso0** [comment]
Okay, so after watching the video I think I got it:
the new Un-Eject / Un-Replace (double-click Eject) is not respecting the "Loading a track when deck is playing" setting ("Reject").
The reason you see this "Only after a couple of switches and cloning it can happen." is that it requires a different being loaded previously.

I'll take a look.

(2/4 deck switching is irrelevant)

**Comment by Eve00000** [comment]
Good thinking!
So you like my video after all, even when it takes more data :-)

**Comment by ronso0** [comment]
Somehow I do ; )
What made the difference to your description:
* clicking the Eject button like mad with the _first track_
* same with the _second_ track

So now that you  are an advanced bug and feature reporter you can try to list all steps you took since starting Mixxx.
Maybe we can figure it out that way next time.

**Comment by Eve00000** [comment]
Clicking like mad :-) I knew I would happen, it occured while playing music in a normal way, so I had to regenerate the ejecting.
Oh I can be mad  :-)
I'll do my best to describe as good as I can, (I crossed my fingers while holding two fingers up in the air)

**Comment by ronso0** [comment]
Okay, the fix was easy. It was just that the "is playing?" check was done too late, should happen right away after eject changed so that we always prohibit eject/un-replace for playing decks.

**Comment by ronso0** [comment]
PR coming soon
