### ISSUE TITLE
add Track colour palette cycling controls for decks

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12905]
### Feature Description

There is `track_color` but that's to set a specific rgb colour. (#2541)

It would be handy to be able to use MIDI to cycle through the limited palette of track colours that are available via the Library UI.

Mapped to a rotary encoder.

**Comment by ronso0** [comment]
So basically a per-deck equivalent for `[Library],track_color_prev`](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[Library]-track_color_prev)

**Comment by mxmilkiib** [comment]
Cheers! I'm going to focus on looking at the fractional BPM scaling control the now.
