### ISSUE TITLE
Clicking to select a track often initiates a drag&drop

### ISSUE THREAD

**Issue by m0dB** [mixxxdj/mixxx#12902]
### Bug Description

Often when I click on a track to select it, this triggers the initiation of a drag&drop. This happens if in the brief time between mouse press and mouse release the mouse is moved only minimally, which is very common, especially when using a track pad. Though nothing happens with the drag&drop, it is strange and confusing and could be easily avoided. I will create a PR with a (very simple) fix.

### Version

2.4, main

### OS

macOS

**Comment by ronso0** [comment]
Isn't this a system setting, "drag-and-drop threshold"?

**Comment by m0dB** [comment]
answered in the fix
