### ISSUE TITLE
Beat Jump forward using TRAKTOR Z1 Controller

### ISSUE THREAD

**Issue by gesacyprus** [mixxxdj/mixxx#12919]
### Bug Description

I have to appreciate the hard work, the Z1 controller working fully, all knobs work fine as well the mapping. However I discovered random Beat jump forward when I was playing past Saturday. I tested the controller on 2 different Lap tops, one PC Intel I5 16GB RAM and the other I7 16GB RAM, both 8th generation, the problem occurs again
then I used the same track with a different sound card, the beat jump did not occur. That made me think the controller Z1 is not fully integrated with XMIXXX 2.4. otherwise everything else works fine.
Thank you

### Version

2.4 new release

### OS

Windows 10 and Windows 11

**Comment by JoergAtGithub** [comment]
Is maybe the NI hardware service installed and running in parallel:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/5cd7dd01-f34c-468e-a137-3de8cfb0c813)

**Comment by gesacyprus** [comment]
Thanks a lot. Issue solved
