### ISSUE TITLE
microphone audio cuts out while recording

### ISSUE THREAD

**Issue by J-Marie123** [mixxxdj/mixxx#12923]
### Bug Description

I have a HP Pavillion 15-B123CL laptop. original windows 8 upgraded to windows 10 but can not upgrade to windows 11. I purchased several different head sets and microphones and they all work fine except in the MIXXX program. My voice cuts out constantly

### OS

Windows 10

**Comment by daschuer** [comment]
Where should you voice hearable and where not. 
When does it work and when starts your voice cutting out? Maybe it is a buffer size issue? Please ostva screenshot of you audio preferences.
