### ISSUE TITLE
applying track properties quickly twice will delete track metadata

### ISSUE THREAD

**Issue by zfhrp6** [mixxxdj/mixxx#12963]
### Bug Description

applying track properties **quickly twice** will delete track metadata.

## Expected Behavior

none

## Current Behavior

track metadata will be deleted

## Steps to Reproduce

1. Open track properties
2. Apply and apply quickly

### log and screenrecord

[mixxx.log](https://github.com/mixxxdj/mixxx/files/14591344/mixxx.log)

https://github.com/mixxxdj/mixxx/assets/1793763/6478957f-dc59-4722-97b9-a449024ca313

### file in filesystem information

The affected file and the backup in filesystem are still the same.

### sqlite information

I didn't check all table, but the value in the `library` table became NULL in mixxx.sqlite .

Here is the records of the affected file(1) and the backup(2).

```sql
SELECT t.* FROM library AS t
-- I tested new DB so I didnt need any WHERE clause
;
```

id | artist | title | album | year | genre | tracknumber | location | comment | url | duration | bitrate | samplerate | cuepoint | bpm | wavesummaryhex | channels | datetime_added | mixxx_deleted | played | header_parsed | filetype | replaygain | timesplayed | rating | key | beats | beats_version | composer | bpm_lock | beats_sub_version | keys | keys_version | keys_sub_version | key_id | grouping | album_artist | coverart_source | coverart_type | coverart_location | coverart_hash | replaygain_peak | tracktotal | color | coverart_color | coverart_digest | last_played_at | source_synchronized_ms
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 |   |   |   |   |   |   | 1 |   |   | 136.176 | 128 | 44100 | 0 | 0.0 |   | 2 | 2024-03-13T17:13:10.438Z | 0 | 0 | 1 |   | 0.305140602914104 | 0 | 0 |   |   |   |   | 0 |   |   | KeyMap-1.0 |   | 0 |   |   | 1 | 1 |   | 61045 | 1.91240704059601 |   |   | 15000290 |   |   |  
2 | Nobuo Uematsu | Spinach Rag | FINAL FANTASY VI Original Soundtrack | 2004 | Other | 6 | 2 |   |   | 136.176 | 128 | 44100 | 0 | 0.0 |   | 2 | 2024-03-13T17:13:10.452Z | 0 | 0 | 1 | mp3 | 0.305140602914104 | 0 | 0 |   |   |   |   | 0 |   |   | KeyMap-1.0 |   | 0 |   | Nobuo Uematsu | 1 | 1 |   | 61045 | 1.91240704059601 | 20 |   | 15000290 |   |   | 1630260428000

## Others

This forum thread may be relevant. https://mixxx.discourse.group/t/mixxx-2-4-metadata-bug-properties/29083 

### Version

2.4.0

### OS

Windows 11

**Comment by ronso0** [comment]
Thanks for tracking that down!

I can reproduce it by triggering Apply and Okay via hotkeys Alt+A -> Alt+O quickly in succession.
I then run into
`DEBUG ASSERT: "pTrack->getDateAdded().isValid()" in function TrackCollectionManager::SaveTrackResult TrackCollectionManager::saveTrack(Track*, TrackMetadataExportMode) const at ./src/library/trackcollectionmanager.cpp:205`
I can't with double-clicking Apply.

I'll take a look...

**Comment by ronso0** [comment]
Got it!
#12965

**Comment by zfhrp6** [comment]
I commented that I tested the PR #12965 and it's good.

This may be a bit off topic, but storage speed might be the reason why it didn't happen with quickly clicks in ronso0's environment. Because I am using USB-HDD instead of SSD, so my storage is not fast.

**Comment by ronso0** [comment]
HmmnonI could reproduce with quick Alt+A but not always with double-click.
And storage speed is unrelated afaict as the database is in memory.

**Comment by zfhrp6** [comment]
Indeed. It is not a problem with the actual files (on the file system), so storage speed is not the cause. my misleading.

**Comment by daschuer** [comment]
By https://github.com/mixxxdj/mixxx/pull/12965
