### ISSUE TITLE
Waveforms not moving 

### ISSUE THREAD

**Issue by abbreviators** [mixxxdj/mixxx#12968]
### Bug Description

Hello, 

Waveforms are completely static when I press play, they do not move however I can see a preview. I will provide screenshots of my config and display. 
![Screenshot from 2024-03-14 15-29-54](https://github.com/mixxxdj/mixxx/assets/138624599/2744c0a6-b0a1-4714-a4f1-971b01af4c5a)
![Screenshot from 2024-03-14 15-32-54](https://github.com/mixxxdj/mixxx/assets/138624599/cdf6a0f2-82e8-4771-ad6b-fdc7ab288101)

### Version

2.3.3

### OS

Debian GNU/Linux 12 (bookworm)

**Comment by ronso0** [comment]
2.3.3 is quite old, please update to current stable 2.4 and let us know whether you can reproduce it.

**Comment by abbreviators** [comment]
> 2.3.3 is quite old, please update to current stable 2.4 and let us know whether you can reproduce it.

Well I feel very silly.

**UPDATING TO VERSION 2.4.0 FIXED THIS ISSUE**

I think I used `apt` to install Mixxx previously and got 2.3.3? I installed the flatpack which has installed the latest and stable version. 

This issue has been fixed, thanks @ronso0

**Comment by abbreviators** [comment]
I installed using "Gnome Software" latest version available there is 2.3.3. 

2.4.0 performed as expected in terms of waveforms.
