### ISSUE TITLE
HDMI AUDIO INTERFACE

### ISSUE THREAD

**Issue by ngoiyaeric** [mixxxdj/mixxx#12986]
### Bug Description

Hi, this software does not work on HDMI audio. I guess it should? Is this a feature or a bug? 

### Version

2.4

### OS

Mac os Intel

**Comment by JosepMaJAZ** [comment]
It should. Are you sure you selected the correct samplerate?
I remember using it on my TV, so it definitely was able to.

**Comment by ngoiyaeric** [comment]
issue resolved, thanks.
