### ISSUE TITLE
Wrong tooltip for samplers expand button

### ISSUE THREAD

**Issue by RafaelFrance** [mixxxdj/mixxx#12998]
### Bug Description

Today it is the same label that button to toggle the full samplers section (on top menu of Mixxx interface).

### Version

2.4

### OS

Ubuntu 22.04

**Comment by Ashnidh** [comment]
Hello. I want to help with it. Can you please provide me with a suitable tooltip for the same.

**Comment by ronso0** [comment]
There is no tooltip fir this action, we need to add it to src/skin/legacy/tooltips.cpp
