### ISSUE TITLE
Exporting a playlist removes history entries

### ISSUE THREAD

**Issue by montoner0** [mixxxdj/mixxx#13000]
### Bug Description

Trying to export a playlist from the history pane when tracks in the library are marked as deleted (field `mixxx_deleted` in the `library` table equals to 1) will wipe their entries from the history. 
Pretty unpleasant issue since this happens silently and you can easily lose a lot of important entries.

### Version

2.4.0

### OS

WIndows 10

**Comment by ronso0** [comment]
Exporting a playlist does not change it, please provide exact steps how to reproduce the issue you experienced.

This is what I have just tried:
* played 3 songs that where not in the music directories watched by Mixxx
* (now those tracks are registered in the library, regardless if their parent directories are watched)
* quit Mixxx, rename those track files, restart Mixxx
* trigger a library rescan
* export that previous history playlist
* = History playlist unchanged
* = exported (.m3u) contained all 3 tracks

**Comment by montoner0** [comment]
@ronso0 
You're right, location isn't a culprit. I've investigated a bit and found that `mixxx_deleted` field in the `library` table is the real reason. When a track has 1 in this field, it will disappear from the history after exporting a playlist. I've changed the issue description.

**Comment by ronso0** [comment]
`mixxx_deleted` stands for hidden tracks. These tracks will be hidden from regular playlists, and Mixxx warns about this when hiding a track.
The History feature however loads all playlists with `keepDeletedTracks` (should be `keepHiddenTracks`).

Long story short: I can still not reproduce the issue. The exported playlist and the Mixxx playlist both contain all tracks after export.

**Comment by montoner0** [comment]
Well, I don't know why you can't reproduce the bug. I've tried this multiple times and every time I export a playlist with such tracks - they disappear from the history. Here a database with a single track and a single playlist that reproduces for me every time, and a screencast in case I wasn't clear enough. 
[mixxxdb.sqlite.zip](https://github.com/mixxxdj/mixxx/files/14779938/mixxxdb.sqlite.zip)
![2024-03-27 21_46_08_mixxx_Mixxx](https://github.com/mixxxdj/mixxx/assets/13542804/f454538c-cd73-4d8a-ab4b-a9e7d4a99c4d)

**Comment by ronso0** [comment]
Okay, I can reproduce it now (no clue why it succeeded earlier, maybe a duplicate test track?)

The issue is that `BasePlaylistFeature::slotExportPlaylist` creates a temp `PlaylistTableModel` which does **not** set the `keepHiddenTracks` flag and thereby removes all hidden tracks from the selected playlist, regardless if the playlist **feature** has set it (History does).

Working on it!
