### ISSUE TITLE
Importing musicbrainz data for ripped WAV files causes track title to disappear

### ISSUE THREAD

**Issue by ka2ddo** [mixxxdj/mixxx#13014]
### Bug Description

I ripped a CD with cdparanoia -B, and renamed the cdda.trackNN.wav files to names matching the actual track names, but without spaces (for example, 01-TurnMeOn.wav from my Kevin Lyttle CD).
I edited the properties of the track to change the track name to just the name (with spaces) and provide the artist and album names, then looked up the track in musicbrainz.
The track was found, but when I clicked the Apply and Close buttons on the Properties dialog, the track, artist, and album columns were blank for the track, and also blank in the Properties dialog when I reopened it. Stopping and restarting Mixxx caused the track to be reordered, but to still have blank track, artist, and album.
Yet the track could still be played with the correct music.

### Version

built from source, latest main branch on 24 March 2024

### OS

Raspbian bookworm, as of 24 March 2024, running on Pi400 hardware

**Comment by ronso0** [comment]
@ka2ddo Can you try to reproduce with a build of #12965?

**Comment by ka2ddo** [comment]
I couldn't find the branch mentioned in the other bug, but whatever was added to the main branch seemed to fix the problem when I 'git pull'd and rebuilt.

Thanks!

**Comment by ka2ddo** [comment]
No, that didn't fix it. But what did fix it was, after 'Apply' and 'Close' the musicbrainz sub-dialog, only clicking 'OK' in the main track properties dialog (instead of clicking 'Apply' and 'OK' like I had done previously).

So, it has a work-around.

**Comment by ronso0** [comment]
> I couldn't find the branch mentioned in the other bug

It's a branch on my fork.
Easiest way to check it out is `gh pr checkout 12965`

**Comment by ronso0** [comment]
I'm not quite sure how to reproduce this.
Can you please list the actions you triggered as a list?

I tried
* drag a new track into a deck, open Track Properties
* click Metadata from MuscBrainz
* new dialog is opened, track was found
* select one of the results (dialog starts cover art fetching, done)
* set "Tags" checkbox (unchecked by default)
* hit Apply (tags are updated in Track Properties), hit Close
*

**Comment by ka2ddo** [comment]
The exact sequence I used to foul it up was:
1. Right-click on a track in the Library section of the screen, and pick "Properties" off the popup menu.
2. In the track properties dialog, click the "Import Metadata from MusicBrainz" button.
3. After it found the song in the DB, click on the correct source in the Metadata list, and click the "Apply" and "Close" buttons in the MusicBrainz dialog.
4. Back at the track properties window, click the "Apply" button, then click the "OK" button (not just the "OK" button).

**Comment by ronso0** [comment]
I can not reproduce it.

> Back at the track properties window, click the "Apply" button, then click the "OK" button (not just the "OK" button).

If you clicked Apply and Close in very quick succession (both call save()) and the metadata is cleared, then it might be #12963 which has been fixed by now.

If you can't reproduce it anymore with current main (or 2.4) please close this.

**Comment by daschuer** [comment]
I can also not reproduce. However there is a misleading error Message "Could not find this track in the MusicBrainz database." in case the track file is no longer accessible due to renaming.
https://github.com/mixxxdj/mixxx/issues/13666
