### ISSUE TITLE
Pre escuta do Mixxx Dj

### ISSUE THREAD

**Issue by djleosapao** [mixxxdj/mixxx#13049]
### Bug Description

Boa noite me chamo Leonardo, migrei do Windows para o Linux há seis anos,  sou dj também tocava com o software Serato Dj Pro, decidi troca-lo pelo mixxx dj por ser software bem mais leve para mexer. 
Faz um mês que estou testando a versão do Mixxx dj 2.4, estava tudo bem até descobrir um pequeno problema nele, seria a Pre- escuta muito utilizada pelos djś para entrar com outra música está tendo alguns bugs tem hora que funciona mas tem hora que não funciona gostaria de saber como resolver esse problema. 
 Desde já agradeço pela atencão.

### Version

2.40

### OS

Linux ( Zorin OS 17.1

**Comment by daschuer** [comment]
Issues should be written in English only. 

Please describe exactly what you did, what happens and what should happen instead. 

Do you see an error message?

**Comment by ronso0** [comment]
#13053
