### ISSUE TITLE
pop when enabling Bessel8 ISO in effect unit

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13055]
### Bug Description

* mix mode: Dry/Wet
* fully Wet
* no effect before or after

Occurs only when toggling ON.
Notable especially if this exact same iso is used as EQ for the playing deck and High and Mid are fully killed (with knob) both in the mixer and the standard effect unit.

No buffer underruns.
Doesn't matter which keylock engine is used.

Loudness seems to vary. When I tried to reproduce after start, the first pop was rather quiet, on further toggling pops where significantly louder but still with some variation in loudness.

FWIW pops also occur when changing the keylock engine.

personal branch based on main 2.5-alpha, no patches related to effects.

### Version

2.5-alpha

**Comment by ronso0** [comment]
Very strange:
with a different DAC and different PA I can't reproduce.
Same Mixxx binary, same effects setup.

Maybe it's just some frequencies in the top range that slip through, and they are somehow filtered by my second setup?

**Comment by daschuer** [comment]
I can confirm a pop when you kill all and then enable the effect. 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/204a8c41-748e-456e-8507-db67e4425c5c)
I will look into this.

**Comment by ronso0** [comment]
I've found this comment which I see no evidence for.
In getManifest() above, there is [pManifest->setEffectRampsFromDry(true);](https://github.com/mixxxdj/mixxx/blob/08be88ff85f82e2ae573a554f0a29d64103b06cb/src/effects/backends/builtin/bessel8lvmixeqeffect.cpp#L27 )
 (but I'm not into effect processing so this might be a dead end)
https://github.com/mixxxdj/mixxx/blob/08be88ff85f82e2ae573a554f0a29d64103b06cb/src/effects/backends/builtin/bessel8lvmixeqeffect.cpp#L57

**Comment by ronso0** [comment]
Oh right, next time I'll record audio issues to figure if it's Mixxx or a later part of the chain.

**Comment by daschuer** [comment]
A fix is here: https://github.com/mixxxdj/mixxx/pull/13073
