### ISSUE TITLE
Alpha 2.5 update error on Linux Mint 21.2

### ISSUE THREAD

**Issue by stefan-franz** [mixxxdj/mixxx#13052]
### Bug Description

W: Die Datei »http://ppa.launchpad.net/mixxx/nightlies/ubuntu/pool/main/m/mixxx/mixxx_2.5%7ealpha%7e299%7eg2145f5f7de-1%7ejammy_amd64.deb« konnte nicht heruntergeladen werden
  404  Not Found [IP: 2620:2d:4000:1::81 80]

### Version

2.5 alpha

### OS

Linux Mint 21.2

**Comment by ronso0** [comment]
Has been deleted for some reason?
How did you try to download? Maybe a missing `sudo apt update` before attempting to install?

Just pick the newest version (307 as of today).

**Comment by stefan-franz** [comment]
Now it works. Update always come automatically over ppa entry

**Comment by daschuer** [comment]
Thank you for confirming
