### ISSUE TITLE
log spam WindowStateChange IGNORE

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/mixxx#13062]
### Bug Description

mixxx is spamming qWarnings about window state changes: 

https://github.com/mixxxdj/mixxx/blob/main/src/mixxxmainwindow.cpp#L1184

These should either be removed, or debugs.

### Version

main

### OS

Ubuntu 22.04

**Comment by ronso0** [comment]
yes, this has not been removed to provide instant feedback for testers. You can easily relate logs to last window action.
As a reminder I created #13030
