### ISSUE TITLE
Cannot select star rating in list view

### ISSUE THREAD

**Issue by nchammas** [mixxxdj/mixxx#13095]
### Bug Description

I can't set a star rating in the list view, but I _can_ set it from the deck up top:

https://github.com/mixxxdj/mixxx/assets/1039369/96e92a76-ad90-4de6-be17-c2fab41c0690

This wouldn't be too annoying for me if I could just import my ratings from macOS Music (formerly known as iTunes), but due to #7513 this is sadly not possible.

### Version

2.4.0 ARM64

### OS

macOS 14.4.1

**Comment by ronso0** [comment]
Thanks for your report.
Is this #9916 yet again?

**Comment by ronso0** [comment]
The star editor currently applies the rating on mouse release.
It resets the rating as soon as the pointer is moved while any button is pressed. This is supposed to allow dragging tracks by grabbing _any_ cell (except the Preview button) without unintentionally setting the rating.

Could it be that there is a slight mouse move happening when you press the left mouse button / trackpad?
To make sure no move is occuring, could you test using a dedicated button for clicking?

I will prepare a PR with some debug output so we can hopefully fix this issue once and for all.
Maybe we can make use of the dnd threshold introduced recently #12903

**Comment by ronso0** [comment]
@foss- Can you reproduce the issue with 2.4?
How about 2.5-alpha?

**Comment by foss-** [comment]
macOS 14.4.1
Mixxx 2.4.0

Cannot reproduce the flicking on a macbook intel when using the trackpad.

Seeing other trouble when trying to set a rating. Sometimes the click on the stars isn't recognized it seems:

![2024-04-19](https://github.com/mixxxdj/mixxx/assets/5708172/fe33bc18-3af2-4d45-afac-cf2448e07be3)

I cannot reproduce my 2.4.0 issues with 2.5-alpha-337-gea9e160680 (main)

@nchammas how does 2.5 alpha behave for you? https://mixxx.org/download/#testing
Please create a backup of database first: https://manual.mixxx.org/2.4/en/chapters/appendix/settings_directory.html

**Comment by ronso0** [comment]
> Seeing other trouble when trying to set a rating. Sometimes the click on the stars isn't recognized it seems:

The animation shows a drag'n'drop cursor.
Seems we need to implement the new dnd threshold separately for the Star delegate.
Maybe that's the same issue @nchammas is seeing.

**Comment by ronso0** [comment]
> I cannot reproduce my 2.4.0 issues with 2.5-alpha-337-gea9e160680 (main)

That is probably because unintented drags are now (2.5-alpha) suppressed, i.e. a move threshodl has to overcome before a drag is initiated. 
I'll try to backport #12903 to 2.4

**Comment by ronso0** [comment]
@nchammas Please try the CI build of #13135 (once it is built).
See notes on testing and backup here https://github.com/mixxxdj/mixxx/wiki/Testing

**Comment by nchammas** [comment]
I tried [the macOS ARM build here][1], and it looks to be working now:

https://github.com/mixxxdj/mixxx/assets/1039369/454c67cb-fe6f-44f7-b7c3-1b381915fb3b

[1]: https://github.com/mixxxdj/mixxx/actions/runs/8759760526

**Comment by ronso0** [comment]
Great, thanks for testing!
