### ISSUE TITLE
Cutting Ctrl+X track with missing track files from track sets removes them irretrievably

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13100]
### Bug

If you want to do cut & paste in track sets while track files are missing, you can cut (copy & remove) but you can't paste due to invalid QFileInfos (no location).

This may happen with tracks on currently unmounted drives and will drop tracks irretrievably..

### Fix?
Use `DragAndDropHelper::supportedTracksFromUrls` and check if the number of returned QFileInfos is equal the number of indices. Else block Cut.
This may be costly. We could first check the `fs_deleted` column and abort if at least one track was deleted.
If no tracks is marked deleted that may be due to an outstanding do the dnd check 

Unfortunately we also need a popup:
"Cut is prohibited because one or more track files of the selection is missing"
(opt1: list missing files)
(opt2: "Remove missing tracks from selection and try again" button)

#### Elaborate, maybe risky alternative:
hybrid copy/paste with QUrls + TrackIds?
is this even possible? 
______
I consider this a blocker since it may wipe user data.

### Version

2.5-alpha

**Comment by m0dB** [comment]
I am trying to wrap my head around this... Wouldn't it be possible to go directly from url to trackId, without going through fileInfo to avoid this?

**Comment by m0dB** [comment]
I tried going from urls to trackIds without going through mixxx::FileInfo (and without calling DragAndDropeHelper::supportedTracksFromUrls) 

https://github.com/mixxxdj/mixxx/pull/13146

This seems to work, but to be honest, I have a hard time understanding all this code and I can't really tell if this is a valid solution or not.

**Comment by ronso0** [comment]
Fixed by #13958
