### ISSUE TITLE
Colorful console output is auto enabled only when adding some comand line option

### ISSUE THREAD

**Issue by danferns** [mixxxdj/mixxx#13118]
### Bug Description

Adding any of the command line option enables colorful console output. The must be an issue with the --color option.

_Originally posted by @daschuer in https://github.com/mixxxdj/mixxx/pull/13017#pullrequestreview-1968497760_
            

After looking into it I found that the default option for the --color flag is `auto`. Which only enables color if the environment variable `NO_COLOR` is absent ([code](https://github.com/mixxxdj/mixxx/blob/395c70e5c24375eff88144128517b40fbe734415/src/util/cmdlineargs.cpp#L429)). After calling `fputs()` around these lines, I found that this part of code (and a lot of the code before it) does not run at all, when no flags are passed. In such cases, the initialized value of [`m_useColors(false)`](https://github.com/mixxxdj/mixxx/blob/395c70e5c24375eff88144128517b40fbe734415/src/util/cmdlineargs.cpp#L33) is being used.

An easy solution would be to set the default value of --color to be `never`, then it would be consistent with the value assigned to `m_useColors(false)`. But we may instead want to get the `NO_COLOR` check to run even when there are no flags.

**Comment by daschuer** [comment]
Mm, I am not sure if this will solve the underlying issue. 
I think the original idea was use color when reasonable but save CPU otherwise. 

I would rather keep the current state and whait until someone finds time to move the code around and fix the route cause.

**Comment by daschuer** [comment]
A fix is here: https://github.com/mixxxdj/mixxx/pull/13153

**Comment by danferns** [comment]
LGTM. Thank you so much!
