### ISSUE TITLE
Novation Dicer default mapping

### ISSUE THREAD

**Issue by Phr3d13** [mixxxdj/mixxx#13134]
### Bug Description

Something feels off/wrong with the default Novation Dicer mapping. Get an error on Mixxx start about an LED issue. Some controls don't appear to do anything. I could probably come up with fixes for the non-working functions/buttons, but I don't think I have the knowledge to fix whatever's going on with the LED error.
```
MIDI output message 0x9F 0x3E has invalid MixxxControl [Channel2], flanger
MIDI output message 0x9C 0x3E has invalid MixxxControl [Channel1], flanger
```

### Version

2.4.0 HEAD

### OS

Windows 11

**Comment by JoergAtGithub** [comment]
This mapping uses a removed control:
![grafik](https://github.com/mixxxdj/mixxx/assets/64457745/97c9039e-1ce2-4a00-890e-4a7ee4127619)

**Comment by Swiftb0y** [comment]
tbh. I'm not sure what would make sense to replace it with. do you have a suggestion @Phr3d13?

**Comment by Phr3d13** [comment]
I'm not even sure, I just use mine for setting up loops on my DVS decks.

**Comment by Phr3d13** [comment]
It's an option in the Effects section still...
![image](https://github.com/mixxxdj/mixxx/assets/8862382/2926a44e-2652-4374-ae5e-2521a7b76dff)

**Comment by Phr3d13** [comment]
maybe this:
Effect Unit 1, Slot 1: Toggle

**Comment by Phr3d13** [comment]
but that would hinge on an ability to get selected effects to persist/save. Every time I close Mixxx, I have to re-select what effects are here:
![image](https://github.com/mixxxdj/mixxx/assets/8862382/1f924805-85ed-4e8b-a096-8ee1235461d7)

**Comment by Phr3d13** [comment]
nevermind, now they wanna save...

**Comment by Phr3d13** [comment]
ok, then yeah, with the options left, I'm ok with it toggling FX Unit 1 Slot 1.

**Comment by Swiftb0y** [comment]
wdyt about toggling the mixers quickeffect instead?
