### ISSUE TITLE
Auto DJ Behaviour when the playing deck is stopped

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#13167]
### Bug Description

When Auto DJ is playing and the user taps on cue in the playing deck the Auto DJ stays active while there is no more music playing.
When user taps on play on the other deck the deck starts playing but the xfader is still on the other side.
Shouldn't the Auto DJ be stopped/deactivated when a user interacts?
(I kept on thinking of the possible problem of the user in the forum and other possible Auto DJ problems)

### Version

2.5 alpha

### OS

Windows 11

**Comment by ronso0** [comment]
I don't think stopping AutoDJ on the first user intervention is a good idea.
Following scenarios come to mind:
* accidentally pressed a key that does jump to a hotcue or main cue, for example if you want to search a track and for some reason the keyboard focus is not on the search bar
* hotcue fun / stutter cue:
   * AutoDJ does it's thing, you're live-curating the playlist
   * then you want to jump in and play with a vocal or whatever

In both cases you do NOT want to interrupt AutoDJ. When you enable it again it will eject the next track, potentially dropping that killer tune you've already queued.

**Comment by Eve00000** [comment]
True.
I meant deck-play/cue-interactions
If Auto DJ stays active and I switch to library/playlists/crates I can't see that Auto DJ is still active and I can forget it (not watching the little symbol next to the clock).
Possible scenarios: 
- Auto DJ is playing Deck 1, I start Deck 2 and cue Deck 1. After song in Deck 2 I want to play song in Deck 3, Song in Deck 2 has a particular ending that needs to be played until the end, I wait for the right moment to start Deck 3 but Auto DJ starts Deck 1 again. (all with Xfader nicely set in the center)
- Auto DJ is playing Deck 1, I start Deck 2 and cue Deck 1. After song in Deck 2 I want to play song in Deck 4, Song in Deck 2 has a particular ending that needs to be played until the end, I wait for the right moment to start Deck 4 but Auto DJ starts Deck 1 again and puts the xfader to the left again.
Internal/external mixxxing can cause extra problems.
Pro's and contra's that can lead to misinterpretations and mixxxing errors .
If you think it's ok like this, I'll rest my case :-) but it does need some extra explanation in the manual.

**Comment by Eve00000** [comment]
OK, no problem for me. I know I have to put Auto DJ off again when I went to the bathroom.
And I suppose users are already used to the current behaviour of Auto DJ, changing it can be confusing.

**Comment by ronso0** [comment]
You don't need to close this only because I disagree.
If you want to collect opinions you should leave it open.

**Comment by Eve00000** [comment]
Oh no, it's not that it's  what we call 'new insights'.
It's sometimes (especially afterwards) difficult to see / rebuild the history of things. 
And habits are also important (and human), I write about consistency, so consistency should also be honoured in the way people use Auto DJ. If they are used that it works like this it should be left so.
More opinions can make it more difficult.
