### ISSUE TITLE
DEBUG_ASSERT in basetracktablemodel.cpp on header splitter click

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#13164]
### Bug Description

```
critical [Main] DEBUG ASSERT: "siblingColumn != index.column()" in function virtual QVariant BaseTrackTableModel::rawSiblingValue(const QModelIndex&, ColumnCache::Column) const at ./src/library/basetracktablemodel.cpp:492
```

### Version

2.4.0

### OS

Ubuntu Focal

**Comment by ronso0** [comment]
I can't reproduce. (I presume you mean double-click)
Which model does it occur with, and maybe: which column configuration?

**Comment by daschuer** [comment]
It happens in every table view, when double clicking on the right splitter of the color column header.

**Comment by ronso0** [comment]
Sorry, I can't reproduce, no matter where I move the Color column :man_shrugging:

**Comment by daschuer** [comment]
Maybe resize before and then double click to get the preferred size?

**Comment by ronso0** [comment]
Nope, it is resized correctly.
I'm testing current 2.4 with d71ebd8bdf5850aeb9082568be1383202f67595e

Can you show me the column config you can reproduce it with?

**Comment by daschuer** [comment]
Just tested with the  same commit: 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/2867ef36-3489-43c6-a872-f5bf8467bd26)

**Comment by ronso0** [comment]
In your screenshot some column labels are truncated by the width of the sort indicator.
I can't reprodue that either, my labels use full width unless the indicator is visible.

I'm still using Qt 5.12.8
