### ISSUE TITLE
Behringer DDM4000: mapping error

### ISSUE THREAD

**Issue by TMK1000** [mixxxdj/mixxx#13179]
### Bug Description

I can't get my Behringer ddm4000 to map to Mixx. 
Say error on 44. Has anyone got a solution?

### Version

2.4.0

### OS

Windows 11

**edit**(ronso0)
> Uncaught exception: file:///C:/Program Files/Mixxx/controllers/Behringer-Extension-scripts.js:244: TypeError: Property 'disable' of object [object Object] is not a function
Backtrace: https://github.com/file:///C:/Program Files/Mixxx/controllers/Behringer-Extension-scripts.js:244

https://github.com/mixxxdj/mixxx/blob/2873f5dd13c3c0ff54e501fa88b245d6c8bf7e28/res/controllers/Behringer-Extension-scripts.js#L244

**Comment by ronso0** [comment]
> Say error on 44

Can you please provide more info:
* what exactly did you do?
* what do you expect to happen?

**Comment by TMK1000** [comment]
i recently bought a Behringer DDM4000 and when connected i was hoping that the channels would all be mapped instead music plays through all channels.

I also get a box with the following warning

"Uncaught exception: file:///C:/Program Files/Mixxx/controllers/Behringer-Extension-scripts.js:244: TypeError: Property 'disable' of object [object Object] is not a function
Backtrace: @file:///C:/Program Files/Mixxx/controllers/Behringer-Extension-scripts.js:244"

**Comment by ronso0** [comment]
> i recently bought a Behringer DDM4000 and when connected i was hoping that the channels would all be mapped instead music plays through all channels.

I presume you want to use the DDM4000 with all Mixxx decks routed to respective channels on the mixer?
Use the Deck 1-4 outputs in Preferences -> Sound Hardware -> Deck [1|2|3|4]
For further help with your setup please create a thread in the forums. Github is only for tracking development (bugs, features, ..).
Thank you!

**Comment by TMK1000** [comment]
Ahh ok thank you this is all so new to me..
Thanks for your help
