### ISSUE TITLE
Bug: hitting hot cues repeatedly on deck 2 makes playback of deck 1 stutter

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#13195]
### Bug Description

A song is playing on deck 1
Loaded a song on deck 2, hit sync on deck 2 so tempo is the same
Set hot cue in song on deck 2
While deck 1 is playing and deck 2 is silenced completely by crossfader, I repeatedly press the hot cue on deck 2
This makes the song on deck 1 playing on the master bus lag significantly

### Version

2.4.0

### OS

macOS 14.4.1 (M1)

**Comment by spotlesscoder** [comment]
If I use both fingers to press the hot cue very very often very quickly, the sound even completely drops out for about 2 secs before it comes back in

**Comment by spotlesscoder** [comment]
OK I just noticed that the dropout also happens if I leave all controls alone so maybe not related to the initial issue

**Comment by spotlesscoder** [comment]
The problem seems to be smaller when I increase the buffer (and latency -.-) in the settings

**Comment by ronso0** [comment]
Yes, sounds like your system simply can't handle such a  low latency.
