### ISSUE TITLE
Bug: Active song on deck 1 stutters when I hit hot cues on deck 2

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#13194]
### Feature Description

A song is playing on deck 1
Loaded a song on deck 2, hit sync on deck 2 so tempo is the same
Set hot cue in song on deck 2
While deck 1 is playing and deck 2 is silenced completely by crossfader, I repeatedly press the hot cue on deck 2
This makes the song on deck 1 playing on the master bus lag significantly

**Comment by spotlesscoder** [comment]
Wrong issue type

**Comment by ronso0** [comment]
You can simply edit the description, i.e. remove the "Feature Description" header.
And no need to mention Bug in the title ; )

**Comment by spotlesscoder** [comment]
I just re-created it because I wanted all necessary information to be present so I just opened a bug and used the template to report it
