### ISSUE TITLE
Update libdjinterop to 0.21.0

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#13231]
### Bug Description

Unfortunately the nighly builds on Launchpad are currently failing because of the recent libdjinterop update. 
This broke the link to https://launchpad.net/~xsco/+archive/ubuntu/djinterop/+sourcefiles/libdjinterop/0.20.2-0ubuntu1/libdjinterop_0.20.2.orig.tar.gz

Maybe we need to move libdjinterop to our PPA to have always the referenced version available.  

Luckily our 2.4.1 build is not affected because it was build before the update. 

@mr-smidge
Do you have a good idea what is the best way to solve this issue? 
 

### Version

main

### OS

Ubuntu

**Comment by mr-smidge** [comment]
Hi @daschuer - I was not aware that Launchpad automatically removes old versions of packages from PPAs, apologies.

I'm not aware of any other users of the PPA, so I'll remove the latest version and downgrade to 0.20.2 to hopefully fix the immediate issue.

Longer-term, I'm not immediately sure what the most appropriate fix is... but happy to contribute to the discussion.

**Comment by mr-smidge** [comment]
Ugh, actually it looks like re-uploading old versions will not work.

The differences between 0.20.2 and 0.21.0 are all non-breaking, so an upgrade might be the simplest fix for the immediate issue: https://github.com/mixxxdj/mixxx/pull/13233

**Comment by daschuer** [comment]
What do you think about the idea to copy the libdjinteropt in the required version to the mixxx PPA? 
 
Package maintainer might be tempted to link it as a package, which brings the stable API question back to the table. 
How has the situation developed since our last discussion?

**Comment by mr-smidge** [comment]
In the meantime, I will not upload any new versions to the PPA unless I am also updating Mixxx at the same time.

Longer term, the suggestion of moving libdjinterop into the Mixxx PPA might be best (until such time as the library has a stable interface).  I wonder if the same package can be simultaneously uploaded to multiple PPAs? :thinking:

**Comment by mr-smidge** [comment]
> which brings the stable API question back to the table.  How has the situation developed since our last discussion?

There are definitely some more breaking changes I can think of making before reaching a 1.0 stable API.  I'm ok with this idea when ready, but I think to try and do this now would be cementing in an API that still has quite a few rough edges.
