### ISSUE TITLE
Replace macos-11 runner image on GitHub Actions

### ISSUE THREAD

**Issue by Holzhaus** [mixxxdj/mixxx#13248]
The following announcement was sent out by GitHub via email:

> The macOS 11 runner image will be removed by 6/28/24. To raise awareness of the upcoming removal, jobs using macOS 11 will temporarily fail during scheduled time periods defined below:
>
> - June 17 2024, 8:00 AM - 2:00 PM EST
> - June 19 2024, 12:00 PM - 6:00 PM EST
> - June 24 2024, 3:00 AM - 9:00 PM EST
> - June 26 2024, 8:00 AM - 2:00 PM EST
>
> #### What you need to do
>
> Jobs using the macos-11 YAML workflow label should be updated to macos-14, macos-13, macos-12, or macos-latest. You can always get up-to-date information on our tools by reading about the software in the [runner images repository](https://github.com/actions/runner-images). Please contact GitHub [Support](https://support.github.com/contact?form%5Bsubject%5D=Re%3A+GitHub+Actions&tags=dotcom-contact-params) if you run into any problems or need help.

We actually use the `macos-11` runner (e. g., in the Build workflow for macOS  ARM64) and need come up with a plan how to replace it.

**Comment by Swiftb0y** [comment]
fixed in #13296
