### ISSUE TITLE
Unicode DeviceSQL strings in PDB are UTF-16-BE, not UTF-16-LE

### ISSUE THREAD

**Issue by 0xsuk** [mixxxdj/mixxx#13291]
### Bug Description

Mixxx uses kaitai struct to extract data from rekordbox pdb files.
rekordbox data binary was reversed by another project called crate-digger.
Mixxx uses an old copy of crate-pdb.ksy file for parsing pdb files, which needs to be updated.

https://github.com/Deep-Symmetry/crate-digger/issues/14

![image](https://github.com/mixxxdj/mixxx/assets/97814789/94f10813-62e3-4b47-80ec-2182acad7d9e)
As shown in the image, Japanese characters are not properly displayed.

**Comment by Swiftb0y** [comment]
I think the title of that pull request you mentioned is backwards, it's actually utf16-le and was just previously assumed to be utf16-be. But you're right, the ksy definitions are outdated.

**Comment by Swiftb0y** [comment]
Thanks for digging through the issue, notifying us and testing the fix. It will be part of the next mixxx release.

**Comment by dimashenme** [comment]
is the fix available in a branch that I can compile locally while waiting for the next release to come out?

**Comment by ronso0** [comment]
#13293 has been merged on June 9th so the fix will be in Mixxx 2.4.2

You can build the 2.4 branch (stable), or 2.5 (currently beta).
