### ISSUE TITLE
Highlight currently playing track in playlists and crates

### ISSUE THREAD

**Issue by tbazant** [mixxxdj/mixxx#13292]
### Feature Description

This one is for convenience purpose - for instance, I'd like to find a track with a similar BPM or key by sorting tracks in a crate by BPM or KEY, then looking at neighbours of the current track. If it was highlighted, it's much easier for the eye.

**Comment by ronso0** [comment]
Duplicate of #10234?

**Comment by tbazant** [comment]
> Duplicate of #10234?

yep, closing this one
