### ISSUE TITLE
Keyboard shortcuts for loading track from library into left/right deck not working anymore

### ISSUE THREAD

**Issue by DJMaxergy** [mixxxdj/mixxx#13305]
### Bug Description

Normally I use custom keyboard shortcuts which worked without problems since 2015. Since the update to 2.4.1 today the shortcuts for loading tracks from the library to the left or right deck are not working anymore (Shift + left/right arrow). Other shortcuts for playing sampler or triggering cue points are working as expected.
I also deleted my custom shortcuts to use the default ones instead, but there these shortcuts are not working, too.
As a last step I started Mixxx from terminal with debug logs, but there were no entries concerning my keyboard shortcuts.

Steps to reproduce the problem:
- Start Mixxx, click into the library window to focus on the library.
- Choose a song by pressing the up/down key of the keyboard.
- Press Shift + left/right arrow to load a song into the left or right deck -> Shift gets ignored. By pressing the left/right arrow I can only change the focus of the song property / column of the song entry in the library window.

CPU: 1,6 GHz Dual-Core Intel Core i5
Graphics: Intel HD Graphics 6000 1536 MB

### Version

2.4.1

### OS

macOS Monterey 12.7.5

**Comment by ronso0** [comment]
If you start Mixxx with keyboard shortcuts enabled, the mixxx log should contain one or more lines about the keyboard file in use, it's amonst the first lines being logged:
```
Debug [Main] Found and will use custom keyboard mapping "[some file path]"
```
or, if Mixxx found a keyboard mappin in your user directory
```
Debug [Main] Found and will use default keyboard mapping "[some file path]"
```
Can you check the content of that file?

**Comment by DJMaxergy** [comment]
If I start Mixxx as always (Custom.kbd.cfg in user folder under .../Application Support/Mixxx) I get the following log entry as you described @ronso0:
`debug [Main] Found and will use custom keyboard mapping "/Users/DJMaxergy/Library/Containers/org.mixxx.mixxx/Data/Library/Application Support/Mixxx/Custom.kbd.cfg"`
Most parts of that config file are working except the track loading in the library as described above.

If I start Mixxx with previously deleting that custom keyboard config file, I get the other log entry as you described:
`debug [Main] Found and will use default keyboard mapping "/Applications/Mixxx.app/Contents/Resources/keyboard/de_DE.kbd.cfg"`

Most custom or default shortcuts are working...except the track loading.

I also see:
`debug [Main] keyboard press:  "Shift+Left"`
when I try to load a track from the library into the left deck.
This should be the default keyboard shortcut I think/hope/saw on the wiki. In my custom keyboard config it is.

**Comment by ronso0** [comment]
Hmm, very strange. I tested the de_DE mapping from 2.4 and 2.5, both work as expected.
To clarify: you also tested with empty and loaded (stopped) decks? (Just to rule out some deck protection prevents loading)

**Comment by DJMaxergy** [comment]
Yes, I start Mixxx (initially the decks are empty / no track loaded) and put the focus on the library frame by clicking on a track with the left mouse button. After that I "scroll" through the library by pressing the up/down arrow key. If I reach the track I want to load to a deck (marked in the library window), I press Shift + Left to load it to the left deck for example....but nothing happens.
Previously I had the Mixxx 2.4.0 stable version where the keyboard shortcuts still worked as expected. Only after the update to 2.4.1 the problem occured.
2.5 is the actual development branch/version, right?
Should I try a nightly build version of 2.5?

**Comment by ronso0** [comment]
Thanks.

Sure, trying 2.5-alpha won't hurt. You'll find backup instructions here https://github.com/mixxxdj/mixxx/wiki/Testing

I'll check the diff 2.4 -> 2.4.1, maybe I can spot something, but from the top of my head, I'm not aware of any related changes, 2.4.1 was just a bugfix release without any major and/or risky changes.

**Comment by ronso0** [comment]
You may also try downgarding to 2.4 (backup your data) and double-check that the regression has indeed been introduced by 2.4.1

**Comment by DJMaxergy** [comment]
So....I thought going back to 2.4.0 stable release would be more helpful to find the difference which causes the problem:
After re-installing the 2.4.0 stable release, loading a track from the library window into the left/right deck using the keyboard shortcuts works!
That's why I conclude that it must be some change in 2.4.1 which causes the problem.
Was there anything done concerning the library focus handling or something?

**Comment by ronso0** [comment]
The load controls are independent from the focus. I'll check the changes soonish.

**Comment by ronso0** [comment]
@DJMaxergy Please check #13331

**Comment by DJMaxergy** [comment]
I checked #13331 and attached the logs there.

**Comment by aboutwout** [comment]
@ronso0 @DJMaxergy 
Just wanted to add: this seems to be an issue with using shortcuts with the **arrow** keys. If I map the `LoadSelectedTrack` shortcut to a different key combination, it works as long as no arrow keys are involved.

**Comment by DJMaxergy** [comment]
So I'm not the only one with this problem...good to hear that.
I tried 2.4.1 on a Windows 10 system and there the keyboard shortcuts for loading a track / arrow keys are working.
And I recently checked 2.5 beta (2.5-beta-15-gdf6529d87e): There the arrow keys as keyboard shortcuts are not working either.
