### ISSUE TITLE
Beats until next markers are not readable with small waveforms

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#13314]
### Bug Description

I have noticed that the artificial font size limitations kicks in a bit early. 
This as the smallest waveform I consider as reasonable, but the additional beat cont is only barely readable, the font size is ignored. 
![grafik](https://github.com/mixxxdj/mixxx/assets/1777442/46c030c5-516e-4ef0-9fe8-c5acb5c636d7)

### Version

2.5~alpha

### OS

Linux

**Comment by m0dB** [comment]
Can this be closed? I believe this was fixed by https://github.com/mixxxdj/mixxx/pull/13311

And related: https://github.com/mixxxdj/mixxx/pull/13465

**Comment by daschuer** [comment]
Oh yes, I can confirm it is fixed.
