### ISSUE TITLE
add GUI controls for `beats_undo_adjustment`

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13318]
### Feature Description

#12954 provides the controls, quoting the TODO from there
> add Undo button to skins to make this more accessible, probably to beatgrid controls section next to the waveforms
(Tango + LateNight only? in Deere controls are already quite dense)

Ideally this happens for 2.5, requires a new tooltip though

**Comment by daschuer** [comment]
This should not be much of a problem because it is a new string. No translations are lost.

**Comment by ronso0** [comment]
> requires a new tooltip though

Ha, tooltips has already been added in #12954 

(my comment was rather about potentially viloating string freeze)

**Comment by ronso0** [comment]
Implemented in #13339
