### ISSUE TITLE
LegacyControllerMappingValidationTest.HidMappingsValid (Failed) on Launchpad

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#13349]
### Bug Description

This is a regression probably since #11407
The last working one is 2.6-alpha-4-g4d9db3e5d0

### Version

2.6-alpha

### OS

Ubuntu

**Comment by Swiftb0y** [comment]
Can you share the log output from the failing tests? Any indicators for causes?

**Comment by daschuer** [comment]
The full log is here: 
https://launchpadlibrarian.net/734318393/buildlog_ubuntu-noble-amd64.mixxx_2.6~alpha~9~g165350481f-1~noble_BUILDING.txt.gz

```
Value of: testLoadMapping(mapping)
  Actual: false
Expected: true
Error while validating /<<PKGBUILDDIR>>/res/controllers/Dummy Device Screen.hid.xml
```

**Comment by daschuer** [comment]
Ah I see, we need to install some more Qt modules.

**Comment by daschuer** [comment]
```
"QtQml.WorkerScript" is not installed
"Qt5Compat.GraphicalEffects" is not installed
"QtQuick.Window" is not installed
"QtQuick.Layouts" is not installed
"QtQuick.Shapes" is not installed
"QtQuick.Controls" is not installed
"QtQml.WorkerScript" is not installed
"Qt5Compat.GraphicalEffects" is not installed
```

**Comment by Swiftb0y** [comment]
yup, looks about right. Not sure about workerscript necessarily, but it doesn't hurt.

**Comment by daschuer** [comment]
Pushed a possible fix directly to main https://github.com/mixxxdj/mixxx/commit/6d124184622dd54be72bc99750cb1d92705c0071
hopefully that fixes the issue.

**Comment by daschuer** [comment]
It is fixed now: https://launchpad.net/~mixxx/+archive/ubuntu/nightlies/+packages
