### ISSUE TITLE
Adds Artist/track information when streaming even when that is left blank or 'static' artist details selected

### ISSUE THREAD

**Issue by palaran** [mixxxdj/mixxx#13345]
### Bug Description

Mixxx 2.4 on Windows 10.

When live broadcasting, and if you do not want to send artist/track information to the stream, Mixxx is still sending that information even if the meta data 'format' field is left blank. Similarly, if I select 'use static artist and title' it still sends the track artist/title. I checked that both leaving the static artist/static track details blank, and also putting some text in there. Ignores the static information and still sends the track artist/track name.

### Version

2.4

### OS

Windows 10

**Comment by ronso0** [comment]
What is sent if you enter any string into the static field, e.g. `.`, or a whitespace?

**Comment by J-Marie123** [comment]
If you are using Live365, they require metada for copyright use. I'm only aware of live performances not having copyright requirements for broadcast

**Comment by palaran** [comment]
Encoder was Icecast 2

When I put text into the static artist and static track details it appeared to ignore that completely and instead simply send the artist/track information of the track that was playing.

**Comment by ronso0** [comment]
So the "static" checkbox is ignored entirely, regardless the artist+title fields?

I'm checking src/engine/sidechain/shoutconnection.cpp just now but (besides some irritating variable naming) I can't spot an obvious flaw in the metadata update calls.
Will try to set up icecast host and add some trace output.

**Comment by palaran** [comment]
That's certainly what appeared to be happening when I did a stream with static checkbox selected and both either nothing or some text in the relevant static artist/title box. Still sent the specific artist/track data each time the track changed, and did not seem to be sending the static data at all.

**Comment by ronso0** [comment]
Hmm, I can't confirm, 'static' works exactly as expected.

* local icecast2 server
* broadcast profile:
stream name: MixxxRonsoFx
format: MP3
bitrate: 128
metadata format: _(empty)_
static metadata: :heavy_check_mark:
artist: _(empty)_
title: _(empty)_
* listen with VLC: window title says "MixxxRonsoFx - VCL"
and that remains, no matter what tracks I play, how I set the crossfader etc.

Mixxx 2.4.1, Linux (Ubuntu Studio 20.04.x)
libshout version: 2.4.1
Icecast version: 2.4.4

**Comment by ronso0** [comment]
Which libshout version do you use?
(this is logged during Mixxx startup, see mixxx.log)

What value does the `<EnableMetadata>` node have in your broadcast profile xml?
Should be 1 for static metadata.

Not sure how to debug this. Could add trace output all over the place..

**Comment by palaran** [comment]
Hrrrm, when I went back in and tried it again it works fine. 

I do have a number of different streams set up so I do wonder whether it is possible that I accidentally edited the metatdata settings for a different one to the one that I then ultimately streamed on to test. If so I apologise for causing unnecessary worry.

Need to go take the kids to swimming but will play with this a bit when I get back, and if I can't reproduce will put down to user error. Either way will report back in a few hours.

**Comment by palaran** [comment]
So, appears I owe aplogies - have played with it a bit with various different settings and can confirm that for me it is working. Can only assume that I was editing the wrong stream details previously. Sorry for wasting your time.

**Comment by ronso0** [comment]
Never mind.
