### ISSUE TITLE
Del key in sidebar doesn't trigger crate/playlist delete dialog anymore

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13361]
### Bug Description

Due to
https://github.com/mixxxdj/mixxx/blame/abd9d11bf7ee09d259e568590a3f669547b53374/src/widget/wlibrarysidebar.cpp#L246-L248
the Delete code can't be reached anymore.

Probably a leftover from #12020 
And i think we overlooked -or I forgot it- that this does clear the AutoDJ queue without confirmation!
(which I consider a blocker btw. Unlikely it happens, but if it does you might screw your carefully curated AutoDJ playlist)

Removing this branch (and related methods like clear()) fixes the original issue.
But what about clearing AutoDJ queue from the sidebar?
1. rename `AutoDJFeature::clear()` -> `AutoDJFeature::deleteItem` and add a confirmation dialog?
2. add a respective sidebar menu action to make the feature discoverable?
3. remove it?

I'd vote for 1. + 2. Though, if we'd be strict with the string freeze we'd need to drop it and reintroduce it in 2.6 with the proper dialog and sidebar menu action.

Additionally, we may allow `deleteItem` for the AutoDJ crates.

### Version

2.5-alpha

**Comment by daschuer** [comment]
I think we can be less strict with string freeze because we have always anyway many untranslated strings. 
So one more to make an important bug-fixvis OK for me 
We should be strict, not to change the source strings of already translated strings during a beta.
