### ISSUE TITLE
Add a Just Played History List

### ISSUE THREAD

**Issue by joeyrain** [mixxxdj/mixxx#13376]
### Feature Description

I think this will be my last suggestion...I think the program is a great program and for myself it only needs a few tweaks. I think it would be really great to have a just played history list...maybe list the last 100 songs played and keep updating the list with every song that plays.. This helps in picking songs to play next when you can see a list of what just played. I think this could be an option to select or unselect... If you do select to see the history list then Maybe half of the screen would be a list of songs that are in the queue to be played and the other half of the screen can be a history list of what just got played... it can be side to side or one above the other with scroll bars for each section. if you do not select this option then your entire screen is of what is in the queue. Just a suggestion.

**Comment by macrophone** [comment]
There is a history section at the bottom of the library menu. Plus, the tracks you've played are ticked in the "played" collumn in library.

**Comment by joeyrain** [comment]
Ohh wow...i never even noticed it... thanks

**Comment by ronso0** [comment]
Recently there was a discussion about a related feature: a list of loaded tracks, i.e. all tracks that been loaded into one of the decks, regardless whether they were actually played (in the main mix).
