### ISSUE TITLE
Auto reconect audio in case of usb disconnect.

### ISSUE THREAD

**Issue by fvfilippetti** [mixxxdj/mixxx#13389]
### Feature Description

I have an Allen and Heath Xone K2 (USB) and in normal usage is common to experiment loose electrical connection because a wear out on laptop USB port.  Because of this, the audio stop working and is necessary to open the setup and reconnect manually. This implies about 30 seconds without music, but is an eternity when you have 1500 people staring at you. some software like Traktor implement this useful functionality.

**Comment by ronso0** [comment]
Yes, that is annoying. The issue / feature request is covered by #6150 from 2011 ; )
It was even a GSoC project proposal at least once but no one applied for it IIRC

**Comment by Eve00000** [comment]
Avoiding this situation is the best solution.
Put your core DJ-Material (Mixer, PC, Soundcard) behind a UPS (uninterruptible power supply) /Surge protector. You can find a small UPS from about 50-60 €. Thes UPS's can deliver power for about 10 minutes and protect your equipment for electrical problems.
If your using a laptop with a good battery you don't have to plug the laptop in the UPS, so you can save even more UPS-power, but I would advise to plug the adapter in a surge protector as well.
