### ISSUE TITLE
Mixxx 2.4: Korg Kaoss DJ not working on macOS Sonoma

### ISSUE THREAD

**Issue by larromba** [mixxxdj/mixxx#13439]
### Bug Description

Hello,

I opened the following PR back in 2018 to get the Korg Kaoss DJ working:
https://github.com/mixxxdj/mixxx/pull/1509

I've noticed since Mixxx 2.1, the controller no longer seems to be recognised by Mixxx on macOS. My hunch is that it's not Mixxx, but that later versions of macOS have a different controller name mapping in the function `namesMatchAllowableEdgeCases` (file: `src/controllers/midi/portmidienumerator.cpp`).

I tried to compile `main` on MacOS Sonoma (macbook M1 Pro) to check this, however after downloading the dependencies via `source tools/macos_buildenv.sh setup`, and running `cmake -DCMAKE_TOOLCHAIN_FILE=/Users/larromba/Documents/Code/Public/mixxx/mixxx/buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/scripts/buildsystems/vcpkg.cmake /Users/larromba/Documents/Code/Public/mixxx/mixxx`, I get the following error at some point:

```
CMake Error at buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Qml/Qt6QmlMacros.cmake:2828 (message):
  Failed to scan target mixxx for QML imports: Illegal instruction
Call Stack (most recent call first):
  buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Qml/Qt6QmlMacros.cmake:2863 (_qt_internal_scan_qml_imports)
  buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Core/Qt6CoreMacros.cmake:636 (qt6_import_qml_plugins)
  buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Core/Qt6CoreMacros.cmake:636 (cmake_language)
  buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Core/Qt6CoreMacros.cmake:709 (_qt_internal_finalize_executable)
  buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5/installed/x64-osx-min1100/share/Qt6Core/Qt6CoreMacros.cmake:679:EVAL:1 (qt6_finalize_target)
  CMakeLists.txt:DEFERRED
```

My exports are:
```
export MIXXX_VCPKG_ROOT=/Users/larromba/Documents/Code/Public/mixxx/mixxx/buildenv/mixxx-deps-2.5-x64-osx-min1100-06fe9b5
export CMAKE_GENERATOR=Ninja
export VCPKG_TARGET_TRIPLET=x64-osx-min1100
```

I'm not sure if I'll find the time to try and figure out these errors, but at least from some recent PRs, it seems the controller is working on other platforms. Either way, I thought it best to raise some awareness about this issue!

Cheers,
Lee

### Version

2.4

### OS

macOS Sonoma (MacBook M1 Pro)

**Comment by Swiftb0y** [comment]
> VCPKG_TARGET_TRIPLET=x64-osx-min1100

You're compiling for x64 on your Arm mac. try https://github.com/fwcd/m1xxx

**Comment by larromba** [comment]
Hello @Swiftb0y. Thanks, I tried to compile that, but still have some issues.

I've done a bit more research, and I believe it's not Mixxx, but that the device is no longer supported for macOS Sonoma, and the software is no longer maintained by Korg. 

Please search for "KAOSS DJ" on this document:
https://www.korg.com/download/global/support/os/pdf/mac_compatibilitychart_KORG_en.pdf

From reading this, I think it's safe to assume Korg Kaoss DJ is still supported on macOS 12, but not on later versions of macOS. I'm not sure if this should be described somewhere in the documents - but hopefully that's useful information!

Cheers

**Comment by larromba** [comment]
I've added a PR to the manual here, and requested in the zulipchat to add this also to the wiki, as I'm not authorized to:
https://github.com/mixxxdj/manual/pull/682

Thanks

**Comment by Swiftb0y** [comment]
Since this is not really our bug (nor can we do much about) I will close this. Thanks for filing this bug, your research and the manual PR.
