### ISSUE TITLE
no BPM column in Auto DJ

### ISSUE THREAD

**Issue by WhaltBabieLuv** [mixxxdj/mixxx#13431]
### Bug Description

There isn't a BPM read out in the "Tracks" area and for "Auto Dj".

### Version

2.4.1 Version

### OS

Windows 7

**Comment by ronso0** [comment]
What's a "read out"?

**Comment by RafaelFrance** [comment]
@WhaltBabieLuv
I think that after a fresh intall of Mixxx the BPM column is not present in the Track list.
You need to add it (Right-click on top of Track list columns).
