### ISSUE TITLE
ID3v2 rating metadata not written to file

### ISSUE THREAD

**Issue by joaonunatings** [mixxxdj/mixxx#13441]
Commented by: **[raffitea](https://launchpad.net/~raffitea)**
Date: 2010-12-12T16:08:36Z

---

By default, ID3v2 comments are written to the mp3 files. As long as these information are reflected tools like Mp3Tag everything is ok. I've similar problems with my Windows Explorer. All my files are manupulated with Mp3Tag, but the Explorer fails in reading the tags for various files. 

You can open the log file to see if metedata has been written successfully to the file.

I could implement an option such that the old ID3v1 tag is written as well. But I think it does not make sense because good music players such as iTunes can handle Id3v2 and up.

BTW: Some fileds are not written to file:
 * Rating
 * ReplayGain

All other metadata be synchronized.

_Originally posted by @mixxxbot in https://github.com/mixxxdj/mixxx/issues/5711#issuecomment-1225394416_

Why is Rating metadata not written to file? I find this to be very useful because I rate songs in Mixxx itself, I would like that to be saved not only in the Mixxx database but also in the file itself.

**Comment by ronso0** [comment]
> Why is Rating metadata not written to file?

This is tracked in #9477, please check the converstaion there.

**Comment by joaonunatings** [comment]
@ronso0 thanks!
Closing this as a duplicate of https://github.com/mixxxdj/mixxx/issues/9477.
