### ISSUE TITLE
Deprecate `lodash.mixxx.js` to be removed in a future version

### ISSUE THREAD

**Issue by christophehenry** [mixxxdj/mixxx#13457]
### Feature Description

Mixxx has been supporting ES6 features since 2.4.0. Lodash implement features that were missing in ES5 but most of them got resolved with ES6 and ES7. As of now, all the current controllers use is  `_.merge()`, `_.assign()`, which can be replaced by `Object.assign()` in most cases, `_.forEach`, which can be replaced by `Array.prototype.forEach()` and `_.filter()` which can be replaced by `Array.prototype.filter()`.

[`script.deepMerge()`](https://github.com/mixxxdj/mixxx/blob/main/res/controllers/common-controller-scripts.js#L168) could also be deprecated in 2.5.0 in favor of `Object.assign()` since I'm not really sure it really has a broader usage. Currently it has been only used in [`ComponentContainer.applyLayer()`](https://github.com/mixxxdj/mixxx/blob/main/res/controllers/midi-components-0.0.js#L664) since [dropping lodash dependency in ComponentJS](https://github.com/mixxxdj/mixxx/pull/12779).

Anyway, less code is better.

**Comment by Swiftb0y** [comment]
I'm in favor. Though care needs to be taken when doing the replacement as lodash and built-in methods work slightly differently on sparse arrays (for example`Array.prototype.forEach()` and `_.forEach`, for their `map()` equivalents).

**Comment by christophehenry** [comment]
Can you expand on how they work differently?

**Comment by Swiftb0y** [comment]
:shrug: yeah. Idk. just saying that if you're replacing code like `_.map(Array(N), f)` it needs to be something like `Array(N).fill(0).map(f)`

**Comment by christophehenry** [comment]
Maybe we could open a wiki migration guide?

**Comment by Swiftb0y** [comment]
Yeah, unfortunately we had a problem of people abusing wiki pages for distributing malware so we had to lock it down. I don't have the time to write a guide myself but I can offer to upload a page for you once you have written it.

**Comment by christophehenry** [comment]
Good. I'll propose something tonight.

**Comment by christophehenry** [comment]
[Here you go.](https://github.com/user-attachments/files/16147781/lodash-migration.md)

**Comment by Swiftb0y** [comment]
Done, thank you. Made some edits, let me know if you have a problem with it. https://github.com/mixxxdj/mixxx/wiki/Lodash-Migration

**Comment by christophehenry** [comment]
Nice, thank you. I'll open a PR resolving this.

**Comment by christophehenry** [comment]
Closed per #13460
