### ISSUE TITLE
Waveform issues with "High details" enabled

### ISSUE THREAD

**Issue by daschuer** [mixxxdj/mixxx#13472]
### Bug Description

RGB high details waveform are showing an offset:
High details, the beat marker is not on the visual beat: 
![image](https://github.com/user-attachments/assets/122163a8-ed50-4d0e-ae5f-00da2b7f7452)
No High details, the beat marker is at the expected position: 
![image](https://github.com/user-attachments/assets/a5625af9-895c-4e13-844a-1052265f6cfa)

Tested with QT 6.2

### Version

2.6~alpha

### OS

Ubuntu Focal

**Comment by daschuer** [comment]
With another track, I see only the upper half. The waveform disappears entirely when I disable "Stereo coloration". 
 
![image](https://github.com/user-attachments/assets/402fd2e7-1476-4d2b-bc3b-bdf3435140ea)

**Comment by Swiftb0y** [comment]
To clarify, the missing bottom half only applies to the "High Details" version?

**Comment by Swiftb0y** [comment]
Both of these refer to https://github.com/mixxxdj/mixxx/issues/13471#issuecomment-2227448930 and https://github.com/mixxxdj/mixxx/issues/13471#issuecomment-2227454898 respectively, right?

**Comment by daschuer** [comment]
> To clarify, the missing bottom half only applies to the "High Details" version? 

Yes.

Non of these issues are in 2.5 with Qt5 
I am just building Qt6

**Comment by daschuer** [comment]
The 2.5 + Qt 6 build is also not affected.

**Comment by ywwg** [comment]
as I suspected, the stem support is causing the problem ( @**Antoine C** ) commit 2911c38809634f2f547325882a4956fdc7a75860

**Comment by acolombier** [comment]
I believe I know how to fix it, I will prepare a fix for it soon.

**Comment by ywwg** [comment]
it looks like the waveform is still stretched by 2x, reopening

**Comment by acolombier** [comment]
Could you please attach some screenshots or reproducing steps?

**Comment by ywwg** [comment]
looks like it's not 2x, but some small fraction
[Screencast from 2024-07-17 13-42-06.webm](https://github.com/user-attachments/assets/0e384235-dc9b-46dd-9c22-79268d734d75)

**Comment by ywwg** [comment]
seeking to the end of the waveform is sufficient for seeing the issue

**Comment by acolombier** [comment]
Wondering if there could be some issue due to memory alignment. I should have some time this weekend, if anyone wants to give it a go in the meantime, please feel free to!

**Comment by Swiftb0y** [comment]
Not trying to be "I told you so", but I think this is a convincing argument for why abusing a texture for uploading a blob to the GPU is a bad idea...

**Comment by ywwg** [comment]
if we could get the same level of detail with another method I'd be all for it

**Comment by ywwg** [comment]
ah it's not an offset, there's just a point in the waveform at which suddenly it starts showing the wrong data.  In this video you can see the left half of the waveform is correct, and the right half is wrong.

[Screencast from 2024-07-19 11-10-37.webm](https://github.com/user-attachments/assets/a2fa6c43-fcea-4e13-9a35-3bf027f2fad5)

**Comment by ywwg** [comment]
it looks like it wraps around to the beginning of the waveform -- I'm guessing there's a miscalculation of the total length of the data?

**Comment by ywwg** [comment]
[Screencast from 2024-07-19 11-20-13.webm](https://github.com/user-attachments/assets/3882a38b-6861-45bd-a97a-a68d87890ff2)

**Comment by ywwg** [comment]
error always starts at 2:28.60

**Comment by ywwg** [comment]
are we overflowing int32

**Comment by ywwg** [comment]
hmmmm it all goes wrong at visualindex 65535 :)

**Comment by ywwg** [comment]
ok well I guess this is technically a different problem than the 2x issue last time... but it seems ok to reuse the bug
