### ISSUE TITLE
BPM / Key Readout

### ISSUE THREAD

**Issue by WhaltBabieLuv** [mixxxdj/mixxx#13478]
### Bug Description

There is no BPM, or Key readout for tacks in the "tracks list", auto dj, and crates.  BPM and key readout only show when loading tracks to decks.  Need to be able to see BPM of tracks and key before loading to decks.

### Version

2.4.1.

### OS

Windows 7

**Comment by ronso0** [comment]
Dupe of #13431, why don't you enable the BPM as advised in the comment https://github.com/mixxxdj/mixxx/issues/13431#issuecomment-2203974850 ?
