### ISSUE TITLE
Plans for implementing mixxx or parts of it in Rust programming language

### ISSUE THREAD

**Issue by spotlesscoder** [mixxxdj/mixxx#13509]
### Feature Description

Unfortunately I can't sign up to the discourse forum currently - no account activation mail arriving so I'm asking here:

Are there any plans to migrate the code or parts of it to Rust?
I really fell in love with that language and would love to do something meaningful with it

**Comment by Holzhaus** [comment]
IIRC we are definitely open to it. However, GitHub issues issues is for bug reports or feature requests, and discourse is for community support. For development discussions, we're using https://mixxx.zulipchat.com :)

Some pointers:

- https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/mixxx.203.20in.20qt.20.2B.20rust.20.3F/near/123133252
- https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/New.20ScratchEngine.20in.20Rust/near/441830188
- https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Moving.20forward.20with.20Rust/near/397012049
