### ISSUE TITLE
Opaque color for played song

### ISSUE THREAD

**Issue by vespadj** [mixxxdj/mixxx#13510]
### Feature Description

In skin, how change color of played songs?
Expected: opacity -30% or gray text for row of played songs.
All views: Tracks, Computer,  etc...

**Comment by Swiftb0y** [comment]
Are you aware of the played column in the library? Can you elaborate on why that is not sufficient for your usecase and why you would prefer the entire row to be colored instead? How would that interact with tracks that have been colored? 
![image](https://github.com/user-attachments/assets/3e096549-77d1-4b13-acf8-1c66ea31b91e)

**Comment by ronso0** [comment]
FYI played tracks are painted with a dim color (grey text) in Mixxx 2.5 (#12744)
Since #12916 this is optional -> Preferences -> Library

The color/opacity can also be customized with this snippet in style.qss (or style_palemoon.qss or whatever color scheme is used)
```
WTrackTableView {
  qproperty-playedInactiveColor: #555;
}
```
