### ISSUE TITLE
Linking "Mix wet / dry" of effectrack with P&C crashes Mixxx

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#13527]
### Bug Description

Linking "Mix wet / dry" of effectrack with P&C crashes Mixxx

in mixxx -developer I get:
warning [Controller] ControlDoublePrivate::getControl returning NULL for ( "[EffectRack1_EffectUnit1]" , "super" )
DEBUG ASSERT: "flags.testFlag(ControlFlag::NoAssertIfMissing)" in function class QSharedPointer<class ControlDoublePrivate> __cdecl ControlDoublePrivate::getControl(const class ConfigKey &,class QFlags<enum ControlFlag>,class ControlObject *,bool,bool,bool,double) at D:\mixxx-git\mixxx\src\control\control.cpp:203

### Version

2.6

### OS

Win 10

**Comment by Swiftb0y** [comment]
Thank you for reporting your issue. Please understand that in order for us to be able to properly debug this, we need a backtrace. Have a look at the wiki for finding out how to create one: https://github.com/mixxxdj/mixxx/wiki/Creating%20Backtraces

**Comment by Eve00000** [comment]
I tried but x96dbg does not let me start in -developer

**Comment by daschuer** [comment]
My guess is yo have an issue with your mapping. 
The control is named "super1"  with 1 as postfix. 

For developer mode you need to use two dashes.
`--developer`

**Comment by ronso0** [comment]
https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1_EffectUnitN]-super1

**Comment by Eve00000** [comment]
Thank you for your insight, I will take a serious look on the mapping.

**Comment by ronso0** [comment]
I'll close this for now (to shrink the open bugs list), feel free to reopen if the issue persists with the fixed mapping.

**Comment by Eve00000** [comment]
OK, today I did not have the problem. Maybe it was an issue of too much midi-controllers
