### ISSUE TITLE
External audio channel on e.g. "Traktor Kontrol S4" and other mixing consoles with appropriate equipment

### ISSUE THREAD

**Issue by VamLykTan** [mixxxdj/mixxx#13534]
### Feature Description

Good morning,

I currently have a Traktor Kontrol S4 on loan, which I would like to use to DJ in the future.

Since I also want to stream, I'm looking for a way to link 2 additional audio sources (e.g. Herkules Serato DJ, CD player, vinyl player) to decks 3 and/or 4.

On which input and, above all, do I have to link the channels?

**Comment by ronso0** [comment]
Hej.
This is the bug tracker, we use it to track bugs and feature request.
For user support there are the forums https://mixxx.discourse.group/
For future request, please ask there (more users will find your question and the solution there), and check the manual, of course:
https://manual.mixxx.org/
https://manual.mixxx.org/2.4/en/hardware/controllers/native_instruments_traktor_kontrol_s4_mk2
https://manual.mixxx.org/2.4/en/hardware/controllers/native_instruments_traktor_kontrol_s4_mk3

https://manual.mixxx.org/2.4/en/chapters/preferences/sound_hardware#output-and-input-devices

Currently the only way to get input streams into main decks 1-4 is via Vinyl Control -- no matter if you want to use time code vinyl / CDs to control a Mixxx deck or just play the raw input through Mixxx:
https://manual.mixxx.org/2.4/en/chapters/vinyl_control
If you want to play the raw audio, you don't need to touch the default VC settings, just setup the input devices and enable Passthrough in the decks (you may need to show Vinyl Controls first: View Menu -> Show Vinyl Control Section (default: Ctrl+3), or via skin settings menu (Ctrl+1) -> Vinyl Controls.

**Comment by ronso0** [comment]
For now I'll close this (you can still comment).
If you have further questions, please open a thread in the forums and I'll copy my answer over.
Thank you!
