### ISSUE TITLE
Document that Xone:23C needs kernel parameter to work

### ISSUE THREAD

**Issue by christophehenry** [mixxxdj/mixxx#13536]
### Bug Description

[The Allen & Heath Xone:23C is documented to work with Linux](https://github.com/mixxxdj/mixxx/wiki/Hardware-Compatibility#mixers-with-audio-interfaces) but as of now, it isn't natively recognized as a 2 in/2 out audio device by Linux. [This kernel ticket](https://bugzilla.kernel.org/show_bug.cgi?id=217089) documents that the mixer has been correctly recognized somewhere around kernel ~5.4 but most distributions have changed the configuration in `/sys/module/usbcore/parameters/old_scheme_first` since then.

Currently, on Fedora (and mostly others) the mixer needs the `usbcore.old_scheme_first=1` kernel parameter to be correctly recognized, which can be added with the following command-line as root:

```bash 
grubby --args="usbcore.old_scheme_first=1" --update-kernel=ALL
```

[I opened this ticket](https://bugzilla.kernel.org/show_bug.cgi?id=219111) to work with the kernel devs to get the mixer to work without the kernel param.

Also, the mixer is documented to need a udev rule, which is not true since #2903 was merged.

### Version

Probably all

### OS

Linux, probably every distribution running kernel 5.4+

**Comment by christophehenry** [comment]
Here is a patch for this issue.
[diff.patch.txt](https://github.com/user-attachments/files/17355973/diff.patch.txt)

**Comment by Swiftb0y** [comment]
Applied. Thank you.
