### ISSUE TITLE
Fixes in hardware wiki page

### ISSUE THREAD

**Issue by christophehenry** [mixxxdj/mixxx#13548]
### Bug Description

Here is a patch with a few fixes in the hardawre wiki page:

- use markdown footnotes for footnotes
- use markdown table instead of HTML table for mappings in dev
- table formatting

[wiki.patch.txt](https://github.com/user-attachments/files/16541702/wiki.patch.txt)

**Comment by daschuer** [comment]
I have applied the patch via the editor. The indentation changes below "[^42]:" where rejected, because the editor shows 42.. 
Don't know how this is related? Please verify.

**Comment by christophehenry** [comment]
Were you able to apply this patch?

**Comment by daschuer** [comment]
Is the patch no longer availabe? I get an obscure error message in xml format.

**Comment by christophehenry** [comment]
Odd. [Here it is.](https://github.com/user-attachments/files/16649674/wiki.patch.txt)

**Comment by daschuer** [comment]
Foodnotes are not supported in the wiki :-(
https://github.com/orgs/community/discussions/56433

So it looks like the current state is OK?

**Comment by christophehenry** [comment]
Dammit! Ok, then.
