### ISSUE TITLE
Numark Party Mix Mk2

### ISSUE THREAD

**Issue by SusikaTheBest** [mixxxdj/mixxx#13554]
### Bug Description

I have a Numark Party Mix Mk2 DJ Controller and i have a mapping file for the Mixxx program, and when i select Party Mix Mk2, i cant control the music with my controller.

### Version

2.4.1

### OS

Windows 10

**Comment by Swiftb0y** [comment]
Please share your mapping file and its source. The mapping is not built into mixxx so we can't really provide support for that.
