### ISSUE TITLE
opus could not be loaded

### ISSUE THREAD

**Issue by Puxap-3opre** [mixxxdj/mixxx#13560]
### Bug Description

Files like OggOpus "can't be loaded" even though they play in Audacious. From the log:

```
Warning [CachingReaderWorker 2] SoundSourceOpus - Opening of OggOpusFile failed with error -132 : "/home/pete/Music/Bach - Chaconne.opus"
Warning [CachingReaderWorker 2] SoundSourceProxy - Failed to open file "file:///home/pete/Music/Bach - Chaconne.opus" with provider "Xiph.org libopusfile" using mode Strict
Warning [CachingReaderWorker 2] SoundSourceOpus - Opening of OggOpusFile failed with error -132 : "/home/pete/Music/Bach - Chaconne.opus"
Warning [CachingReaderWorker 2] SoundSourceProxy - Failed to open file "file:///home/pete/Music/Bach - Chaconne.opus" with provider "Xiph.org libopusfile" using mode Permissive
Warning [CachingReaderWorker 2] CachingReaderWorker - "[Channel1]" Failed to open file QFileInfo(/home/pete/Music/Bach - Chaconne.opus)
Debug [Main] Failed to load track QFileInfo(/home/pete/Music/Bach - Chaconne.opus) "The file '/home/pete/Music/Bach - Chaconne.opus' could not be loaded."
```

https://archlinux.org/packages/extra/x86_64/mixxx/

### Version

2.4.1-4

### OS

Arch Linux

**Comment by daschuer** [comment]
The error is generated in the opus codec library: 

#define 	[OP_ENOTFORMAT](https://opus-codec.org/docs/opusfile_api-0.12/group__error__codes.html#gafca3ae244d24e10b2851c77379453220)   (-132)

A purported Ogg Opus stream did not begin with an Ogg page, a purported header packet did not start with one of the required strings, "OpusHead" or "OpusTags", or a link in a chained file was encountered that did not contain any logical Opus streams.
```

**Comment by daschuer** [comment]
You may send me the file for further analysis.

**Comment by Puxap-3opre** [comment]
> You may send me the file for further analysis.

https://ufile.io/ag44o5qw

By some info programs it's recognized as .ogg. Audacious says it's codec is Opus. Whatever it is, here is it.

Thank you.

**Comment by daschuer** [comment]
The file is an opus file in an ogg (audio/x-opus+ogg) container in an webm (video/webm) container. So the correct file extension is "webm". Mixxx does not yet support webm files. As a workaround you can extract the opus+ogg file form the webm container by: 

`mkvextract Lara-Louise-_-Un-jour-de-difference.webm tracks 0:Lara-Louise-_-Un-jour-de-difference.opus`

**Comment by daschuer** [comment]
We have a bug for webm support: 
https://github.com/mixxxdj/mixxx/issues/12832
