### ISSUE TITLE
Waveforms not showing 

### ISSUE THREAD

**Issue by WandernderVogel** [mixxxdj/mixxx#13565]
### Bug Description

The waveforms are not showing on my Mixxx 2.4.1 installation, instead the program opened before will show, i already tried to switch the waveform style, witch resulted in not moving waveforms except for the first few pixels offset( shown in the second picture)

![Screenshot_20240813_124546](https://github.com/user-attachments/assets/ce57cc75-dc25-4ae6-a587-55109821e3ae)

![Screenshot_20240813_125208](https://github.com/user-attachments/assets/87ca9302-73f6-4f91-9a4b-ac34a6e6ec40)

### Version

2.4.1

### OS

Debian 12

**Comment by Swiftb0y** [comment]
Thats weird. it should contain the exact mesa version you are using. Can you look that up using your package manager?

**Comment by WandernderVogel** [comment]
The version string of my OpenGL installation is 4.6 (Core Profile) Mesa 22.3.6

**Comment by Swiftb0y** [comment]
thanks. two weird things:
1. why is mixxx only saying opengl 4.3 even though the driver seems to support 4.6? 
2. Mesa 22. is quite old...

Can you share your [mixxx.log file](https://github.com/mixxxdj/mixxx/wiki/Finding%20the%20Mixxx.log%20file)?

**Comment by WandernderVogel** [comment]
Debug [Main]: SoundSourceProxy - Registering SoundSource providers
Debug [Main]: SoundSourceProxy - Registering platform and fallback SoundSource providers
Debug [Main]: SoundSourceProviderRegistry - Registering provider "FFmpeg"
Info [Main]: SoundSourceFFmpeg - Disabling untested input formats: aa, aax, ac3, ace, acm, act, adf, adp, ads, adx, aea, afc, aix, alp, amr, amrnb, amrwb, anm, apc, ape, apm, apng, aptx, aptx_hd, aqtitle, argo_asf, argo_brp, argo_cvg, asf, asf_o, ass, ast, au, av1, avi, avr, avs, avs2, avs3, bethsoftvid, bfi, bin, bink, binka, bit, bitpacked, bmv, bfstm, brstm, boa, c93, caf, cavsvideo, cdg, cdxl, cine, codec2, codec2raw, concat, dash, data, daud, dcstr, derf, dfa, dfpwm, dhav, dirac, dnxhd, dsf, dsicin, dss, dts, dtshd, dv, dvbsub, dvbtxt, dxa, ea, ea_cdata, eac3, epaf, ffmetadata, filmstrip, fits, flac, flic, flv, live_flv, 4xm, frm, fsb, fwse, g722, g723_1, g726, g726le, g729, gdv, genh, gif, gsm, gxf, h261, h263, h264, hca, hcom, hevc, hls, hnm, ico, idcin, idf, iff, ifv, ilbc, image2, image2pipe, alias_pix, brender_pix, imf, ingenient, ipmovie, ipu, ircam, iss, iv8, ivf, ivr, jacosub, jv, kux, kvag, lmlm4, loas, luodat, lrc, lvf, lxf, mca, mcc, matroska,webm, mgsts, microdvd, mjpeg, mjpeg_2000, mlp, mlv, mm, mmf, mods, moflex, mpc, mpc8, mpeg, mpegts, mpegtsraw, mpegvideo, mpjpeg, mpl2, mpsub, msf, msnwctcp, msp, mtaf, mtv, musx, mv, mvi, mxf, mxg, nc, nistsphere, nsp, nsv, nut, nuv, obu, ogg, oma, paf, alaw, mulaw, vidc, f64be, f64le, f32be, f32le, s32be, s32le, s24be, s24le, s16be, s16le, s8, u32be, u32le, u24be, u24le, u16be, u16le, u8, pjs, pmp, pp_bnk, pva, pvf, qcp, r3d, rawvideo, realtext, redspark, rl2, rm, roq, rpl, rsd, rso, rtp, rtsp, s337m, sami, sap, sbc, sbg, scc, scd, sdp, sdr2, sds, sdx, film_cpk, ser, sga, shn, siff, simbiosis_imx, sln, smk, smjpeg, smush, sol, sox, spdif, srt, psxstr, stl, subviewer1, subviewer, sup, svag, svs, swf, tak, tedcaptions, thp, 3dostr, tiertexseq, tmv, truehd, tta, txd, tty, ty, v210, v210x, vag, vc1, vc1test, vividas, vivo, vmd, vobsub, voc, vpk, vplayer, vqf, w64, wc3movie, webm_dash_manifest, webvtt, wsaud, wsd, wsvqa, wtv, wve, xa, xbin, xmv, xvag, xwma, yop, yuv4mpegpipe, bmp_pipe, cri_pipe, dds_pipe, dpx_pipe, exr_pipe, gem_pipe, gif_pipe, j2k_pipe, jpeg_pipe, jpegls_pipe, jpegxl_pipe, pam_pipe, pbm_pipe, pcx_pipe, pfm_pipe, pgmyuv_pipe, pgm_pipe, pgx_pipe, phm_pipe, photocd_pipe, pictor_pipe, png_pipe, ppm_pipe, psd_pipe, qdraw_pipe, qoi_pipe, sgi_pipe, svg_pipe, sunrast_pipe, tiff_pipe, vbn_pipe, webp_pipe, xbm_pipe, xpm_pipe, xwd_pipe, libgme, libopenmpt
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aac" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aif" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aiff" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "m4v" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mov" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp4" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "m4a" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "3gp" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "3g2" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mj2" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp3" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wav" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wv" for provider "FFmpeg" with priority 1 (lowest)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "MAD: MPEG Audio Decoder"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mp3" for provider "MAD: MPEG Audio Decoder" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "MODPlug"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "mod" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "med" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "okt" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "s3m" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "stm" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "xm" for provider "MODPlug" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "it" for provider "MODPlug" with priority 3 (default)
Info [Main]: SoundSourceSndFile - Disabling OGG decoding for "libsndfile-1.2.0"
Debug [Main]: SoundSourceProviderRegistry - Registering provider "libsndfile"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aif" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "aiff" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "caf" for provider "libsndfile" with priority 2 (lower)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "flac" for provider "libsndfile" with priority 2 (lower)
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wav" for provider "libsndfile" with priority 3 (default)
Debug [Main]: SoundSourceProxy - Registering reference SoundSource providers
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org libFLAC"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "flac" for provider "Xiph.org libFLAC" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org OggVorbis"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "ogg" for provider "Xiph.org OggVorbis" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "Xiph.org libopusfile"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "opus" for provider "Xiph.org libopusfile" with priority 4 (higher)
Debug [Main]: SoundSourceProviderRegistry - Registering provider "WavPack"
Debug [Main]: SoundSourceProviderRegistry - Registering file extension "wv" for provider "WavPack" with priority 4 (higher)
Debug [Main]: Mixxx 2.3.3 (git unknown; built on: Nov 22 2022 @ 23:03:45; flags: -pipe;-O3;-ffast-math;-funroll-loops;-fomit-frame-pointer;-mtune=generic;-Wall;-Wextra;$<$<COMPILE_LANGUAGE:CXX>:-Woverloaded-virtual>;-Wfloat-conversion;-Werror=return-type) is starting...
Debug [Main]: Compile time library versions:
Debug [Main]: Qt: 5.15.8
Debug [Main]: libshout: 2.4.1
Debug [Main]: PortAudio: 1246720 PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
Debug [Main]: RubberBand: 3.1.0
Debug [Main]: SoundTouch: 2.3.1
Debug [Main]: TagLib: 1.13.0
Debug [Main]: ChromaPrint: 1.5.1
Debug [Main]: Vorbis: Xiph.Org libVorbis 1.3.7
Debug [Main]: libsndfile: libsndfile-1.2.0
Debug [Main]: FLAC: 1.4.2
Debug [Main]: libmp3lame: 3.100
Debug [Main]: QStandardPaths::writableLocation(HomeLocation): "/home/sven"
Debug [Main]: QStandardPaths::writableLocation(DataLocation): "/home/sven/.local/share/Mixxx"
Debug [Main]: QCoreApplication::applicationDirPath() "/usr/bin"
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Configuration file is at the current version "2.3.3"
Info [Main]: BroadcastSettings - Found 1 profile(s)
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Found and will use default keyboard preset "/usr/share/mixxx/keyboard/en_US.kbd.cfg"
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Debug [Main]: Skipping loading of translations because the locale is 'en' or 'en_US'.
Debug [Main]: Loading resources from  "/usr/share/mixxx/"
Warning [Main]: Wayland does not support QWindow::requestActivate()
Debug [Main]: No fonts directory found in "/usr/share/mixxx/"
Info [Main]: DbConnection - Available drivers for database connections: ("QSQLITE", "QMARIADB", "QMYSQL", "QMYSQL3")
Info [Main]: DbConnectionPool - Cloned thread-local database connection "MIXXX-1" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Info [Main]: MixxxMainWindow - Connecting to database
Info [Main]: MixxxMainWindow - Initializing or upgrading database schema
Info [Main]: SchemaManager - Database schema is up-to-date at version 32
Debug [Main]: JACK client name set
Debug [Main]: EngineNetworkStream - addWorker: worker added
Debug [Main]: EngineNetworkStream - worker slots used: "1 out of 16"
Debug [Main]: BroadcastManager - addConnection: created connection for profile "Connection 1"
Warning [Main]: "EffectParameter(Mid)" WARNING: Value was outside of limits, clamped.
Info [Main]: GlobalTrackCache - Creating instance
Info [Main]: TrackCollection - Connecting database
Info [Main]: TrackCollectionManager - Starting library scanner thread
Debug [LibraryScanner 1]: LibraryScanner - Entering thread
Info [LibraryScanner 1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-2" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Debug [LibraryScanner 1]: LibraryScanner - Event loop starting
Info [Main]: TrackCollection - Connecting track source
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: PlaylistTableModel(0x55f3b63a1d40) select() took 0 ms 0
Debug [Main]: CrateFeature::rebuildChildModel() -1
Debug [Main]: Appending Quick Link:  "Music" --- "/home/sven/Music/"
Debug [Main]: Appending Quick Link:  "Downloads" --- "/home/sven/Downloads/"
Debug [Main]: Appending Quick Link:  "Desktop" --- "/home/sven/Desktop/"
Debug [Main]: Appending Quick Link:  "Documents" --- "/home/sven/Documents/"
Debug [Main]: Appending Quick Link:  "05B0-120E" --- "/media/sven/05B0-120E/"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Traktor Library Location=[ "/home/sven/collection.nml" ]
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlist_tracks"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_playlists"
Debug [Main]: Dropping Rekordbox table:  "rekordbox_library"
Debug [Main]: Creating Rekordbox library table:  "rekordbox_library"
Debug [Main]: Creating Rekordbox playlists table:  "rekordbox_playlists"
Debug [Main]: Creating Rekordbox playlist tracks table:  "rekordbox_playlist_tracks"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Dropping Serato table:  "serato_playlist_tracks"
Debug [Main]: Dropping Serato table:  "serato_playlists"
Debug [Main]: Dropping Serato table:  "serato_library"
Debug [Main]: Creating Serato library table:  "serato_library"
Debug [Main]: Creating Serato playlists table:  "serato_playlists"
Debug [Main]: Creating Serato playlist tracks table:  "serato_playlist_tracks"
Debug [Main]: Committing transaction on "MIXXX-1" result: true
Debug [Main]: Checking for access to user's library directories:
Debug [Main]: Checking for access to "/home/sven/Music" : true
Debug [Main]: Checking for access to "/media/sven/05B0-120E/mp3/" : true
Debug [Main]: TrackAnalysisScheduler - Starting 4 worker threads. Priority:  normal
Debug [AnalyzerThread 0 #1]: AnalyzerThread 0 - Running
Debug [AnalyzerThread 1 #2]: AnalyzerThread 1 - Running
Debug [AnalyzerThread 2 #3]: AnalyzerThread 2 - Running
Debug [AnalyzerThread 3 #4]: AnalyzerThread 3 - Running
Info [AnalyzerThread 0 #1]: DbConnectionPool - Cloned thread-local database connection "MIXXX-3" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Debug [AnalyzerThread 0 #1]: AnalyzerThread - Activated 5 analyzers
Info [AnalyzerThread 3 #4]: DbConnectionPool - Cloned thread-local database connection "MIXXX-6" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Info [AnalyzerThread 1 #2]: DbConnectionPool - Cloned thread-local database connection "MIXXX-4" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Info [AnalyzerThread 2 #3]: DbConnectionPool - Cloned thread-local database connection "MIXXX-5" QSqlDatabase(driver="QSQLITE", database="file:///home/sven/.mixxx/mixxxdb.sqlite", host="", port=-1, user="mixxx", open=true)
Debug [AnalyzerThread 3 #4]: AnalyzerThread - Activated 5 analyzers
Debug [AnalyzerThread 1 #2]: AnalyzerThread - Activated 5 analyzers
Debug [AnalyzerThread 2 #3]: AnalyzerThread - Activated 5 analyzers
Debug [Main]: Creating ControllerManager
Debug [Controller]: ControllerManager:slotInitialize
Debug [Controller]: Extension .midi.xml total 0 presets
Debug [Controller]: Extension .hid.xml total 0 presets
Debug [Controller]: Extension .bulk.xml total 0 presets
Debug [Main]: Set root GL Context widget valid: QGLWidget(0x55f3b876b820) true
Debug [Main]: Created root GL Context valid: 0x55f3b875d870 true
Debug [Main]: Root GL Context format:
Debug [Main]: Double Buffering: true
Debug [Main]: Swap interval: 0
Debug [Main]: Depth buffer: true
Debug [Main]: Direct rendering: true
Debug [Main]: Has overlay: false
Debug [Main]: RGBA: true
Debug [Main]: Sample buffers: false
Debug [Main]: Samples: -1
Debug [Main]: Stencil buffers: true
Debug [Main]: Stereo: false
Debug [Main]: "openGLVersionFlags 0xff07f" "4.6 (Compatibility Profile) Mesa 22.3.6" "Intel" "Mesa Intel(R) HD Graphics 530 (SKL GT2)"
Debug [Main]: DBus screensaver  org.freedesktop.ScreenSaver  inhibited
Debug [Main]: RLimit Cur  0
Debug [Main]: RLimit Max  0
Debug [Main]: ControllerManager::getControllerList
Debug [Controller]: Extension .midi.xml total 127 presets
Debug [Controller]: Extension .hid.xml total 13 presets
Debug [Controller]: Extension .bulk.xml total 1 presets
Debug [Main]: Key plugin ID: "qm-keydetector:2"
Debug [Main]: LegacySkinParser loading skin: "/usr/share/mixxx/skins/LateNight"
Debug [Main]: Skin is a >=1.12.0 style skin.
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSpinny(): Created QGLWidget, Context Valid: true Sharing: true
Debug [Main]: WSearchLineEdit - Background color: QColor(ARGB 1, 0, 0, 0)
Debug [Main]: WTrackTableView::loadTrackModel() HiddenTableModel(0x55f3c64c0d80)
Debug [Main]: HiddenTableModel(0x55f3c64c0d80) select() took 0 ms 0
Debug [Main]: WTrackTableView::loadTrackModel() MissingTableModel(0x55f3c64f5f00)
Debug [Main]: MissingTableModel(0x55f3c64f5f00) select() took 0 ms 0
Debug [Main]: WTrackTableView::loadTrackModel() PlaylistTableModel(0x55f3b63a1d40)
Debug [Main]: Recordings folder set to "/home/sven/Music/Mixxx/Recordings"
Debug [Main]: WTrackTableView::loadTrackModel() QSortFilterProxyModel(0x55f3c665c7d8)
Info [BrowseThread]: MetadataSourceTagLib - No track metadata or cover art found in file "/home/sven/Music/Mixxx/Recordings/2024-08-12_23h24m56s.wav" with type 7

**Comment by Swiftb0y** [comment]
Thank you. Unfortunately I'm not able to spot anything obvious. Please try the other waveform styles as well. I suspect this is related to the graphics driver so you may want to try one of the software-rendered waveforms until your distribution has caught up. 
---
From personal experience: I would advise you against using Debian as your Desktop OS distribution. Ubuntu is more than stable enough (and used by many mixxx devs). As a developer, I have switched from Debian (because of its very slow release process) to Fedora and have never looked back since.

**Comment by Swiftb0y** [comment]
@m0dB can you spot anything in the mixxx log above?

**Comment by WandernderVogel** [comment]
I have now fixed it by installing Debian testing wich uses mesa 24
