### ISSUE TITLE
Waveforms: Simple and Stacked broken (empty) on main

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13561]
### Bug Description

when I load a track with these waveform types, the waveform remains empty.
When I resize the waveform container I get the blue playpos bar (LateNight).

Note that this is with Qt 6.2.3 which is admittedly outdated.
Can anyone confirm with a newer Qt version?

### Version

2.6-alpha

### OS

Ubuntu

**Comment by Swiftb0y** [comment]
Can not confirm on Fedora 40 with Qt 6.7.2.

**Comment by ronso0** [comment]
Now all is good again :man_shrugging: 
Maybe because 2.5 has been merged, idk? Apart from that no changes, same Qt version.
