### ISSUE TITLE
Regression: BPM and bitrate columns are wider than they used to be

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#13570]
### Bug Description

In recent main builds, the BPM and bitrate columns seem to require more space and truncate their content earlier:

https://github.com/user-attachments/assets/d97c731e-249e-4dfa-bf49-8d4c77067d4c

For comparison, this is how it used to look:

https://github.com/user-attachments/assets/6a2d6523-6d37-4881-a16c-ac07ea53ecdb

According to a quick bisect, 1dc1b9b3c4 was the last good and edb0806b48 the first bad commit ([diff](https://github.com/mixxxdj/mixxx/compare/1dc1b9b3c41cf5fbe27eedb85317eed77501ae14...edb0806b48a757e5bd358d1df3203c7ada955704)). Thus it looks like the regression was introduced by this PR:

- https://github.com/mixxxdj/mixxx/pull/13497

cc @danferns

### Version

2.6-alpha-62-gd87006546d (HEAD)

### OS

macOS 14.5

**Comment by danferns** [comment]
Thanks spotting this! The DecorationRole is receiving the the column's rawValue by default, instead of receiving an empty QVariant (correct old behavior).

I just fixed it, will open the PR shortly.
