### ISSUE TITLE
Star up/down in MC7000 mapping is broken

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#13587]
### Bug Description

The MC7000 mapping applies a star up/down on button down _and_ button up, resulting in two stars being applied or removed per press:

https://github.com/user-attachments/assets/10088abc-7d94-4913-87de-e6adc370d9ae

I suspect this to be a regression from #4729, since that PR last refactored this logic.

### Version

2.5

### OS

macOS 14.5

**Comment by ronso0** [comment]
fixed by #13588
