### ISSUE TITLE
Stars rating is lose when right click on multiple tracks.

### ISSUE THREAD

**Issue by j-wiedemann** [mixxxdj/mixxx#13597]
### Bug Description

Select multiple tracks at the same time, tracks should have different stars count.
Right click on one track to edit all selected tracks (like if you want to apply a color to all selected tracks).
Notice that stars rating is gone for all selected tracks. 

No problem on Mixxx 2.4.1

### Version

2.5-beta-43-g34aa89c780

### OS

PopOS 22.04 (Ubuntu 22.04), X11, NVIDIA

**Comment by ronso0** [comment]
Thanks for the report!
I can not confirm, neither by only opening the context menu, nor by doing some mass-edit (tested color, reset playcount, reset BPM).

> Right click on one track to edit all selected tracks

Or do yo mean you open Track Properties for the selected tracks, edit some tag, Appl/Okay, and then the rating is reset?

Can you please provide a short screencast of the issue?

**Comment by j-wiedemann** [comment]
Hello,
I was having hard time to reproduce. So I try different things as you can see on the video.
It look like its have to be new added song...
Sorry for the quality, have to reduce the video size. You can see the stars disappear at 1:14.

**Comment by j-wiedemann** [comment]
[Uploading bug mixxx stars.webm…]()

**Comment by j-wiedemann** [comment]
[bug mixxx stars.webm](https://github.com/user-attachments/assets/f5ac2468-f18d-4847-908d-1d03c7366b0f)

Hello,
I was having hard time to reproduce. So I try different things as you can see on the video.
It look like its have to be new added song...
Sorry for the quality, have to reduce the video size. You can see the stars disappear at 1:14.

**Comment by ronso0** [comment]
Alright, thanks for taking the time.

I could reproduce a few times (though not relaibly) with these steps:
* track C selected
* change the star rating of track A (selects track A) to > 0
* hold Shift
* move cursor over stars of track B to (empty) title field of track B
* click on track B title (A + B selected, "selectedClick is switched Off)
* right-click on track B
* menu pops up, ratings of A and B are reset to zero

I'll try to repro again with the ["selectedClick" switch](https://github.com/mixxxdj/mixxx/blob/400ae4618078fb07c063fceae3056253c6725d09/src/widget/wtracktableview.cpp#L111-L117) disabled.

**Comment by ronso0** [comment]
> I'll try to repro again with the ["selectedClick" switch](https://github.com/mixxxdj/mixxx/blob/400ae4618078fb07c063fceae3056253c6725d09/src/widget/wtracktableview.cpp#L111-L117) disabled.

That workaround is unrelated, can now repro somewhat reliably with the steps from above.
(and couldn't repro with 2.4.2 until now)

**Comment by ronso0** [comment]
Got it, fix is #13609
