### ISSUE TITLE
playlist label with count and duration does not update when you add or remove items from the playlist

### ISSUE THREAD

**Issue by designbymichael** [mixxxdj/mixxx#13590]
### Bug Description

In the playlist view, when you add or remove tracks from a given playlist, the label (which displays the name, quantity, and duration) on the left-hand side does not update. It only updates when you click on a different playlist and then back into the one you were working on.

### Version

2.4.1 (HEAD)

### OS

Mac 13.5.2

**Comment by ronso0** [comment]
Thanks for the report.
I just tested with 2.4.1 and this happens only if tracks are dragged into playlists tracks table, either from a deck or from file manager.
It works when dragging onto a sidebar item and when using the track menu -> Add to playlist

Fix is #13591 and will be available in Mixxx 2.4.2 (will be released shortly before 2.5).
If you like you can test it with the CI build once it's done. For details see Backup and Github pull requests in https://github.com/mixxxdj/mixxx/wiki/Testing

**Comment by ronso0** [comment]
I can not confirm the issue when removing tracks.
How do can you reproduce?

**Comment by designbymichael** [comment]
Sorry, I misspoke about removing tracks — those seem to auto-update on the
left pane.  But yes, to confirm, it is when dragging tracks from Finder (or
in other apps that offer a Finder-esque interface for managing
tracks/metadata) onto the Mixxx interface.



[image: --]

michael tangen
[image: http://]about.me/designbymichael
<http://about.me/designbymichael?promo=email_sig>

**Comment by ronso0** [comment]
Okay, thanks. So this is fixed by #13591
