### ISSUE TITLE
Allow programs folder to be in config folder in Linux

### ISSUE THREAD

**Issue by audio2000** [mixxxdj/mixxx#13618]
### Bug Description

Not really a bug.
In Linux, program configuration folders are typically put in 
`$HOME/.config/<program-folder>`
Mixxx however places its folder in 
`$HOME/.mixxx`
I was wondering if it would be considered to add a setting that would allow users to use a folder within the ".config" folder instead.

Thank You

### OS

Linux Debian based distro

**Comment by ronso0** [comment]
Thanjs, this is already covered by #8090

**Comment by audio2000** [comment]
Ahh sorry about that, I will close this.
I did a search for "config" before posting, probably because that post is older it ended up quite a few pages deep.  Still do not understand searches though, if "config" is in the title you would think it would end up ahead of all the ones that do not.
Anyways, thank you again for pointing this again, again I apologize.

**Comment by Swiftb0y** [comment]
No worries ;)
