### ISSUE TITLE
No Array.flat in JS

### ISSUE THREAD

**Issue by neopostmodern** [mixxxdj/mixxx#13635]
### Bug Description

Lodash is to be removed, but `Array.prototype.flat` doesn't exist, so I can't find a reasonable way to flatten an array.

### Version

2.5

### OS

Arch/Manjaro

**Comment by Swiftb0y** [comment]
QJSEngine is currently limited to roughly ES7 (see [QTBUG-97724](https://bugreports.qt.io/browse/QTBUG-97724)). The algorithm is not complicated so feel free to add a [polyfill](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill) in your mapping.

Closing as this is not really our bug.

**Comment by neopostmodern** [comment]
It sure ain't a bug in Mixxx, it's just that the [Wiki](https://github.com/mixxxdj/mixxx/wiki/Lodash-Migration) makes it sound as if all [widely available](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) modern JS functions are available now natively. Maybe the [Other?](https://github.com/mixxxdj/mixxx/wiki/Lodash-Migration#other) section could handle this better. Would it be feasible to provide an exhaustive list of features `lodash.mixxx.js` provided that are not covered by QJSEngine?

**Comment by Swiftb0y** [comment]
Well, its just ES7 as described at the top of the section. Unfortunately MDN stopped documenting which features where introduced in which ecmascript version. Do you know a better source that publishes this? I will add it to the wiki page.

**Comment by neopostmodern** [comment]
This is the best I know and unfortunately it's quite hard to navigate/grasp... https://compat-table.github.io/compat-table/es2016plus/

**Comment by neopostmodern** [comment]
I guess the problem is that technically "ES7" is very concise, but even for people who deal with JavaScript professionally it mostly translates to "modern" in the head and everything beyond that you'd look up on MDN/caniuse, which doesn't cover QJS...

**Comment by Swiftb0y** [comment]
Yeah, I mean AFAICT they basically pin a precise version of JavascriptCore (not sure which one), but that could be used as a very precise baseline.
