### ISSUE TITLE
Mixxx doesn't send Sysex or MIDI out to Launchpad X (custom script, macOS Sonoma ARM)

### ISSUE THREAD

**Issue by frankgrimy** [mixxxdj/mixxx#13633]
### Bug Description

Hi.

I've coded a script for a Novation Launchpad X controller on my Windows machine. As of now, it can start the controller's DAW mode (by sending Sysex), and it also sends Midi messages to it, to light some pads (based on the 4 decks play status), just fine.

Now, I'm trying to get that script working on my Macbook Air M1, but neither Sysex nor Midi messages seems to be sent to the device. I thought of this because I started the DAW mode manually with Pocket MIDI, and when pressing the configured pads, they perform the actions I've coded.

I wonder if this is a Mixxx bug, or some macOS permissions, but I've search some info about this and haven't found anything.

If you want to check the code, I'd probably open a repo for it soon, but as I said the script works fine on Windows.

### Version

2.4.1

### OS

macOS Sonoma ARM

**Comment by Swiftb0y** [comment]
Hey there, thank you for filling your issue. In order to get to the bottom of this. We would like to inspect your log file. Please use [our guide to find it](https://github.com/mixxxdj/mixxx/wiki/Finding%20the%20Mixxx.log%20file) and then upload it here and we'll see if we can spot anything in the log. Thank you.

**Comment by frankgrimy** [comment]
Hi, here's the log file.
[mixxx.log](https://github.com/user-attachments/files/16913704/mixxx.log)

**Comment by frankgrimy** [comment]
Line 234 says that the controller is being opened for input
> Info [Controller] PortMidiController: Opening Launchpad X LPX DAW Out index 0 for input

But two lines in the log file on my windows machine say that the device was opened for input and output.
> Info [Controller] PortMidiController: Opening LPX MIDI index 2 for input
> Info [Controller] PortMidiController: Opening LPX MIDI index 6 for output

So I guess the output port isn't being configured properly.

PS: Windows name scheme for the DAW port is different from macOS, that LPX MIDI is the DAW connection.

**Comment by frankgrimy** [comment]
Hi.
This bug might be happening because macOS lists Launchpad X with different names for input and output, while on Linux and Windows they have the same name.
Names for input and output are respectively:

`Launchpad X LPX DAW Out`
`Launchpad X LPX DAW In`

On portmidienumerator.cpp, it seems that no function catches that name difference, and probably the workaround used for KAOSS DJ CONTROL and Ableton Push might be useful to fix Novation controllers (this bug also occurs with a Launchkey Mini MK3)

This issue is happening on both x64 and ARM64 builds.

PS: I've been trying to build Mixxx to try and fix this, but haven't got success, so any advice is welcome.

**Comment by daschuer** [comment]
The function is here: 
https://github.com/mixxxdj/mixxx/blob/2934ba7620c406524a302e02ead2dd3911a89b2d/src/controllers/midi/portmidienumerator.cpp#L76

What is the issue you have when building? 

You may just use the GitHub edit. Fork Mixxx in GitHub, edit the file, and create a feature branch in the save dialog. This way the GitHub workflow will build a Windows and a MacOS binary.

**Comment by frankgrimy** [comment]
I was trying to build locally both Mixxx and m1xxx on my M1 MBA. Mixxx failed because of architecture incompatibility, and m1xxx had some dependency error.

Anyway, this repo was built successfully with GitHub Actions, and managed to fix the Launchpad X detection issue in macOS.
I will open a PR soon (btw it will be the first PR I've ever opened 😁).

**Comment by daschuer** [comment]
Welcome to Mixxx😃
