### ISSUE TITLE
Ability to Access Track Metadata in MIDI Scripts

### ISSUE THREAD

**Issue by not-my-username** [mixxxdj/mixxx#13652]
### Feature Description

Currently, the `[ChannelN], track_loaded` control in MIDI scripts only gives a 1 or 0 to show if a track is loaded into a deck. While that’s helpful, it doesn’t give access to track metadata like the title, artist, album, or other details, which you can currently only see in the UI.

It’d be great if MIDI scripts could access this metadata directly. This would be really useful for controllers with built-in screens that display track info, and for more advanced setups. For example, being able to send timecode based on the track’s metadata, where each track gets a unique hour timestamp, could help trigger the right cues in external software like lighting systems.

At the moment, I haven’t found a way to do this without using a workaround. Adding this feature would make it much easier to sync Mixxx with external systems and open up more possibilities for creative setups.

**Comment by ronso0** [comment]
Thanks for the request, but this is a duoe of #6898

**Comment by not-my-username** [comment]
:+1:
