### ISSUE TITLE
Native Instruments Traktor Kontrol Z2 - No MIDI in Linux

### ISSUE THREAD

**Issue by sub-zerohm** [mixxxdj/mixxx#13651]
![Screenshot_20240914_021733](https://github.com/user-attachments/assets/c664685f-afe1-4bf3-8a20-39f8d4cb7cb7)
### Bug Description

I have followed the instructions to get the custom mapping via MIDI-only mode to work on Windows for this mixer, but I wanted to be able to use it on Linux, since I have the Traktor software on Windows anyway -- I only see the regular one on the controllers list on Linux, I've tried both Ubuntu Studio (which has a bunch of MIDI utilities, maybe I need to configure something), and Manjaro (Arch based), but both have the same problem

Here is a screenshot from Windows with the MIDI only option 

![Capture](https://github.com/user-attachments/assets/ea185ff9-e5b1-4547-ad7d-92dab47d6468)

### Version

2.4.0 (built into Ubuntu Studio)

### OS

Ubuntu Studio, Manjaro

**Comment by sub-zerohm** [comment]
Just adding to this, I don't believe this is a "big" on th dev end, it's something with Linux and MIDI.  I see it's also not recognizing the mouse and keyboard as controllers in Linux, so I'm guessing it has something to do with USB configuration

**Comment by JoergAtGithub** [comment]
The only Traktor Kontrol device that has MIDI support in hardware is the TRAKTOR KONTROL S2 MK3. All other, including the Traktor Z2, have MIDI emulation in the Native Instruments device driver. If you really need MIDI support for the Z2, you must use macOS or Windows.

But for Mixxx no MIDI support is needed, as Mixxx supports also the USB HID protocol used by Native Instruments for the Z2 as well. Try: https://github.com/mixxxdj/mixxx/pull/3038

**Comment by ronso0** [comment]
> I see it's also not recognizing the mouse and keyboard as controllers in Linux, so I'm guessing it has something to do with USB configuration

Those are usually HID and they are filtered by the comtroller manager. this happens to prevent users from locking themselves out (if a mapping is loaded for a HID keyboard for example, all its keystrokes are consumed by Mixxx).

**Comment by sub-zerohm** [comment]
> The only Traktor Kontrol device that has MIDI support in hardware is the TRAKTOR KONTROL S2 MK3. All other, including the Traktor Z2, have MIDI emulation in the Native Instruments device driver. If you really need MIDI support for the Z2, you must use macOS or Windows.
> 
> But for Mixxx no MIDI support is needed, as Mixxx supports also the USB HID protocol used by Native Instruments for the Z2 as well. Try: #3038

Thank you, now I know it's still a work in progress.  I don't really need MIDI support, I was just going to use it because there was no mapping for the Z2, at least not completed yet.  I mix with a combination of digital tracks and analogue records, so this mixer is perfect for me.  My main focus is scratching, so the function that really helps me is to blend tracks into each other with the audio interface while still having the analogue records to scratch with on the 2nd deck.  I have 4 action buttons and 2 jogwheels with this plus the Innofader which is key for scratch DJs.
