### ISSUE TITLE
Sort by Key broken (happens intermittently)

### ISSUE THREAD

**Issue by m0dB** [mixxxdj/mixxx#13686]
### Bug Description

This has happened to me several times now. During a long session, at some point "sort by Key" stopped working correctly.

Steps: sort by BPM (click in column header), select some row, sort by Key (click in column header).

The sorting itself worked correctly, except for the selected row, which would not be in the  part of the table with the same Key.

E.g. I would select a row with key Fm, and after sorting the rows above and below the selected row would be with key A, and subsequently sorted as expected. But the selected row was not in the right position.

In addition to that, normally the rows are ordered by tempo as the secondary sort key (as in all tracks with the same key are grouped, and order by tempo). When this situation occurs the tracks with the same key are ordered seemingly random (or probably by some key, but not tempo).

This behaviour continued but occasionally the sorting would work correctly. After restarting the app the problem disappeared.

I am not sure if this happens at random, or if it is some specific action or circumstance that triggers this (I am even wondering if it is by design and I haven't figured out the rationale). I haven't seen this in the past though.

### Version

2.5

### OS

macOS

**Comment by m0dB** [comment]
I am seeing this quite often. I will try to debug this.

**Comment by m0dB** [comment]
So far I have only seen this with 2.5, not with 2.4, but that might be coincidence.

**Comment by Swiftb0y** [comment]
You may want to look into these PRs: https://github.com/mixxxdj/mixxx/pulls?q=is%3Apr+is%3Aclosed+author%3Adanferns

**Comment by m0dB** [comment]
At these PRs or just at the code, since there is no guarantee this was introduced by any of these PRs... But It will be difficult to figure this out as it only happens occasionally... I will ask in zulip for people to watch out for a specific sequence of events to trigger this bug.

**Comment by Swiftb0y** [comment]
I rather meant just as a starting point where to poke at when you want to do a `git bisect`. Buf of course thats hard with a problem thats hard to reproduce...

**Comment by fwcd** [comment]
I ran into this a couple of times too, see also the Zulip thread: https://mixxx.zulipchat.com/#narrow/channel/109122-general/topic/Key.20sorting.20bug.20on.202.2E6.2Fmain

Changing the sort order causes it to sort correctly, so it definitely seems like a bug:

https://github.com/user-attachments/assets/0ba6ed87-d632-4f1f-9f6c-8cd23bdb6dc7

**Comment by fwcd** [comment]
> You may want to look into these PRs: https://github.com/mixxxdj/mixxx/pulls?q=is%3Apr+is%3Aclosed+author%3Adanferns

Those PRs were largely going to `main`, if this is a bug on 2.5 too, it's likely something earlier.

**Comment by m0dB** [comment]
I have tracked this down to `BaseTrackCache::findSortInsertionPoint`.  This function is called for certain tracks under certain circumstances when sorting. (I don't understand the logic behind the mechanism that requires this function to be called, but it doesn't really matter I guess). This function does a bisection search using the current sort columns. I observe that when it calls `BaseTrackCache::compareColumnValues` for the COLUMN_LIBRARYTABLE_KEY column, it occasionally ends up comparing with an empty key string. Indeed when I look at properties dialog of the track that is being compared, the Key value is empty (though in the table it isn't). It looks like the key can be stored as a string, COLUMN_LIBRARYTABLE_KEY, or as an int, ColumnCache::COLUMN_LIBRARYTABLE_KEY_ID. I don't know the details behind this, but it looks like BaseTrackCache::compareColumnValues should use ColumnCache::COLUMN_LIBRARYTABLE_KEY_ID if COLUMN_LIBRARYTABLE_KEY is not set. Or maybe always? Does anybody now why we have two different keys for the same?

**Comment by m0dB** [comment]
Fixed. I used these steps to reproduce the bug, and to confirm that with the PR the bug is solved:

- Open the properties dialog for a track until you find one with an empty Key value.
- Select the track
- Load the track on a deck
- Sort by bpm
- Play the track for a couple of seconds
- Sort by key

The track will be out of order (either key or bpm or both).

**Comment by ywwg** [comment]
closing as fixed
