### ISSUE TITLE
Accessibility for auto DJ controls.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [mixxxdj/mixxx#13690]
Hi, lots of controls are in the sidebar which is totally unaccesible to screen reader users. At least I didn't find a way to reach it.
AutoDJ controls are in the sidebar.
Moreover, the shift+f9...shift+f12 are often in conflict with Windows and screen reader and they must be remapped. In my case I saw Ctrl+f9 ...to...Ctrl+f12 seem to work.
I'm available as a Beta Tester for accessibility with NVDA screen Reader under Win11.

**Comment by daschuer** [comment]
How is the situation compareing different screen reader solutions an their keyboard mappings? Is there a kind of industrial standard regarding keyboard mappings? 

Can you describe your Auto DJ task, step by step? What happens, and what schoul happen instead?

**Comment by ronso0** [comment]
> Hi, lots of controls are in the sidebar which is totally unaccesible to screen reader users. At least I didn't find a way to reach it.
AutoDJ controls are in the sidebar.

These controls are in the AutoDJ toolbar, not the library sidebar.
We decided to disallow focusing them by Tab key (if that's what you mean with "unreachable") to simplify library navigation with Tab key and the respective emulation for library controls (for controllers).
The tab order is Search -> Search clear button -> sidebar -> tracks table (if available).

@GabrieleBattaglia why did you close this as resolved?
