### ISSUE TITLE
Metronome effect sometimes indefinitely repeats last buffer when releasing hotcue during at certain timing

### ISSUE THREAD

**Issue by Swiftb0y** [mixxxdj/mixxx#13727]
### Bug Description

Just filing this right now quickly so we don't forget. I suspects its a regression from #13636.

### Version

2.4.1-73-g8cb86e9449 (local-patches)

### OS

Fedora 41

**Comment by daschuer** [comment]
Fixed here: 
https://github.com/mixxxdj/mixxx/pull/13733
