### ISSUE TITLE
Document controller mapping settings definition 

### ISSUE THREAD

**Issue by acolombier** [mixxxdj/mixxx#13723]
At the time when this feature was written, no updates were provided in the wiki to document how to define controller settings. This should be added to help with future development.

The best reference is the mapping for the S4 Mk3: https://github.com/mixxxdj/mixxx/pull/12995

_Originally posted by @JoergAtGithub in https://github.com/mixxxdj/mixxx/pull/13721#issuecomment-2395602321_

**Comment by acolombier** [comment]
Documented in the wiki:
https://github.com/mixxxdj/mixxx/wiki/MIDI-Scripting#settings-api

**Comment by JoergAtGithub** [comment]
Thank you!

**Comment by acolombier** [comment]
No problem, sorry for taking this long in a first place.
Note that I have already documented introduced settings in #13669

**Comment by JoergAtGithub** [comment]
Better mark, that these will be introduced in 2.6
