### ISSUE TITLE
Live broadcast does not work when IPv6 is used as host

### ISSUE THREAD

**Issue by LeiCraft** [mixxxdj/mixxx#13744]
### Bug Description

It is not possible to use an IPv6 or a domain that only has an AAAA record as a host for live broadcasting.
The error message is:
Error in connection '1':
Connection to server cannot be established

**Comment by acolombier** [comment]
Could you please share the log file? You may want to start Mixxx with debug log on (using the command argument `log-level`). Could you please also complete `version` and `OS` details?
If you can, could you try installing [this version](https://github.com/mixxxdj/mixxx/actions/runs/10980988560) of Mixxx (links at the bottom of the page) - this included the latest update of libshout idjc, library used for live broadcasting.
