### ISSUE TITLE
Keyboard shortcuts for Stemcontrols are 'fishy'

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#13749]
### Bug Description

To help a user on the [forum ](https://mixxx.discourse.group/t/gsoc-2024-adding-stem-mixing-support/30192/26)
I tried to map the stemcontrols to my keyboard.

The [ChannelXStemY],mute does not keep the value: the value changes when pressed and when released (not only key-pressed but also key-released makes the value change)
So if you make a combination fi Ctrl+F1 to control [Channel1Stem1],mute the mute works only as long you keep the combination pressed.
The _up _down suffix does not work to the CO's [ChannelXStemY],volume.

### Version

2.6

### OS

Win

**Comment by Swiftb0y** [comment]
So I guess its just a matter of the keypress being recognized as push instead of a toggle button?

**Comment by Swiftb0y** [comment]
That could also be an issue with your keyboard key map. I'm not very familiar with those.

**Comment by ronso0** [comment]
The stem mute controls should have `ButtonMode::PowerWindow` like the deck's 'mute' controls.
So this is an inconsistency.
#13751

**Comment by Eve00000** [comment]
Closed to early, ;-)
my issue contains 2 parts:
- mute button 'solved in #13751 
- keyboard mapping for  CO's like [ChannelXStemY],volume with _up & _down suffix

**Comment by Swiftb0y** [comment]
great, then create a separate one to track that ;)
