### ISSUE TITLE
Keyboard shortcuts for [ChannelXStemY],volume_up/_down don't work

### ISSUE THREAD

**Issue by Eve00000** [mixxxdj/mixxx#13753]
To help a user on the forum
I tried to map the stemcontrols to my keyboard.

The _up _down suffix does not work to the CO's [ChannelXStemY],volume.

### Version

2.6

### OS

Win

**Comment by Swiftb0y** [comment]
That CO is probably not a `ControlPotMeter`. Should be simple to fix.

**Comment by ronso0** [comment]
It is, and all controls work like they do for the other volume controls.
Just tested [Channel1Stem1],volume_up/_down

@Eve00000 what keys are you mapping?

**Comment by ronso0** [comment]
I'm closing this since controls work, but we can of course try to debug the mapping.

**Comment by Eve00000** [comment]
> It is, and all controls work like they do for the other volume controls. Just tested [Channel1Stem1],volume_up/_down
> 
> @Eve00000 what keys are you mapping?

Hi,
I pulled the changes and tried again.
Now everything works.
(it's possible it worked  before and I made a mistake but I used the same mapping, if so I apologize )

I use [Channel1StemX]
volume_up Ctrl+F1 ... 4 // 5 ... 8 for Ch2
volume_down Shift+F1 .. 4 // 5 ... 8 for Ch2
mute Ctrl+Shift+F1 ... 4 // 5 ... 8 for Ch2
I tested the fx [QuickEffectRack1_[ChannelXStemY]], enabled  / super1 _up & -down  as well.
All works fine.
Thank you.
I'll update the answer in the forum.
