### ISSUE TITLE
LegacyControllerMappingValidationTest.MidiMappingsValid ctest timeout under Address Sanitizer option.

### ISSUE THREAD

**Issue by brianGriifin114** [mixxxdj/mixxx#13771]
### Bug Description

Hey, We are MSVC test team and use Mixxx as part of the compiler testing. Recently we encountered an issue where the LegacyControllerMappingValidationTest.MidiMappingsValid test failed(we are using commit c4a740a in main branch). Part of the error message is as follows:
```
warning [0x11a1427a2fd0] ControllerScriptHandlerBase: "Uncaught exception: file:///C:/gitP/mixxxdj/mixxx/res/controllers/Stanton-SCS3d-alternate-scripts.js:30:\nTypeError: Cannot call method 'stop' of undefined\n\nBacktrace: @file:///C:/gitP/mixxxdj/mixxx/res/controllers/Stanton-SCS3d-alternate-scripts.js:30"
warning [0x11a1427a2fd0] LINT: "C:/gitP/mixxxdj/mixxx/res/controllers/Stanton SCS.3m.midi.xml" has no forum link.
warning [0x11a1427a2fd0] LINT: "C:/gitP/mixxxdj/mixxx/res/controllers/Stanton SCS.3m.midi.xml" has no wiki link.
info [0x11a1427a2fd0] Starting engine
info [0x11a1427a2fd0] Applying controller mapping...
warning [0x11a1427a2fd0] file:///C:/gitP/mixxxdj/mixxx/res/controllers/Stanton-SCS3m-scripts.js:403:52 Variable "flushModeset" is used before its declaration at 408:9.
info [0x11a1427a2fd0] Shutting down engine
warning [0x11a1427a2fd0] ControllerScriptHandlerBase: "Uncaught exception: file:///C:/gitP/mixxxdj/mixxx/res/controllers/Stanton-SCS3m-scripts.js:34:\nTypeError: Cannot call method 'stop' of undefined\n\nBacktrace: @file:///C:/gitP/mixxxdj/mixxx/res/controllers/Stanton-SCS3m-scripts.js:34"
warning [0x11a1427a2fd0] LINT: "C:/gitP/mixxxdj/mixxx/res/controllers/us428.midi.xml" has no forum link.
warning [0x11a1427a2fd0] LINT: "C:/gitP/mixxxdj/mixxx/res/controllers/us428.midi.xml" has no wiki link.
```

I noticed there is a related issue https://github.com/mixxxdj/mixxx/issues/11293, but it doesn't seem to solve my problem. This problem occurs when the Asan option is enabled, which causes the LegacyControllerMappingValidationTest.MidiMappingsValid ctest to timeout.
Plz refer test.log for more info 
[Test.log](https://github.com/user-attachments/files/17374674/Test.log)

Step to repro:

1. open VS2022 comand prompt
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_=  /fsanitize=address /GS- /wd5072 & set _LINK_=  /InferASanLibs /incremental:no /debug
3. set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%PATH%
4. cd /d C:\gitP\mixxxdj\mixxx\build
5. ctest --timeout 48 --exclude-regex "^AutoDJProcessorTest.*$|SoundSourceProxyTest.seekForwardBackward|SoundSourceProxyTest.seekBoundaries|SoundSourceProxyTest.regressionTestCachingReaderChunkJumpForward" 2>&1

### Version

commit c4a740a in main branch

### OS

Windows 10

**Comment by Swiftb0y** [comment]
48 seconds is simply too short of a timeout. The code runs way slower under ASAN and the MidiMappingsValid test runs through hundreds of files. I don't know what you would expect us to do here. Increase your timeout to something more sensible under ASAN.

**Comment by JoergAtGithub** [comment]
This test is one of our largest unit test and barely maintable anyway. Some time ago I started a PR to split it into multiple test runs, executing the same test case with the mapping script file as parameter: https://github.com/mixxxdj/mixxx/pull/13281
This is working in general, but to cover all the edge cases of GoogleTest and CTest at the same time is non-trivial.

**Comment by brianGriifin114** [comment]
Thanks for your attention. This problem occurred after we obtained and built the latest commit of Mixxx. Before the update, the timeout was 48 seconds and the build was successful. So I didn't expect that the test time was too short. Could you Plz tell me what the timeout should be? I will rebuild after updating the timeout.

**Comment by JoergAtGithub** [comment]
What was the last commit, you compiled without this timeout?

**Comment by brianGriifin114** [comment]
> What was the last commit, you compiled without this timeout?

9c6b16e in main branch
