### ISSUE TITLE
I cannot open STEM files

### ISSUE THREAD

**Issue by rromualdi** [mixxxdj/mixxx#13838]
### Bug Description

I own my stem tracks created with the Native Instrument tool, but when i load it into mixxx it is not read like a stem file, but like a classic wav or mp3 file, how do i fix it? I have installed the development snapshot on windows
![382558118-b1c06713-c34b-4973-b9d6-6abb92c21767](https://github.com/user-attachments/assets/f0fc14a6-2c93-4e25-815f-052fc933f326)
.

### Version

development version

### OS

windows 11

**Comment by Eve00000** [comment]
Hi,
Did you download the 'development snapshot' on the website -> download?
That version is of may 26, before implementation of stems.
If you want to try stems you need to build Mixxx yourself with the latest version of de code.
Manual on the [Mixxx wiki](https://github.com/mixxxdj/mixxx/wiki) -> Developer Documentation -> Compile on Linux / Windows / mac OS
Or you can download an installer that's automatily created by github.
On the [PR #13855](https://github.com/mixxxdj/mixxx/pull/13835) , this one has OSC support to, go to the tab 'checks' -> scroll down to 'build' ([or click on this](https://github.com/mixxxdj/mixxx/actions/runs/11679486227)) down the page you can find Artefacts : installers.

**Comment by rromualdi** [comment]
> Hi, Did you download the 'development snapshot' on the website -> download? That version is of may 26, before implementation of stems. If you want to try stems you need to build Mixxx yourself with the latest version of de code. Manual on the [Mixxx wiki](https://github.com/mixxxdj/mixxx/wiki) -> Developer Documentation -> Compile on Linux / Windows / mac OS Or you can download an installer that's automatily created by github. On the [PR #13855](https://github.com/mixxxdj/mixxx/pull/13835) , this one has OSC support to, go to the tab 'checks' -> scroll down to 'build' ([or click on this](https://github.com/mixxxdj/mixxx/actions/runs/11679486227)) down the page you can find Artefacts : installers.

I have downloaded it from the server wich is linked on the download page .I have downloaded the version modified on 3 of November (https://mixxx.org/download/#previous)

**Comment by ronso0** [comment]
Stem support requires Ffmpeg, not sure if that is enabled by default for Windows builds.
@mixxxdj/developers  can someone clarify the current situation?

**Comment by ronso0** [comment]
@rromualdi 
https://mixxx.org/download/#previous points to Mixxx 2.3.6, not 2.6-alpha
Try https://mixxx.org/download/#testing instead.

**Comment by rromualdi** [comment]
> @rromualdi https://mixxx.org/download/#previous points to Mixxx 2.3.6, not 2.6-alpha Try https://mixxx.org/download/#testing instead.

I have tried it, but it doesn't work yet

**Comment by Eve00000** [comment]
> > @rromualdi https://mixxx.org/download/#previous points to Mixxx 2.3.6, not 2.6-alpha Try https://mixxx.org/download/#testing instead.
> 
> I have tried it, but it doesn't work
Please try the Mixxx in OSC build I pointed, if your files don't work in that one, there is something wrong with your files,
to be sure you can send me one of your files in a DM on Zulip.

**Comment by rromualdi** [comment]
> 

It doesn't work I'm uploading the stem filo on wetransfer
2 of the tracks are mute
https://we.tl/t-CqPM6C8yuJ

**Comment by rromualdi** [comment]
> > > @rromualdi https://mixxx.org/download/#previous points to Mixxx 2.3.6, not 2.6-alpha Try https://mixxx.org/download/#testing instead.
> > 
> > I have tried it, but it doesn't work
> Please try the Mixxx in OSC build I pointed, if your files don't work in that one, there is something wrong with your files,
> to be sure you can send me one of your files in a DM on Zulip.

It doesn't work I'm uploading the stem filo on wetransfer
2 of the tracks are mute
https://we.tl/t-CqPM6C8yuJ

**Comment by Eve00000** [comment]
Sei Italiano, da parte di Milano? 
Mi piacono molte le canzone di Shiva :-)

Problem is solved:
the file you send me is no stem-file.
I think you (or your tool) tried to convert an aac to mp3 or wav and then back to aac to combine it in a stem container.
that won't work. extra: stemtracks 2, 3, 4 were empty.
The format in a stem container has to be mp3 (lossy) or m4a (alac, lossless).
to let you try I created a [stem file from the original](https://mega.nz/file/dlpU1JaR#iW3SZmcMwtuv21BgSTOb62jDzsC_e2LvPFAUvo6hJ7M) (lossless, so also bigger but HQ)
(You'll have to download it because I will remove the song in half an hour from my cloud and the link here).

How did you create the stem?

**Comment by rromualdi** [comment]
> stem
Yes, i'm from Bologna an north italian city.

I have created it with the official tool of Native Instrument, by uploading wav file. how do I am suppose to do it?

**Comment by rromualdi** [comment]
> Sei Italiano, da parte di Milano? Mi piacono molte le canzone di Shiva :-)
> 
> Problem is solved: the file you send me is no stem-file. I think you (or your tool) tried to convert an aac to mp3 or wav and then back to aac to combine it in a stem container. that won't work. extra: stemtracks 2, 3, 4 were empty. The bitrate of the different tracks in your file was different) The format in a stem container has to be mp3 (lossy) or m4a (alac, lossless). to let you try I created a [stem file from the original](https://mega.nz/file/dlpU1JaR#iW3SZmcMwtuv21BgSTOb62jDzsC_e2LvPFAUvo6hJ7M) (lossless, so also bigger but HQ) (You'll have to download it because I will remove the song in half an hour from my cloud and the link here).
> 
> How did you create the stem?

![Screenshot 2024-11-05 112544](https://github.com/user-attachments/assets/02dae331-2f78-41f5-9148-65bdb914c98c)
I'm getting this error with your file

**Comment by Eve00000** [comment]
> > stem
> > Yes, i'm from Bologna an north italian city.
> 
> I have created it with the official tool of Native Instrument, by uploading wav file. how do I am suppose to do it?

la grassa, la rossa, la dotta ;-)

**does it work?**
I'd prefer to help you on the [discourse forum ](https://mixxx.discourse.group/) so other users can learn from it to, 
please create a topic 'help wanted to create stems' and post your question.
I will reply and guide you.

**Comment by rromualdi** [comment]
> > > stem
> > > Yes, i'm from Bologna an north italian city.
> > 
> > 
> > I have created it with the official tool of Native Instrument, by uploading wav file. how do I am suppose to do it?
> 
> la grassa, la rossa, la dotta ;-)
> 
> **does it work?** I'd prefer to help you on the [discourse forum ](https://mixxx.discourse.group/) so other users can learn from it to, please create a topic 'help wanted to create stems' and post your question. I will reply and guide you.

Done

**Comment by Eve00000** [comment]
I'm getting this error with your file
-> which version of Mixxx? There was also an error with the directory path of the stems.
Please use one of [these](https://github.com/mixxxdj/mixxx/actions/runs/11679486227)
