### ISSUE TITLE
Weird colors after migrating the database to a new computer

### ISSUE THREAD

**Issue by Marina071170** [mixxxdj/mixxx#13849]
### Bug Description

I was running Mixxx 2.4.1 on Ubuntustudio 22.04 up until about a month ago. The automatic upgrade to 24.04 has failed and I had to make a complete new installation. In order to maintain all my settings I followed this guide: [14. Advanced Topics — Mixxx User Manual](https://manual.mixxx.org/2.4/en/chapters/advanced_topics#migrate-your-mixxx-library-and-settings-to-a-new-computer)

This worked so far, except for one quirk: All the colors on my tracks are now full brightness and the text is hardly readable. See attached screen capture.

In the meantime I have changed most of the colors to somewhat less bright ones. But even when I set the color back to none/black and then assign a different color, the new color is again full brightness. The dimmed down "stripes" are no longer there.

Ubuntustudio 24.04.1 comes with Mixxx 2.4.0
 I have since switched to the ppa and upgraded to 2.4.1 - still the same

![Screenshot_20241021_161141](https://github.com/user-attachments/assets/a13bae27-06f6-4723-9b66-4b25d774ab4d)

### Version

Mixxx 2.4.1, Qt 5.15.13

### OS

Ubuntustudio 24.04.1

**Comment by Marina071170** [comment]
Forgot to attach the log files
[mixxx.log.zip](https://github.com/user-attachments/files/17679180/mixxx.log.zip)

**Comment by ronso0** [comment]
Thanks for the report. (fyi just the last log mixxx.log is sufficient)

The [default track color opacity is 0.125](https://github.com/mixxxdj/mixxx/blob/704e2d4509a66b03326c1af0ac8f2bca911b24c7/src/widget/wlibrary.h#L43), and it is set to 0.175 - 0.25 in official skins (parsed [here](https://github.com/mixxxdj/mixxx/blob/704e2d4509a66b03326c1af0ac8f2bca911b24c7/src/widget/wlibrary.cpp#L25-L31)).
BaseTrackTableModel provides the resulting background color [here](https://github.com/mixxxdj/mixxx/blob/704e2d4509a66b03326c1af0ac8f2bca911b24c7/src/library/basetracktablemodel.cpp#L436-L450) (there are debug asserts for opacity > 0.0 and < 1.0)
Not sure where it fails to apply the skin's opacity.

Are okay with testing 2.5-beta? You can get it from the beta ppa https://mixxx.org/download/#beta-ubuntu
(just to be safe, backup your data https://github.com/mixxxdj/mixxx/wiki/Testing#backup-settings-and-database)
If that doesn't make a difference I can provide a binary with some debug output.

**Comment by Marina071170** [comment]
Thanks,

I‘ll try that and will report back then.

-Marina

**Comment by Marina071170** [comment]
Installed the latest 2.5-beta and everything seems to be back to normal. I hope that this beta is stable enough and won't give me any headaches during a performance.

Thanks for the quick support.
-Marina

![Screenshot_20241111_164414](https://github.com/user-attachments/assets/206c3d32-704f-4a2c-a2da-b37339c5979b)

**Comment by ronso0** [comment]
Okay, great news!
Just do a few test sessions with your live setup before going live.

**Comment by ronso0** [comment]
I'll close this now because 2.4.2 is already on the door step and not much later 2.5 will be released.
