### ISSUE TITLE
unlock load new track in order when ...

### ISSUE THREAD

**Issue by founded** [mixxxdj/mixxx#13840]
### Feature Description

When a deck is play you can not load new track thats ok and nice to have.
There is a way when a track play and no sound is comming out the fader is down or crossfader is the other way . It was maybe nice that we can load then also new song.
An other thinking object was also if we can have a fixed output bpm to set ... Or a fixed output level ... When it is over some level for some time it wil slow move to selected level (by track or by mainlevel) .  PS it was nice if i had some info to count bpm by php I can develop php and i woud like to read it and safe to a database.
There is an option to load music on vlc . is it possible to share the right shell line to load a song from website list and/or read and send what is play. and bythe way i think to place the scripts under my github when i find out to push them from visual code studio [and find the time ;) ].

**Comment by daschuer** [comment]
In general, please file one issue for one topic. We can than handled your request independently. 

The "no sound' track replace feature can be complex if we consider an external mixer setup as well. So I guess this should be a third option. But I am not sure if this is worth the efforts. If you still think it is, pleasefile a new bug including your use case why the track is still playing. 

Please do the same for the fixed level and as well the fixed BPM output (two issues) 

I think you already can open the mixxxdb.sqlite file with PHP. It contains all metadata of all tracks including BPM.

Such a remote interface is not yet available. We have a working prototype using MPRIS. does it work for you. 
If you like to populate the Auto DJ playlist, this is already possible using the mixxxdb.sqlite (please file an extra issue) 

I will now close this.

**Comment by ronso0** [comment]
> The "no sound' track replace feature can be complex if we consider an external mixer setup as well. So I guess this should be a third option.

@founded did you notice you can turn of the deck load protection in Preferences -> Decks?
