### ISSUE TITLE
Color waveform bug version 2.4.1 windows 8.1

### ISSUE THREAD

**Issue by Ju5332** [mixxxdj/mixxx#13881]
### Bug Description

Hello,

I'm having a problem with changing the waveform color.

When I change the color of the waveform, nothing happens no matter what color I choose and I get stuck on the Mixxx track colors.

![Mixxx waveform](https://github.com/user-attachments/assets/5f6d3975-c5bc-45e4-86ed-24c7a6d48239)

Can you help me please 

(Sorry I'm French my English is bad)

THANKS

### Version

2.4.1

### OS

windows 8.1

**Comment by Swiftb0y** [comment]
Hey there. It seems like you're confused by the preferences. The color dialog you have open only changes the colors available for usage in hotcues and track colors. If you want to change the waveform look, you'll have to go to `Waveforms>Waveform Type` (in your case this seems to be called "Formes d'onde" (I unfortunately don't speak french)). Note that in case of the waveforms you currently can't choose an arbitrary color (not implemented atm) and have to use one of the styles shown instead.

**Comment by Ju5332** [comment]
Actually I didn't understand that it was for the choice of track colors, thank you for your answer. 

I mix techno (tribe acid hardstyle....) what is the ideal setting to have a waveform that resembles what I experienced on Serato? 
Because I can't find my way in the waveform.. :/ 

THANKS !

**Comment by Swiftb0y** [comment]
If you're on 2.4 I'd say the closest would be some RGB variant. Try `RGB (GLSL L/R)` first and then the other variants if those don't happen to work on your particular PC. Note that this doesn't resemble serato exactly because the waveforms are still stereo (as opposed to seratos mono display).

**Comment by Swiftb0y** [comment]
I'll go ahead and close this for now since your original has been addressed.

**Comment by ronso0** [comment]
FWIW there are default colors, and they may be overwritten per skin, either per variable in skin.xml or directly in the template that holds the waveform (`<Visual>`).
For example in LateNight you can set colors in these empty elements (format is either #rrggbb or a valid css color name)
https://github.com/mixxxdj/mixxx/blob/028e3ff4ee0ca464c7c47faa89a1c12a3e99b4e9/res/skins/LateNight/decks/overview.xml#L11-L17
