### ISSUE TITLE
modifying multiple tracks comment tags only works by selecting an existing comment from the list

### ISSUE THREAD

**Issue by ywwg** [mixxxdj/mixxx#13915]
### Bug Description

I would like to pre-set the comments of a group of tracks.

1. I select all the tracks
2. I open the properties editor
3. I write a new comment in the box
4. I click Apply or OK

what happens: nothing changes

But, if I edit one track to have the comment I want I can do:

1. I select all the tracks
2. I open the properties editor
3. Select the comment I want from the dropdown list
4. I click Apply or OK

then all the tracks get that comment.

### Version

HEAD

**Comment by ronso0** [comment]
The fix is #13631, please review.
