### ISSUE TITLE
Add effects channell to sampler

### ISSUE THREAD

**Issue by fid0did0** [mixxxdj/mixxx#13926]
### Feature Description

It should be nice to attach an effect channel to every sampler slot. In this way, as an example, it should be possible to add echo to one sample.

**Comment by ronso0** [comment]
You can already assign samplers to effect units, though this setting is exposed only in **LateNight** skin.
* Just expand a sampler row with the central expand/collapse toggle
* open the skin settings menu with the rightmost button in the toolbar
* find the Samplers section, enable **Fx controls** and you get this

![image](https://github.com/user-attachments/assets/883390ad-6f20-4622-a042-eb2a0f191175)

If you want to modify a skin or use these controls in a controller or keyboard mapping ,check out the [**Mixxx controls** section in the manual](https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[EffectRack1_EffectUnitN]-group_[SamplerJ]_enable)
