### ISSUE TITLE
"Kill Mid" and "High" affect each other in the Waveform Display

### ISSUE THREAD

**Issue by g-rden** [mixxxdj/mixxx#13922]
### Bug Description

I won't go into depth describing the bevavior. Because either I am completely missing something and there's no bug or it is apperent that something is wrong and must be looked into further anyway.

**BUG:**
"Kill Mid" button and "High" knob affect each other in the Waveform Display when using "Filtered", "RGB" or "Stacked" Waveform Type. This does only affect the Waveform Display as the audio output is as expected.

Image shows two cases (there are more) where the display is incorrect.
![mixxx 2.4.1](https://github.com/user-attachments/assets/87ca0ffb-a4b1-44fe-bbab-22a904b209d7)

edit: Just noticed the "Kill High" button does not affect the Waveform Display.

### Version

2.4.1, 2.6-alpha-136-g894e96f9b2 (main)

### OS

Linux 6.11.9-arch1-1

**Comment by Swiftb0y** [comment]
Does this only affect the latenight skin?

**Comment by Swiftb0y** [comment]
I can reproduce in 2.4.1

**Comment by Swiftb0y** [comment]
As far as I can tell, the issue is that the high kill does nothing and the middle kill kills high and mid bands. Lows work as expected. Affected waveform types are (Mixxx 2.4) "Filtered", "Filtered (GLSL)"m "Filtered (legacy, GL)", "RGB", "RGB (GLSL)", "RGB (legacy, GL)", "RGB L/R (GLSL)". Does that match your observation @g-rden?

**Comment by Swiftb0y** [comment]
Found (part of) the culprit: https://github.com/mixxxdj/mixxx/commit/94041d8cf96c730b97cc564cb25de38256e682b9

**Comment by Swiftb0y** [comment]
@g-rden can you please confirm whether #13923 fixes the issues you reported?

**Comment by g-rden** [comment]
Sorry that I was unresponsive. Yes it works! Thank you
