### ISSUE TITLE
Regression: Waveform overview seeking is broken in 2.6/main

### ISSUE THREAD

**Issue by fwcd** [mixxxdj/mixxx#13946]
### Bug Description

Seeking one of the waveforms doesn't seem to work correctly on the latest 2.6/main builds:

https://github.com/user-attachments/assets/29ce4f97-6e69-44e4-936c-b8ec9abc78e1

A quick bisect shows that the issue was introduced somewhere between 437db42f5f (good) and 0eccb1b2db (bad) ([diff](https://github.com/mixxxdj/mixxx/compare/437db42f5fc36ba8a1b6b0a6e84162d7525ba7d2...0eccb1b2db589745f27fa84ccd42347f4a064212)), so very likely here:

- https://github.com/mixxxdj/mixxx/pull/13853

cc @Swiftb0y 

### Version

2.6-alpha-138-g0eccb1b2db (HEAD)

### OS

macOS 15.1.1

**Comment by Swiftb0y** [comment]
ACK. Thanks for the report. I'll try to find some time to look into it.

**Comment by fwcd** [comment]
Did a finer-grained bisect, the issue was introduced somewhere in 3aea4edb7dc39333598ec4795dd978373399eb1f.

**Comment by Swiftb0y** [comment]
I see, that kinda makes sense. I will double check there.
