### ISSUE TITLE
script.absoluteNonLin() does not map correctly for EQ knobs

### ISSUE THREAD

**Issue by g-rden** [mixxxdj/mixxx#13941]
### Bug Description

Values of script.absoluteNonLin() differ from mapping EQ knobs directly. The two methods should act the same.

Here is an example with two knobs with the same values, but the parameter values differ:

0x3E is mapped to low with 
```
<control>
    <group>[EqualizerRack1_[Channel2]_Effect1]</group>
    <key>parameter1</key>
    <status>0xB0</status>
    <midino>0x3E</midino>
    <options>
        <normal/>
    </options>
</control>
```
0x3D is mapped to HCIS.eq() with
```
<control>
    <group>[EqualizerRack1_[Channel2]_Effect1]</group>
    <key>HCIS.eq</key>
    <status>0xB0</status>
    <midino>0x3D</midino>
    <options>
        <script-binding/>
    </options>
</control>
```

```
HCIS.eq = function(_channel, control, value, _status, group) {
	var scale = value;
	var command = '';
	switch (control) {
		case 0x37:
		case 0x3C:
			// high
			command = 'parameter3';
			break;
		case 0x38:
		case 0x3D:
			// mid
			command = 'parameter2';
			break;
		case 0x39:
		case 0x3E:
			// low
			command = 'parameter1';
			break;
		default:
			break; // invalid: bail
	}

	print(value);

	scale = script.absoluteNonLin(scale, 0, 1, 4);
	print(scale);
	engine.setValue(group, command, scale);
	print(engine.getValue(group, command));
};
```
![](https://github.com/user-attachments/assets/d266d19b-6b45-477c-a2b3-fc0a6b8d7d0b)
The directly mapped knob (Low) shows the correct position in mixxx, the other does not.

I discovered this when I wanted to implement script.absoluteNonLin() myself without knowing it existed:
```
if (scale <= 0x40) {
	// 0.0 to 1.0
	scale /= 0x40;
} else {
	// 1.0 to 4.0
	scale -= 0x40;
	scale /= 0x15;
	scale++;
}
```
and it didn't map correctly. While trying to fix it I found script.absoluteNonLin().
I couldn't find the relevant code for the knobs to reverse engineer the correct mapping.

### Version

2.4.2 git

### OS

Linux 6.12.1-arch1-1

**Comment by g-rden** [comment]
If you use `engine.setParameter(group, command, value/0x7F);` the max value will be 1 and not 4, so it can only lower the given parameter.

I have looked at `common-controller-scripts.js` before opening this issue.

The existing mapping is lacking so much stuff that at first I thought it was not compatible with the Instinct S (and the wiki wrongly says so too), which I have. So I made a new one.

**Comment by g-rden** [comment]
I am already sorry for opening this issue.

This also happens with volume sliders. Both have a value of 64, but the left one uses `engine.setValue(group, 'volume', value / 0x7F);` and the right one is mapped directly.
![](https://github.com/user-attachments/assets/ba8957fc-bb07-482e-8bad-36581b349325)

I assume the default behavior for these inputs are some kind of non-linear, but when using directly mapped inputs this is accounted for. Idk yet what I should rename this issue to.

**Comment by Swiftb0y** [comment]
> If you use engine.setParameter(group, command, value/0x7F); the max value will be 1 and not 4, so it can only lower the given parameter.

If thats truly the case then there is a much more significant issue on your side. The scaling is exactly the difference between `engine.setValue` and `engine.setParameter`. `setParameter` does the scaling thats done automatically when mapping via XML. You can test out the behavior by starting mixxx with `--developer` and playing around with the CO in the `Developer Tools`. You will see that the entire range of the control is mapped to the $[0,1]$ range. Prefer `setParameter` over `setValue` by default.

**Comment by g-rden** [comment]
I read about `engine.setParameter` a few days ago and it didn't seem important and now I assumed it does nothing substantially different to `engine.setValue`. That's why I didn't even try `engine.setParameter`.

ComponentsJS seems more complicated to ignorant me, I like doing it this way and there are only a few inputs I am not sure which functions they should have. This mapping won't be a replacement for the existing mapping, because the buttons are mapped differently. However I will make a git repo when I think the mapping is alright.
