### ISSUE TITLE
`jog` CO behaviour regression

### ISSUE THREAD

**Issue by acolombier** [mixxxdj/mixxx#13965]
### Bug Description

Starting from 0df68b7c0fb7f57aef2c10e80233394cc92fe894 or 64d9f000a5356ef5e089dff064a3759b93de95ce, the behaviour of `[ChannelX],jog` has changed and doesn't seem to react to the same value any more.

This has broken the the S4 MK3 mapping, but I suspect this would have broken other mapping as well. 

## Expected/previous behaviour

Nudge the jog wheel crown slows down or speeds up the track

## Current behaviour

Nothing noticeable

### Version

main

### OS

Ubuntu 22.04/Qt 6.2

**Comment by acolombier** [comment]
@Swiftb0y do you have any idea what could have gone wrong there?

**Comment by Swiftb0y** [comment]
Oh yeah, sorry for the regression. I think I know whats wrong.
