### ISSUE TITLE
Kontrol S4 Mk3 init issue

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#13962]
### Bug Description

Loading the S4 Mk3 mapping for the first time (with a clean user mapping directroy) gives me this mapping error:
> Uncaught exception: file:///src/mixxx/res/controllers/Traktor-Kontrol-S4-MK3.js:235:
TypeError: Type error
> 
> Backtrace: handleInput@file:///src/mixxx/res/controllers/Traktor-Kontrol-S4-MK3.js:235
init@file:///src/mixxx/res/controllers/Traktor-Kontrol-S4-MK3.js:3130

When I comment everything in init() (except the wheel timer vars) it starts up fine.
https://github.com/mixxxdj/mixxx/blob/9f43c3e798bb05f835ac9ee85403317586723bb1/res/controllers/Traktor-Kontrol-S4-MK3.js#L3116-L3131

Note this is with 2.5 and main on Ubuntu 20.04 and 2.5 not being officially supported anymore IIRC.
So if this is an issue with an outdated libhidapi I'd expect a cmake warning or something.

The Kontrol S4 firmware is 0.6.0 (latest).

### Version

2.5 and main (2.6-alpha)

### OS

Ubuntu 20.04.5

### Qt version

6.2.3 (backport) from @daschuer's ppa https://launchpad.net/~daschuer/+archive/ubuntu/qt6-backports

**Comment by ronso0** [comment]
I see libhidapi 0.11.2 is included so this might not be the cause?

**Comment by acolombier** [comment]
```
Uncaught exception: file:///src/mixxx/res/controllers/Traktor-Kontrol-S4-MK3.js:235:
TypeError: Type error
```
Seems to correspond to 
```
        const view = new DataView(reportData);
```
What Qt version are you using? I'm wondering if something in the JS API could be causing issues.

**Comment by ronso0** [comment]
I'm using Qt 6.2.3

**Comment by acolombier** [comment]
I cannot reproduce the issue on Qt 6.2.4/libhidapi 0.11.2-1(/Linux 6.9.3). I think you will need to add couple of debugging instruction. For a start, perhaps something like this?

```patch
diff --git a/res/controllers/Traktor-Kontrol-S4-MK3.js b/res/controllers/Traktor-Kontrol-S4-MK3.js
index 960c2ac50c..7f5e024318 100644
--- a/res/controllers/Traktor-Kontrol-S4-MK3.js
+++ b/res/controllers/Traktor-Kontrol-S4-MK3.js
@@ -232,6 +232,7 @@ class HIDInputReport {
     }
 
     handleInput(reportData) {
+        console.log(DataView, reportData, typeof reportData, new DataView())
         const view = new DataView(reportData);
 
         for (const field of this.fields) {
```

Also, did you change any controller setting or is that the stock config?

**Comment by ronso0** [comment]
I adjusted some stuff, sure.

with a console.warn() added I get
```
controller.traktorkontrols4mk3f1f43.input:warning [Controller] getInputReport is unable to get data from "Traktor Kontrol S4 MK3 F1F4_3" serial # "262FF1F4" : "ioctl (GINPUT): Invalid argument"
```

**Comment by JoergAtGithub** [comment]
Sound like you need to update the hidraw kernel module: https://github.com/torvalds/linux/commit/f43d3870cafa2a0f3854c1819c8385733db8f9ae

**Comment by ronso0** [comment]
Okay, thanks for the pointer!

Though, building a kernel module is not something I'm up to right now ; )

**Comment by ronso0** [comment]
Update:
so all I had to do was get a kernel with the required hidraw module (5.11+) built with `CONFIG_HIDRAW=y`.
All working now!
