### ISSUE TITLE
key empy in track Info, but displayed in tracks table

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#14019]
### Bug Description

quoting from https://github.com/mixxxdj/mixxx/pull/14011#issuecomment-2542653733
**Max Graef - Jazz 104**, FLAC

 | | |
 |---|---|
  Tracks | 8B
  Deck | 8B
 Track Properties dialog|   ---
  -> Re-imp| 8B
 Track Properties dialog |    ---
 -> Re-import from file |8B
 | | |  
 database |  ---
 file metadata|     8B

So the track models query the file metadata for missing properties?
Note that I didn't have "Syncronize metadata from/to file tags" enabled while testing.

Didn't check if this is related to and maybe fixed by #14008, will do.

### Version

2.5

**Comment by ronso0** [comment]
Forgot to mention this is a FLAC file, in case that matters.

**Comment by m0dB** [comment]
I assume it is related, and I had some hope that #14008 would fix it, but it didn't.

**Comment by ronso0** [comment]
No it is I think, see #14020

**Comment by ronso0** [comment]
Thanks for taking a look though!
