### ISSUE TITLE
Glitch when scratching waveform across loop boundaries

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/mixxx#14040]
### Bug Description

This was working well in 2.4, now broken again.
Waveform seeks back to previous position infinitly as long as the mouse is pressed.

### Version

2.5-beta

**Comment by ronso0** [comment]
I think we fixed this earlier, will try to find the PR and check what's going on.

**Comment by ronso0** [comment]
Marking this as blocker because it gives really nasty sounds...

**Comment by ronso0** [comment]
old commit: 50e16c96face8890d7f912385a9ba59f26953ed2

**Comment by ronso0** [comment]
whoopsy, did I break this with #14024 / https://github.com/mixxxdj/mixxx/pull/14024/commits/4965d2b8f1c776c5b82adaebe52764dc8a9ca0a6 ?

**Comment by ronso0** [comment]
yup, that's it.
Either I can fix it or we revert #14024

**Comment by ywwg** [comment]
fixed by https://github.com/mixxxdj/mixxx/pull/14043
