### ISSUE TITLE
Mixxx PPA for Ubuntu 22.04 (Jammy) does not appear to have a working link to install Mixxx 2.5.0

### ISSUE THREAD

**Issue by dln949** [mixxxdj/mixxx#14053]
### Bug Description

Mixxx PPA for Ubuntu 22.04 (Jammy) does not appear to have a working link to install Mixxx 2.5.0.  

At this link the build status appears as failed:  https://launchpad.net/~mixxx/+archive/ubuntu/mixxx/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy

Or, am I just looking in the wrong place?  

### Version

2.5.0

### OS

Ubuntu 22.04

**Comment by Swiftb0y** [comment]
CC @daschuer in case you have time to look into it.

**Comment by daschuer** [comment]
Oh, thank you for noticing. Sometimes we run into timeouts of our unittestest. I have restarted the build, so it will be hopefully available soon.

**Comment by ronso0** [comment]
Tests have passed, I'll close this.
